### PR TITLE
fix: Schedule: Add list and calendar button to schedule page

### LINKED ISSUE #6713: Schedule: Add list and calendar button to schedule page
The system has two ways to display the schedule a) as a list and b) as a calendar.

Therefore please add a calendar button and a list button for the two different views directly next to the "Schedule" heading.

Compare
* Schedule https://eventyay.com/e/8fa7fd14/schedule
* Calendar https://eventyay.com/e/8fa7fd14/calendar

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6713

#### Short description of what this resolves:
By default list view is displayed

Screenshot from 2021-02-15 20-29-40
Screenshot from 2021-02-15 20-29-49

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please change as follows:

Screenshot from 2021-02-18 16-49-02

**Comment by mariobehling** [comment]
Same for calendar view.

Screenshot from 2021-02-18 16-51-52

**Comment by MeghalBisht** [comment]
**New changes -** 
Screenshot from 2021-02-18 21-39-29
Screenshot from 2021-02-18 21-39-21

**Comment by mariobehling** [comment]
1. When I switch from list view to calendar view the page loads and directs the user to the top.
2. When I switch from calendar view to list view the page loads and keeps the user in the same area.

Is it possible change the behavior for 1. to match the behavior of 2.?

**Comment by maze-runnar** [comment]
in mobile view button got hidden behind timezone switcher -
open-event-frontend-gy6cl68yg vercel app_e_fa96ae2c_calendar(Moto G4)

**Comment by MeghalBisht** [comment]
Screenshot from 2021-02-22 15-41-09

**Comment by mariobehling** [comment]
On calendar page please make "Schedule", "List Button" and "Timezone dropdown" into the same line. If that is not possible please move "Schedule" and "List button" to the top row and "Timezone" below.

Screenshot from 2021-02-22 15-33-30

Compare https://open-event-frontend-git-fork-meghalbisht-schedule-btns-eventyay.vercel.app/e/fa96ae2c/calendar

**Comment by mariobehling** [comment]
In mobile view it would also be best if the buttons would all go into the same line.

Please reduce the spacing to the above "Tweet" area to match the spacing between other widget areas.

Screenshot from 2021-02-22 15-35-23

**Comment by MeghalBisht** [comment]
**Recent update**

Screenshot from 2021-02-22 21-00-46
Screenshot from 2021-02-22 21-00-38

**Comment by MeghalBisht** [comment]
cont in #6791

**Pull request closed without merging**
