### PR TITLE
fix: Video Tab: Icons aligned when event or video room has a long name 

### LINKED ISSUE #6187: Video Tab: Icons disaligned when event or video room has a long name
In the video tab overview first column the icons are disaligned when an event or video room name has a longer name. Please ensure the icons stay aligned.

Screenshot from 2020-12-31 09-08-26

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6187 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by afzal442** [comment]
@MeghalBisht In mobile view I got something like this....
c2

**Comment by MeghalBisht** [comment]
> @MeghalBisht In mobile view I got something like this....

Please provide a screenshot without these changes

**Comment by mariobehling** [comment]
Ok, I was originally thinking about another solution. In any case the icons should be either next to each other or below to each other. It looks like you achieved this in this PR. We need to come up with a mobile view UI probably in another PR. So, looks good to me. Thanks.

**Comment by iamareebjamal** [comment]
@MeghalBisht We don't need media query for this. Too much media queries complicate things. Just flexbox can solve the issue

**Comment by MeghalBisht** [comment]
@iamareebjamal  But we don't want the wrap property to work for bigger screen resolution.
Also, mobile view starts at about 767px but at that resolution the original icon position works fine.

**Comment by iamareebjamal** [comment]
It won't work on bigger screens, that's how flex works

**Comment by MeghalBisht** [comment]
wrap for bigger screen :


no wrap for bigger screen :

**Comment by MeghalBisht** [comment]
> It won't wrap on bigger screens, that's how flex works

I think it will wrap on bigger screens as once the text is long the icons have no other choice but to shift to the next line.

**Comment by iamareebjamal** [comment]
There are other flex options like flex grow shrink. Try a few options

**Comment by MeghalBisht** [comment]
Current commit changes work better than the last one.
Few relevant screenshots -

**NOW -**







**BEFORE -**  (some icons were horizontal, some were vertically aligned)

**Comment by iamareebjamal** [comment]
You mean flex solution is better than media query or last commit is better than first flex solution?

**Comment by MeghalBisht** [comment]
Both are flex wrap solutions only, in the previous commit wrap was done after a particular resolution, in the current commit wrap will happen for all resolutions whenever text is long

**Pull request merged**
