### PR TITLE
Improving filters for confirmed sessions

### LINKED ISSUE #1959: Sessions in an event showing Rejected and Pending sessions
**Describe the bug**

Clicking on Sessions tab of any **event** is showing the sessions which have been rejected or are pending for confirmation by the Organizer. In practice, the link should only show the sessions which have been confirmed

**To Reproduce**
1. Go to any event
2. Click on Sessions
3. Correlate given sessions with the one which are actually confirmed

**Expected behavior**

Only the Sessions which have been **confirmed** should be shown on the event page

**Screenshots**

The series of images shows the sessions being displayed on a **Test Event**
image
image
image

While the following image actually shows the confirmed / rejected / pending status of the sessions
image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] 71.0.3578.98

**Additional context**

None

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
It resolves the fact that only ``accepted`` or ``confirmed`` sessions should be shown in the event's sessions

#### Changes proposed in this pull request:

- Adding ``state`` = ``accepted`` condition to show only confirmed sessions

Using the reference of the screenshots shown in the issues, here is a screenshot of how the search looks after the improve filtering:

image

Fixes #1959

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 doing so

**Comment by uds5501** [comment]
@CosmicCoder96  any assistance in squashing them would be lovely, I squashed b1ad8ef, 4333e02, 98e5bfa into 63dd090 using ``git rebase -i``, is there anything else I should do?

**Comment by CosmicCoder96** [comment]
@uds5501 you should merge your commits in a way such that there is a single commit in your PR.

You should use git rebase -i HEAD~5 to go get rebase options for the last 5 commits, then replace `pick` with `squash` for four of the commits you want to squash into your first commit.

**Comment by CosmicCoder96** [comment]
@uds5501 Read git documentation or google how to squash commits.

**Pull request merged**
