### PR TITLE
fix: Updating file signatures for extended jpeg support

### LINKED ISSUE #3769: Error in uploading user profile image
**Describe the bug**
The image upload for user is not working on eventyay.com as well on dev branch

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to account section
2. Upload a `jpeg` image
First time the error is shown, file not supported.
Repeat the process, the error is not shown and you can click on save changes 

**Expected behaviour**
The error should be shown again if I am uploading the jpeg image

**Additional context**
@kushthedude @maze-runnar - Please verify

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3769

### CODE REVIEW

**Comment by kushthedude** [comment]
@maze-runnar Can you please test if it is working now ?

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/utils/file.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4768744&bid=15894303)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/utils/file.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4768744&bid=15894303)

**Comment by maze-runnar** [comment]
it's working , same image as previous . Now uploaded correctyly :)
Screenshot from 2020-01-06 18-51-40

**Comment by kushthedude** [comment]
@codedsun Please verify and report .

**Pull request merged**
