### PR TITLE
Fix-9127: Add the unique ticket code into the downlad CSV file

### PR DESCRIPTION
**Pull request by lthanhhieu**
Fixes #https://github.com/fossasia/open-event-server/issues/9127

#### Short description of what this resolves:
- Add the unique ticket code into the downlad CSV file

#### Changes proposed in this pull request:
- Add the unique ticket code into the downlad CSV file

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by lthanhhieu** [comment]
After I tried to figure out the problem, the UI crashed on the 'View attendees' screen.
I see 2 problems:
1/ If the order has 2 or more tickets, the UI will not display the "Order Id" price.
2/ The "View attendees" screen has 2 columns "Ticket number". I checked the source code and found out this problem happened 7 months ago.

After fixing the above two issues, at "View Attendees" I noticed that the "Order" Column is not the "Ticket ID" in the QR and CSV. Do you want to change the value of the "Orders" column?
Table

**Review by norbusan — APPROVED** [review]
Thanks!

**Comment by mariobehling** [comment]
The issue is now that it only works in English, but not in Vietnamese.

Screenshot from 2024-03-26 15-39-09

**Comment by lthanhhieu** [comment]
Hi @mariobehling 

According to the image you provided, your UI is still using the old source code. Try logging in and logging out again to see if you still have the problem. Thanks

**Pull request merged**
