### PR TITLE
fix: removing orderStatistics relation in serializer

### LINKED ISSUE #3890: Wizard Step 1: Editing Description results in Unexpected Error
When the user tries to edit the "Description" area in step 1 of the wizard an "Unexpected Error" appears. If the user refreshes the wizard and copy/pastes the info it works, but initially it always shows the error.

Screenshot from 2020-01-29 10-46-58

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3890
Partially Fix for https://github.com/fossasia/open-event-server/issues/6776

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Remove both and tell me what's breaking

**Comment by kushthedude** [comment]
EventStatistics is breaking after removing the second one.

**Comment by iamareebjamal** [comment]
What's the error

**Comment by kushthedude** [comment]
> What's the error

No error in console, The data is not getting rendered.
Screenshot 2020-01-29 at 8 37 41 PM

**Comment by iamareebjamal** [comment]
This will not fix the issue. Need to find the solution of why it was added in the first place which I assume was because there were no links to these resources in event JSON. Now they are present, so why are they needed now?

**Comment by kushthedude** [comment]
> This will not fix the issue. Need to find the solution of why it was added in the first place which I assume was because there were no links to these resources in event JSON. Now they are present, so why are they needed now?

There is no relationship in event for name eventGeneralStatistics in event model like orderStatistics.

**Comment by iamareebjamal** [comment]
There should be

**Comment by iamareebjamal** [comment]
Codacy has some foolish requirement - `Seems like there are some contributions to this repository not being analyzed because these users don't belong to your organization.`

**Comment by kushthedude** [comment]
> Codacy has some foolish requirement - `Seems like there are some contributions to this repository not being analyzed because these users don't belong to your organization.`

I am a org member, Then why it's not analysing my PR 😆

**Comment by iamareebjamal** [comment]
Org member on codacy

**Comment by kushthedude** [comment]
> Org member on codacy

Lets see the status now .

**Comment by kushthedude** [comment]
> Org member on codacy

Open Event Frontend is not even listed under fossasia org on codacy. There must be some other issue

**Comment by iamareebjamal** [comment]
It is

**Comment by kushthedude** [comment]
What now then? 😕

**Comment by kushthedude** [comment]
@iamareebjamal Merge?

**Comment by iamareebjamal** [comment]
That's for deserializing server response to JS object

**Comment by iamareebjamal** [comment]
Superseded by #3980

**Pull request closed without merging**
