### PR TITLE
fix(payments): error message on stripe checkout button

### LINKED ISSUE #8166: Choosing "Stripe" as a payment option results in "TypeError: Cannot read properties of undefined (reading 'message')"
Choosing "Stripe" as a payment option results in "TypeError: Cannot read properties of undefined (reading 'message')"

_Originally posted by @mariobehling in https://github.com/fossasia/open-event-frontend/issues/8136#issuecomment-988064239_

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #8166 

#### Short description of what this resolves:
A small edge case was left during implementation causing this error.

### CODE REVIEW

**Review by codedsun — APPROVED** [review]

**Comment by pc-beast** [comment]
It just striked that we need to make similar changes for other online payment methods too.

**Comment by mariobehling** [comment]
Cannot fully test this as Stripe only connects to eventyay.com.

I also get the error as in the screenshot below when trying to connect to Stripe as an organizer in the wizard on test.eventyay.com.
Screenshot from 2021-12-07 20-42-12

**Comment by pc-beast** [comment]
> Cannot fully test this as Stripe only connects to eventyay.com.
> 
> I also get the error as in the screenshot below when trying to connect to Stripe as an organizer in the wizard on test.eventyay.com. Screenshot from 2021-12-07 20-42-12

I just tested, on `localhost` everything is working fine with these changes. Error is you posted in on ```test.eventyay.com``. looking more into it.

**Comment by mariobehling** [comment]
Ok, thanks for looking into this error. I am merging this, so we can test it on the test system.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
