### PR TITLE
Changed order of left side menu

### LINKED ISSUE #6800: Public Event Page: Change order of left side menu
The left side menu has a lot of menu items now. Please change the order as follows to ensure the most important links are on the top:
- Info
- Tickets
- Schedule
- Speakers
- Sponsors
- Exhibition
- Organizer
- Call for Speakers
- Getting here
- Code of Conduct

### PR DESCRIPTION
**Pull request by MuditJain5**
Fixes #6800 

**Changed the order of left side menu**

The new order :
 - Info
 - Tickets
 - Schedule
 - Speakers
 - Calendar
 - Sponsors
 - Exhibition
 - Organizer
 - Call for Speakers
 - Getting here
 - Code of Conduct

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x]  I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Naman-1234 — COMMENTED** [review]
Try to provide a screenshot, Whenever you deal with issues related to designing or reordering etc. This makes it easy for maintainers to review.

**Comment by MuditJain5** [comment]
> Try to provide a screenshot, Whenever you deal with issues related to designing or reordering etc. This makes it easy for maintainers to review.

Sorry, but I can't find all the menu items together in any event that's why I didn't provide any screenshot.

**Comment by afzal442** [comment]
@MuditJain5 lookup here https://open-event-frontend-git-fork-muditjain5-issue-6800-eventyay.vercel.app/e/fa96ae2c
and share the screenshot here as well.

**Comment by MuditJain5** [comment]
> @MuditJain5 lookup here https://open-event-frontend-git-fork-muditjain5-issue-6800-eventyay.vercel.app/e/fa96ae2c
> and share the screenshot here as well.

Thanks @afzal442 for helping me

**Comment by MuditJain5** [comment]
Screenshot of the new order of Left Side Menu :

issue-6800

**Review by mariobehling — APPROVED** [review]
Works for me.

**Pull request merged**
