### PR TITLE
fix: fixing error with the price of donation ticket

### LINKED ISSUE #4475: Counting error with the price of donation ticket
**Describe the bug**
There has been some error when we set the price for donation ticket. Sometimes it works, some time it just doesn't. Need to change the numbers up and down a few times. 

**Expected behaviour**
Able to set prices donation ticket normally (as long as min price is smaller than max price)

**Screenshots**
Screen Shot 2020-06-17 at 16 02 03

**Desktop (please complete the following information):**
 - OS: [Mac OS 10.14]
 - Browser [Chrome]

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4475 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Still happening

**Comment by maze-runnar** [comment]
I have tested it several times, it's working :confused:

**Comment by iamareebjamal** [comment]
@edenyay is testing this soon. Let's check if her problem is solved

**Review by mariobehling — APPROVED** [review]
Eden and I tested it. Seems to be working as expected now.

**Comment by mariobehling** [comment]
Oh, however, the error message on the ticket itself does not appear anymore.

Screenshot from 2020-09-28 17-44-11

So, solving this issue results in another issue.

**Comment by mariobehling** [comment]
Add another issue here now https://github.com/fossasia/open-event-frontend/issues/5169

**Pull request merged**
