### PR TITLE
chore: Replace cachedshoe with data-storefront

### LINKED ISSUE #3740: Use ember-data-storefront instead of cached-shoe
https://embermap.github.io/ember-data-storefront/

cached-shoe is deprecated https://github.com/ember-fastboot/ember-cli-fastboot/pull/718

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3740 
Refers #3704

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Have you tested with fastboot

**Comment by kushthedude** [comment]
Build was successful with command 
```js
ember build --environment production
```

**Comment by iamareebjamal** [comment]
That doesn't mean fastboot is working. Add fastboot dependencies mentioned in Dockerfile and `node scripts/fastboot-server.js` and ensure that calls made in the server are not remade through XHR when page loads

**Comment by iamareebjamal** [comment]
Tested. Working perfectly

**Pull request merged**
