### PR TITLE
 Admin: By default sort users by last date joined with the most recent users showing up on top 

### LINKED ISSUE #5157: Admin: By default sort users by last date joined with the most recent users showing up on top
In https://eventyay.com/admin/users please
* sort according to the most recent user on the top (member since).
* show 50 users per page by default

Compare: https://eventyay.com/admin/users/all?sort_by=created-at&sort_dir=ASC

Screenshot from 2020-09-26 10-45-17

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5157

#### Short description of what this resolves:
User per page = 50

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@mariobehling user are already sorted acc to the most recent user created. I have made changes pls let me know anything to change.

**Comment by iamareebjamal** [comment]
50 will crash the system. Can't merge until https://github.com/fossasia/open-event-server/issues/7255

**Comment by iamareebjamal** [comment]
Closing till server issue is resolved

**Comment by maze-runnar** [comment]
@sachinchauhan2889 @MeghalBisht @ranjitkshah as the server part of this is complicated, can we add per_page 20 here and merge this  😶?

**Pull request closed without merging**
