### PR TITLE
fix: user can't edit session after cfs is closed

### LINKED ISSUE #3768: Session & Speaker: User can change his session/speaker details after CFS is closed
**Describe the bug**

User can change his session/speaker details after CFS is closed.

**To Reproduce**

Steps to reproduce the behaviour:

1. Submit a Proposal and Confirm it.
2. Wait for CFS to get closed and then edit your proposal.
3. See error

**Expected behaviour**

User should not have the right to edit the proposal once CFS is ended.

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #3768 

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@kushthedude @uds5501 please review .

**Comment by kushthedude** [comment]
It is incomplete, Make changes in public pages too

**Comment by kushthedude** [comment]
Never close your PR, Incase you are not able to revert the changes Force push another branch to the same. Closing the PR in favour of another is not a good developer habit.
Please avoid it from next time.

**Comment by maze-runnar** [comment]
> Never close your PR, Incase you are not able to revert the changes Force push another branch to the same. Closing the PR in favour of another is not a good developer habit.
> Please avoid it from next time.

i will take care of this from the next time .

**Comment by maze-runnar** [comment]
> It is incomplete, Make changes in public pages too



> It is incomplete, Make changes in public pages too

can you please specify  where to make changes in public page ?

**Comment by kushthedude** [comment]
> > It is incomplete, Make changes in public pages too
> 
> > It is incomplete, Make changes in public pages too
> 
> can you please specify where to make changes in public page ?

In CFS Subroute

**Comment by kushthedude** [comment]
Fix CI

**Comment by maze-runnar** [comment]
@kushthedude should i update branch now?

**Pull request closed without merging**
