### PR TITLE
feat : Add soft closing date for submissions to wizard and CfS page

### LINKED ISSUE #6408: Call for speakers: Add soft closing date for submissions to wizard and CfS page
As many events nowadays started to have a soft closing date and after this date still accept late submissions, we need this option in the wizard and public CfS page.

Please add the feature to the wizard and CfS page therefore.

Example: "The soft closing date for submissions is 1 February, 2021 6:59 AM (SGT). The final closing date of the Call for Speakers is Monday, 15 February, 2021 6:59 AM (SGT)."

Screenshot from 2021-01-18 00-24-48

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #6408 

#### Short description of what this resolves:
self-explanatory

#### Screenshot:
image
image

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
There is a space after `.` in english

**Comment by ranjitkshah** [comment]
> There is a space after `.` in english

image

**Comment by mariobehling** [comment]
Soft closing date is optional. If it is not filled in, it should not appear on the public CfS.

Screenshot from 2021-02-07 11-54-27

Please make a line break after "The soft closing date for submissions is ... (SGT). "

**Comment by ranjitkshah** [comment]
> Soft closing date is optional. If it is not filled in, it should not appear on the public CfS.
> 
> Screenshot from 2021-02-07 11-54-27
> 
> Please make a line break after "The soft closing date for submissions is ... (SGT). "

**Comment by ranjitkshah** [comment]
> > Please make a line break after "The soft closing date for submissions is ... (SGT). "
> 
> image

@mariobehling please check

**Comment by mariobehling** [comment]
It looks good, but I think I did not make it completely clear. The soft closing date should be an option. If the organizer does not want to add a soft closing date the field should be left black and the sentence should not show up on the CfS page.

What is the best way to make this as an option?

Maybe a tick box in the wizard?

**Comment by maze-runnar** [comment]
@sachinchauhan2889 you are looking into it, right?

**Comment by sachinchauhan2889** [comment]
@maze-runnar  yes right

**Pull request closed without merging**
