### PR TITLE
fix: Access Code Functionality

### LINKED ISSUE #6274: Access Code Functionality Not Working
The access code functionality is not working and has a number of issues:
1. "Hidden Tickets" do not get saved in the wizard Compare https://eventyay.com/events/5ac8e4d9/edit/basic-details
Screenshot from 2021-01-08 11-16-28
2. The old previous UI of the access code appears at times when creating an access code. (Please check in the code as this cannot be replicated always. Ensure the old previous interface is deleted from the code.)
Screenshot from 2021-01-08 11-18-35

### PR DESCRIPTION
**Pull request by SARTHAK1SINGH**
Fixes #6274

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by SARTHAK1SINGH** [comment]
# Screenshots
<hr>

Screenshot 2021-01-08 212614


Screenshot 2021-01-09 003113

**Comment by iamareebjamal** [comment]
Please check this end to end, is only UI working or the entire logic is working

**Comment by iamareebjamal** [comment]
Closed by mistake

**Comment by SARTHAK1SINGH** [comment]
@iamareebjamal it is showing something like this when I click on the access code URL of the hidden ticket.
<hr>
 
image

**Review by mariobehling — CHANGES_REQUESTED** [review]
Code functionality is working for me. The only thing:
When the user changes the status of tickets - hidden or closed - the ticket settings close after pressing ok. Expected: The ticket settings of the specific ticket should stay open and show the changed status.

Screenshot from 2021-01-09 23-26-07

**Comment by SARTHAK1SINGH** [comment]
Looking into it.

**Comment by maze-runnar** [comment]
@iamareebjamal I have tried to complete the rest part of PR but it is showing unusual behaviour. When modal is open, and I clicked on hide ticket then `isExpanded` is always toggled. There is no action attached. But in ticket-list.hbs when i replaced prop `ishidden` or `ticket.isHidden` with anyother val, it was not toggled.

**Comment by iamareebjamal** [comment]
OK, I'll check

**Pull request merged**
