### PR TITLE
fix: Removed unneccesary line breaks in event title

### LINKED ISSUE #5474: Event Dashboard: Unwanted Line Break in longer Event Titles
There is an unneeded line break in longer event titles on the event dashboard. Expected line breaks should only happen to prevent the title to overlap other areas.
Screenshot from 2020-11-03 20-02-25

### PR DESCRIPTION
**Pull request by Gautam-Arora24**
Fixes #5474 

**Changes proposed in this pull request**
1. Remove unnecessary line breaks.

**Before**
github

**After**
Screenshot 2020-11-04 at 2 19 48 AM

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Use flexbox instead because this will look bad on smaller screens

**Comment by Gautam-Arora24** [comment]
I have checked in smaller screens. It works fine. I can make some changes to this commit only so that it looks good in all screen sizes

**Comment by iamareebjamal** [comment]
That is what I am asking

**Comment by Gautam-Arora24** [comment]
[Fossasia Trim.mov.zip](https://github.com/fossasia/open-event-frontend/files/5485765/Fossasia.Trim.mov.zip)

The latter commit makes the UI to look good in all screen sizes. I have included a Zip file which demonstrates the video. Kindly have a look

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
