### PR TITLE
Organizer Speaker/Session Page: Colors of status badge differ #6521

### LINKED ISSUE #6521: Organizer Speaker/Session Page: Colors of status badge differ
The colors of the status badges e.g. "Accepted" differ between the speaker overview page and the session overview page of organizers.

Please use the same colors everyhwere.

Screenshot from 2021-01-29 06-58-43
Screenshot from 2021-01-29 06-58-26
Screenshot from 2021-01-29 06-58-00

### PR DESCRIPTION
**Pull request by akash2408**
Fixes #6521 
#### Short description of what this resolves:
change color or accepted and cancelled in helper
done
confirm

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by afzal442** [comment]
@akash2408 why did u make PR for this??

**Comment by afzal442** [comment]
Without working on this.. I was waiting to make a PR for this.

**Comment by akash2408** [comment]
> @akash2408 why did u make PR for this??

I saw a comment yesterday saying working on it.
But still there is no pr so today i send the pr.
So i was not sure is someone really doing it or not
So send it

**Comment by afzal442** [comment]
That's fine. But u can see my comment. I was waiting too. I asked that other person and waiting for his reply as per the guideliness.

**Comment by iamareebjamal** [comment]
@akash2408 Always say you are working on a PR, or ask from previous commentor whether you can work on it. If PR is not created for more than a day, then go ahead and send a PR after commenting on the issue.

I'm going to prefer @afzal442 PR, there are some changes required. If he's not able to complete it till next day, I'll check your PR.

This is the issue:

This is a workaround. Why were the colors different in the first place? Make both places use the same source of color

**Pull request closed without merging**
