### PR TITLE
feat: Integrate the user API at settings/applications

### LINKED ISSUE #507: Implement user API on settings/applications
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

screenshot from 2017-07-19 14-11-02

### PR DESCRIPTION
**Pull request by sumedh123**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #507

### CODE REVIEW

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 Here, the URL has to be entered in the type:
```
https://facebook.com/sample-username
```
But, we have our UI something like:
settingsapplications2
Its confusing since the user would enter the username onlyl in first place. One way is to do it in frontend. Second is to modify server to accept these. Opinions?

**Comment by niranjan94** [comment]
Deployment link: https://pr-858-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@sumedh123 Please check https://github.com/fossasia/open-event-frontend/issues/507#issuecomment-316339281

**Comment by sumedh123** [comment]
@geekyd Shall I close this?

**Pull request closed without merging**
