### PR TITLE
#8763 iframe for translation video

### PR DESCRIPTION
**Pull request by minhho89**
issue #8763 #8959

Adding translation sub-stream into the Main Stream.
- Main Stream will be muted, showing only the video
- Translation will be hidden, only audio is audible
The diagram for the workflow
video_channel_live_translation

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by minhho89** [comment]
Please see this draft PR for the current status @mariobehling @cweitat 

This is the draft PR, to check the functionality
- Add a Youtube video (draft PR works only with Youtube at the moment).

Play the video by the "Play" Button to get the translation Stream plays as well
image

**Comment by mariobehling** [comment]
Thanks. Good to see there there is progress, but I wonder why you do not follow the issue. A simple drop-down next to the channel with the translation options is what we are looking for. Another "play" button seems illogical as users do not know what to play. Please follow the issue description.

image
Translate Icon/Text to show at end of menu link if translation exists.

**Comment by minhho89** [comment]
This draft PR focuses mostly on the "video-stream" screen.
## Integrate with the backend to get a list of available channels.
- Besides loading the channels to combobox, adding "Original" to get rid of all translation channels. If "Original" is chosen, the mainstream audio is unmuted. Otherwise, the audio is muted 🔇 .
 - Choosing a translation channel will trigger to load of the corresponding StreamYard stream.
## Open points
- Implementing the hovering at the sidebar takes more effort since have to build a whole new element, behaviors. Instead, at the moment I reuse the language Combobox, clicking on the Combobox to choose the channel from (see the screenshot)

image

### StreamYard issues:
- StreamYard is muted by default, to unmute it, users have to click the button "Unmuted" inside the iframe.
- StreamYard provides no API and does not allow to use Javascript to control any component inside its iframe. So currently there is no way to get the audio unmuted by code. Already sent concerns to StreamYard customer services.
- **If we hide the StreamYard iframe, the user cannot get the audio!**
### Syncing between Mainstream and Translation channel stream
- If mainstream iframe is got paused, the translation channel audio still going, and vice versa.

**Comment by minhho89** [comment]
*Update*
StreamYard team has replied, there is no feature that matches with our requirements:

**Comment by mariobehling** [comment]
Is the following possible? 

Note green color is only to make things more easily visible. Font color should be white. "A" is intended to symbolize the Internatiolization icon/language icon.

Screenshot from 2023-07-23 11-11-31a

Screenshot from 2023-07-23 11-11-31b

Screenshot from 2023-07-23 11-11-31c

**Comment by mariobehling** [comment]
Best would be a language icon like in Wikipedia.

Screenshot from 2023-07-23 11-36-42

**Comment by minhho89** [comment]
Changing the Combobox into this:
image

When users click on a translation channel, a small iframe appears.
Due to the security from StreamYard, cannot use code but users must interact directly with the Stream to mute/unmute.
Because of that, after selecting unmute from StreamYard player, users click to "Hide this" button to hide the StreamYard iframe.
 
image

If there is no translation channel, there will be no combobox

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
Screenshot from 2023-07-25 23-40-29

1. For grey area please only use the required width. Left side room names might be longer and the grey dropdown should not use more width than necessary.
2. For dropdown white area, it should have the same design, width and color as the the grey box.

**Comment by cweitat** [comment]
@minhho89 also typo, 
language, languages

**Pull request closed without merging**
