### PR TITLE
 Adding labels to State 

### LINKED ISSUE #2815: Addition of colour labels to `Event State`
**Is your feature request related to a problem? Please describe.**

Currently there is no label for `Event State` under `Admin/Events`

**Describe the solution you'd like**

Add `Labels` as added in `Session State`

**Screenshot**
Screenshot 2019-04-27 at 7 57 05 AM

### PR DESCRIPTION
**Pull request by kushthedude**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

- Added Labels for `Events State`
- Disabled Sorting for `Feature Event` Toggle

Fixes #2815

### CODE REVIEW

**Comment by kushthedude** [comment]
@CosmicCoder96 @pradeepgangwar Review Please . 😄

**Comment by uds5501** [comment]
@kushthedude @CosmicCoder96 asked specifically not to disable sorting during implementation.

**Comment by kushthedude** [comment]
@uds5501 Oops lemme update it .

**Comment by ritikamotwani** [comment]
No, it's not required.

**Pull request closed without merging**
