### PR TITLE
fix: remove \n, \r from rich text editor and remove "line feed" character.

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7242
Fixes https://github.com/fossasia/open-event-frontend/issues/6943

#### Short description of what this resolves:
remove `\r`, `\n` and `\r\n` in text editor.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by sachinchauhan2889 — APPROVED** [review]

**Comment by maze-runnar** [comment]
firefox : 

https://user-images.githubusercontent.com/56407566/118788304-49188d00-b8b1-11eb-9f8b-613df15cbdc0.mp4

**Comment by sachinchauhan2889** [comment]
https://github.com/fossasia/open-event-frontend/issues/7242#issuecomment-843953151

@maze-runnar Do we still need to drop `\n` since editor already covert it to `\\n` before request. Or it is fine to remove `\n`. What is user want to add `\n` as text(not as line break).

**Comment by maze-runnar** [comment]
> [#7242 (comment)](https://github.com/fossasia/open-event-frontend/issues/7242#issuecomment-843953151)
> 
> @maze-runnar Do we still need to drop `\n` since editor already covert it to `\\n` before request. Or it is fine to remove `\n`. What is user want to add `\n` as text(not as line break).

after updation of PR, I don't think, we need it. we can revert regex to previous one.

**Comment by maze-runnar** [comment]
> @maze-runnar I face the issue with cursor now in Chrome. Please confirm

is it happening with first word only?

**Comment by MeghalBisht** [comment]
> is it happening with first word only?

Yes same as it use to happen with Firefox

**Comment by maze-runnar** [comment]
> > is it happening with first word only?
> 
> Yes same as it use to happen with Firefox

No, firefox issue was different, it was when we hit space, here it is automatically jumping to first after 200ms I think.

**Comment by maze-runnar** [comment]
I have tested only with firefox, let me see this with chrome too.

**Comment by maze-runnar** [comment]
@MeghalBisht please test this now.

**Comment by MeghalBisht** [comment]
Yes works fine now with Firefox and Chrome

**Comment by ranjitkshah** [comment]
works for chrome and firefox. have to check with other browsers also safari etc

**Comment by maze-runnar** [comment]
we will see safari if anyone raises an issue later. Or if Any one can test it now on safari, test it.

**Review by MeghalBisht — APPROVED** [review]

**Pull request merged**
