### PR TITLE
fix: Speaker Images now using content area fully

### LINKED ISSUE #6554: Public Event Page: Speaker images not using content area fully
The speaker images in the content area of the public event page and the speaker page are not fully using the content area. The result is that there is a blank area to the right of the speaker area in the content area.

Please increase the size of the speaker images proportionally so they the speaker images fill the space of the middle area on both the public event page (for featured speakers) and the speaker page.

Screenshot from 2021-01-31 00-35-10

### PR DESCRIPTION
**Pull request by Naman-1234**
Fixes #6554

#### Changes proposed in this pull request:

As requested in the issue, Size of image is increased such that there is no right margin left as there were before. 
Please see the screenshot below for further clearance, Area is being highlighted to see margins properly.

Screenshot (901)

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Not working for me on https://open-event-frontend-git-fork-naman-1234-responsive.eventyay.now.sh/e/fa96ae2c/speakers

**Comment by Naman-1234** [comment]
Oh sorry sir, I will do that.

**Comment by Naman-1234** [comment]
As requested in the issue, Size of image is increased such that there is no right margin left as there were before.Please find the screenshot of the page you mentioned in the link here.
<br></br>

Screenshot (902)

**Review by mariobehling — COMMENTED** [review]
Works for me.

@iamareebjamal Are changes ok code-wise?

**Pull request merged**
