### PR TITLE
enh: cancel order button on proceed to checkout page

### LINKED ISSUE #2759: Addition of `Cancel Order` button in `Order Checkout` Page
**Is your feature request related to a problem? Please describe.**

Currently in the `Order Checkout` page there is no `Cancel Order` Button

**Describe the solution you'd like**

Add a `Cancel` Button which routes to `Events Page`

**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #2759 
video url of enhancement : https://youtu.be/tpNLsuyeDbM
Screenshot from 2020-01-09 22-10-38
Screenshot from 2020-01-09 22-11-17

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
This will need API functionality to `Cancel` too. This is not the correct way, It won't even cancel the order will continue and the attendee will get mail. Please implement it correctly with server functionality too.

**Comment by maze-runnar** [comment]
> This will need API functionality to `Cancel` too. This is not the correct way, It won't even cancel the order will continue and the attendee will get mail. Please implement it correctly with server functionality too.

@kushthedude can you please help me in that `what is mean by API functionality` here . Is there any server functionality to cancel orders .

**Comment by kushthedude** [comment]
I dont think there is, as soon as the order button is hitted order os
initialised but with cancel order , the order must be deleted and get
assigned no label.
@iamareebjamal can tell you more better about its api requirement.

**Comment by kushthedude** [comment]
Cancel Order functionality needs further discussion about it's implementation.

**Pull request closed without merging**
