### PR TITLE
feat: Display event logo in public event page

### LINKED ISSUE #4781: The Date of the event  is overlapping to navbar in mobile view
**Describe the bug**
The date of the Event is overlapping to Nav bar and user Cannot read the date of the event properly

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/d414fc2c'
2. changed to mobile view  'iphone5/se and galaxy fold'
3. See error.

### Screenshots for desktop 
now open event

### screenshot for galaxy fold and iphone 5/se for the bug ---
now event
### saturday ,july25th 2020 missing in mobile view but visible in desktop view 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone5/se , galaxy fold]
 - Browser [e.g. stock browser,]

**Additional context**
@iamareebjamal plz reviews on this issue

### LINKED ISSUE #4857: Wizard 1 Basic Event Details/Public Page: Event logo from Form not displayed on event page
In the create event wizard step 1 an event logo can be added. However, the logo is not shown anywhere.

Please add the logo on top of the event page in front of the event description as in the example below.

Compare live site https://eventyay.com/e/8fa7fd14 to the below image.

Screenshot from 2020-08-24 12-06-23

### LINKED ISSUE #4858: Public Page: Avoid Linebreaks in date/time and event title
The event date/time sometimes has line breaks even if there is still sufficient space. Please avoid line breaks if there is enough space.

Screenshot from 2020-08-24 12-15-20

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #4857 
Fixes #4858 
Fixes #4781 

image
image

### CODE REVIEW

**Comment by Raunaksingh100** [comment]
> Fixes #4857 
> Fixes #4858 
> Fixes #4781 
> 
> image
> image
> 

Can we plz reply to my pr what is wrong in my pr plz reply @iamareebjamal

**Comment by iamareebjamal** [comment]
When I reimplemented the UI to display the logo, the issues mentioned in the PR were solved automatically. The problem in your PR was that you were relying on a stray div for layout, which is not even a practice to be a bad practice

**Comment by Raunaksingh100** [comment]
I added a margin top to the event date plz review my Pr

**Comment by iamareebjamal** [comment]
The issue is already solved

**Comment by Raunaksingh100** [comment]
> The issue is already solved

@iamareebjamal  first you say  plz update the pr then you create a pr for this and fixed this bug and ignore my  pr which I created 7 days ago

**Comment by iamareebjamal** [comment]
You made the required changes 2 hours ago. The PR could have been created in 5000 BC, if it didn't contain required changes, it doesn't matter

**Comment by Raunaksingh100** [comment]
> You made the required changes 2 hours ago. The PR could have been created in 5000 BC, if it didn't contain required changes, it doesn't matter

@iamareebjamal no problem sir I will find some other issues 
So plz help me in my others pr 
Which I create 
Thanks

**Pull request merged**
