### PR TITLE
fix: Group: create page and edit page alike

### LINKED ISSUE #7571: Groups: Create and Edit Group page should be identical
Currently the create group page and edit group page are different. Please make them identical. As much as possible this should be abstracted and use the actual same code.

Screenshot from 2021-07-15 13-32-19

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #7571
Screenshot from 2021-07-16 15-17-19

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
When I create a new group and click on "Settings" without saving the group nothing happens.

**Comment by MeghalBisht** [comment]
> When I create a new group and click on "Settings" without saving the group nothing happens.

Yes that is expected. The settings route needs a group id to display the required group settings.
Since you did not save any group and tried to access the settings of a null group it wont work.

**Comment by mariobehling** [comment]
> > When I create a new group and click on "Settings" without saving the group nothing happens.
> 
> Yes that is expected. The settings route needs a group id to display the required group settings.
> Since you did not save any group and tried to access the settings of a null group it didnt work.

Ok, but it is confusing to have a UI element that cannot be used.

Can we move the group name to "Settings" and make that the "Create" start page?

**Comment by MeghalBisht** [comment]
> Can we move the group name to "Settings" and make that the "Create" start page?

Then the events page won't be accessible.

**Comment by mariobehling** [comment]
> > Can we move the group name to "Settings" and make that the "Create" start page?
> 
> Then the events page won't be accessible.

This would seem more logic. So 1. the user creates a group and then 2. the user can add events.

In that case the create logic should not yet show the inaccessible event tab. The event tab should be the (first) default tab for "Edit Group" just as is though.

**Comment by MeghalBisht** [comment]
@mariobehling Please check the latest changes!

**Comment by mariobehling** [comment]
Thank you.

1. Please keep the "Events" tab as the default tab on the left of "Edit Group"
2. No need to have the headings "Events" and "Group Events". Just use "Group Events" only.

Screenshot from 2021-07-20 22-30-19

**Comment by MeghalBisht** [comment]
Screenshot from 2021-07-21 16-52-16

**Review by mariobehling — DISMISSED** [review]
Thank you!

**Comment by mariobehling** [comment]
Screenshot from 2021-07-21 15-35-01

Hm. Just seeing that the "Save" button is a bit misaligned and too close to the event boxes.

**Comment by MeghalBisht** [comment]
fixed!
Screenshot from 2021-07-22 00-00-20

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
