### PR TITLE
Added status Withdrawn into sessions and speakers column in table

### LINKED ISSUE #5010: Organizer Events Dashboard: Add status "Withdrawn" into sessions and speakers column in table
On the events dashboard at https://eventyay.com/events/live in the speakers and sessions column the status "Withdrawn" and "Canceled" are missing. Please add them. Ensure it is also working on the other tabs like Draft etc.

Screenshot from 2020-09-08 08-53-20

### PR DESCRIPTION
**Pull request by AbhipsaGuru1012**
Fixes #5010 

#### Short description of what this resolves:
Added status withdrawn and canceled to sessions and speakers column in table

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Are fields like `sessionsWithdrawn` present in the model?

**Comment by AbhipsaGuru1012** [comment]
> Are fields like `sessionsWithdrawn` present in the model?

@iamareebjamal I have made the changes in model. Please have a look.

**Comment by iamareebjamal** [comment]
Is the data of fields sessionsWithdrawn coming from the backend? Screenshots?

**Comment by AbhipsaGuru1012** [comment]
> Is the data of fields sessionsWithdrawn coming from the backend? Screenshots?

event-page

The sessions and speakers columns are not available in my profile, so I am not able to see the changes. But the data of withdrawn and canceled status should be available like the other options such as submitted and accepted.

**Comment by AbhipsaGuru1012** [comment]
> > Is the data of fields sessionsWithdrawn coming from the backend? Screenshots?
> 
> event-page
> 
> The sessions and speakers columns are not available in my profile, so I am not able to see the changes. But the data of withdrawn and canceled status should be available like the other options such as submitted and accepted.

**Comment by maze-runnar** [comment]
>  The sessions and speakers columns are not available in my profile, so I am not able to see the changes.

create an event, enable session-speaker form add speakers from dash board, then test it.

**Comment by maze-runnar** [comment]
> the data of withdrawn and canceled status should be available like the other options such as submitted and accepted.

the other options are coming from backend. And withdrawn is not avail I guess. But you should test.

**Comment by mariobehling** [comment]
Due to inactivity on this PR I am closing it. Please re-open if you can work on it again. Thank you!

**Pull request closed without merging**
