### PR TITLE
fix: Using ember tables for Admin/Sales/Invoices

### LINKED ISSUE #3428: Remove Model Table from `Admin/Sales`
Parent Issue #3018

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3428

### CODE REVIEW

**Comment by kushthedude** [comment]
@CosmicCoder96 Please Review & Merge

**Comment by kushthedude** [comment]
> Looks good. Would be great if a screenshot were there 👍

There was no data in `Invoices` so left out the SS

**Comment by kushthedude** [comment]
@shreyanshdwivedi @uds5501 @CosmicCoder96 Please Review

**Comment by kushthedude** [comment]
@CosmicCoder96 Please REview

**Comment by shreyanshdwivedi** [comment]
> > Looks good. Would be great if a screenshot were there +1
> 
> There was no data in `Invoices` so left out the SS

@kushthedude you can add data manually to the db and share the screenshot. This will ensure that we are not missing something

**Pull request merged**
