### PR TITLE
fix: admin section cursor

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7568

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Unexpected error on admin area on test deployment.

Screenshot from 2021-07-17 17-02-03

**Comment by maze-runnar** [comment]
on my local it's showing correctly - 
Screenshot from 2021-07-17 22-14-09

**Comment by mariobehling** [comment]
https://open-event-frontend-git-fork-maze-runnar-cursor-eventyay.vercel.app/admin

Please test with the test deployment.

**Review by MeghalBisht — APPROVED** [review]

**Comment by MeghalBisht** [comment]
> Unexpected error on admin area on test deployment.

It is happening because the vercel deployment is using master branch of server.
We have merged changes in frontend which have a server component (which are currently merged only in test deployment.)
Hence it throws an error. We need to change the server api that vercel is consuming.

**Comment by mariobehling** [comment]
Ok, I am merging it then. We can see it on the test system.

**Comment by mariobehling** [comment]
Ok, it is not solved. Therefore reopening it.

When I go with the cursor over the green area, it becomes a hand symbol for links, but there is no link.

Screenshot from 2021-07-21 10-09-51

**Pull request merged**
