### PR TITLE
feat: Allow sorting of fields for Attendee, Speaker & Session Form

### LINKED ISSUE #6454: Attendee Form: Simplify form, fix order, show helper text
The attendee form in the wizard and public form are not ordered in the same way. Instead of alphabetical order they should be ordered according to content logic. Furthermore the implementation of address fields in Home Address, Billing Address, Shipping Address, Work Address is not complete as it is missing city, country etc. and it would be helpful if the helper text was visible in the wizard itself.

Therefore please change the following:
1. Hide the following address options but keep the standard form field "Address". For now we will not use the address options such as:
* Home Address
* Billing Address
* Shipping Address
* Work Address
2. Change the field "Address" to "Address (Street, Building, Number etc.)"
3. Change the order of the fields to the following:
- Job Title
- Phone
- Work Phone
- Age Group
- Gender
- Organisation
- Tax Business Info
- Address (Street, Building, Number etc.)
- City
- State
- Country
- Website
- Blog
- LinkedIn
- Twitter
- GitHub
- Facebook
- Instagram
- Email consent
- Partner contact consent
- Photo & video & text consent
4. Increase the width of the table and include the "Helper Text" below each option (in the same cell)
5. Ensure the order on the public form page of attendees is the same as in the wizard
6. Fix the display of the form type column - show "switch" for switches instead of "checkbox"

Screenshot from 2021-01-21 12-01-19

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6454

#### Short description of what this resolves:
Sorting added for Attendee, Speaker and Session Form

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by MeghalBisht** [comment]
| SS  | Page |
| ------------- | ------------- |
| 
Screenshot from 2021-02-12 18-11-31 | Create Session  |
|  
Screenshot from 2021-02-12 18-12-06 | Attendee Form  |
Screenshot from 2021-02-12 18-11-45 | Order Forml  |
| 
Screenshot from 2021-02-12 18-11-40| Create Speaker  |
| 
Screenshot from 2021-02-12 18-12-14 | Speaker & Session Form  |

**Comment by maze-runnar** [comment]
After switching the slider on, it seems like they are disabled. Not possible to switch off.
https://user-images.githubusercontent.com/56407566/107865966-2cc01b00-6e92-11eb-8220-c3e952350dd6.mp4

**Comment by iamareebjamal** [comment]
Check again

**Comment by MeghalBisht** [comment]
@maze-runnar works after the branch update, please check!

**Comment by maze-runnar** [comment]
yes, working now.

**Pull request merged**
