### PR TITLE
fix: Timezone issue in cfs

### LINKED ISSUE #6150: Wizard Step 1: Ticket Error for "Ticket End Date" even though end date is before Event End
Adding new tickets for an event here https://eventyay.com/events/fa96ae2c/edit/basic-details with the following dates of the event and end of ticket sales is not possible due to error message as below. Expected: It should be possible to sell tickets until the event ends.
Event End Date: 03-21-2021 23:59
Ticket End Date: 03-21-2021 23:00

Error Message:
* Ticket end date cannot be greater than event end date

Even if the end date was wrong the message should say something like:
* End of ticket sales date of [ticket names of erroneous tickets] cannot be after end of event date.

Screenshot
Screenshot from 2020-12-26 22-03-39

### LINKED ISSUE #6259: Call for Speakers: Display wrong end date
Organizers set CFS ends on 31 January 2021. On the page, it displayed 1 February 2021: https://eventyay.com/e/fa96ae2c/cfs 
Screenshot from 2021-01-06 23-16-45

### LINKED ISSUE #6500: CfS: Deadline in wizard different to deadline on public event page
At the FOSSASIA Summit the deadline on the wizard shows 11:59 SGT and the deadline on the public CfS page shows the next day 6:59 SGT. I filled in the CfS while in another timezone. Did the system confuse my browser time?

Compare https://eventyay.com/e/fa96ae2c/cfs

Screenshot from 2021-01-27 03-30-21
Screenshot from 2021-01-27 03-29-55

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #6500 
Fixes #6259 
Fixes #6150

### CODE REVIEW

**Comment by sachinchauhan2889** [comment]
## for this please try to set endsAt of cfs once again.

new pr

**Comment by sachinchauhan2889** [comment]
i think also fixing #6259

**Comment by sachinchauhan2889** [comment]
now also fix #6150

**Comment by iamareebjamal** [comment]
@sachinchauhan2889 Please implement the changes discussed in call

**Comment by iamareebjamal** [comment]
Thank You. I'll handle the lint issue and other stuff

**Pull request merged**
