### PR TITLE
fix error message for invalid email on register form.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Fixes: #2215

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This changes the error message shown on entering an invalid email address while registering a user.

#### Changes proposed in this pull request:

- change error message for invalid email address

### CODE REVIEW

**Comment by kushthedude** [comment]
@Anupam-dagar the solution you have provided still is not proper, as told by @uds5501 The error message should have been appeared like this
screenshot 2019-03-02 at 3 23 03 pm
Rather than a Invalid email
It was just my opinion still @CosmicCoder96 may tell the final review.

**Comment by Anupam-dagar** [comment]
@kushthedude can you steps which you performed beacuse that unexpected error has occured shouldnt have appeared this time. I'll fix the tooltip also.

**Comment by kushthedude** [comment]
Thats just due to my previous login attempt ,not related to the PR.
I was just saying rather than changing the text in the tag, You could have made the tooltip to display whenever user try to login with wrong E-mail.

**Comment by Anupam-dagar** [comment]
@kushthedude the issue refers to the event when the user has submitted the request using `register` button, at that time the current replacement looks good to me rather than the tooltip which is already functional while filling up the form.
Also the use case which you entered is correct in itself, it's not valid email and the tooltip is shown when it proceeds next and on submission the error. Put an input like `testemail@host`, in this case the tooltip isn't shown. But the email is wrong and hence the error to be shown after submission is correct.
Maybe it's good to show the tooltip in that case.

**Comment by kushthedude** [comment]
@Anupam-dagar ,
That was exactly my point,When you enter email like adc@adc , A tootip showing email is invalid should be there rather than a dialog box.
But that was just my suggestion the final review still be dependent on mentors :).

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I have added a regex for email validation. It accepts any value of the type `string@string.string`.

**Comment by CosmicCoder96** [comment]
um... can you point me to the issue description which this PR solves, also add it as `Fixes #`

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I changed the position of Fixes at the first line of PR description.
The issue is here https://github.com/fossasia/open-event-frontend/issues/2215

**Comment by Anupam-dagar** [comment]
This means I should do a lookup for the email entered when register button is clicked and if the user exists I should display that the user already exists.

**Comment by CosmicCoder96** [comment]
> This means I should do a lookup for the email entered when register button is clicked and if the user exists I should display that the user already exists.

No, server should return a 404 when a user does not exist and FE should handle it.

> Also is an email of the form string@string considered valid?

Yes. https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot

**Comment by Anupam-dagar** [comment]
I guess if the user email is not in database, then user should be allowed to register, right?

**Comment by CosmicCoder96** [comment]
@Anupam-dagar yes.

**Comment by Anupam-dagar** [comment]
I'll push a commit for that issue also, but for the issue #2215, is changing the message only enough?

**Comment by kushthedude** [comment]
But since ‘string@string’ is considered a valid email than why should it return the changed message.

**Comment by Anupam-dagar** [comment]
So I guess the issue is misleading, the issue shouldn't be regarding incorrect message when invalid email is entered as `string@string` is a valid email.

The main issue arises when the user try to register with an email of the type `string@string`, then the registration process doesn't get completed.
This probably needs a server side fix too, I'll do a thorough research and get back on this.

**Comment by CosmicCoder96** [comment]
Please reopen it when the server side changes, if required are complete.

**Pull request closed without merging**
