### PR TITLE
feat: add stripe payment-element support

### LINKED ISSUE #8176: Allow users to change payment methods stripe.
In the current system, the stripe redirects to the checkout page when we click the 'Pay Now' Button. There is no option to come back and change the payment method if the user doesn't want to continue with the stripe. Please make it possible.

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #8176

Screenshot:
image

Test with https://github.com/fossasia/open-event-server/pull/8428

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. As discussed, please move the web elements box below the Stripe line directly.

**Comment by pc-beast** [comment]
image
image

**Comment by pc-beast** [comment]
image
Its working for Other payment methods too

**Review by mariobehling — APPROVED** [review]
Ok, great. Let's try this on the test server.

**Pull request merged**
