### PR TITLE
dropdown for social media options

### LINKED ISSUE #4610: Basic Event Info External Links: Simplify Form by offering dropdown options
Currently the Form for social event links in the wizard step 1 requires the user to fill the name of a social media service. 

Expected: 
1. Offer a dropdown menu of all kinds of social media services and require the user to only fill in the user name.
2. Change the name "External Event URL" to "Website"

Screenshot from 2020-07-22 18-23-07

### PR DESCRIPTION
**Pull request by ruhci28**
Fixes #4610

#### Short description of what this resolves:
No need to type social media name
#### Changes proposed in this pull request:

- A dropdown with options of social media 
-
-

#### Checklist

- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)
Screenshot 2020-07-29 at 2 12 33 PM

### CODE REVIEW

**Comment by ruhci28** [comment]
Hii @iamareebjamal can you review it .

**Comment by iamareebjamal** [comment]
Issue mentions:

> Offer a dropdown menu of all kinds of social media services and require the user to only fill in the user name.

This does not fulfill **require the user to only fill in the user name**

**Comment by ruhci28** [comment]
There is a separate issue for the social media link .

**Comment by iamareebjamal** [comment]
There should be a dropdown for the option of social media, and not for the links

**Comment by ruhci28** [comment]
can you make it more clear

**Comment by iamareebjamal** [comment]
@snitin315 Can you please help?

**Comment by snitin315** [comment]
@ruhci28  The expected behavior is something like below - 
Screenshot at 2020-07-30 12-03-32

Furthermore, if the user selects Instagram the URL will change to `https://instagram.com/` and the user should only fill the username. similarly for other values.

**Comment by ruhci28** [comment]
ok

**Comment by ruhci28** [comment]
socialmedia
Hii @iamareebjamal @snitin315 , any suggestion .?

**Comment by iamareebjamal** [comment]
Looks good, is it saving the links with the prefix? Try to edit or create an event

**Comment by snitin315** [comment]
Not working as expected. You need to change the validation rules too.
Screenshot at 2020-07-31 15-31-57

Also, I get an error after correcting validation
Screenshot at 2020-07-31 15-39-37

**Pull request closed without merging**
