### PR TITLE
feat: add search feature in schedule page

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/5822

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. This position is also good.

Please fix the following:
1. When a user enters a search phrase the page jumps to the top. It should just stay where it is.
2. Add some spacing between buttons. They should not be directly connected.
Screenshot from 2020-11-29 12-55-26

**Comment by mariobehling** [comment]
Results of speakers are not showing up as expected, e.g. type in "Andrew". The session of Andrew Aitken should show up here: https://open-event-frontend-git-searchfeature.eventyay.now.sh/e/3dbaaa50/schedule?search=Andrew

**Comment by iamareebjamal** [comment]
Please add debounce to the query. The search should only happen after 250ms of user finishing the typing

**Comment by iamareebjamal** [comment]
For not reloading the page, we'll have to reimplement something like https://github.com/fossasia/open-event-frontend/issues/4882

**Review by mariobehling — CHANGES_REQUESTED** [review]
Page is moving to session heading when the search result appears. The page should not move. I

**Comment by iamareebjamal** [comment]
@mariobehling That is another issue not introduced in this PR. The issue is raised separately here https://github.com/fossasia/open-event-frontend/issues/5826

Shouldn't it be handled in another PR?

**Comment by iamareebjamal** [comment]
@mariobehling Ping

**Comment by iamareebjamal** [comment]
#5826 has been fixed in another PR, hence merging

**Pull request merged**
