### PR TITLE
fix: updated tagline

### LINKED ISSUE #6327: Update tagline on start page of platform
Change tagline on start page from "The simplest way to create events." to -> "The open source event solution for virtual and in-person events."

### PR DESCRIPTION
**Pull request by nlok5923**
Fixes #6327 

#### Short description of what this resolves:
tagline updated

#### Changes proposed in this pull request:

- updated the tagline to The open source event solution for virtual and in-person events.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by nlok5923** [comment]
Screenshot of changes:
image

**Comment by mariobehling** [comment]
After the changes in this PR the front page header text is no longer translatable and the text moved down. Please help to fix this here asap: https://github.com/fossasia/open-event-frontend/issues/6350

**Comment by mariobehling** [comment]
Or maybe weblate needs to be synced?

**Comment by nlok5923** [comment]
Sir the tagline has been hardcoded in hbs file instead rendering it from some components.

**Pull request merged**
