### PR TITLE
fix: Hotfix for non-rendering paymentCurrencies

### LINKED ISSUE #3556: Public Ticket List: `Unability of rendering of Currency Symbol`
So the following issue is due to the `Unability of rendering of Currency Symbol`

_Originally posted by @kushthedude in https://github.com/fossasia/open-event-frontend/issues/3555#issuecomment-542169132_

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3556

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I can't access the deployment. Add a before/after screenshot?

**Comment by kushthedude** [comment]
After : 
Screenshot 2019-10-16 at 3 22 34 AM

Also @iamareebjamal since I am not sure which currency was used in the following event. It wont be solved until a new release is made.

**Comment by iamareebjamal** [comment]
You can change the API_URL locally to api.eventyay.com and see if it fixes the issue

**Comment by kushthedude** [comment]
> You can change the API_URL locally to api.eventyay.com and see if it fixes the issue

Issue Solved :
Screenshot 2019-10-16 at 4 15 55 AM

Thanks for this nice little trick

**Comment by kushthedude** [comment]
But what's more interesting is that we don't have `IDR` in the `paymentsDictionary` then how was he able to enter IDR into the dropdown?

**Comment by kushthedude** [comment]
@iamareebjamal

**Comment by iamareebjamal** [comment]
Again, most probably because JS validations mean nothing?

**Comment by kushthedude** [comment]
@iamareebjamal Please merge. Also there is a need for new release for FE after this commit.

**Comment by iamareebjamal** [comment]
It's not that big a bug to warrant a release. We need to fix #3555 before

**Pull request merged**
