### PR TITLE
fix: scroll in one click

### LINKED ISSUE #5123: Public Event Page Menu: Moving to Sponsors, Organizers etc. requires two clicks
To get to sections on the same page that are listed on the menu requires two clicks, e.g. sponsors or organizers.

Compare https://eventyay.com/e/16fa59c7

Screenshot from 2020-09-23 00-38-17

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #5123 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
It does not scroll it jumps. How can we keep the scrolling effect?

**Comment by maze-runnar** [comment]
It jumps only first time, them it scrolls smooth.

**Comment by mariobehling** [comment]
> It jumps only first time, them it scrolls smooth.

So, for the first time the feature works in a different way to following times?

Features should always work in the same way.

**Comment by maze-runnar** [comment]
> > It jumps only first time, them it scrolls smooth.
> 
> So, for the first time the feature works in a different way to following times?

I have tried several ways since two hours, but it is not triggering in first time without `OnClick` and on first click it's not giving smooth scroll, after that it's working.

**Comment by mariobehling** [comment]
We had issues in other projects in the past, where it was a conflict between two JS files. If you cannot find a solution, you could also close the PR and move on to something else.

**Comment by maze-runnar** [comment]
```
<a href='#owner' {{action "scrollToTarget"}} class='item scroll'>
   <button onClick={{action "scrollToTarget"}}>
        {{t 'Organizer'}}
  </button>
 </a>
```
this is working as expected

**Comment by iamareebjamal** [comment]
Please add to the PR so we can test

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
this is giving no-nested-interactive and no-invalid-interactive error. One alternate is to use 
`<a href='#sponsor' {{action "scrollToTarget" preventDefault=false}} class='item scroll'>` from the docs. But in fist it it will jump to scroll. After that it working correctly.

**Comment by iamareebjamal** [comment]
Add `role="button"`

**Comment by maze-runnar** [comment]
> Add `role="button"` to anchor tag

it jumps for first time again

**Comment by iamareebjamal** [comment]
Disable lint by adding a comment on that line

**Comment by iamareebjamal** [comment]
It is still jumping for me

**Comment by maze-runnar** [comment]
Actually it will scroll on clicking the text, as span is put on text only.

**Comment by iamareebjamal** [comment]
Add the click listener on the menu item instead

**Comment by maze-runnar** [comment]
> Add the click listener on the menu item instead

not working, jumping from there too

**Pull request closed without merging**
