### PR TITLE
feat: adding team section for groups for managing roles

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #as per meeting notes

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@iamareebjamal I am getting this error while adding the new user role - 
`"errors": [{"detail": "Invalid type. Expected \"users-groups-roles\".", "source": {"pointer": "/data/type"}, "status": "409", "title": "Incorrect type"}], "jsonapi": {"version": "1.0"}}`

Screenshot from 2021-04-16 13-11-30

**Comment by iamareebjamal** [comment]
See the type going in the request

**Comment by maze-runnar** [comment]
> See the type going in the request
```

{data: {attributes: {email: "sd0321@gmail.com", accepted: false},…}}
data: {attributes: {email: "sd0321@gmail.com", accepted: false},…}
attributes: {email: "sd0321@gmail.com", accepted: false}
accepted: false
email: "sd0321@gmail.com"
relationships: {group: {data: {type: "group", id: "1"}}, role: {data: {type: "role", id: "1"}},…}
group: {data: {type: "group", id: "1"}}
data: {type: "group", id: "1"}
id: "1"
type: "group"
role: {data: {type: "role", id: "1"}}
data: {type: "role", id: "1"}
id: "1"
type: "role"
user: {data: {type: "user", id: "1"}}
data: {type: "user", id: "1"}
id: "1"
type: "user"
type: "users-groups-role"
```

**Comment by iamareebjamal** [comment]
Make it roles

**Comment by maze-runnar** [comment]
I am not understanding this.

**Comment by iamareebjamal** [comment]
Change model name

**Comment by iamareebjamal** [comment]
@sachinchauhan2889 Please test

**Comment by maze-runnar** [comment]
> @sachinchauhan2889 Please test

requires https://github.com/fossasia/open-event-server/pull/7894

**Review by sachinchauhan2889 — APPROVED** [review]
LGTM!

**Pull request merged**
