### PR TITLE
fix: added url to the speaker image and action buttons

### LINKED ISSUE #6376: Organizer Session Overview Page and Speaker Overview Page: Link speaker photo and speaker or session name to view page
Please link the left hand rows for name or title on the following organizer pages to the session view or the speaker view page:
* The image/speaker name on the speaker overview page should link to the speaker view page
* The session title should link to the session view page

Speaker overview page
Screenshot from 2021-01-14 23-22-38

Session overview page
Screenshot from 2021-01-14 23-19-54

### LINKED ISSUE #6541: Organizer Session/Speaker Page: Make buttons and title into a link
The action buttons and titles are not links. This means the organizer cannot simply open them in a new tab. Please change them into links. The titles should link to the organizer "view" page.

Please also make the speaker image into a link to the speaker "View" page for the organizer.

Screenshot from 2021-01-30 10-30-26
Screenshot from 2021-01-30 10-30-00

### PR DESCRIPTION
**Pull request by Creatoon**
Fixes #6541 
Fixes #6376 

#### Short description of what this resolves:
This pr adds url to the speaker image and action buttons

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by afzal442** [comment]
@Creatoon thanks for this PR. I think u missed session page to make links of the buttons.

**Comment by Creatoon** [comment]
> @Creatoon thanks for this PR. I think u missed session page to make links of the action buttons.

Thanks i just seen speakers,  i am making chengess

**Comment by afzal442** [comment]
@Creatoon Plz also add url on titles of both pages. Thanks.

**Comment by mariobehling** [comment]
Please also make the speaker name and the session title into links to the "view" page.

**Comment by Creatoon** [comment]
@mariobehling sir pr looks complete now, please have a look, thanks

**Comment by Creatoon** [comment]
@iamareebjamal sir please review, thanks

**Pull request merged**
