### PR TITLE
chore: Swap payments

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Fixes https://github.com/fossasia/open-event-frontend/issues/7758

#### Short description of what this resolves:
swap the payments methods

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@iamdevvalecha there are 2 fields of purchase on invoice - 
Screenshot from 2021-10-03 07-58-56

**Comment by iamdevvalecha** [comment]
@maze-runnar sorry for that i will fix this soon..

**Comment by iamdevvalecha** [comment]
Screenshot from 2021-10-03 14-17-00

**Comment by iamdevvalecha** [comment]
@maze-runnar fixed

**Review by pc-beast — CHANGES_REQUESTED** [review]
image
1. change it on orders page too
2. Change text from "invoice" to "Pay on Invoice"

**Comment by iamdevvalecha** [comment]
@pc-beast  done 👍🏻

**Review by pc-beast — APPROVED** [review]

**Review by maze-runnar — APPROVED** [review]

**Pull request merged**
