### PR TITLE
Url display length set

### LINKED ISSUE #5962: Virtual Events: Organizer Video Room tab long URLs overlapping column
On the video room tab long URLs are overlapping the next column. Please show a URL and if it is too long add "...".

Screenshot from 2020-12-08 15-12-35

### PR DESCRIPTION
**Pull request by nlok5923**
Fixes #5962 

#### Short description of what this resolves:
This pr resolves the issue of display and overlapping through long urls,

#### Changes proposed in this pull request:

- length of url is fixed

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
How am I going to visit the URL then?

**Comment by nlok5923** [comment]
@iamareebjamal sir please suggest any alternate way to resolve this issue.

**Comment by iamareebjamal** [comment]
See how it's done in other parts of the project

**Comment by nlok5923** [comment]
sir please can you give me a hint in which part of project such functionality is used.

**Comment by MeghalBisht** [comment]
I think you can use smart overflow (which is already used in the project) to crop the url.

**Comment by nlok5923** [comment]
Thanks @MeghalBisht i got it

**Pull request closed without merging**
