### PR TITLE
fix: Changed size of image in Attendee Landing Page (#3529) 

### LINKED ISSUE #3529: Attendee Landing Page: Change the Semantic Class for the Image used
Current Image used in the `Attendee App Landing` is much larger than it should be. Change the class used for image and fix up. 

Screenshot 2019-09-18 at 3 44 21 PM

### PR DESCRIPTION
**Pull request by nishantwrp**
Fixes #3529 

#### Short description of what this resolves:
The image in the attendee landing page is too large, therefore, it needs to be scaled down

#### Changes proposed in this pull request:
- Changed the class of image from `fluid` to `medium`

Screenshot_20191116_231105

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
What about the ample amount of space in the right side now ?

**Comment by nishantwrp** [comment]
@kushthedude What about moving everything to the center?

**Comment by kushthedude** [comment]
IMO It is not required, We will already be migrating to new landing pages for apps.
Thanks for your efforts 👍

**Comment by nishantwrp** [comment]
@kushthedude I'd advice you to close the issues, you don't want to be worked on.

**Comment by kushthedude** [comment]
There is already an issue opened for changing the way of landing pages
currently designed. Also, there are way more bugs present than changing the
semantic class of image.

**Comment by nishantwrp** [comment]
@kushthedude Sure you do have more important stuff to work on. But I'm just saying that if the issue is obsolete let's just close them.

**Comment by snitin315** [comment]
@kushthedude still valid??

**Pull request closed without merging**
