### PR TITLE
fix: change placeholder to minPrice for donation ticket

### LINKED ISSUE #8296: FOSSASIA Summit event page shows "9" in donation ticket field
The donation ticket field shows a "9" in the FOSSASIA Summit. Expected: It should show the minimum donation ticket payment set by the organizer.

Compare https://eventyay.com/e/6b901f56

Screenshot from 2022-01-23 20-54-51

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #8296

### Screenshot
image

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Does not work for me on the test deployment of this PR. Where did you get your screenshot?

Screenshot from 2022-01-24 16-25-22

**Comment by pc-beast** [comment]
> Does not work for me on the test deployment of this PR. Where did you get your screenshot?
> 
> Compare https://open-event-frontend-git-fork-pc-beast-fix-donation-eventyay.vercel.app/e/6b901f56
> 
> 

I changed API on localhost after doing changes...let me have a look again.

**Comment by pc-beast** [comment]
image

@mariobehling required changes in the database after the recent push. Works fine now

**Review by progmatic-99 — APPROVED** [review]
Screenshot 2022-01-25 at 11-51-39 FOSSASIA Summit 2022 eventyay

**Comment by pc-beast** [comment]
Change for registration

**Pull request closed without merging**
