### PR TITLE
Replaces <br> tags in system-roles and event-roles with hidden divider

### LINKED ISSUE #571: Replace the <br> tags in 'event roles' and 'sytem-roles' with hidden dividers.
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
There are <br> tags in code at event-roles.hbs and system-roles.hbs.

Expected:
We have a better way to do it by using hidden dividers in the semantic ui.

### PR DESCRIPTION
**Pull request by sumedh123**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #571

### CODE REVIEW

**Comment by sumedh123** [comment]
@niranjan94 Sorry I missed that comment. Shall I close this then?

**Comment by niranjan94** [comment]
Don't close it now since you already made a PR. Just do the requested change ... And we'll merge this soon

**Comment by sumedh123** [comment]
@niranjan94 Actually what happened was, I rebased my branch with origin/development but then I had to install the npm packages. While doing npm install, it got hanged, I tried it multiple times. It was always gettting hanged at installing a package called 'xgettext-template', so I deleted that module and tried to do npm install again which dint fix the problem for me. Then I restarted my PC and did npm install which installed the package but modified package.json.

**Comment by sumedh123** [comment]
@niranjan94 Please review.

**Pull request merged**
