### PR TITLE
fix: Match color of activated "Event Types" boxes to other boxes

### LINKED ISSUE #5675: Wizard Step 1: Match color of activated "Event Types" boxes to other boxes
The event types boxes have a black color line when they are activated, while other boxes have a blue color.

Please match the event types boxes colors and style with the other boxes. While the timezone box has a blue line around the entire form area, the event types box only has a black line around the top area. Please change this.

Compare timezone
Screenshot from 2020-11-17 15-12-28

Event types
Screenshot from 2020-11-17 15-13-03

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5675 

#### Short description of what this resolves:
Matched Color with other UiDropdown

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
Screenshot from 2020-11-18 01-26-26
@iamareebjamal Please see the changes

**Comment by daretobedifferent18** [comment]
Screenshot from 2020-11-18 04-08-59

**Comment by daretobedifferent18** [comment]
@iamareebjamal This is best I think could be done to change the styling

**Comment by iamareebjamal** [comment]
Open in chrome and read the issue

**Review by iamareebjamal — APPROVED** [review]

**Comment by daretobedifferent18** [comment]
@iamareebjamal we could add box shadow as well, this looks even better

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by daretobedifferent18** [comment]
@iamareebjamal In this PR only?

**Comment by iamareebjamal** [comment]
No, this is already merged

**Comment by daretobedifferent18** [comment]
> No, this is already merged

okay so I should refer same issue #5675 and create new one

**Comment by iamareebjamal** [comment]
same

**Pull request merged**
