### PR TITLE
update the  Readme

### PR DESCRIPTION
**Pull request by Raunaksingh100**
### description
The unnecessary Full stop you can also check in the offical readme.MD there is also present this unnecessary full-stop
I also update my branch then I found this 

@iamareebjamal  this pr are totally different from previous one so, plz review it

### screenshot before---
Capture

### after
after

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Raunaksingh100** [comment]
@iamareebjamal  this is not the old bug  which i fixed this bug i fixed after  the upadting the branch

**Comment by iamareebjamal** [comment]
It's same

**Comment by Raunaksingh100** [comment]
> It's same

No it's not same 

In first pr I remove the full stop from leads 
In this pr I removed the full stop from the to 

Plz see the file changed

**Comment by iamareebjamal** [comment]
Both are wrong and unneeded

**Comment by Raunaksingh100** [comment]
> Both are wrong and unneeded

That why I removed a full stop

**Comment by Raunaksingh100** [comment]
> > Both are wrong and unneeded
> 
> That why I removed a full stop

No need of extra full stop only need after the Explorer word

**Comment by iamareebjamal** [comment]
Sorry, my mistake that I wasn't clear. Both of **your changes** are wrong and unneeded

**Comment by Raunaksingh100** [comment]
> ### description
> The unnecessary Full stop you can also check in the offical readme.MD there is also present this unnecessary full-stop
> I also update my branch then I found this 
> 
> 
> @iamareebjamal  this pr are totally different from previous one so, plz review it
> 
> ### screenshot before---
> Capture
> 
> ### after
> after
> 
> #### Checklist
> 
> - [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
> - [x] My branch is up-to-date with the Upstream `development` branch.
> - [x] The acceptance, integration, unit tests and linter pass locally with my changes 
> - [x] I have added tests that prove my fix is effective or that my feature works
> - [x] I have added necessary documentation (if appropriate)
> 

So this is correct a full-stop after  the to in the readme.Md even the line is not ended


See my in the screenshot for the better understanding

So, i basically suggested to you the  above statement
@iamareebjamal

**Comment by iamareebjamal** [comment]
The line has ended. It is absolutely correct. No need of any change

**Comment by Raunaksingh100** [comment]
new

sure but why we need two full-stop 
and thanks for reviewing my pr 
@iamareebjamal

**Comment by iamareebjamal** [comment]
Because these are 2 separate sentences. Last time I studied English, that requires 2 full stops

**Comment by Raunaksingh100** [comment]
can you review this issue #4781

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by Raunaksingh100** [comment]
@iamareebjamal  Thanks
can i use margin:bottom with the media query to fixed that bug 
using the margin in negative is this Good or Bad plz reply

**Comment by iamareebjamal** [comment]
Please comment on the relevant issue

**Pull request closed without merging**
