### PR TITLE
Fixes the typo in languages dropdown table

### LINKED ISSUE #2845: Typo in languages drop-down
**Describe the bug**

Typo in the languages dropdown

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to home page
2. Click on 'languages'
3. See error

**Expected behaviour**

Fix the typo

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Browser : chrome
 - Version : 71.0398

**Additional context**

Working

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixes the typo in languages dropdown table

#### Changes proposed in this pull request:

- Update `languages.js`

Fixes #2845

### CODE REVIEW

**Comment by mohitm15** [comment]
@CosmicCoder96 @pradeepgangwar Review this

**Comment by mariobehling** [comment]
Please avoid micro-PRs. Please don't do PRs that take longer time to review than to create the PR. Bundle micro-PRs into a bigger one. We want to ensure that devs who review PRs use their time efficiently. Closing it therefore. Thank you.

**Comment by kushthedude** [comment]
@mariobehling Thats a great step initiative to be followed from now👍

**Comment by mohitm15** [comment]
> Please avoid micro-PRs. Please don't do PRs that take longer time to review than to create the PR. Bundle micro-PRs into a bigger one. We want to ensure that devs who review PRs use their time efficiently. Closing it therefore. Thank you.

Sure !! @mariobehling

**Comment by mohitm15** [comment]
@CosmicCoder96 what are your reviews?

**Comment by pradeepgangwar** [comment]
As pointed out by @mariobehling such PRs should be avoided. Such PRs are good for people who are new to open source and have just started contributing. I see you have already opened many PRs and you should start working on major bugs.

**Comment by mohitm15** [comment]
> As pointed out by @mariobehling such PRs should be avoided. Such PRs are good for people who are new to open source and have just started contributing. I see you have already opened many PRs and you should start working on major bugs.

@pradeepgangwar Sure Sir, Thanks for the motivation.

**Comment by CosmicCoder96** [comment]
@mohitm15 My views are that a repo admin closed this pretty trivial PR with enough justification, and you asking for my views on this already closed discussion really defeats the purpose and intent expressed through `We want to ensure that devs who review PRs use their time efficiently`

**Comment by mohitm15** [comment]
Okay @CosmicCoder96 , I will take care it from next time.

**Pull request closed without merging**
