### PR TITLE
feat:Next month for Date Filter

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes part of #2566
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of the feature:
- A filter for the events happening next month

#### Changes proposed in this pull request:

- Added next_month case in the quick-filter component

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@pradeepgangwar @CosmicCoder96 Please review.

**Comment by ritikamotwani** [comment]
@mrsaicharan1 does this filter exist on version1?
And which issue does it fix?

**Comment by mrsaicharan1** [comment]
@ritikamotwani It doesn't exist on v1. Will open a new issue for it.

**Comment by kushthedude** [comment]
@mrsaicharan1 This filter does not exist on EventYay V.1, So adding an additional filter is useless and you have not opened a specific issue related to it, Directly opening a PR without referring it to an issue is not a good practice

**Comment by mrsaicharan1** [comment]
@ritikamotwani Opened a parent issue for some missing filters.

**Comment by mrsaicharan1** [comment]
Closing this as v1 replication is the main priority.

**Comment by ritikamotwani** [comment]
Replicating v1 is the priority right now as we have to make a switch to version2 soon.
@kushthedude there's no point of repeating what I said. :D

**Pull request closed without merging**
