### PR TITLE
Delete all placeholder unit, fix failing integration tests[TEMP]

### LINKED ISSUE #1100: Tests are failing for the application
Some tests are failing on the application currently. This is affecting all incoming pull requests as contributors/reviewers are not sure if the PR is causing a test fail or it was an already failing test.

The test suite needs to be fixed on priority.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Comment out two failing integration tests
- Delete all the unit tests [temporarily] as they are the ones timing out
- Remove node 10 deployment on travis for now as broccli-postcss, a dependency in app is not compatible with node 10 as of now.

All the unit tests are the default boiler plate tests generated while creating routes and controllers and may be reinstated at a later time when we figure out where we are going wrong.

Fixes #1100

### CODE REVIEW

**Comment by CosmicCoder96** [comment]
@niranjan94 Could this possibly be a short term solution, we can add the unit tests back when we know what's wrong with the build, meanwhile depending on the existing integration and lint tests.

**Comment by niranjan94** [comment]
Deployment link: https://pr-1127-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
@CosmicCoder96 I'm okay with removing the unit tests as they already just placeholders in a way. But not okay with removing the two integration tests. Could you at-least attempt to fix those two ?

**Comment by CosmicCoder96** [comment]
@niranjan94 sure !

**Comment by niranjan94** [comment]
Deployment link: https://pr-1127-open-event-frontend-fossasia.surge.sh

**Comment by CosmicCoder96** [comment]
@niranjan94 done, please review

**Comment by niranjan94** [comment]
Deployment link: https://pr-1127-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Ah also @CosmicCoder96 . Forgot about it, can we have `tests/unit/services/sanitizer-test.js` and `tests/unit/services/loader-test.js`

---

Remove `bash scripts/pr_deploy.sh` from `.travis.yml` (Let the script file still stay in the repo). Netlify gives us auto-deployments. 

Eg. https://deploy-preview-1127--open-event-frontend.netlify.com/

**Comment by CosmicCoder96** [comment]
@niranjan94 done 👍

**Pull request merged**
