### PR TITLE
fix: standarize all pages to same

### LINKED ISSUE #5094: System Content: Standardize Pages - Terms, Privacy etc.
Our system pages should be improved. Please change the pages 
* [ ] Pricing
* [ ] Contact
* [ ] Terms and Conditions
* [ ] Refund Policy
* [ ] Privacy
* [ ] Attendee App
* [ ] Organizer App

as follows:
* [ ] make all pages into a central content column
* [ ] show the page title over a header similar to the below image
* [ ] use the same header for all pages except the mobile pages. Use the source image for the background here: https://pixabay.com/photos/startup-meeting-brainstorming-594090/ 
* [ ] use the following linked image for Attendee and Organizer App page: https://pixabay.com/photos/office-meeting-business-partners-336368/
* [ ] add a gray overlay over the image similar to the public event pages using html (do not change the source image)
Screenshot from 2020-09-19 02-04-21
* [ ] add a full-width gray bottom bar above the footer on each page with the text "Still have questions? [Visit our FAQ](https://support.eventyay.com) to find answers." Ensure you include the link.
Screenshot from 2020-09-19 02-06-43

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #5094

scrnli_9_25_2020_11-10-45 PM
scrnli_9_25_2020_11-10-27 PM
scrnli_9_25_2020_11-10-12 PM
scrnli_9_25_2020_11-09-50 PM

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I don't think central content column means center align text, which should never be done for content

**Comment by iamareebjamal** [comment]
The image is not `attendee-header`, rename it to `content-page-header`

**Comment by maze-runnar** [comment]
scrnli_9_25_2020_11-27-27 PM

**Comment by mariobehling** [comment]
Thank you.

* App pages dont seem to have an equal spacing to the left and right, left spacing is smaller than spacing to right
* Pricing page is missing page title header
* Page titles are using Page Name. They should be using Title as defined in content
Screenshot from 2020-09-26 02-41-38
* Increase height and font on bottom bar please. Compare design and font size to Eventbrite bottom bar for inspiration e.g. here https://www.eventbrite.com/support

**Review by mariobehling — APPROVED** [review]
Thank you. Looks good to me.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Sorry, I missed this:
* On the app pages there is still a menu on top. Please take this out.

Screenshot from 2020-09-28 07-43-13

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Updating the branch. Lets see if that fixes the Travis build fail.

**Pull request merged**
