### PR TITLE
feat: Implement new custom attendee form while placing the order

### LINKED ISSUE #1529: Implement new custom attendee form while placing order
**Is your feature request related to a problem? Please describe.**
Presently, while placing the order we ask only for the ticket holder's name and email-id. A new feature was added to make a custom form for the attendee. This is similar to the custom forms of speakers and sessions and the organizer can edit it as per his requirements. The form customizer on the organizer side has been implemented. It needs to be implemented on the new orders page.

**Additional context**
Parent #1452

### PR DESCRIPTION
**Pull request by mayank8318**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Adds the new custom attendee form while placing an order

#### Changes proposed in this pull request:
- Implement the new custom attendee form.
- Add validations for each field.

screenshot from 2018-08-01 16-36-12

Fixes #1529

### CODE REVIEW

**Comment by mayank8318** [comment]
@pradeepgangwar I was going to add that in another PR as this would become too big to review. Should I add it in this PR itself?

**Comment by pradeepgangwar** [comment]
@mayank8318 I am not getting field names after pulling this PR. Is this problem related to my setup? I have both server and FE updated.
screenshot_2018-08-01 screenshot 1
screenshot_2018-08-01 screenshot

**Comment by mayank8318** [comment]
@pradeepgangwar Make sure that you are running the latest server and your db is upgraded as this PR https://github.com/fossasia/open-event-server/pull/5245 is required

**Comment by pradeepgangwar** [comment]
Cool :+1:

**Comment by pradeepgangwar** [comment]
LGTM :+1:

**Pull request merged**
