### PR TITLE
Revert "Comment out login with Facebook which is not working"

### PR DESCRIPTION
**Pull request by iamareebjamal**
Reverts fossasia/open-event-frontend#2510

### CODE REVIEW

**Comment by kushthedude** [comment]
@iamareebjamal Please merge it so that it can be done in proper way

**Comment by harsh-jindal** [comment]
@iamareebjamal I am on it. Will make the requested changes made by @pradeepgangwar

**Comment by kushthedude** [comment]
@harsh-jindal please push the PR on priority

**Comment by harsh-jindal** [comment]
@kushthedude I am not able to force push to this branch since it does not exist on my local. Any Idea how can push to this branch or shall I create a new PR.

**Comment by pradeepgangwar** [comment]
@harsh-jindal You will not be to push to this branch since this branch exists on fossasia's repo and you do not have access. You need to create a new PR from older branch (from which you created 2510) or from a new branch.

**Comment by harsh-jindal** [comment]
@pradeepgangwar Okay

**Comment by kushthedude** [comment]
@harsh-jindal one more thing please comment it out from profile/application section too .
It is redundant to put the icon there too

**Pull request merged**
