### PR TITLE
Disabled auto-filling of information other than country name  during Tax Pop-up in wizard step-1

### LINKED ISSUE #4504: Tax Information Country Field offers Autofill of other information
The country field in the tax info offer overlapping auto complete info, if this info is saved in the browser. Expected: The field should not allow autocompletion of data other than the country name.

Screenshot from 2020-06-29 23-39-21

### PR DESCRIPTION
**Pull request by ShreyanshSrivastava**
Fixes #4504 

#### Short description of what this resolves:
The proposed changes disabled the auto-filling of information other than country name during the Tax Pop-up in wizard step-1.

#### Changes proposed in this pull request:

- Added @autocomplete="some-random-string" in all the input fields separately.

### old view
old-view
### new view
new-view

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I can still see the autocomplete

**Comment by ShreyanshSrivastava** [comment]
> I can still see the autocomplete

The autocomplete is now coming only for the country name field. No field other than the country name is getting filled automatically unlike previously.

**Comment by iamareebjamal** [comment]
Funny, cause the issue was about the country field only, not any other, so the issue linked in the PR won't be fixed if I merge the PR 🤷‍♂️

**Comment by ShreyanshSrivastava** [comment]
> Funny, cause the issue was about the country field only, not any other, so the issue linked in the PR won't be fixed if I merge the PR

issue
Please guide me if doing anything wrong, from what I have understood after reading the expected line is that field should not allow auto-completion of data other than the country name, because previously clicking on that field was allowing auto-completion of all other data too including country name.

**Comment by iamareebjamal** [comment]
@mariobehling Can clarify on this

**Comment by mariobehling** [comment]
>  field should not allow auto-completion of data other than the country name

That is correct and it should choose that data from the dropdown menu as well as the form sometimes might give an error.

**Pull request closed without merging**
