### PR TITLE
fix: follow group button overlapping on event page.

### LINKED ISSUE #7497: Follow group button overlapping on event page
Please move the "Follow Group" button widget to the right bottom of the sidebar for now and avoid that it overlaps with other UI elements.

Screenshot from 2021-06-30 10-47-49

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Fixes #7497 

#### Short description of what this resolves:
fixes follow group button overlapping.

#### Changes proposed in this pull request:
PREVIOUSLY:-
Screenshot from 2021-07-01 21-52-33

AFTER CHANGES:-
Screenshot from 2021-07-01 21-51-03

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ranjitkshah** [comment]
Screenshot from 2021-07-02 07-52-53
also change position for mobile view ( place it above the recent tweets button )

**Comment by iamdevvalecha** [comment]
@ranjitkshah mario sir, told me place the follow group button below tweets section.

**Comment by maze-runnar** [comment]
> @ranjitkshah mario sir, told me place the follow group button below tweets section.


then why it is above twitter section in your above screenshot?

**Comment by iamdevvalecha** [comment]
> > @ranjitkshah mario sir, told me place the follow group button below tweets section.
> 
> then why it is above twitter section in your above screenshot?

confused

**Comment by MeghalBisht** [comment]
> @ranjitkshah mario sir, told me place the follow group button below tweets section.

Screenshot from 2021-07-04 02-01-12

**Review by MeghalBisht — APPROVED** [review]

**Pull request merged**
