### PR TITLE
show tax information with each ticket.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Fixes: #2082

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This adds the tax information associated with each ticket at the event page.

#### Changes proposed in this pull request:
Show the tax information with each ticket in the table.

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
Here is the screenshot @niranjan94 
test - open event 12-02-2019 16-48-11

**Comment by Anupam-dagar** [comment]
@niranjan94 I was trying to calculate total with tax in this part of the code https://github.com/fossasia/open-event-frontend/blob/development/app/components/public/ticket-list.js#L38
I can access all properties of the ticket model by using `ticket.propertyName`. But when accessing a relationship property in this way `ticket.event.name`, this gives undefined.
This is working in the `hbs` files. What is the proper method to access the relationship attribute in the `js` file?

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar if you are not wroking on this anymore, I would like to take this up

**Comment by Anupam-dagar** [comment]
@shreyanshdwiwedi I am working on it,figuring out how I can prefetch the data.

**Comment by mrsaicharan1** [comment]
@anupam-dagar Would like to work on this.

**Comment by Anupam-dagar** [comment]
@mrsaicharan1 I was working on other issue. Please proceed.

**Comment by mrsaicharan1** [comment]
@Anupam-dagar Please close this as I would like to open a PR for this. Thanks!

**Pull request closed without merging**
