### PR TITLE
fix: Put exhibitor logo above Name and make it larger.

### LINKED ISSUE #6933: Exhibition: Increase logo size
The logo size is way too small on exhibition pages. Please increase the logo, e.g. similar to the sponsor logo sizes on the event front page.

Compare https://eventyay.com/e/fa96ae2c/exhibition/36

Screenshot from 2021-03-07 11-37-31

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #6933

### CODE REVIEW

**Comment by mariobehling** [comment]
Need to be bigger and standardized spacing between logo and below heading.

See here the logo is too small https://open-event-fro-git-fork-sachinchauhan2889-exhibitor-logo-546e87.vercel.app/e/fa96ae2c/exhibition/46

**Comment by sachinchauhan2889** [comment]
@mariobehling sir, i updated logo to medium size. Is it good or need to be some more bigger?

**Comment by sachinchauhan2889** [comment]
the space between logo and name is varying due to different sizes of logos. working on this.

**Comment by sachinchauhan2889** [comment]
Since all logo have different logo size. thats why i fixed max-height of logo to 150px and object-fit the logo also. 
space between logo and name is same in all pages. 
We still notice large white space logo and name. example:- eventyay, iosd, dsc etc.
Please inspect image. You notice image size is fixed.
white space is due to white space around logo in image. image contains smaller logo surrounded by huge space example: eventyay.
this logo need to upload again with good size.
I can scale these smaller logo but this make other logo unfit for box and some portion of them is cut.

**Comment by Naman-1234** [comment]
@sachinchauhan2889, Sir I actually my Pr is already open on this issue and I have even found the answer for dynamic Images, I was just waiting for Mario Sir Reply. So Please let me work on this one.

**Comment by sachinchauhan2889** [comment]
> @sachinchauhan2889, Sir I actually my Pr is already open on this issue and I have even found the answer for dynamic Images, I was just waiting for Mario Sir Reply. So Please let me work on this one.

@Naman-1234 sorry for this. Don't take this in wrong way.
Since fossasia summit starts today. We want logo in bigger size.

At night i was assigned to change logo size of exhibitors. I created PR. I even don't know that an issue is opened for this and your PR is active. I saw that after.

I saw your PR. You are making good efforts.

**Comment by Naman-1234** [comment]
> > @sachinchauhan2889, Sir I actually my Pr is already open on this issue and I have even found the answer for dynamic Images, I was just waiting for Mario Sir Reply. So Please let me work on this one.
> 
> @Naman-1234 sorry for this. Don't take this in wrong way.
> Since fossasia summit starts today. We want logo in bigger size.
> 
> At night i was assigned to change logo size of exhibitors. I created PR. I even don't know that an issue is opened for this and your PR is active. I saw that after.
> 
> I saw your PR. You are making good efforts.

@sachinchauhan2889  Sir Have you seen the latest Pr I did today. If yes Can you share any opinions on that. If changes are required please let me know, else Could you approve it if it fixes the issue. That will help a lot.

**Comment by iamareebjamal** [comment]
@Naman-1234 For this issue, we need less discussion and quick merge. So, I assigned Sachin on this, but as you can still see, the solution is not perfect, hence I don't think it is good to keep discussing it in 2 places with lots of comments. This PR is closer to requirement, and yours have several hit and trial related unwanted changes. Once Mario lists the required changes, we'll make changes here and merge the PR. I recommend taking up non-high priority issues first

**Comment by Naman-1234** [comment]
@iamareebjamal  Ok Sir No Problem, I have closed my PR.

**Comment by mariobehling** [comment]
I will merge this PR and follow up on the issue as this is a bit of an improvement and we need an improvement now.

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
