### PR TITLE
feat: Add contact exhibitor & Improve Exhibitor Page

### LINKED ISSUE #6649: Improve Organizer Exhibitor Page
Please also implement the following in the organizer exhibitor page:
1. Extra Links (e.g. exhibitors said they would like to add a blog or newsletter)
2. Change the "State" to work similarly to the session state: In the overview add move the column to the very left front. Do not show the "State" in the edit form of the exhibition
Screenshot from 2021-02-09 01-52-54
3. Add an "Contact Exhibitor" into the exhibitor form where the exhibitor can either add a link to a contact form or an email.
4. Add an option "Join Exhibitor Video" in the exhibitor form where the organizer can choose to add a video to the exhibitor page or not.
5. Add buttons for 3) and 4) below the social links and above the slides:
 * Button 1 "Contact Exhibitor" (in red) 
 * Button 2 "Join Exhibitor Video" (in green)
 * Only make both buttons work if users are logged in and have a ticket. Otherwise show a pop up "You need to be logged in and get a ticket in order to access these links."
Screenshot from 2021-02-09 02-25-47

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6649

#### Short description of what this resolves:

1. Change the "State" to work similarly to the session state: In the overview add move the column to the very left front. Do not show the "State" in the edit form of the exhibition
2. Add an "Contact Exhibitor" into the exhibitor form where the exhibitor can either add a link to a contact form or an email.
(only shown when user is logged in)

#### Checklist
Screenshot from 2021-02-16 04-20-56
Screenshot from 2021-02-16 04-20-43

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Ok, thank you.

1. Could you please increase the width of the column "Description" in the table and reduce the other columns width.
2. The email or link is not working as expected. It just shows "true". Compare https://open-event-frontend-git-fork-meghalbisht-exhibitor-6649.eventyay.now.sh/e/fa96ae2c/exhibition/11
* If I add an email it opens the email program and shows "true" in the email field
* If I add a URL it directs to a link on the system

I think we need to make it clearer to the user that they can enter either a link or a URL. 
Could you please add a switch button that shows a field "Enter contact URL e.g. a form link here." if switched to the left or "Enter contact email here." if switched to the right.

Screenshot from 2021-02-13 19-19-54

**Comment by MeghalBisht** [comment]
> Could you please add a switch button that shows a field "Enter contact URL e.g. a form link here." if switched to the left or "Enter contact email here." if switched to the right.

And what if one wants to add both? Shall I add both?

**Comment by mariobehling** [comment]
> > Could you please add a switch button that shows a field "Enter contact URL e.g. a form link here." if switched to the left or "Enter contact email here." if switched to the right.
> 
> And what if one wants to add both? Shall I add both?

No, we only offer one. 

Furthermore, please increase the spacing below the red button.

**Comment by MeghalBisht** [comment]
> I think we need to make it clearer to the user that they can enter either a link or an Email.
> Could you please add a switch button that shows a field "Enter contact URL e.g. a form link here." if switched to the left or "Enter contact email here." if switched to the right.

@iamareebjamal Can this be implemented as only contact field is present and hence I believe validation cannot work for email and link together, so should I create one more column in server contact email and rename this one to contact link?

**Comment by iamareebjamal** [comment]
Yes, but how will you show the switch if both of them are filled?

**Comment by MeghalBisht** [comment]
I am not sure, can you please elaborate what needs to be done. As in future if emails and links both are needed then again one column cannot do the work.

**Comment by iamareebjamal** [comment]
Will need to add one more column but not sure how the switch will work. Move ahead with adding a new column and send a PR

**Comment by mariobehling** [comment]
Ok, as this adds confusion, how about we do like that: We add two fields one for the email and one for contact URL. If the user fills in both fields we also show two buttons: a) Email b) Contact.

**Comment by mariobehling** [comment]
So, forget about the switch.

**Comment by mariobehling** [comment]
Thanks! Almost done.

* Could you please increase the width of the column "Description" in the organizer table and reduce the other columns width.
* Please add more spacing above the red buttons

Screenshot from 2021-02-16 08-06-41

**Comment by MeghalBisht** [comment]
**Update**
Screenshot from 2021-02-16 13-52-21
Screenshot from 2021-02-16 05-12-24

**Comment by iamareebjamal** [comment]
Please resolve conflicts

**Pull request merged**
