### PR TITLE
[WIP] Implement search event by name in explore events.

### LINKED ISSUE #2254: Implement search event by name in explore events.
**Is your feature request related to a problem? Please describe.**

Currently there is no option to search an event by name in event explorer at `/explore`, a user may require to search events by its name.

*Describe the solution you'd like**

Implement a search bar to search events by name.

## Screenshot
screenshot from 2019-03-04 19-03-40

**Additional context**

I am working on it.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Currently there is no search by event name option in browse events page.

#### Changes proposed in this pull request:

- Add a search by event name field in the sidebar of browse events page.

## Screenshots
screenshot from 2019-03-08 00-02-17

Fixes #2254

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
I'll continue on this tomorrow.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I'll change it according to https://github.com/fossasia/open-event-frontend/issues/1322
as pointed out by @ritikamotwani

**Comment by Anupam-dagar** [comment]
@cosmiccoder96 I'll update it in a day.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I have done some changes, its not complete, the issue coming up is that on query param change, the requset doesn't change. More appropriately, the load events and query happen only on load. Can you provide a direction on how should I take it forward, I implemented in similar way I implemented it in side bar.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 @pradeepgangwar I am able to set query parameter but it doesn't query on being set. The only time it is querying is when I hardcode the value in url, at that time I am able to receive the response in the console.
How can I execute the query on filling the input with search term and pressing enter. It currently sets only the parameter value. Also the asyncParamsDidChange wasn't working for me.

**Comment by Anupam-dagar** [comment]
> @CosmicCoder96 @pradeepgangwar I am able to set query parameter but it doesn't query on being set. The only time it is querying is when I hardcode the value in url, at that time I am able to receive the response in the console.
> How can I execute the query on filling the input with search term and pressing enter. It currently sets only the parameter value. Also the asyncParamsDidChange wasn't working for me.

@pradeepgangwar help needed.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 Help needed.

**Comment by kushthedude** [comment]
@Anupam-dagar still on it?

**Comment by Anupam-dagar** [comment]
@kushthedude I'll am working on it.

**Pull request closed without merging**
