### PR TITLE
fix: Link sessions in speaker list to sessions page

### LINKED ISSUE #4832: Link sessions in speaker list to sessions page
The session used to link to the extended session description on the "sessions page". It is not linked now.

Parent Issue: #4000

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4832 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
captured (1)

**Comment by iamareebjamal** [comment]
That's the page we want to show only to the speaker. The session page linked should show the expanded session tile on the page

**Comment by iamareebjamal** [comment]
So, `/session/:id` will be page to show to speakers (not public)

And `/sessions/:id` should be public session page with `SessionItem` component expanded.

**Comment by iamareebjamal** [comment]
Also, someone who's not a speaker shouldn't be able to see the withdraw and edit session buttons

**Comment by maze-runnar** [comment]
> Also, someone who's not a speaker shouldn't be able to see the withdraw and edit session buttons

could it be that everyone can see that page but disable button, if user is not authorized to withdraw and edit session?
is there any this kind of feature is available?

**Comment by iamareebjamal** [comment]
Buttons should be hidden but everyone can see the page

**Comment by maze-runnar** [comment]
@iamareebjamal what about this https://github.com/fossasia/open-event-frontend/issues/4832#issuecomment-678613164 ?

**Comment by maze-runnar** [comment]
is it an correct iplementation if only one of speakers can edit http://localhost:4200/e/16fa59c7/session/6240 page, but every one can see?

**Comment by maze-runnar** [comment]
Session Detail page when one is not authorized to edit details and withdraw proposal -
Screenshot from 2020-08-27 22-48-50
Session Detail page when one is authorized to edit details and withdraw proposal -
Screenshot from 2020-08-27 22-48-43

**Comment by mariobehling** [comment]
This is a single session view, right? So, there is no way to filter a session here and therefore no need to show track and room filter in the sidebar.

**Comment by iamareebjamal** [comment]
That's when I didn't remove the sidebar from other pages. @maze-runnar must not have rebased the latest changes, thus the screenshot

**Review by iamareebjamal — APPROVED** [review]

**Review by iamareebjamal — APPROVED** [review]

**Comment by mariobehling** [comment]
The implementation does not work for anonymous users. The linked page should be available openly on the web (without options to edit session details). Please give permissions to view this page for everyone. Therefore opening the issue.

Compare event here: https://eventyay.com/e/8fa7fd14/speakers and click on sessions without being logged in.

**Comment by iamareebjamal** [comment]
Opened a new issue for this

**Pull request merged**
