### PR TITLE
fix: Clicking Join Event on session don't expand & forward

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/6630

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Please post a screenshot and describe what you changed.

**Comment by mariobehling** [comment]
This is not solving the issue, compare https://open-event-frontend-git-fork-maze-runnar-expand.eventyay.vercel.app/e/19128bdf/schedule

But this is also not a priority issue. How can we focus on priority issues?

**Comment by maze-runnar** [comment]
https://user-images.githubusercontent.com/56407566/107865728-b91d0e80-6e8f-11eb-903c-2e9780e28589.mp4

**Comment by iamareebjamal** [comment]
Please focus on milestone and high priority issues only

**Comment by mariobehling** [comment]
You did not read the issue itself. There is no mentioning of the side panel in the issue. The issue talks about the sessions on the schedule. As this PR is not related to the issue mentioned, I am closing it.

**Comment by mariobehling** [comment]
But I think I might have added to the confusion as I did not mention the "Join Video" button itself. This issue appears with all buttons in the sessions area though. I wonder if this can be solved more generally. I will bring it up in the next meeting. Thanks.

**Pull request closed without merging**
