### PR TITLE
Change notification icon from mail box to bell.

### LINKED ISSUE #2475: Change notification icon from mail to bell.
**Describe the bug**

Currently the notification icon has a `mail` as its icon which is more appropriate for messages rather than notifications. `bell` icon is more suitable for notifications.

**To Reproduce**
1. Go to '/'
2. See error

**Expected behavior**

The notification icon should be bell icon.

**Screenshots**

Screenshot from 2019-04-05 20-41-28
**Additional context**

I am working on this issue.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This replaces mail icon with bell icon for notifications dropdown.

#### Changes proposed in this pull request:

- Replace mail icon with bell icon.

## Screenshots

Screenshot from 2019-04-05 20-45-35

Fixes #2475

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 @ritikamotwani please review.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 Can this be merged now?

**Comment by CosmicCoder96** [comment]
@anupam-Dagar I didn’t mean reviews from random people. We have had this
discussion about notification icon last phase before. Hence this PR is not
merged. @mariobehling will take this one.

**Comment by mariobehling** [comment]
I think this is not needed currently and the existing one is in line with the former eventbrite UI. So, seems ok as is. Let's focus on real issues that don't work currently instead of changing stuff that works well-enough.

**Pull request closed without merging**
