### PR TITLE
fix: Password input box width greater than login and register form.

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Fixes #
https://github.com/fossasia/open-event-frontend/issues/7155
#### Short description of what this resolves:
resolves ui part of password box

#### Changes proposed in this pull request:
just width part fixed
#### Checklist
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
Previous Pr was closed https://github.com/fossasia/open-event-frontend/pull/7272

**Comment by iamdevvalecha** [comment]
@ranjitkshah @MeghalBisht please review.

**Comment by iamdevvalecha** [comment]
The changes:- 
Screenshot from 2021-05-17 08-42-51

**Comment by MeghalBisht** [comment]
Why new PR?

**Comment by MeghalBisht** [comment]
> Previous Pr was closed #7272 due to some conflicts.

You could have force pushed

**Comment by iamdevvalecha** [comment]
> > Previous Pr was closed #7272 due to some conflicts.
> 
> You could have force pushed

sorry for that nxt time i will remember di

**Comment by klsingh016** [comment]
i want to work on this may i ?

**Comment by Creatoon** [comment]
@iamdevvalecha you have added the class only for login page, this issue still coming on all the forms which have password field, for ex (sign up page) also. 
Please have a look.

**Comment by iamdevvalecha** [comment]
> @iamdevvalecha you have added the class only for login page, this issue still coming on all the forms which have password field, for ex (sign up page) also.
> Please have a look.

@Creatoon ooh really bhaiya, thanks. i will fix this  i was working as per the issue it was specific to login form.

**Comment by iamdevvalecha** [comment]
Previous changes +New Changes of register page:-
Screenshot from 2021-05-18 03-22-38

**Comment by iamdevvalecha** [comment]
@MeghalBisht please review.

**Review by Creatoon — DISMISSED** [review]

**Comment by klsingh016** [comment]
can i work on this?

**Comment by iamdevvalecha** [comment]
> can i work on this?

it's a pull req.. not an issue find issue that you can solve. 😖

**Comment by MeghalBisht** [comment]
Please fix the issue with h captcha as well.
Screenshot from 2021-05-19 19-10-50

**Comment by iamdevvalecha** [comment]
sure! di

**Review by MeghalBisht — APPROVED** [review]

**Pull request merged**
