### PR TITLE
feat: Show current day schedule in schedule page if event is running.

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes https://github.com/fossasia/open-event-frontend/issues/801

#### Short description of what this resolves:
As discussed in meeting.
In this PR, if an event is running then public.sessions will show current current day schedule. 
and if event is not running it work as usual.

### CODE REVIEW

**Comment by hpdang** [comment]
@sachinchauhan2889 where is the original issue for this pull request? Please always reference to an issue, create one if it does not exist

**Comment by mariobehling** [comment]
I added https://github.com/fossasia/open-event-frontend/issues/801

**Comment by mariobehling** [comment]
Would be great to add screenshots and a short video or gif to speed up the PR process.

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-03 15-18-06

**Comment by sachinchauhan2889** [comment]
@iamareebjamal @mariobehling @maze-runnar please visit 
https://open-event-frontend-i8mewftnj-eventyay.vercel.app/e/6286ba39/schedule




https://user-images.githubusercontent.com/72552281/110083346-96a65300-7db4-11eb-827a-c9c785d19abd.mp4

**Review by mariobehling — DISMISSED** [review]
Works though with a slight delay. Not sure if it could be made faster.

**Comment by sachinchauhan2889** [comment]
now it is working faster than previous.

**Review by mariobehling — APPROVED** [review]
Works well for me.

**Comment by mariobehling** [comment]
Ok, here is a side effect when we are in the current day: Some links are changed that result in empty filtered pages: https://github.com/fossasia/open-event-frontend/issues/7016

**Pull request merged**
