### PR TITLE
Fix order date display across the app

### LINKED ISSUE #2084: Invalid date showing in Tickets
**Describe the bug**

All the dates on the Ticket Card of Tickets/Upcoming Events are showing Invalid Date

**To Reproduce**
1. Book any ticket
2. Go to MyTickets
3. See error

**Expected behavior**

I believe the footer of the ticket card must be formatted in the following way:

`{currency_symbol}{price}/Free order#____ {Date}`

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

I am working on it

### PR DESCRIPTION
**Pull request by CosmicCoder96**
#### Changes proposed in this pull request:

- Display dates based on order status
- Fixes the invalid date appearing on my tickets page.

Fixes #2084

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 Please have a look at this triage, the issue still prevails even if the order is completed
image
As you can see here, the order has been completed yet the `order.completedAt` column is displaying `null` and hence `Invalid Date`

**Comment by CosmicCoder96** [comment]
This is related to a different issue which is already opened (#1890) , regarding payment modes. I am assuming in order to place these orders you didn't have to enter any credit card details or paypal sandbox(development) mode. In production, or locally if you specify payment modes and enter paypal or stripe developer keys, it won't happen.

**Comment by uds5501** [comment]
@CosmicCoder96 Alright, Understood :+1:

**Comment by CosmicCoder96** [comment]
@uds5501 
> . I am assuming in order to place these orders you didn't have to enter any credit card details or paypal sandbox(development) mode.

Can you confirm this?

**Comment by uds5501** [comment]
@CosmicCoder96 Okay, Triaging now

**Pull request merged**
