### PR TITLE
hotfix: Reverting forms controller to ES5

### LINKED ISSUE #3733: Event Creation: Call for Speaker is Broken
**Describe the bug**

Call for Speaker is Broken.

**To Reproduce**

Steps to reproduce the behaviour:

- Create a Event.
- Fill up CFS with custom fields.
- Try to submit and see `undefined e.error` on console.

**Expected behaviour**

Fix up the CFS before the new release with hotfix for #3731

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3733

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4742182&bid=15826070)

**Comment by iamareebjamal** [comment]
Why reverting? Find the cause of the issue and fix it

**Comment by iamareebjamal** [comment]
@kushthedude Ping

**Comment by kushthedude** [comment]
Working on migrating the mixins. Forms Mixin and Event wizard mixin needs
to be updated. There are some issues while extending a created mixin to
another new one.

**Comment by iamareebjamal** [comment]
OK, then merging this for now and making a release

**Comment by kushthedude** [comment]
No, wait for release.

**Comment by kushthedude** [comment]
Custom form widget is getting shown, I recommend adding a warning div for
this tool, as it is still under development and too much primitive.

**Comment by iamareebjamal** [comment]
Then please do it soon

**Comment by iamareebjamal** [comment]
ping

**Comment by kushthedude** [comment]
> ping

PR in few minutes

**Pull request merged**
