### PR TITLE
removed random info from country dropdown

### LINKED ISSUE #5438: Country Field in Billing Information: Only show country dropdown, do not automatically fill in random info - only country
* [ ] Fix Country dropdown. It automatically shows data saved in the browsers instead of using the dropdown country option

Expected: Only show country options. Do not show other possible data saved in the browser.

Screenshot from 2020-07-30 10-25-29

### PR DESCRIPTION
**Pull request by Soumi150**
Fixes #5438 

#### Short description of what this resolves:
Removed random info from country dropdown.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Completely unrelated and absolutely wrong fix

**Comment by Soumi150** [comment]
@iamareebjamal but there was a lot of random info in the file and names of non-existent countries like Dahomey ,Guersney ,USSR and many more. Also it was repeated across all country dropdowns like tax model info etc wherever countries have been imported from this file .This probably was not a browser auto complete issue. Please look into it Sir. Thank You.

**Comment by iamareebjamal** [comment]
Yes that is not the issue this PR is solving

**Comment by Soumi150** [comment]
Those random places have been removed and are no more showing up in the drop-down.

**Pull request closed without merging**
