### PR TITLE
feat: Reorder action buttons in Event/Orders

### LINKED ISSUE #2949: Orders Page: Move Actions to first column below existing info
The actions column of the Orders Page cannot be sorted and it is not required that it has its own column. Please 
* move it to the front row
* below the existing info
* increase the size of the icons
* make it in horizontal order

Screenshot from 2019-05-18 16-20-07

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #2949

- reorders the action buttons
- remove redundant action button file

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by uds5501** [comment]
@kushthedude @shreyanshdwivedi @mrsaicharan1 Please review!

**Comment by uds5501** [comment]
@mariobehling the page after the changes : 
image

**Comment by mariobehling** [comment]
Cancel Order is missing. There is a different between cancel and delete. Cancel will show as a canceled order, while delete will just delete the whole thing and the user also cannot see it anymore.

**Comment by uds5501** [comment]
@mariobehling  wait, I will provide a better sample

**Comment by uds5501** [comment]
Screenshot from 2019-05-19 01-49-52
@mariobehling

**Pull request merged**
