### PR TITLE
fix #8959 integrate translation channels

### LINKED ISSUE #8959: [Integrate translation channels] Implement Mockup of Iframes for video channels
Subtask of #8763 

Implement the iframes that plays video translation channel and hide it, just let the audio plays in the background

### PR DESCRIPTION
**Pull request by minhho89**
issue #8763

Official PR of https://github.com/fossasia/open-event-frontend/pull/8973/

### CODE REVIEW

**Comment by cweitat** [comment]
@minhho89 take note of github lint. refer to the commits

**Review by cweitat — CHANGES_REQUESTED** [review]
follow existing liniting

**Comment by minhho89** [comment]
Forgive the lint, will refactor it later

**Review by cweitat — APPROVED** [review]
approve for now

**Comment by mariobehling** [comment]
> Dropbox redo image

It already shows in the screenshot that this is not pixel correct. Dropdown is different width to above grey box.

**Comment by minhho89** [comment]
> > Dropbox redo image
> 
> It already shows in the screenshot that this is not pixel correct. Dropdown is different width to above grey box.
> 

Will fix with the Lint issues

**Comment by minhho89** [comment]
Sorry please ignore this PR

**Comment by minhho89** [comment]
Please ignore this PR

**Comment by minhho89** [comment]
@cweitat please review the lint fixed and combobox

**Comment by cweitat** [comment]
@minhho89 codacy

**Review by cweitat — CHANGES_REQUESTED** [review]
Codacy

**Comment by minhho89** [comment]
I'd tested it before, it passed in my local 
image

Checking what's wrong

**Comment by minhho89** [comment]
Combobox fixed the pixels 
image

**Comment by minhho89** [comment]
Hello @cweitat please review

**Review by cweitat — APPROVED** [review]

**Pull request merged**
