### PR TITLE
fix: Public schedule mobile view made responsive

### LINKED ISSUE #5893: Public Schedule Mobile View: Move date and filters up
Event date and filters are not accessible as they are on the bottom on the mobile View. Please move them to the top and display tracks and rooms next to each other.

Screenshot_20201203_163827_com android chrome

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #5893 #5908 

#### Short description of what this resolves:
1. Moved date and filters to the top and displayed tracks and rooms next to each other.
2. Removed extra space b/w date and track blocks when social links are not present

Screenshots - 

**DEKSTOP VIEW :**

**without social links -**

**with social links -**

**MOBILE VIEW :** 

**without social links -**

**with social links -**

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Looks like you did not pull in all the changes that happened on this area before. Please resolve conflicts.

**Comment by MeghalBisht** [comment]
> Looks like you did not pull in all the changes that happened on this area before. Please resolve conflicts.



> Looks like you did not pull in all the changes that happened on this area before. Please resolve conflicts.

Yes just realized, updating it. Thanks

**Review by daretobedifferent18 — COMMENTED** [review]
Pls decrease the size of tracks and rooms links to .9rem
Before | After
-------- | --------
Screen Shot 2020-12-04 at 10 42 19 | Screen Shot 2020-12-04 at 10 43 13

**Comment by MeghalBisht** [comment]
> Pls decrease the size of tracks and rooms links to .9rem
> 
> Before	After
> Screen Shot 2020-12-04 at 10 42 19	Screen Shot 2020-12-04 at 10 43 13

Which breakpoint?

**Comment by daretobedifferent18** [comment]
> > Pls decrease the size of tracks and rooms links to .9rem
> 
> Which breakpoint?

u can do it for mobile view

**Review by daretobedifferent18 — COMMENTED** [review]
Working fine for me. Pls add screenshots before/after for #5908

**Comment by MeghalBisht** [comment]
> Working fine for me. Pls add screenshots before/after for #5908

Already added for both mobile & desktop. Check screenshots marked as "without social links".

**Comment by daretobedifferent18** [comment]
> Already added for both mobile & desktop. Check screenshots marked as "without social links".

Great Working fine for me

**Review by daretobedifferent18 — DISMISSED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
This looks already much better, but the test page is different to your screenshots for me. I think the following makes sense for the moment (but we need to iterate a bit more after this PR and see what works and what does not). Please implement the following order for now:
1. Date and Time
2. Social and Web Links
3. Twitter
4. Session and date filter, Search, Sort by
5. Tracks and Rooms filter
6. The list of sessions

**Comment by MeghalBisht** [comment]
Changed order screenshots-
4 and 5 order is reversed as 5 and 6 together is added as {{outlet}}.

**Comment by MeghalBisht** [comment]
@mariobehling Please review.

**Review by mariobehling — APPROVED** [review]
Thank you! Looks good for me. Let's test this more and iterate further from here. Cheers.

**Pull request merged**
