### PR TITLE
Fix date formats and add end time to tickets sales end date/time column

### LINKED ISSUE #1341: Fix date formats on public pages
**Describe the bug**
- Fix date formats on public pages of event to match it with most of the platforms for ex. eventbrite.
- Include sales end time for tickets whose sale is going on.

**Additional context**
Discussed in meeting.

### PR DESCRIPTION
**Pull request by pradeepgangwar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
- Currently event header shows short forms of month and days. As discussed in meeting we should change it to what other platforms like eventbrite use. Since they use full forms with time zone mentioned, so we are modifying it.
- Ticket sales end date/time column does not include sales end time currently. This PR adds sales end time to that column.

#### Changes proposed in this pull request:
- change date formats.
- add sales end time to tickets list.

Fixes #1341

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@srv-twry @mayank8318 @ritikamotwani @agbilotia1998. Now it looks something like this. Do you guys have something else in mind? If yes, please suggest.

screenshot_2018-07-03 tickets testing open event 1
screenshot_2018-07-03 tickets testing open event

**Comment by srv-twry** [comment]
Looks good.

**Comment by srv-twry** [comment]
@pradeepgangwar Also change it elsewhere in the project.

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 this is not possible from moment format helper itself. I think I will have to modify it with help of custom helper or component. I will check that .
@srv-twry I will check which places in app needs modification.

**Comment by CosmicCoder96** [comment]
@bhaveshAn Again, what has changed since https://github.com/fossasia/open-event-frontend/pull/1342#issuecomment-402089426 for it to be approved/reviewed.

**Comment by srv-twry** [comment]
@pradeepgangwar The changes look fine but you have to change in other places also. Please check https://github.com/fossasia/open-event-frontend/pull/1255 to know the other places where the changes need to be done.

**Pull request merged**
