### PR TITLE
fix: Group Following Tab: add group follow/unfollow buttons

### LINKED ISSUE #7520: Group Following Tab: Add Follow/Unfollow Buttons
Allow user to follow or unfollow a group from the following tab itself.

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #7520

#### Short description of what this resolves:
Screenshot from 2021-07-08 06-20-08
Screenshot from 2021-07-08 06-20-01

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by MeghalBisht** [comment]
@sachinchauhan2889 @maze-runnar @ranjitkshah Not sure why `group.follower` is not working. Can you please test it ?

**Review by maze-runnar — DISMISSED** [review]

**Comment by mariobehling** [comment]
This is not so logic. The follow button is on the page where all events that you follow already are listed. In this case it should show "unfollow" here.

A follow button should be on the groups view page, maybe on the top right somewhere.

**Comment by MeghalBisht** [comment]
@maze-runnar  @sachinchauhan2889 @ranjitkshah what is this error about?
Screenshot from 2021-07-08 06-19-07

**Comment by maze-runnar** [comment]
> @maze-runnar @sachinchauhan2889 @ranjitkshah what is this error about?
> Screenshot from 2021-07-08 06-19-07

@MeghalBisht check it now

**Comment by maze-runnar** [comment]
> This is not so logic. The follow button is on the page where all events that you follow already are listed. In this case it should show "unfollow" here.

Screenshot from 2021-07-08 13-37-56

**Comment by mariobehling** [comment]
Latest changes are not applied yet. I guess this is why the Unfollow button does not show up on the "Following" page.

Screenshot from 2021-07-16 14-12-21

**Comment by MeghalBisht** [comment]
Screenshot from 2021-07-28 20-40-54
Screenshot from 2021-07-28 20-40-49

**Comment by MeghalBisht** [comment]
@mariobehling Please check

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
