### PR TITLE
fix: simplify admin sales page

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7539
required https://github.com/fossasia/open-event-server/pull/8097/files

Screenshot from 2021-07-13 15-47-14
Screenshot from 2021-07-13 15-47-09

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
As discussed in meeting, users did not always enter their name. Therefore please change name to email and instead of showing a view icon make it into a link to the profile.

**Comment by mariobehling** [comment]
Missing is still that the ticket numbers and sales are sortable.

**Comment by maze-runnar** [comment]
> Missing is still that the ticket numbers and sales are sortable.

these are computed properties, so we can't sort on basis of it.

**Comment by maze-runnar** [comment]
Screenshot from 2021-07-14 13-05-00

**Review by MeghalBisht — APPROVED** [review]

**Comment by mariobehling** [comment]
What is the default sorting of the events here? I think default should be date? If yes, then please sort it according to date. Right not it is not sorted that way.

**Pull request merged**
