### PR TITLE
fix: Changed 'Add Session Details' to 'Add Session' (#3513)

### LINKED ISSUE #3513: Call for Speakers: Instead of "Add Session Details" there should be only "Add Session"
It could be confusing to show add session details. The button is actually to add an entirely new session. Therefore please change "Add Session Details" to "Add Session" in Call for Speakers.

Screenshot from 2019-09-08 01-35-04

### PR DESCRIPTION
**Pull request by Hardik500**
Fixes #3513

#### Short description of what this resolves:
Changed every occurrence of 'Add Session Details' to 'Add Session'

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Screenshot

Screenshot from 2019-09-15 14-44-28

### CODE REVIEW

**Comment by Hardik500** [comment]
I don't know why Codacy/PR Quality Review. Even when I click on details then on analyse it just keeps on analysing. Can someone help me with it.

**Comment by kushthedude** [comment]
@Hardik500 Before making any more PR, I request you to read  [FOSSASIA's Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia). You didn't drop any comment to the issue before making a PR. Such behaviour is discouraged. Please follow best practices from next time

**Comment by Hardik500** [comment]
Sorry @kushthedude I did it cause I was way too excited. I'll definitely remember it next time or if you want I can do it now.
But still can you please tell me what's the issue with Codacy?

**Comment by kushthedude** [comment]
> Sorry @kushthedude I did it cause I was way too excited. I'll definitely remember it next time or if you want I can do it now.
> But still can you please tell me what's the issue with Codacy?

Dont change the `.po` files and follow [Semantic PR Naming](https://github.com/probot/semantic-pull-requests)

**Comment by Hardik500** [comment]
> > Sorry @kushthedude I did it cause I was way too excited. I'll definitely remember it next time or if you want I can do it now.
> > But still can you please tell me what's the issue with Codacy?
> 
> Dont change the `.po` files and follow [Semantic PR Naming](https://github.com/probot/semantic-pull-requests)

What about the messages.pot file

**Comment by kushthedude** [comment]
> > > Sorry @kushthedude I did it cause I was way too excited. I'll definitely remember it next time or if you want I can do it now.
> > > But still can you please tell me what's the issue with Codacy?
> > 
> > 
> > Dont change the `.po` files and follow [Semantic PR Naming](https://github.com/probot/semantic-pull-requests)
> 
> What about the messages.pot file?
> 
> Should I close this PR and create a new one?
Make changes in the same and dont change any other file except `.hbs`

**Pull request merged**
