### PR TITLE
fix: make video & audio field in session edit form visible

### LINKED ISSUE #8201: Video and Audio Form Element in Session not Visible
The video form element in sessions is not showing up if it is activated later in the wizard.

Compare https://eventyay.com/events/c5cce3ed/session/7309/edit (This link is only accessible for admins)

Screenshot from 2021-12-16 23-56-03

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #8201 

To test: **Create a new event and turn on speaker-session forms and turn on audio and video fields**

Screenshot 2021-12-22 at 12-44-48 Create session Sessions test-video-field Events Open Event

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Comment by progmatic-99** [comment]
@snitin315 Are you a maintainer ?? Have you contributed previously to this repo??

**Comment by snitin315** [comment]
> Are you a maintainer ??

No

> Have you contributed previously to this repo??

Yes

**Review by pc-beast — COMMENTED** [review]
Doesn't work for old events.

**Comment by progmatic-99** [comment]
@pc-beast @mariobehling We would need to change the values in the database for the old events.

**Review by pc-beast — APPROVED** [review]

**Pull request merged**
