### PR TITLE
fix: add group widget button

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7788
Screenshot from 2021-09-20 22-04-05
Screenshot from 2021-09-20 22-04-09

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Please also 

1. On top of "Follow button" a **Row with logo of group, name of group**

Goal is to have kind of a widget.
So, please move the name of the group above the button itself. Reason is that many groups have longer names and do not fit nicely into the buttons.

**Comment by maze-runnar** [comment]
is this ok?
Screenshot from 2021-09-23 21-04-36

**Comment by mariobehling** [comment]
Could you make it a bit more like the screenshot below.

134540754-8ab3e3e4-7354-4745-a9c0-8e2b2e1130e5

Can you confirm that you show the group icon, not the group background image, please?

**Comment by mariobehling** [comment]
Please also change:
* Red color for "Following" should also be blue (no need to have the red color)
* Add a bit of spacing on between "Follow Group/Following" text and icons (on the left and right)

**Comment by maze-runnar** [comment]
> Please also change:
> 
> * Red color for "Following" should also be blue (no need to have the red color)
> * Add a bit of spacing on between "Follow Group/Following" text and icons (on the left and right)

Done
Screenshot from 2021-09-24 08-11-23

**Comment by mariobehling** [comment]
Thanks. Please also
* Link the logo and group name to the public group page
* Add a spacing above the widget. There is very little space to the above widget.

Compare https://open-event-frontend-git-fork-maze-runnar-group-widget-eventyay.vercel.app/e/c5fc6d42

Screenshot from 2021-09-24 06-10-14

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
