### PR TITLE
Enhancing UI for user-profile

### LINKED ISSUE #2591: UI for the user profile page
**Is your feature request related to a problem? Please describe.**

The UI seems to be very cohesive between the image upload instruction and User name.

**Describe the solution you'd like**

- To minimize the image upload instruction which introduces a line break between.

**Describe alternatives you've considered**

- To enchance the UI for user name ,family name and email.
 
**Screenshot**
Screenshot 2019-04-12 02:24:07

**Additional context**

Share views, like to work on it

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
  It resolves the UI issue related to user-profile page

#### Changes proposed in this pull request:

- Update `user-profile-form.hbs`

Fixes #2591 

#### Screenshot

Screenshot 2019-04-14 18:43:25

### CODE REVIEW

**Comment by ritikamotwani** [comment]
The PR has unrelated changes.
You've reopened these PRs and still they're incorrect.

**Comment by mohitm15** [comment]
@ritikamotwani Please review

**Comment by CosmicCoder96** [comment]
Changes are unrelated to this PR.

**Comment by mohitm15** [comment]
@CosmicCoder96 should I wil
l remove the unnecessary change ? Please reopen this PR

**Comment by CosmicCoder96** [comment]
I can’t reipen it because it’s from an unknown repository. Also the reason why you can’t make any changes to it @mohitm15

**Comment by mohitm15** [comment]
@CosmicCoder96 Sorry for the mistakes I commited.

**Pull request closed without merging**
