### PR TITLE
fix: add icon from create discount button under discount codes tab

### LINKED ISSUE #333: Remove add icon from discount code page under tickets to maintain uniformity
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Everywhere in the app for creating any item, we are using only text starting with "create" but in discount code page under the tickets tab, there is an additional add icon along with the text on "Create a discount" button.
 
selection_073
 
**Expected behavior:**
Remove the add icon from the "Create a discount" button to maintain consistency

**Steps to reproduce:**
Check "Create a discount" button under discount codes in tickets tab.

### PR DESCRIPTION
**Pull request by harshitagupta30**
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This PR removes the add icon from 'Create a discount' button under Discount codes under Tickets tab to maintain the consistency of Create button across the app.
image

#### Changes proposed in this pull request:
Remove the add icon.

Fixes #333 
@niranjan94 @geekyd @CosmicCoder96 @sumedh123 @utkarshnath @anu-007 Please review :+1:

### CODE REVIEW

**Comment by harshitagupta30** [comment]
@niranjan94 If we do not consider the events//tickets/discounts/ & events//tickets/access/ as they have been in https://open-event-dev.herokuapp.com then in the entire app wherever we're creating or adding something then we don't have icon with the text. I tried to make changes taking that into account. Let me know if we want to keep the icon or remove it to maintain uniformity.

**Comment by anu-007** [comment]
@harshitagupta30 I think this could be handled with PR https://github.com/fossasia/open-event-frontend/pull/292 .thanks!!

**Comment by sumedh123** [comment]
@geekyd @harshitagupta30 It would be better to add it rather than removing. It is also needed in the create access code button where I added it since I am working on it. @harshitagupta30 Add it wherever it is missing.

**Comment by niranjan94** [comment]
Lets add the plus button. 

And @harshitagupta30, your commit message is very mis-leading and doesn't make sense either.
`ix: add icon from create discount button under discount codes tab` does this supposed to mean you're adding an icon or fixing the addition of an icon or removal of the add icon ?

**Comment by harshitagupta30** [comment]
@niranjan94 Thanks for clarifying and sorry for the commit message I will make changes.

**Comment by harshitagupta30** [comment]
I am closing this PR since it was about removing the button. @sumedh123 Please make sure to add this to the access-codes tab. Thanks.

**Pull request closed without merging**
