### PR TITLE
fix: Speaker Name Shown in Overview Mode

### LINKED ISSUE #4815: Public Session Page: Speaker Name Not Shown in Overview Mode
In the overview mode, where the sessions are not expanded the speaker names are not shown. Please show the speaker name here as well.

Compare here https://eventyay.com/e/16fa59c7/sessions/all

Screenshot from 2020-08-19 09-37-03

Expected similar to website generator.

Screenshot from 2020-08-20 20-43-26

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #4815 

#### Short description of what this resolves:
In the overview mode, where the sessions are not expanded the speaker names are not shown. This PR resolves it.
Now Speaker name is shown in the overview mode of Public Session Page.

#### Changes proposed in this pull request:

- Speaker name is shown in overview mode of Public Session Page.
- His position and organisation name is also shown along with name.
#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

#### Path
/e/:event_id/schedule

#### Screenshots

__Before__
Before 4815

__After__
after 4815

### CODE REVIEW

**Comment by sachinchauhan2889** [comment]
@mariobehling @iamareebjamal please review this PR.

**Review by mariobehling — CHANGES_REQUESTED** [review]
There is an unneeded space between speaker image and name. Expected: The names should move according to the number of speakers similar to the website generator.
Screenshot from 2020-10-14 00-20-18

**Comment by sachinchauhan2889** [comment]
@mariobehling @iamareebjamal please approve these changes

**Comment by sachinchauhan2889** [comment]
@mariobehling @iamareebjamal i have removed inline CSS. please review this. please suggest any changes if required.

**Comment by Raunaksingh100** [comment]
Plz squash your commits

**Review by snitin315 — APPROVED** [review]
Looks good to me.

**Review by Raunaksingh100 — APPROVED** [review]

**Comment by sachinchauhan2889** [comment]
@mariobehling @iamareebjamal please review this PR

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
