### PR TITLE
fix: adding when sales ends in discount and access code

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/6476

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] The acceptance, integration, unit tests and linter pass locally with my changes

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Why can't null handle this?

**Comment by maze-runnar** [comment]
> Why can't null handle this?

what it means?

**Comment by iamareebjamal** [comment]
If ends_at is null, use event.ends_at

**Comment by maze-runnar** [comment]
`{"errors": [{"detail": "Field may not be null.", "source": {"pointer": "/data/attributes/valid-till"}, "status": "422", "title": "Validation error"}], "jsonapi": {"version": "1.0"}}`

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-server/pull/7680

**Comment by maze-runnar** [comment]
one thing is remaining please don't review now.

**Comment by maze-runnar** [comment]
Screenshot from 2021-01-29 17-33-30
Screenshot from 2021-01-29 17-06-41
Screenshot from 2021-01-29 17-06-37
Screenshot from 2021-01-29 16-50-13
Screenshot from 2021-01-29 16-49-00
Screenshot from 2021-01-29 16-48-54

**Pull request closed without merging**
