### PR TITLE
feat: Show "promoted to front page" posts on front page before regular events

### LINKED ISSUE #3658: Show only "Promoted to Front Page" posts on Front Page
The front page sometimes shows events that are of less relevance and have incomplete information. We already show "Featured Events" on top of the page. Featured events are controlled through the admin interface. Please implement an additional button on the admin UI "Promote to Front" page at https://eventyay.com/admin/events/live to show events in the section "Upcoming Events"

Screenshot from 2019-11-25 14-19-00

Screenshot from 2019-11-25 14-15-58

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3658

### CODE REVIEW

**Comment by kushthedude** [comment]
To be merged after https://github.com/fossasia/open-event-server/pull/6755

**Comment by iamareebjamal** [comment]
What will be the behavior on home page after this?

**Comment by kushthedude** [comment]
As expected, promoted events will be shown before and all filters are
working properly too.

**Comment by kushthedude** [comment]
@iamareebjamal  Please review

**Pull request merged**
