### PR TITLE
fix: Public Event Page: Right hand side

### LINKED ISSUE #6764: Public Event Page: Right hand side
On the right hand side of public event pages all widgets below the join event button are slightly indented. Make all widgets areas the same width as the blue join event button.

Screenshot_20210218_222254_com android chrome

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6764

#### Short description of what this resolves:
Screenshot from 2021-02-23 18-34-56
Screenshot from 2021-02-23 18-35-02

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks.

On the schedule page there is too little spacing below the icon widget.

Screenshot from 2021-02-23 16-37-47

**Comment by mariobehling** [comment]
https://open-event-frontend-git-fork-meghalbisht-responsive-eventyay.vercel.app/e/fa96ae2c/schedule

**Comment by mariobehling** [comment]
The filters are also not yet adjusted in their width.

**Comment by MeghalBisht** [comment]
Screenshot from 2021-02-23 21-20-31
Screenshot from 2021-02-23 21-20-13

**Review by mariobehling — APPROVED** [review]
Thank you!

**Pull request merged**
