### PR TITLE
fix: show social-links only on pages having side-menu

### LINKED ISSUE #4608: Call for Speakers: Only show Twitter Widget on Event Pages that are listed on the left side bar
The twitter sidebar widget shows up on all kinds of pages and even on the speaker submission pages (session page and speaker page).

Expected: Only show twitter widget on the event pages linked on the left hand side, e.g.:
Show: https://eventyay.com/e/0917096d

Do not show on: 
https://eventyay.com/e/0917096d/cfs/edit/session/6255
https://eventyay.com/e/0917096d/cfs/edit/speaker/4763
https://eventyay.com/e/0917096d/cfs/new-session

Screenshot from 2020-07-22 17-53-02

### PR DESCRIPTION
**Pull request by snitin315**
#### Short description of what this resolves:

Fixes #4608

#### Changes proposed in this pull request:

show social-links only on pages having side-menu

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
That's not what the issue says. Read again

**Comment by snitin315** [comment]
Screenshot at 2020-08-20 14-18-41
Screenshot at 2020-08-20 14-18-33
Screenshot at 2020-08-20 14-17-46

**Comment by iamareebjamal** [comment]
The opposite approach should be taken. Only allow it in certain sections, and not by route name, but by a variable `showSocialLinks` which these corresponding routes will set to true

**Review by Leovaldez42 — APPROVED** [review]

**Comment by DhairyaBahl** [comment]
-

**Comment by iamareebjamal** [comment]
> The opposite approach should be taken. Only allow it in certain sections, and not by route name, but by a variable `showSocialLinks` which these corresponding routes will set to true

.

**Pull request closed without merging**
