### PR TITLE
fix: Buttons alignment done with above rows

### LINKED ISSUE #6855: Publice Event Page: Reduce size of social icon boxes
The social icon boxes were in a good size as they fit into the width well in a number of resolutions. After we increased the font base font size the icon boxes are now bigger as well. Please keep the font size but reduce the icon boxes to the size of before.

Compare
Screenshot from 2021-02-27 21-04-32

### PR DESCRIPTION
**Pull request by Naman-1234**
Fixes #6855 
#### Short description of what this resolves:
Basically, the issue was opened due to improper alignment of buttons(4 in a row in 100% resolution).Which was making it looking asymmetrical as compared to above rows. This Pr fixes this issue and now Buttons are properly aligned as above rows.

#### Changes proposed in this pull request:

-Buttons alignment made equal to that of above rows.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Naman-1234** [comment]
@mariobehling and @iamareebjamal Sir, I think the issue is addressed now. Please have a look at the below screenshots in different resolutions for better clarity.
Screenshot (1135)
Screenshot (1136)
Screenshot (1134)
Screenshot (1137)

**Comment by Naman-1234** [comment]
@sachinchauhan2889  Sir Could you review this PR. I think this issue is fixed. Please let me know if any changes are required.

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
Thank you for PR. You are working good.
I think the horizontal space between two button must be equal to vertical space between buttons.

Currently the horizontal space between buttons is dynamic. And in mobile view it is not looking nice.


https://user-images.githubusercontent.com/72552281/111368550-0a513580-86bc-11eb-84cc-0a87177666db.mp4

 @Naman-1234 PTAL!

**Comment by Naman-1234** [comment]
@iamareebjamal Sir, Could you review this and tell me if that works or not. If not please guide me on how should I approach this 
I have tried to approach this with almost 4 approaches, you could also see it in my previous PR here https://github.com/fossasia/open-event-frontend/pull/6863.
Amongst all of them, I think this is the best-suited approach as this is making buttons responsive as well. Looking forward for your review Sir.

**Comment by Naman-1234** [comment]
@sachinchauhan2889  Sir Could you guide me,What should I do?

**Comment by Naman-1234** [comment]
@mariobehling  Sir Could you please review this. Thanks
I have tried to approach this with almost 4 approaches, you could also see it in my previous PR here #6863.
Amongst all of them, I think this is the best-suited approach as this is making buttons responsive as well. Looking forward for your review Sir.

**Comment by iamareebjamal** [comment]
@Naman-1234 If not apparent, this issue is not of priority and we are busy in other things

**Comment by Naman-1234** [comment]
@iamareebjamal Ok Sir. No Problem.

**Comment by MeghalBisht** [comment]
This solution does not work in different resolutions.

**Pull request closed without merging**
