### PR TITLE
feat: Push and highlight active video stream

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by mariobehling** [comment]
Very good. Could you make the active room a bit brighter, please? The difference is not that big that it is apparent right away.

Screenshot from 2020-12-31 08-54-42

**Comment by iamareebjamal** [comment]
image

I can change the outline from white to blue for selected item

**Comment by iamareebjamal** [comment]
Or should I make it brighter than the side panel?

image

**Comment by mariobehling** [comment]
> Or should I make it brighter than the side panel?
> 
> image

Yes, I think this one would be good.

**Pull request merged**
