### PR TITLE
fix: grey colour with space in event

### LINKED ISSUE #4975: Grey colour visible in the below of the event in mobile view
**Describe the bug**
The white space or grey colour  visible in the below of the event  and this bug only visible in the mobile view see in the screenshot given  below for the better understanding 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/19128bdf'
2. Click on 'inspect element '
3. See error

**Screenshots**
open event front

**Smartphone (please complete the following information):**
 - Device: [e.g. moto g4, iPhone6/7/8]
 - Browser [e.g. stock browser]

**Additional context**
i am working on this issue

### PR DESCRIPTION
**Pull request by Raunaksingh100**
Fixes #4975 

#### Short description of what this resolves:
The grey or space is visible in the event  in the mobile view ,,,
i mixed this bug with the media queries because this bug only visible in mobile view so, i fixed this bug completely with the media queries see in the screebshot given below for the better understanding...
@iamareebjamal plz review

### screenshot before --
nw

### screenshot after --
nw after

now

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Too complex of a fix for a too simple issue. The burden of this fix is much more than the allowance of the bug

**Comment by Raunaksingh100** [comment]
> Too complex of a fix for a too simple issue. The burden of this fix is much more than the allowance of the bug

i cannot get your point

**Comment by iamareebjamal** [comment]
The bug is too irrelevant to get solved by this complex fix. The fix of such small bug must be very simple or it is not worth solving with this amount of code.

**Comment by Raunaksingh100** [comment]
> The bug is too irrelevant to get solved by this complex fix. The fix of such small bug must be very simple or it is not worth solving with this amount of code.

we can also fixed this bug with  to add the margin-bottom without the media queries

**Comment by iamareebjamal** [comment]
Then do it

**Comment by Raunaksingh100** [comment]
> Then do it
@iamareebjamal  plz review

**Review by cggvuhh — APPROVED** [review]

**Comment by iamareebjamal** [comment]
Add before after pics

**Comment by Raunaksingh100** [comment]
> Add before after pics

added the screenshots plz review @iamareebjamal

**Comment by iamareebjamal** [comment]
The line is still there, just smaller

**Comment by Raunaksingh100** [comment]
> The line is still there, just smaller

fixed now plz review now bug is completely fixed @iamareebjamal 
added the above screenshot

**Review by cggvuhh — DISMISSED** [review]

**Comment by Raunaksingh100** [comment]
> The line is still there, just smaller

now i updated the code plz review

**Review by cggvuhh — APPROVED** [review]

**Comment by iamareebjamal** [comment]
Please update the screenshots

**Comment by Raunaksingh100** [comment]
> Please update the screenshots

updated the screenshot plz review

**Comment by iamareebjamal** [comment]
How it looked like first - 
image

How it looks like now -

**Comment by Raunaksingh100** [comment]
> How it looked like first -
> image
> 
> How it looks like now -
> image

added the screenshot for before and after

**Comment by iamareebjamal** [comment]
Doesn't matter. It doesn't look correct

**Pull request closed without merging**
