### PR TITLE
User links of deleted users are removed

### LINKED ISSUE #2609: User Links should not be visible if user is deleted
**Describe the bug**
User Links are there even if user is deleted

**Expected behaviour**
User Links should not be visible if user is deleted

**Screenshots**
u5

**Additional context**
I am working on it

### PR DESCRIPTION
**Pull request by shubham3211**
#### Short description of what this resolves:
User links of deleted users are removed

Fixes #2609

### CODE REVIEW

**Comment by ritikamotwani** [comment]
@shubham3211 , I asked you to handle it according to v1.
It's not removed for deleted users.

**Comment by shreyanshdwivedi** [comment]
@shubham3211 are you still working on it?

**Comment by shubham3211** [comment]
@shreyanshdwivedi go ahead. I am busy right now I wont be able to contribute.

**Comment by shreyanshdwivedi** [comment]
@shubham3211 okay thanks
I'll open PR for the other issues you opened too as you are busy currently. :)

**Comment by shreyanshdwivedi** [comment]
Please close this PR so that I can proceed

**Pull request closed without merging**
