### PR TITLE
fix: remove dangling comma

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Why?

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4902280&bid=16233562)

**Comment by kushthedude** [comment]
> Why?

PR was not upto standard for release . https://github.com/fossasia/open-event-frontend/pull/3855#discussion_r371944228

**Comment by kushthedude** [comment]
> > Why?
> 
> PR was not upto standard for release . [#3855 (comment)](https://github.com/fossasia/open-event-frontend/pull/3855#discussion_r371944228)

Also a warning while running the FE on local

**Pull request merged**
