### PR TITLE
fix: removed divider from events/view.hbs

### LINKED ISSUE #133: Improvement UI event/sessions
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently buttons have overflown and the divider is unnecessarily added in the parent route

screen shot 2017-06-04 at 4 12 49 pm

**Expected behavior:**

screen shot 2017-06-04 at 4 16 16 pm

@niranjan94 should I work on this , this occurred in PR #100

### PR DESCRIPTION
**Pull request by utkarshnath**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #133 
@niranjan94 plz review

### CODE REVIEW

**Comment by geekyd** [comment]
@utkarshnath Please deploy it on heroku & share the link. Thanks

**Comment by utkarshnath** [comment]
https://young-wildwood-91762.herokuapp.com plz review

**Comment by CosmicCoder96** [comment]
@geekyd 
After merging this, it introduced a whole new bug, let's both approve each pull request before merging from now on :)  I will take care of this in #142

**Comment by geekyd** [comment]
@CosmicCoder96 I intentionally merged it, as the `ui grid` was added in the parent template which was causing distortions in other sub routes. It was going to be fixed in #121.

**Pull request merged**
