### PR TITLE
fix: Add custom global filters in report tabs

### LINKED ISSUE #2331: None of Activity Logs filter is working
**Describe the bug**

The Global Filter in System Logs in Admin/Reports isn't working.

**To Reproduce**
1. Go to Admin/Reports
2. Search Anything in Global Filter
3. See error

**Expected behavior**

It should filter properly

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Chrome
 - Browser [e.g. chrome, safari] Ubuntu 16.04 LTS
 
**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Makes sure that 2 out of 3 filters are working

#### Changes proposed in this pull request:

- add `customGlobalFilter` in mail-logs and activity-logs

Fixes #2331

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 using a `user.first-name` on notification-logs is giving a `400(Bad Request) Error` any guidance would be appreciated!

**Comment by CosmicCoder96** [comment]
@uds5501 what's user.first-name? 
Do you mean user.firstName?

**Comment by uds5501** [comment]
I was referring to the property name given to the column. It's
'user.first-name'

**Comment by CosmicCoder96** [comment]
did you try changing it to camelCase?

**Pull request merged**
