### PR TITLE
feat: Add "view-session" page for cfs speaker

### LINKED ISSUE #6293: Speaker CfS Submission: Redirect speaker to private "view" page of session instead of public session page after editing
A session and speaker view page for organizers have been implemented here https://github.com/fossasia/open-event-frontend/pull/6234

We need the same kind of page for speakers for sessions submitted to the CfS.

After a speaker adds a session they are currently being directed to the future public page of their session. Instead expected is:
1. After a speaker submits a session they should be redirected to a page with all the info they entered. This page should be very plain UI (same as implemented [here](https://github.com/fossasia/open-event-frontend/pull/6234) and it should not be publicly visible.
2. The page URL should be as follows `https://eventyay.com/e/[event ID]/cfs/session/[Session ID]/`. An example would be https://eventyay.com/e/fa96ae2c/cfs/session/6612/
3. On the top add a menu with two links:
a) My Sessions
b) [Event Name] Call for Speakers 
4. Below show the following buttons:
Edit, Edit Speaker Details, Withdraw
5. The current public pages shows an option for speakers to withdraw. The withdraw button here opens a pop-up to reconfirm the speaker wants to withdraw. Please show this pop up here.

Screenshot from 2021-01-15 11-47-49

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #6293 

separate session

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thanks. Please change the following:
1. There should be no sidebars left or right, but the width should be identical to the "Edit Session Page"
2. The field "public/private" are somehow distorted, some in English but even more visible in other languages.
3. Change "Edit" to "Edit Session"
4. The edit, withdraw and edit speaker buttons are somehow misplaced

Screenshot from 2021-01-20 00-42-02

**Comment by mariobehling** [comment]
Screenshot from 2021-01-21 09-34-11

**Comment by sachinchauhan2889** [comment]
working on this.

**Comment by sachinchauhan2889** [comment]
label badge
saaaaa

**Comment by mariobehling** [comment]
You are going in the right direction. Just increase the left side column a bit more please. So it works in other resolutions as well. Thanks.

Screenshot from 2021-01-21 11-07-51

**Comment by mariobehling** [comment]
On the "My Sessions" page (https://open-event-fro-git-fork-sachinchauhan2889-separate-cfs-s-d6bd04.eventyay.now.sh/my-sessions) please also correct the links to the new private "View" session page instead of the public session page.

**Comment by sachinchauhan2889** [comment]
this much space is enough?

space

**Review by mariobehling — APPROVED** [review]
Works well now. Very good!

**Pull request merged**
