### PR TITLE
fix:Mobile schedule page schedule cut off #6761

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Fixes https://github.com/fossasia/open-event-frontend/issues/6761

#### Short description of what this resolves:

fixes mobile schedule page ui 

#### Screenshots

Screenshot from 2021-05-22 09-32-59

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
not solving I think -
open-event-frontend-ooz1pecc4-eventyay vercel app_e_fa96ae2c_schedule(Pixel 2 XL)

**Comment by iamdevvalecha** [comment]
@maze-runnar what is the screen resolution i should test?

**Comment by iamdevvalecha** [comment]
The changes look good in my mobile:-
WhatsApp Image 2021-05-28 at 15 35 56

**Comment by iamdevvalecha** [comment]
@maze-runnar @MeghalBisht please check:-

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
working for only some events.
Working here:
https://open-event-frontend-ooz1pecc4-eventyay.vercel.app/e/add36405/schedule

not working here:
https://open-event-frontend-ooz1pecc4-eventyay.vercel.app/e/fa96ae2c/schedule

**Comment by iamdevvalecha** [comment]
@sachinchauhan2889 bhaiya,i figured out that i think pr is only not working for fossasia summit 2021 tried lot of times with different approches but it does'nt work. and also pr is working for other events.

**Comment by maze-runnar** [comment]
the question is why it's not working for fossasia summit 21, and can it be
happen with other events too in future?

**Comment by mariobehling** [comment]
I also do not know, but the PR is not yet fixing the issue for all events. Therefore it cannot be merged.

**Comment by iamdevvalecha** [comment]
@mariobehling @maze-runnar @sachinchauhan2889 i checked the pr is not working summit 19,21 for old events i guess 😕. should i close this pr?

**Comment by maze-runnar** [comment]
> @mariobehling @maze-runnar @sachinchauhan2889 i checked the pr is not working summit 19,21 for old events i guess 😕. should i close this pr?

Try to fix it, if not able to then close it.

**Comment by iamdevvalecha** [comment]
> > @mariobehling @maze-runnar @sachinchauhan2889 i checked the pr is not working summit 19,21 for old events i guess confused. should i close this pr?
> 
> Try to fix it, if not able to then close it.

i will try one more time.

**Comment by maze-runnar** [comment]
reopen it, when you will fix it.

**Pull request closed without merging**
