### PR TITLE
chore: Migrate admin,account to ES6 in app/controllers

### PR DESCRIPTION
**Pull request by kushthedude**
Refers #3618 

#### Short description of what this resolves:

- Migrating the Controllers of Admin,Account section to ES6 syntax
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
@iamareebjamal Tested complete admin section with all function.
Please have a look and merge.

**Comment by iamareebjamal** [comment]
Why not using codemods to automatically do this change rather than manually doing this repetitive task?

**Comment by kushthedude** [comment]
I did try some of the codemods, but they broke almost each action since
ember community is small, none of those were compatible.
There is one codemod for ember but ultimately it again requires a manual
overlook for checking the breakage of computed property.

**Comment by iamareebjamal** [comment]
I'm talking about from ember-cli-update

**Comment by kushthedude** [comment]
I think it was used when the app was updated to 3.10 in summers. It still
left many. I will try again if it was not used.

**Comment by kushthedude** [comment]
@iamareebjamal The following happens:
- `CLI-Update` codemods does not work on babel parser and is an experimental feature which runs only on`decorators-legacy`.
- Also, The codemods always skips the main files :
 
Screenshot 2019-12-22 at 10 57 18 PM

Also, the codemods changed the hbs files rather than going to js, I don't know why:- 
Screenshot 2019-12-22 at 10 59 25 PM

Hence doing it manually.

**Comment by iamareebjamal** [comment]
For me, it changed the js files and hbs files both. hbs files need to be changed as well to glimmer syntax for octane

**Comment by kushthedude** [comment]
> For me, it changed the js files and hbs files both. hbs files need to be changed as well to glimmer syntax for octane

Can you please push the js files it changes?

**Comment by iamareebjamal** [comment]
It was a quick test. But basically converts old syntax to new ES6 syntax, getters, decorators etc

**Comment by kushthedude** [comment]
> It was a quick test. But basically converts old syntax to new ES6 syntax, getters, decorators etc

It just changes the js files in `tests` directory and none others

**Comment by iamareebjamal** [comment]
Not true

**Comment by iamareebjamal** [comment]
I ran 

```
ember update
ember update --run-codemods
```

**Comment by kushthedude** [comment]
> ```
> ember update --run-codemods
> ```

Let me try I was doing with `ember-cli-update` as I installed it globally

**Comment by iamareebjamal** [comment]
That command is installed with ember-cli-update only

**Comment by kushthedude** [comment]
> That command is installed with ember-cli-update only

Again not successful, Also it broke the complete build.

**Comment by iamareebjamal** [comment]
> it broke the complete build

That is expected

**Pull request merged**
