### PR TITLE
fix: Organizer Video Page - Move add room button and enhance design

### LINKED ISSUE #5983: Virtual Events: Organizer Video Page - Move add room button and enhance design
We now have the new feature of event rooms. For the organizer it is a bit difficult to grasp what is the difference between the two tables on the video tab for organizers. Therefore please enhance the area:
* Change the upper table color to distinguish it to the second table
* Move the "Add Room" button to the right of the search bar 
* Move "show xx entries" a bit closer to the second table. Currently it looks like it belongs to the upper table
* Check if it makes sense to separate the tables a bit more by adding some space below the first table or propose another change that achieves the same goal

Screenshot from 2020-12-10 17-45-02

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5983 

#### TODO

  - [x] Change the upper table color to distinguish it to the second table
  - [x] Move the "Add Room" button to the right of the search bar
  - [x] Move "show xx entries" a bit closer to the second table. Currently it looks like it belongs to the upper table
  - [x] Check if it makes sense to separate the tables a bit more by adding some space below the first table or propose another change that achieves the same goal

#### Screenshots
Screenshot from 2020-12-11 19-40-56

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@mariobehling @iamareebjamal pls have a look.
Left with changing table color.

**Comment by daretobedifferent18** [comment]
Screenshot from 2020-12-11 06-20-33
This look good? and if so of course we can set color what's best for styling but if this styling looks good then I think we should also change at other places as well to make styling consistent and set default table color and we can also specify specific color if we want to.

**Comment by mariobehling** [comment]
Thank you! Could you make these small changes, please:
1. Move "Add Room" to the right of the search bar.
2. Add a heading above the sections
* top: Event Video Room
* second: Session Video Rooms

**Comment by iamareebjamal** [comment]
@mariobehling Moving `Add Room` beside search bar will not be possible as search bar is part of table which is a different component

**Comment by daretobedifferent18** [comment]
@iamareebjamal @mariobehling Done

**Comment by mariobehling** [comment]
> @mariobehling Moving `Add Room` beside search bar will not be possible as search bar is part of table which is a different component

Ok, thanks for the info.

**Comment by mariobehling** [comment]
Session Video Room -> Session Video Rooms

**Review by mariobehling — APPROVED** [review]
Please take care of the room name change and then it is good to merge for me. Thanks.

**Comment by daretobedifferent18** [comment]
@mariobehling Done

**Comment by mariobehling** [comment]
Thank you for this enhancement! Please see this issue here to enhance it further: https://github.com/fossasia/open-event-frontend/issues/6005

**Comment by mariobehling** [comment]
I missed the point that you also changed all tables on all pages to come with a blue line now. This results in the blue line being very dominant on pages. Whereas: There is no reason to change the color on other pages except the video page. Please revert this specific change in the follow up PR.

**Pull request merged**
