### PR TITLE
feat: Create a pricing page with info 

### LINKED ISSUE #4741: Pricing Page: Create a pricing page with info in the central column
As the service gets more reliable we will be able to cover our cost through pro-features that users would like to pay for. Therefore please implement a pricing page at /pricing

Relevant examples of pricing pages are https://www.eventbrite.co.uk/organizer/pricing/ and https://www.papercall.io/pricing.

* [x] Change the pricing link on the footer to the page.
Screenshot from 2020-09-03 18-43-45

* [ ] On the top menu add the menu item "Pricing" behind the "Browse Events" link **but** only show it for non-logged in users. For logged in users do not show the "Pricing" tab. It is sufficient to have it in the footer for them.
Screenshot from 2020-09-03 18-54-58

* [x] Add the following to the Page Content

  * [ ] Pricing (header)
Screenshot from 2020-09-03 18-41-58

  * [x] Find the plan that's right for you.
Screenshot from 2020-08-11 15-32-54

  * [x] Add table similar to Eventbrite. Use the details as provided in the spreadsheet here: https://docs.google.com/spreadsheets/d/1WTgOEtqmeGl-p2HCsBBNKJWC8Z_owwN8hpNoggezL4Y/edit?usp=sharing

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4741

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
Screenshot from 2020-08-31 17-19-35
Screenshot from 2020-08-31 17-19-30

**Comment by mariobehling** [comment]
This design is a bit far from the design of the rest of the frontend. Could you make something more similar to the rest of the site, please?

As we only have 1 tier for now maybe also look at other pricing page examples on the Internet, e.g. Hetzner https://www.hetzner.com/webhosting

Screenshot from 2020-08-31 21-36-51

**Comment by maze-runnar** [comment]
@mariobehling I think this UI is similar to rest of website.
Screenshot from 2020-09-01 15-04-59

**Comment by iamareebjamal** [comment]
- Please make it a single table (Features, Availability)
- Add actual data in it
- Still different from website design. Look at how cards are present in Event Dashboard

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-01 22-02-39
Screenshot from 2020-09-01 22-02-36

**Comment by maze-runnar** [comment]
@iamareebjamal please review.
Screenshot from 2020-09-01 22-02-32

**Comment by iamareebjamal** [comment]
Looks good to me. Please remove double border

**Comment by mariobehling** [comment]
Thanks. Looks good to me. 

Please use a full page screenshot tool to make it easier for everyone when viewing examples.

Check out for example https://chrome.google.com/webstore/search/screenshot

**Comment by maze-runnar** [comment]
scrnli_9_2_2020_12-49-43 PM

**Comment by iamareebjamal** [comment]
Please use a container like done previously so the content doesn't span the entire page width

**Comment by maze-runnar** [comment]
> Please use a container like done previously so the content doesn't span the entire page width

it will add border like before after using grid.

**Comment by maze-runnar** [comment]
scrnli_9_2_2020_1-31-46 PM

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
