### PR TITLE
Adds creation & deletion of sessions

### LINKED ISSUE #792: Implement session & speaker creation on event panel
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add:
- File upload component
- Add API integration to create sessions

### PR DESCRIPTION
**Pull request by geekyd**
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds speaker & session creation from event panel
- Adds deletion of sessions from events panel

Fixes #792

### CODE REVIEW

**Comment by niranjan94** [comment]
Deployment link: https://pr-880-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@fossasia/open-event-frontend Please review.

**Comment by niranjan94** [comment]
Deployment link: https://pr-880-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@CosmicCoder96 Done. Please review again.

**Comment by niranjan94** [comment]
Deployment link: https://pr-880-open-event-frontend-fossasia.surge.sh

**Pull request merged**
