### PR TITLE
Adds mobile-buttons component for responsive buttons

### LINKED ISSUE #124: Propose & implement solution for overflowing buttons on mobile devices
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
- location `events/<id>/sessions`

screenshot from 2017-06-04 05-07-39

**Expected behavior:**
The buttons must not overflow the parent Div.
Please propose a solution for this problem that can be used throughout the application.

### PR DESCRIPTION
**Pull request by geekyd**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Adds mobile-buttons custom component which adds responsive behaviour to button groups, and solves overflowing of the buttons for mobile devices.

Deployment link: https://open-event-frontend-app.herokuapp.com/events/963d3ba5/sessions
Fixes #124 
@niranjan94 @CosmicCoder96 @utkarshnath @harshitagupta30 @anu-007 @sumedh123
Please review. Thanks.

### CODE REVIEW

**Comment by utkarshnath** [comment]
@geekyd I think it would look better if we keep them in same line
screen shot 2017-06-15 at 9 43 55 pm

**Comment by geekyd** [comment]
@utkarshnath @CosmicCoder96 Thanks for your inputs, I will make the suggested changes.

**Comment by geekyd** [comment]
@niranjan94 @CosmicCoder96 @utkarshnath @harshitagupta30 @anu-007 @sumedh123
I have made some changes please review.

Deployment link:
https://open-event-frontend-app2.herokuapp.com/events/963d3ba5/sessions

**Comment by geekyd** [comment]
@niranjan94 Closing this as #124 is no longer required. Thanks

**Pull request closed without merging**
