### PR TITLE
Adds UI for settings/password route

### LINKED ISSUE #126: Add password sub-route to settings route(UI only)
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
Add UI for password sub-route in settings route.

screenshot from 2017-06-04 05-20-29

- Located at `settings/password`
- Reference URL https://eventyay.com/settings/password/

### PR DESCRIPTION
**Pull request by CosmicCoder96**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Adds UI for settings/password page (with form validation)

#### Changes proposed in this pull request:

image

Fixes #126

### CODE REVIEW

**Comment by CosmicCoder96** [comment]
@niranjan94 @geekyd Please review.

**Comment by geekyd** [comment]
@CosmicCoder96 Please provide link of application(heroku) for test.

**Comment by CosmicCoder96** [comment]
@geekyd https://pr-126-opev-frontend.herokuapp.com/settings/password
PR deployment link

**Comment by geekyd** [comment]
Great job :+1:

**Pull request merged**
