### PR TITLE
feat: Schedule: Show date and time in left column

### LINKED ISSUE #5762: Schedule: Show date and time in left column
Please change the schedule view as follows:
* Show Date and time in a column on the left 
   * Compare to website generator pages (ensure left column text is aligned with right column text)
   * Also compare to sched.com schedules e.g. https://ocs2020.sched.com/

When changing this feature please ensure that the design is consistent, e.g. pictures of speakers and names of speakers should be aligned.

Screenshot from 2020-11-25 20-53-14

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5762 

#### Short description of what this resolves:
Show Date and time in a column on the left 

#### ScreenShots
Screenshot_2020-11-26 Sessions Robotics Open Event
Screenshot_2020-11-26 Sessions Robotics Open Event(1)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Mixed 24 hour time and 12 hour time. Use general date helper with 12 hour time so it works correctly with #5748

**Comment by iamareebjamal** [comment]
Remove horizontal line and add vertical line

**Comment by mariobehling** [comment]
Please also change the following:
* Time font needs to be larger to be visible
* Use a darker gray. It is too light. Difficult to see.
* Time in left column is not in one visual line with text on the right hand side

**Comment by daretobedifferent18** [comment]
Screenshot_2020-11-26 Sessions Robotics Open Event(2)
Screenshot_2020-11-26 Sessions Robotics Open Event(3)

**Comment by daretobedifferent18** [comment]
@iamareebjamal Pls let me know to make any changes in UI

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
