### PR TITLE
Added show/hide functionality for password

### LINKED ISSUE #1681: Add show/hide password button in login form
**Is your feature request related to a problem? Please describe.**

Show/hide Password button in login form

**Describe the solution you'd like**

When User presses the button , the password becomes visible

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This PR adds show/hide functionality for password in login and register form

Fixes #1681 
showhidepassword

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar please review

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi I will pull and check it. 👍

**Comment by pradeepgangwar** [comment]
I guess we can keep only one icon i.e. Eye icon if Eye Slash is not rendering. And we should keep default `showPass` as False.
Did you try to research why it is not working?

**Comment by shreyanshdwivedi** [comment]
> Did you try to research why it is not working?
Yes, I tried and I get few similar issues but did not get any appropriate saolution to this problem. It would be great if anyone can help me in this. :)

**Pull request merged**
