### PR TITLE
Video admin

### LINKED ISSUE #7183: Rename Admin "video-channels" to "Video"
Please simplify the tab "video-channels" to be "Video" in the admin section of the platform.

### PR DESCRIPTION
**Pull request by tanay123456789**
Fixes #7183 

#### Short description of what this resolves:
Renamed "video-channels" to "Video"

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by iamdevvalecha — COMMENTED** [review]
NLGTM. plz link server changes.

**Comment by iamdevvalecha** [comment]
admin panel req. it

**Comment by MeghalBisht** [comment]
No server changes are required.
It just needs a one line change. You are not testing the changes.

**Review by sachinchauhan2889 — COMMENTED** [review]
need rebasing with development branch.

**Comment by tanay123456789** [comment]
@MeghalBisht @iamdevvalecha @sachinchauhan2889 sorry yesterday I was inactive as I went for vaccination which took a good amount of time yesterday. I am new to open source contribution and there are things that are taking time in understanding. For example, @MeghalBisht ma'am is saying to test changes that I am not able to understand. I referred to codecov and ember documentation on how to test changes. I ran the "ember -test" command but to no help, I was unsuccessful in finding out any conclusion. My humble request is to guide me if possible. If this issue is very urgent to sort out then you can give it to another person however I am trying my best to sort this issue out.

**Comment by tanay123456789** [comment]
@MeghalBisht @iamdevvalecha @sachinchauhan2889 sorry yesterday I was inactive as I went for vaccination which took a good amount of time yesterday. I am new to open source contribution and there are things that are taking time in understanding. For example, @MeghalBisht ma'am is saying to test changes that I am not able to understand. I referred to codecov and ember documentation on how to test changes. I ran the "ember -test" command but to no help, I was unsuccessful in finding out any conclusion. My humble request is to guide me if possible. If this issue is very urgent to sort out then you can give it to another person however I am trying my best to sort this issue out.

**Comment by tanay123456789** [comment]
@sachinchauhan2889 I merged it by mistake

**Comment by MeghalBisht** [comment]
> I ran the "ember -test" 

By test I meant to test the changes in your localhost by running the app and then paste the screenshot of the changes here

**Comment by tanay123456789** [comment]
@MeghalBisht ok

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
None of the following change is relevant to issue. You are changing model name while creating record and fetching record from ember data.

**Pull request closed without merging**
