### PR TITLE
feature 9069:Improve mobile top menu and add calendar icon

### LINKED ISSUE #9069: Improve mobile top menu and add calendar icon
Screenshot from 2023-08-08 13-15-28
1. When a user is on an event page, please add the following menu items next the logo. The menu items should be to the right of the logo as follows:
* Schedule
* Speakers
* Exhibition

2. When a user is on a schedule page, please change the "Calendar View" to a calendar icon.
Screenshot from 2023-08-08 14-00-35

### PR DESCRIPTION
**Pull request by ntthitrinh**
Fixes #9069

#### Short description of what this resolves:
Improve mobile top menu and add calendar icon

#### Changes proposed in this pull request:

-Improve mobile top menu and add calendar icon

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Could you change this to something similar to the following please.

Screenshot from 2023-08-14 20-14-56

**Comment by ntthitrinh** [comment]
Hi @mariobehling,
I think that if we make such a change, when logging in, some screens might not have enough space to accommodate all three items at the top.
For instance, consider the images below:
image
image

**Comment by mariobehling** [comment]
This issue is only relevant for public event pages. It is not relevant for system or organizer pages. Therefore it should fit. There is not search bar or other things on this menu.

Screenshot from 2023-08-14 20-14-56

**Comment by lthanhhieu** [comment]
> This issue is only relevant for public event pages. It is not relevant for system or organizer pages. Therefore it should fit. There is no search bar or other things on this menu.
> 
> Screenshot from 2023-08-14 20-14-56

Hi @mariobehling, So I just summarize that we only display 3 buttons : Speakers, Schedule, Exhibition on the public event page. If user moves to other page like: schedule, speaker, etc. That 3 buttons will removed.

Apart from that, I think it could not be shown in the mobile with phone screen size is small such as 6 inches and less. How do you think about it? please share me your idea.

**Comment by ntthitrinh** [comment]
Hi @mariobehling, @lthanhhieu,

image
I've fixed it locally, but there isn't enough space to accommodate all the items, even though I've removed spaces between them and made the text smaller.

**Comment by mariobehling** [comment]
Please try to decrease the size a bit more. Thanks.

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket #9069 
Please help me check and verify.
Thanks,
Screenshot from 2023-08-15 18-42-12

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please reduce font size to allow some spacing and resolve conflicts.

**Comment by khangon** [comment]
> Please reduce font size to allow some spacing and resolve conflicts.

Hi @mariobehling ,
We have fixed it.
Please help me check and verify.
Thanks,
Screenshot from 2023-08-16 14-37-22

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
