### PR TITLE
Adding featured event functionality in project

### LINKED ISSUE #1925: Add Featured Event Section to Startpage
The start page currently shows latest events always. Please add a section above the current section "Featured Events".

screenshot from 2019-01-21 09-21-32

In the admin section events tab add the option "Featured" into the table. So admins can control the featured events at https://eventyay.com/admin/events/live

screenshot from 2019-01-21 10-16-04

See here:
screenshot from 2019-01-21 10-17-54

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
After this PR, a `Featured Event` toggle can be seen in the admin-event panel.

After commit phase 1 (Toggle Addition) the admin bar looks like this
testing1

#### Changes proposed in this pull request:

- Adding a `Featured Event` toggle in admin/events
- Created a new local component in admin scope for toggling

Fixes #1925

### CODE REVIEW

**Comment by uds5501** [comment]
Corresponding **server** PR : fossasia/open-event-server#5563

**Comment by uds5501** [comment]
Featured Events Display update:

ezgif com-video-to-gif 1

**Comment by uds5501** [comment]
@CosmicCoder96 please review

**Comment by CosmicCoder96** [comment]
To be opened later when server-side functionality is complete.

**Pull request closed without merging**
