### PR TITLE
feat: Session Forms: Provide dropdown field for levels

### PR DESCRIPTION
**Pull request by MeghalBisht**
related : fossasia/open-event-server#7915

Fixes: #6959

remaining task: add level filter in schedule page

Screenshot from 2021-04-27 23-54-13

#### Checklist

-  [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thank you. Please sort the list according to levels instead of alphabetically as follows:
* Beginner
* Intermediate
* Advanced
* Expert

**Comment by mariobehling** [comment]
Please also provide the option on the schedule page with a widget below the "Session Types" widget. Follow the same approach as the session widget.

Screenshot from 2021-04-28 00-32-50

**Review by sachinchauhan2889 — COMMENTED** [review]
meghal please test.

**Comment by klsingh016** [comment]
can i work on this?

**Comment by klsingh016** [comment]
can i work on this?

**Comment by MeghalBisht** [comment]
@klsingh016 Stop spamming every PR. If you want to work, go to the issues tab. Pick an issue and start working. This is not an issue but a PR.

**Comment by klsingh016** [comment]
ooookkkkkyyyyyyyiiiii

**Comment by klsingh016** [comment]
opan sorce zindabaddd

**Review by mariobehling — APPROVED** [review]

**Review by mariobehling — APPROVED** [review]
Works for me. Thanks.

**Pull request merged**
