### PR TITLE
feat: Exhibitor Page: Add Twitter Widget

### LINKED ISSUE #6721: Exhibitor Page: Add Twitter Widget
Please add a twitter widget in the central column above the exhibitor video in full width if the exhibitor has added a twitter account.

Compare: https://eventyay.com/e/fa96ae2c/exhibition/14

Screenshot from 2021-02-15 22-55-16

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6721 

#### Short description of what this resolves:
Screenshot from 2021-02-16 03-53-51

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Nice, but why is the font in the tweet so big? Can we have it in standard size?

**Comment by mariobehling** [comment]
Any chance to get rid of "Embed" and "View on Twitter"?

Screenshot from 2021-02-16 00-12-44

**Comment by MeghalBisht** [comment]
> Nice, but why is the font in the tweet so big? Can we have it in standard size?

I believe CSS cannot be applied to the twitter widget as it is rendered using a script. We can decrease the width of the tweet to make it small
Like this maybe
Screenshot from 2021-02-16 05-12-24

**Comment by MeghalBisht** [comment]
> Any chance to get rid of "Embed" and "View on Twitter"?

Done

**Comment by mariobehling** [comment]
It looks like some people have found a way to override the CSS with the huge font of Twitter. We can investigate this later or create another widget ourselves. So, this looks good to me now.

**Review by mariobehling — DISMISSED** [review]

**Comment by mariobehling** [comment]
Sorry, I found some small things:
1. The width of the twitter widget is slightly bigger than the below video and slide widget.
2. Please increase the space above the slider heading. It should be the same space as video heading.

Screenshot from 2021-02-16 09-53-12

**Comment by MeghalBisht** [comment]
**Update:**
Screenshot from 2021-02-16 14-52-35

**Comment by mariobehling** [comment]
Perfect. Thanks!

**Pull request merged**
