### PR TITLE
Add detailed rating info to overview session table #3202

### LINKED ISSUE #3202: Add detailed rating info to overview session table
The overview session table already has columns for ratings. Please add an (i) icon in the rows Avg ratings and Number of Ratings. On scroll over on these icons show:
* on avg ratings - the distribution of ratings e.g. 1 star - 3, 2 star - 0, 3 star - 4 etc.
* Number of ratings: The names of who gave how many stars

Screenshot_2019-06-26 Session Sessions Order Events Open Event(1)

The final structure which is expected from this issue -
* [x] the option to choose any star from 1 to 5
* * [ ] Also then we can have two more column showing
  * [ ] average rating
  * [ ] number of people who rated
* [ ] Columns - | Rate session | Avg Rating | No. of people rated |

Compare -

https://blog.papercall.io/ratings-changes-2847518c95cf
https://papercall.zendesk.com/hc/en-us/articles/216407887-Inviting-Co-Organizers
https://vimeo.com/174958216

### PR DESCRIPTION
**Pull request by akash2408**
Fixes #3202

#### Short description of what this resolves:
ezgif com-gif-maker (5)

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
new review sessions

average rating is not working. average rating tab is not looking nice. I think you need to show average rating, not the count of each of rating number. table is not nicely spaced. center align no. of people rated.

**Comment by akash2408** [comment]
> new review sessions
> 
> average rating is not working. average rating tab is not looking nice. I think you need to show average rating, not the count of each of rating number. table is not nicely spaced. center align no. of people rated.

on avg ratings - the distribution of ratings e.g. 1 star - 3, 2 star - 0, 3 star - 4 etc.
Number of ratings: The names of who gave how many stars

in issue it stated that in avg rating, distribution of rating is needed. and iam working on other things thnx for the review

**Comment by iamareebjamal** [comment]
I think it would be concise to show the number of ratings in hover. So only one column will remain and show horizontal stars. If you hover on 3rd star, it'll show amount of rating for that. The same column will be used to rate the session as well

**Review by sachinchauhan2889 — COMMENTED** [review]
@akash2408 you haven't followed up this PR from last 6 days. Can you continue your work? Please completed this by this week.

**Comment by akash2408** [comment]
Yes sir, i would like to continue on this pr. i will surely solve this in
this week.thanks

**Pull request closed without merging**
