### PR TITLE
fix: Move and simplify "Event Types" 

### LINKED ISSUE #5014: Wizard Step 1: Move and simplify "Event Types"
In Wizard Step 1 please

1. Move "Event Types" right below "Event Name" and above "Venue/Location".
Screenshot from 2020-09-08 11-00-27

2. Simplify the forms by moving them next to each other. There is also no need to have a box description outside of the box.
Screenshot from 2020-09-08 10-54-31

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5014 

#### Short description of what this resolves:
Moved up Event Types

#### Changes proposed in this pull request:

- Moved up event types.
- Removed Label
- Working in mobile view as well

### ScreenShots
Screenshot from 2020-11-16 02-33-38
---
#### (Mobile View)
Screenshot from 2020-11-16 02-34-13

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see the changes I have made.

**Comment by iamareebjamal** [comment]
Please don't take up issues labeled 'project', they're for the freelancer

**Comment by daretobedifferent18** [comment]
@iamareebjamal next time I will take care of that, I was not knowing. but for now can u review and if ok review and merge it.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thanks!

Please also do the following in this PR:
* Adjust the box design to match the other boxes in the areas (Compare to the Timezone box)
  * Make the box height the same as the other one-line boxes
  * Make the spacing of the text the same as in the other boxes (in particular the spacing on the left side)

**Comment by mariobehling** [comment]
Please also make the box line the same as the other boxes. Basically you could just reuse the design of the timezone box entirely. Thanks.

**Comment by iamareebjamal** [comment]
@mariobehling That's a different component from semantic UI component because semantic UI component does not work with items with `&` in them. We'll have issues like #4546 if we revert to semantic UI dropdown

**Comment by daretobedifferent18** [comment]
> @mariobehling That's a different component from semantic UI component because semantic UI component does not work with items with `&` in them. We'll have issues like #4546 if we revert to semantic UI dropdown

@iamareebjamal should i make any changes now bcz this is entirely different component than UiDropdown. So pls let me know?

**Comment by daretobedifferent18** [comment]
@iamareebjamal @mariobehling Please see the changes made.

Screen Shot 2020-11-17 at 13 37 28
---
Screenshot from 2020-11-17 13-37-03

**Comment by iamareebjamal** [comment]
Before:
image
After:
image

Options selector is much more squished now than before. And considering the height has been raised, looks much worse

**Comment by daretobedifferent18** [comment]
Screenshot from 2020-11-17 14-35-39
@iamareebjamal PLease see the chnages

**Comment by iamareebjamal** [comment]
When you are editing it anyway, why not make it the same size as the dropdown height? And change the color to grey like timezone dropdown

**Comment by daretobedifferent18** [comment]
@iamareebjamal we don't have various options, 
We have limited options to changes
I am referring from 
https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select/variables.scss
https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select/base.scss
> When you are editing it anyway, why not make it the same size as the dropdown height? And change the color to grey like timezone dropdown

Let me see this also

**Comment by iamareebjamal** [comment]
$ember-power-select-highlighted-background for color and you already know how to change height

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see the changes
Screenshot from 2020-11-17 15-14-16

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
