### PR TITLE
feat: Left align footer and capitalize item

### LINKED ISSUE #4612: Simplify footer and change to 4 column instead of 5 column
The current features of the footer would need more attention and resources, while not giving a lot of benefit. There are a number of bugs in this area. But actually a simpler footer would also serve its purpose. Therefore please simplify the footer as follows:

* Change 5 columns to 4 column
* Left align columns
* Heading "Connect With Us" -> capital W in with, capital U in us
* Provide options in the admin content area for each column here https://eventyay.com/admin/content (no hardcoding of links instead give the admin the option to change it)

The intended footer content is as follows, but the links on the support site have to be created still partly.

**Use Eventyay**
How it Works -> https://support.eventyay.com
Pricing -> https://support.eventyay.com/pricing
Event Blog -> https://blog.fossasia.org/tags/open-event

**Plan Events**
Online Registration -> https://support.eventyay.com/online-registration
Sell Event Tickets -> https://support.eventyay.com/sell-tickets
Event Management Software -> https://support.eventyay.com/open-event-software

**Find Events**
Browse Local Events -> https://eventyay.com/explore
Get the Eventyay App -> https://eventyay.com/attendee-app
Organizer App -> https://eventyay.com/organizer-app

**Connect With Us**
Blog -> https://http://blog.fossasia.org/tag/open-event/
Facebook -> https://www.facebook.com/eventyay/
Twitter -> https://twitter.com/eventyay
GitHub -> https://github.com/fossasia/open-event-orga-server/
YouTube -> https://www.youtube.com/fossasiaorg

Screenshot from 2020-07-22 19-12-08

### PR DESCRIPTION
**Pull request by chetas411**
Fixes #4612 - author @mariobehling 

#### Short description of what this resolves:
This aligns the footer columns to left using semantic UI classes and corrects the capitalization in one footer heading 

#### Changes proposed in this pull request:

-left align the footer columns
-Heading "Connect With Us"-> capital 'W' in "with", capital 'U' in "us"
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
open event footer

### CODE REVIEW

**Comment by chetas411** [comment]
I have used semantics UI to align the columns as suggested by @snitin315

**Comment by chetas411** [comment]
Please review my PR @snitin315 @mariobehling @iamareebjamal

**Comment by iamareebjamal** [comment]
Please rename PR title according to semantic guidelines

**Comment by chetas411** [comment]
Where can I take reference for semantic guidelines?

**Comment by iamareebjamal** [comment]
See merged PRs title

**Comment by chetas411** [comment]
> See merged PRs title

Changed the PR title , please review it.

**Comment by chetas411** [comment]
when this PR will merge ?

**Comment by chetas411** [comment]
@iamareebjamal  sir can you too review the PR ?

**Comment by iamareebjamal** [comment]
Proper title should mention specific fixes. "Simplify footer" is too generic

"Left align footer and capitalize item"

**Comment by iamareebjamal** [comment]
And it was a fix

**Comment by chetas411** [comment]
> And it was a fix

oh okay thanks

**Pull request merged**
