### PR TITLE
fix: Add scroll to top button

### LINKED ISSUE #3635: Add scroll to top button for long pages
**Is your feature request related to a problem? Please describe.**
It will take time to scroll pages like event browsing if there are large number of events.

**Describe the solution you'd like**
A scroll to top button will enhance user experience by allowing users to scroll to top on a single click. 

**Additional context**
I am working on this.

### PR DESCRIPTION
**Pull request by sharmaaditya570191**
Fixes #3635

#### Short description of what this resolves:
Adds scroll to top button to enable easy scrolling for long pages.

#### Changes proposed in this pull request:

- Add scroll to top button  
#### Screenshot  
Screenshot from 2019-11-17 02-19-42

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Hi @iamareebjamal . Please review this.

**Comment by iamareebjamal** [comment]
Not needed

**Comment by sharmaaditya570191** [comment]
Hi @iamareebjamal . Scroll to top button can be helpful for pages like browse events page where there can be large number of events. What do you think about it?

**Comment by kushthedude** [comment]
Not needed

**Pull request closed without merging**
