### PR TITLE
fix: standardize follow/unfollow button in groups

### LINKED ISSUE #7862: Standardize group follow/unfollow button
Please change the group follow/unfollow button on group pages to match the design of the button on event pages. Merge the two buttons on the group page into one as on the event pages.

Currently

Screenshot from 2021-09-25 11-37-13

Expected

Screenshot from 2021-09-25 11-36-33

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #7862 
ss_1632640311
ss_1632640286

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Expected

Screenshot from 2021-09-25 11-36-33

**Comment by progmatic-99** [comment]
@mariobehling 

ss_1632664481
ss_1632664495

**Comment by maze-runnar** [comment]
@progmatic-99 can you please fix UI for mobile too.
Screenshot from 2021-09-26 20-32-15

**Comment by progmatic-99** [comment]
@maze-runnar Done.

**Comment by mariobehling** [comment]
Looks like the changes resulted in a different size of follower icons. Please only change the button.

Screenshot from 2021-09-26 19-48-19

Compare https://open-event-frontend-git-fork-progmatic-99-fix-7862-eventyay.vercel.app/g/40

**Comment by progmatic-99** [comment]
ss_1632681487

**Comment by maze-runnar** [comment]
@progmatic-99 please align it in center, 
Screenshot from 2021-09-27 06-51-29

**Comment by progmatic-99** [comment]
Screen Shot 2021-09-27 at 13 30 11

**Comment by mariobehling** [comment]
Space above blue button was increased compared to the previous button. Expected: Change the button itself. Do not change the spacing above the button.

Screenshot from 2021-09-28 13-05-33

**Comment by progmatic-99** [comment]
ss_1632829278

**Review by maze-runnar — APPROVED** [review]

**Comment by maze-runnar** [comment]
@mariobehling

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
