### PR TITLE
fix: Add checkbox in session card

### LINKED ISSUE #5788: My Schedule Page: Show two areas a) My Speaker Sessions b) My Schedule
On the my schedule page there should be two areas. Please implement them as follows:
1. My Speaker Sessions
2. My Schedule

Style-wise please use the existing styles of session tiles.

Below an example of "My Speaker Sessions"

Screenshot from 2020-11-27 19-22-41

Below is an example of "My Schedule". 

Screenshot from 2020-11-27 19-21-38

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
fixes #5788 icon part.

this PR implement circle Checkbox icon in session card instead of star icon. This is discussed in meeting.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
That's wrong. Use checkbox icon from fontawesome

As discussed in call, take care of details in PR and think what should be the end result

**Comment by iamareebjamal** [comment]
check circle should be filled

**Comment by mariobehling** [comment]
Thank you. Could you add some spacing on the left-hand side of the button, please? There should be some more spacing between the "Join Video" button and the tick box.

Screenshot from 2021-02-17 23-56-50


Please change the message "Please login to favourite this session" -> "Please login to add a session to your personal schedule."

Do not forget to include the full stop.

**Comment by mariobehling** [comment]
There is a change of the spacing and position of the heading in this test deployment. Not sure why it is there and where it comes from. There should not be any change here.

Screenshot from 2021-02-18 00-26-25

**Comment by iamareebjamal** [comment]
It's not added in this PR

**Pull request merged**
