### PR TITLE
video tab URL made consistent

### LINKED ISSUE #6186: Make video tab URL name consistent with tab name
The video tab URL on event organizer menus is https://eventyay.com/events/[event ID]/videoroom/. The tab name is "Video". Please make this consistent and change the video URL to https://eventyay.com/events/[event ID]/video/ therefore.

Screenshot from 2020-12-31 09-09-23

### PR DESCRIPTION
**Pull request by afzal442**
Fixes #6186 

#### Changes proposed in this pull request:

- changed video file locations
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Please add a screenshot of a working video tab. If PRs are not finished, please use the option to make a Draft PR.

**Comment by iamareebjamal** [comment]
Only 1 file and 1 line needs to be changed

**Comment by afzal442** [comment]
@iamareebjamal Sir, I am getting below result now. Should I close this PR since it's failed and if there is an alternative solution for this? Thanks.
c2

**Comment by iamareebjamal** [comment]
See router.js

**Comment by afzal442** [comment]
> See router.js

I m not able to get it. What else I need to change?

**Comment by iamareebjamal** [comment]
Undo all changes and make changes there

**Comment by afzal442** [comment]
Closing this for now.

**Comment by iamareebjamal** [comment]
This is all you had to do https://github.com/fossasia/open-event-frontend/pull/6197/files

After telling it to undo all changes and make changes in router.js and look at session route, you still couldn't

**Pull request closed without merging**
