### PR TITLE
feat: Add groups filter in explore page.

### LINKED ISSUE #7588: Search: Add option to search for Groups
On meetup.com a user can search either for events on the calendar or for groups.

Please implement such a search filter option on the search page https://eventyay.com/explore of eventyay as well. Enable the user to search either for events or for groups. Change the left side bar accordingly and show the date option to display all groups with e.g. past and future events etc.

Ensure that the search box adheres to the filter set when performing a new search.

Screenshot from 2021-07-20 14-00-04

Screenshot from 2021-07-20 14-03-09

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #7588

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thank you. Please also see the following:
1. Hide filters when the user chooses the group search.
Screenshot from 2021-07-28 13-28-39

2. Do not apply filters when the user chooses the group option.
3. Currently the user can see the search results for a group, but cannot access the group page if not logged in. Enable the user to access group pages without being logged in.

**Comment by mariobehling** [comment]
Maybe consider solving this issue with this PR also https://github.com/fossasia/open-event-frontend/issues/7587

**Comment by mariobehling** [comment]
Just to clarify: The event filters do not make sense for groups in the same way, e.g. past and future filters do not make sense as groups can have both past and future events. Also other filters for groups do not make sense. We can discuss filters for groups at a later stage, but group filters would be different to event filters in any case.

**Comment by sachinchauhan2889** [comment]
- [X] Separate view page of group.
- [X] make view page of group public.
- [X] Hide follow button if user is not logged in.

**Comment by sachinchauhan2889** [comment]
`Currently the user can see the search results for a group, but cannot access the group page if not logged in. Enable the user to access group pages without being logged in.`

Will handle this part in https://github.com/fossasia/open-event-frontend/issues/7626

**Comment by sachinchauhan2889** [comment]
We get "unexpected error" when we explore group without login.
It is due to 403 error from backend due to not loading followers of a group.And i will handle it in https://github.com/fossasia/open-event-frontend/issues/7626

**Comment by mariobehling** [comment]
Ok.

Please left-align the search box in the main content column to show it above "Events".

Screenshot from 2021-07-31 13-58-06

**Pull request merged**
