### PR TITLE
Close the create pages form after save.

### LINKED ISSUE #810: Reset the form at admin/content/pages after save.
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Currently the information remains in the form even after submitting even if it is successful.
Todo:
Reset the form once it is successful.

### PR DESCRIPTION
**Pull request by sumedh123**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #810

### CODE REVIEW

**Comment by niranjan94** [comment]
Deployment link: https://pr-813-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 Please review.

**Comment by niranjan94** [comment]
Deployment link: https://pr-813-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@CosmicCoder96 Please review again.

**Comment by niranjan94** [comment]
Deployment link: https://pr-813-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-813-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-813-open-event-frontend-fossasia.surge.sh

**Pull request merged**
