### PR TITLE
Aligning options horizontally in sponsors section

### LINKED ISSUE #2597: Aligning the options horizontally in sponsors section
**Is your feature request related to a problem? Please describe.**
 
Aligning the options horizontally in the sponsors section as they are vertical and taking a lot of space in mobile view. Similar to #2541 but in sponsors section

**Describe the solution you'd like**

Make them horizontal

**Describe alternatives you've considered**
 drop-down table but not preferred as earlier discussed in #2541 .

Screenshot 2019-04-12 03:47:18

**Additional context**

working on it.

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Removes the extra space taken by these options boxes before when aligned vertically in mobile view

#### Changes proposed in this pull request:

- updated `cell-sponsor-options.hbs`

#### Screenshots

Screenshot 2019-04-12 03:58:03

Fixes #2597

### CODE REVIEW

**Comment by mohitm15** [comment]
@CosmicCoder96 What i am planning is to close this PR because whenever I tried to push due to some indentation error, hence the build is getting failed  and also i am getting this error

while squashing commit. 
I had now revisit about the git tutorial from scratch today and now wanted to make PR in a proper way!
This thing also happens with the my two more PRs too.

**Comment by kushthedude** [comment]
You can force push another branch into it if you have messed up in local

**Comment by mohitm15** [comment]
> You can force push another branch into it if you have messed up in local

Is there any method to create a local branch which is head to the master branch.

**Comment by CosmicCoder96** [comment]
Figure out git, before making more PRs.

**Pull request closed without merging**
