### PR TITLE
feature-8753: Enhance the top menu bar on mobile views

### LINKED ISSUE #8753: Enhance the top menu bar on mobile views
Screenshot from 2023-05-26 15-28-25
Compare https://eventyay.com/e/7cfe0771/schedule

On the mobile view of the event pages change the top menu. Do not change it on other pages, but on the event pages show this:
* Do not show "Create Event" on top right
* Instead show "eventyay" on the top right
* Instead of showing "eventyay" on the top left show the logo of the event here. If the event does not have a logo, display "Home" here.
* On the mobile page do not show the logo on top of the image.

### PR DESCRIPTION
**Pull request by ntthitrinh**
Fixes #8753

#### Short description of what this resolves:
- Enhance the top menu bar on mobile views

#### Changes proposed in this pull request:

- Enhance the top menu bar on mobile views

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-frontend/issues/8753
Please help me check and verify.
Thanks,
Note: CI fail network
### Event has logo
Screenshot from 2023-08-04 18-15-55
### Event hasn't logo
Screenshot from 2023-08-04 18-16-24

**Review by mariobehling — CHANGES_REQUESTED** [review]
* [x] Do not show "Create Event" on top right
* [x] Instead show "eventyay" on the top right
* [x] Instead of showing "eventyay" on the top left show the logo of the event here. If the event does not have a logo, display "Home" here.
-> But: The logo area is too small and can hardly be seen. Please increase the event logo size on the top menu bar.
* [ ] On the mobile page do not show the logo on top of the image.
Last point is missing. When you take out the logo on top of the event image please expand the time and date text shown here accordingly.

**Comment by mariobehling** [comment]
Please resolve conflicts as well.

**Comment by ntthitrinh** [comment]
> * [x]  Do not show "Create Event" on top right
> * [x]  Instead show "eventyay" on the top right
> * [x]  Instead of showing "eventyay" on the top left show the logo of the event here. If the event does not have a logo, display "Home" here.
>   -> But: The logo area is too small and can hardly be seen. Please increase the event logo size on the top menu bar.
>   Screenshot from 2023-08-04 17-12-01
> * [ ]  On the mobile page do not show the logo on top of the image.
>   Last point is missing. When you take out the logo on top of the event image please expand the time and date text shown here accordingly.

Hi @mariobehling,
I fixed it. Please help me check.
Thanks,
image

**Comment by mariobehling** [comment]
Something is broken in your code with the logo.

Compare https://eventyay.com/e/7cfe0771 and https://open-event-frontend-git-fork-lthanhhieu-ntthitr-71a086-eventyay.vercel.app/e/7cfe0771

Screenshot from 2023-08-08 04-18-55
Screenshot from 2023-08-08 04-18-30

**Comment by lthanhhieu** [comment]
> Something is broken in your code with the logo.
> 
> Compare https://eventyay.com/e/7cfe0771 and https://open-event-frontend-git-fork-lthanhhieu-ntthitr-71a086-eventyay.vercel.app/e/7cfe0771
> 
> Screenshot from 2023-08-08 04-18-55 Screenshot from 2023-08-08 04-18-30

Hi @mariobehling 
As checked I found that image has been removed in server. Could you please check why?

**Comment by mariobehling** [comment]
Thanks for pointing this out! These images are stored in the temp folder and this folder was cleaned up. Well, this is another topic that we will tackle another time.

The top bar is not optimized yet for images of different ratio. Please check the FOSSASIA logo. It looks out of place. There needs to be some spacing above and below the image.

Screenshot from 2023-08-08 13-15-28

**Comment by ntthitrinh** [comment]
> The top bar is not optimized yet for images of different ratio. Please check the FOSSASIA logo. It looks out of place. There needs to be some spacing above and below the image.
> 
> Compare https://open-event-frontend-git-fork-lthanhhieu-ntthitr-71a086-eventyay.vercel.app/e/7cfe0771
> 
> Screenshot from 2023-08-08 13-15-28

Hi @mariobehling,
I fixed it.
Please help me check. 
Thanks,

**Comment by mariobehling** [comment]
Ok, the image is in the right kind of area, but unfortunately the aspect ratio has been distorted.

Compare mobile logo shape 
Screenshot from 2023-08-10 11-28-38

And desktop logo shape (which is correct)
Screenshot from 2023-08-10 11-29-01

**Comment by ntthitrinh** [comment]
image
image

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
