### PR TITLE
fix: Side Navbar made equal to calendar

### LINKED ISSUE #6711: Scheduler: Decrease the height of the left side bar for unscheduled sessions and rename to "Not Yet Scheduled"
The left side bar of the scheduler page is extending beyond the bottom of the calendar area of the scheduler. Please change the following to improve the area:
* Match the height of the left side bar with the bottom of the calendar area of the scheduler
* Rename "Unscheduled Sessions" to "Not Yet Scheduled Sessions"

Compare https://eventyay.com/events/fa96ae2c/scheduler

Screenshot from 2021-02-15 13-30-58

### PR DESCRIPTION
**Pull request by Naman-1234**
Fixes #6711 

#### Short description of what this resolves:
Screenshot (1018)

#### Changes proposed in this pull request:

- Navbar equal to calendar.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
->  "Not Yet Scheduled Sessions"

**Comment by Naman-1234** [comment]
Ok Sir,Just a sec.

**Comment by Naman-1234** [comment]
@mariobehling, Please review this PR sir.

**Comment by mariobehling** [comment]
Looks like you cut off the bottom edge of the area.

Screenshot from 2021-02-24 05-44-37

**Comment by Naman-1234** [comment]
@mariobehling  Sir Sorry for that, Actually by mistake I wrote hidden instead of auto, Now I have corrected it. Here is the screenshot for that. And again sorry for the previous mistake.

Screenshot (1019)

**Comment by Naman-1234** [comment]
@iamareebjamal , Sir Please review this PR.

**Comment by mariobehling** [comment]
Please compare the left-side. You cut it off instead of making it shorter.

**Comment by Naman-1234** [comment]
@mariobehling  Sir it is not cut off, It has been given overflow auto, which basically gives scroll on elements larger than that of height, Please try to check on the events made by you( As I don't have access to them ), and if you still find the problem Please let me know I will be happy to perform the changes.

**Comment by Naman-1234** [comment]
@iamareebjamal  Sir Could you please review this PR.

**Review by maze-runnar — COMMENTED** [review]
changes are looking good.

**Review by nlok5923 — APPROVED** [review]
Looks good to me.

**Comment by mariobehling** [comment]
Reopening the issue as we now have an internal scroll bar with a long empty space.

**Comment by mariobehling** [comment]
Can this be reverted. This PR simply moves the scroll bar to another area. The previous implementation was more suitable. The only thing that needs to be done was to reduce the height of the area of the left side panel in that view.

**Pull request merged**
