### PR TITLE
fix: Move payment choices to checkout page

### LINKED ISSUE #8068: Move Payment Choice to the Checkout Page for Orders
Users currently choose the payment option on the second step of orders. Please move this choice to the checkout page (step 3). Show the payment options above the "Pay Now" button.

Step 2
Screenshot from 2021-11-11 12-32-13

Step 3 Checkout Page
Screenshot from 2021-11-11 12-32-39

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #8068

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by codedsun** [comment]
image

This is how it looks @mariobehling @pc-beast

**Comment by codedsun** [comment]
@mariobehling @pc-beast @progmatic-99  Please test

**Comment by pc-beast** [comment]
image

**Comment by mariobehling** [comment]
Please change the following:
* follow the box design for the payment area as well 
* display the info boxes right below the payment method, e.g. Cheque info below the radio button and Cheque choice

**Comment by pc-beast** [comment]
> * display the info boxes right below the payment method, e.g. Cheque info below the radio button and Cheque choice

Should the info box show up non conditionally or should I keep the behavior of the infobox the same?


Current:
image

**Comment by pc-beast** [comment]
image

**Comment by mariobehling** [comment]
Could you move the Stripe logos directly behind the word "Stripe", please?

**Comment by mariobehling** [comment]
Did you test it with "Paypal" as a payment option as well?

**Comment by pc-beast** [comment]
image

**Comment by codedsun** [comment]
@pc-beast Looks nice, we can merge

**Comment by mariobehling** [comment]
Choosing "Stripe" as a payment option results in "TypeError: Cannot read properties of undefined (reading 'message')"

**Comment by pc-beast** [comment]
Looking into it

**Pull request merged**
