### PR TITLE
Fixes typo in system-form

### LINKED ISSUE #2587: Typo in the system-form.
**Describe the bug**

A typo in the system form. A word is missing more specifically.

**Expected behaviour**

typo should be corrected.

**Additional context**

I am Working

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixes the typo. See commit.
  
#### Changes proposed in this pull request:

- update `system-form.hbs`

Fixes #2587

### CODE REVIEW

**Comment by kushthedude** [comment]
Always squash you commits and some vague commits are present which are not related to PR

**Comment by mohitm15** [comment]
@ritikamotwani I forgot that.

**Comment by mohitm15** [comment]
@ritikamotwani I am getting this while squashing the commits
Screenshot 2019-04-13 05:17:27

I squash in this way
Screenshot 2019-04-13 05:22:14

What Should I do??

**Comment by kushthedude** [comment]
Replace pick with squash and rebase it

**Comment by mohitm15** [comment]
@kushthedude should I replace pick from all the commits before the blue one

**Comment by kushthedude** [comment]
Not from every commit , the commits you want to squash just replace from them

**Comment by mohitm15** [comment]
@kushthedude It says to squash them one by one as they are not continous. But i do this 
Screenshot 2019-04-13 06:35:33
(squash only first one)
then then it says 
`error: cannot 'squash' without a previous commit`
`You can fix this with 'git rebase --edit-todo' and then run 'git rebase --continue'.`
`Or you can abort the rebase with 'git rebase --abort'`

**Comment by pradeepgangwar** [comment]
@mohitm15 Leave first one as `pick` and replace others as `squash`. It should work if other things are fine on your branch.

**Comment by mohitm15** [comment]
> @mohitm15 Leave first one as `pick` and replace others as `squash`. It should work if other things are fine on your branch.

Its not working and getting cherry -pick error

**Comment by CosmicCoder96** [comment]
Figure out git before making more PRs.

**Comment by mohitm15** [comment]
@CosmicCoder96 I had revisited git now. will not repeat this practice.

**Pull request closed without merging**
