### PR TITLE
Added checkbox option in attendee form

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes [#5833 ](https://github.com/fossasia/open-event-frontend/issues/5833)

#### Short description of what this resolves:
This PR adds the checkbox option in the custom field of attendee form

**Screenshots**:
image
image

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by daretobedifferent18 — COMMENTED** [review]
Screenshot from 2020-12-16 19-46-04
Checkbox is not showing its value on attendeeList

**Review by daretobedifferent18 — COMMENTED** [review]
Screenshot from 2020-12-16 19-49-15
Make checkbox left to the text

**Comment by iamareebjamal** [comment]
All of these require server changes first

**Comment by ranjitkshah** [comment]
@iamareebjamal checkbox field is already present in a custom form field. still, it requires any server changes? 
image

**Comment by iamareebjamal** [comment]
There's no logic for adding options for those check boxes, so yes

**Pull request closed without merging**
