### PR TITLE
Adds JSON API support to ember-models-table & integrates events API to events/list route

### LINKED ISSUE #551: Add JSON API compatibility to ember models table & Integrate event API to event/list route
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Add compatibility JSON API compatibility for filtering ember models table.
- Integrate event API to event/list route.

### PR DESCRIPTION
**Pull request by geekyd**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds JSON API support to ember-models-table
- Adds events API to events/list route

Fixes #551 

Deployment link : https://open-event-frontend-app.herokuapp.com/

### CODE REVIEW

**Comment by geekyd** [comment]
@niranjan94 Okay, so I should add the request for all the events in `events` route, and then filter it in `list` route using lodash? Please guide.

**Comment by niranjan94** [comment]
@geekyd I'm talking about the related records (such as sessions, tickets, etc).

**Comment by geekyd** [comment]
@niranjan94 Please review. Thanks

**Comment by geekyd** [comment]
@niranjan94 The following features seem to work for me: 
- Sorting is working
- Column search is working
Can you please check again?

I will add the other requested features. Thanks

**Comment by niranjan94** [comment]
@geekyd sorry ... rechecked and have updated my previous comment.

**Comment by niranjan94** [comment]
Deployment link: https://pr-565-open-event-frontend-fossasia.surge.sh

**Pull request merged**
