### PR TITLE
fix: Simplify Access code

### LINKED ISSUE #5857: Make Access Form similar to Discount Form
The discount form was simplified recently. Please simplify the access form in the same way.

Compare discount form
Screenshot from 2020-12-01 21-33-12

### PR DESCRIPTION
**Pull request by Saumyachitransh01**
Fixes #5857

#### Short description of what this resolves:
Making access form similar to discount form
 
Screenshot from 2021-01-05 17-45-01

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
Screenshot from 2021-01-05 19-51-19

**Review by sachinchauhan2889 — COMMENTED** [review]
I have previously created a PR for this issue. But my forked project get some bugs and i reforked project. Due to this my branch deleted. I checked this now after seeing your PR 😂. You can refer that. I completed solved that. https://github.com/fossasia/open-event-frontend/pull/6196 . Checkout my last commit. You can copy.

**Comment by Saumyachitransh01** [comment]
> I have previously created a PR for this issue. But my forked project get some bugs and i reforked project. Due to this my branch deleted. I checked this now after seeing your PR 😂. You can refer that. I completed solved that. #6196 . Checkout my last commit. You can copy.

Okay! But can you point if there's anything wrong in this pr at this point?

**Comment by sachinchauhan2889** [comment]
> > I have previously created a PR for this issue. But my forked project get some bugs and i reforked project. Due to this my branch deleted. I checked this now after seeing your PR 😂. You can refer that. I completed solved that. #6196 . Checkout my last commit. You can copy.
> 
> Okay! But can you point if there's anything wrong in this pr at this point?

Actually in model hook. This.params is not set to params. Thats why we are geeting this error in console.

**Comment by Saumyachitransh01** [comment]
Yes I figured that out. And fixed too. In last commit update list.js

**Comment by sachinchauhan2889** [comment]
> Yes I figured that out. And fixed too. In last commit update list.js
> There's no console error now

ohh my mistake i haven't seen your last commit. i only see last review. i will review this.

**Review by sachinchauhan2889 — APPROVED** [review]
looks good to me.

**Comment by mariobehling** [comment]
While the UI has been changed in the end the feature is not working unfortunately. It is not possible to store a hidden ticket or at least it does not work in my test right now. Follow up issue here https://github.com/fossasia/open-event-frontend/issues/6274

**Pull request merged**
