### PR TITLE
feat: Groups Team page: add sub page for permissions

### LINKED ISSUE #7677: Groups Team Page: Add sub-page for permissions
Similarly to the event team page for the group team page add a sub page for permissions.

Screenshot from 2021-08-10 00-59-17

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #7677 

#### Screenshot:
image

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@pc-beast what is remaining in this PR?

**Comment by pc-beast** [comment]
> @pc-beast what is remaining in this PR?

Adding what all permissions are there for groups. Will do it by evening.

**Comment by pc-beast** [comment]
I am not able to access the group as an organizer account. Only admins and owners can access the group page. I think there is some permissions issue there. Should I open a new issue for that?

**Comment by pc-beast** [comment]
Dealing  #7718 and other issues in different pr

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
