### PR TITLE
feat: Enable admins to change users from "Unverified" to "Verified"

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/5040
Screenshot from 2021-01-13 16-19-44

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@iamareebjamal this is currently giving me this error (for testing I have also made is_verified `dump_only` in server too, but that also gave same error) - 
Screenshot from 2021-01-13 16-17-21
Screenshot from 2021-01-13 16-17-01

**Comment by iamareebjamal** [comment]
1. Making it dump_only makes it read only, which will make it not work even more
2. See the request body to know why it is throwing error

**Comment by maze-runnar** [comment]
`"marketer-events":{"data":[{"type":"event","id":"3e44abb2"},{"type":"event","id":"0ccd0d34"},{"type":"event","id":"bf0a821f"},{"type":"event","id":"3b67cff2"},{"type":"event","id":"53170e0a"},{"type":"event","id":"a68ec65f"},{"type":"event","id":"825d4796"}]},"sales-admin-events":{"data":[{"type":"event","id":"3e44abb2"}`

sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "3e44abb2"
LINE 3: WHERE events.id = '3e44abb2'

**Comment by maze-runnar** [comment]
complete payload - 

```

{"data":{"id":"2","attributes":{"email":"sd060210@gmail.com","is-blocked":true,"is-admin":false,"is-user-owner":false,"is-user-organizer":false,"is-user-coorganizer":false,"is-user-track-organizer":false,"is-user-moderator":false,"is-user-registrar":false,"is-sales-admin":false,"is-marketer":false,"was-registered-with-order":false,"first-name":null,"last-name":null,"details":null,"contact":null,"avatar-url":null,"icon-image-url":null,"small-image-url":null,"thumbnail-image-url":null,"original-image-url":null,"facebook-url":null,"instagram-url":null,"twitter-url":null,"google-plus-url":null,"deleted-at":null,"billing-contact-name":null,"billing-phone":null,"billing-country":null,"company":null,"billing-address":null,"billing-city":null,"billing-zip-code":null,"billing-tax-info":null,"billing-additional-info":null,"billing-state":null},"relationships":{"owner-events":{"data":[]},"organizer-events":{"data":[]},"coorganizer-events":{"data":[]},"track-organizer-events":{"data":[]},"registrar-events":{"data":[]},"moderator-events":{"data":[]},"marketer-events":{"data":[{"type":"event","id":"3e44abb2"},{"type":"event","id":"0ccd0d34"},{"type":"event","id":"bf0a821f"},{"type":"event","id":"3b67cff2"},{"type":"event","id":"53170e0a"},{"type":"event","id":"a68ec65f"},{"type":"event","id":"825d4796"}]},"sales-admin-events":{"data":[{"type":"event","id":"3e44abb2"},{"type":"event","id":"0ccd0d34"},{"type":"event","id":"bf0a821f"},{"type":"event","id":"3b67cff2"},{"type":"event","id":"53170e0a"},{"type":"event","id":"a68ec65f"},{"type":"event","id":"825d4796"}]}},"type":"user"}}

```

**Comment by iamareebjamal** [comment]
Exactly. event ID is identifier instead of id

**Comment by maze-runnar** [comment]
> Exactly. event ID is identifier instead of id

but I am passing only user id, and how to paas event id in toggleBlocked?

**Comment by maze-runnar** [comment]
> Exactly. event ID is identifier instead of id

but I am passing only user id, and how to paas event id in toggleBlocked?

**Comment by iamareebjamal** [comment]
See event relation serializer

**Comment by maze-runnar** [comment]
The error is comming due to these relation. What to do next?

```
# owner_events = Relationship(
    #     self_view='v1.user_owner_events',
    #     self_view_kwargs={'id': '<id>'},
    #     related_view='v1.event_list',
    #     related_view_kwargs={'user_owner_id': '<id>'},
    #     schema='EventSchema',
    #     many=True,
    #     type_='event',
    # )
    organizer_events = Relationship(
        self_view='v1.user_organizer_events',
        self_view_kwargs={'id': '<id>'},
        related_view_kwargs={'user_organizer_id': '<id>'},
        related_view='v1.event_list',
        schema='EventSchema',
        many=True,
        type_='event',
    )
    coorganizer_events = Relationship(
        self_view='v1.user_coorganizer_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        related_view_kwargs={'user_coorganizer_id': '<id>'},
        schema='EventSchema',
        many=True,
        type_='event',
    )
    track_organizer_events = Relationship(
        self_view='v1.user_track_organizer_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        related_view_kwargs={'user_track_organizer_id': '<id>'},
        schema='EventSchema',
        many=True,
        type_='event',
    )
    registrar_events = Relationship(
        self_view='v1.user_registrar_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        related_view_kwargs={'user_registrar_id': '<id>'},
        schema='EventSchema',
        many=True,
        type_='event',
    )
    moderator_events = Relationship(
        self_view='v1.user_moderator_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        related_view_kwargs={'user_moderator_id': '<id>'},
        schema='EventSchema',
        many=True,
        type_='event',
    )

marketer_events = Relationship(
        self_view='v1.user_marketer_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        schema='EventSchema',
        type_='event',
        many=True,
    )
    sales_admin_events = Relationship(
        self_view='v1.user_sales_admin_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        schema='EventSchema',
        type_='event',
        many=True,
    )
```

**Comment by iamareebjamal** [comment]
It's issue in frontend, not server, see event relation serializer

**Comment by maze-runnar** [comment]
I have reverted changes of event-relation to previous version but still getting the same error.

**Pull request merged**
