### PR TITLE
feat: add chatmosphere to video forms

### LINKED ISSUE #8293: Integrate Chatmosphere as a Video Option
1. Please add the option "Chatmosphere" as a video room option in the event video area.

Screenshot from 2022-01-23 18-10-59

2. In the video room area add an option to set a background image for the Chatmosphere screen.

3. Use the following URL structure to generate rooms in the chatmosphere system: https://app.chatmosphere.cc/session/eventyay/[event ID]-[6 digit random number]

4. On the Chatmosphere screen in eventyay hide the following
* On middle top "Welcome to Prototype"
- the "Leave Call" button
- Chatmosphere text on top right (but keep the logo)
- On bottom left Github and twitter icon and "Feedback"

Screenshot from 2022-01-23 18-24-46

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #8293 

Needs server PR https://github.com/fossasia/open-event-server/pull/8520

### CODE REVIEW

**Comment by mariobehling** [comment]
Please add some screenshots. Thanks.

**Comment by progmatic-99** [comment]
@mariobehling 
Screenshot 2022-02-05 at 12-04-53 HackY - Edit Microlocation HackY Events Open Event

**Review by pc-beast — DISMISSED** [review]

**Comment by progmatic-99** [comment]
Screenshot 2022-02-10 at 18-46-48 again-fix - Edit Microlocation again-fix Events eventyay

**Review by pc-beast — APPROVED** [review]

**Comment by mariobehling** [comment]
Please execute the server command on test.eventyay.com in order to get this feature fully working there. Thanks.

**Comment by pc-beast** [comment]
> Please execute the server command on test.eventyay.com in order to get this feature fully working there. Thanks.

image
Done :+1:

**Pull request merged**
