### PR TITLE
Speaker Form: Make Speaking Experience into Paragraph and Gender as dropdown

### LINKED ISSUE #1860: Speaker Form: Make "Speaking Experience" into Paragraph and "Gender" as dropdown
* The speaking experience form element should be offering a paragraph.
* The Gender should be a dropdown with the option to enter "Other" and specify that.

screenshot from 2019-01-17 00-46-58

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
   - The speaking experience form element should be offering a paragraph.
   - The Gender should be a dropdown with the option to enter "Other" and specify that.

#### Changes proposed in this pull request:
 - Changes `type` of gender to `select`
 - Made `Speaking Experience` a paragraph
 - Added genders `Male`, `Female`, `Other`
 - Added a textbox to specify `Other` gender

Fixes #1860

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@uds5501 @CosmicCoder96 everything with PR is working fine but there is a glitch.
Whenever I select `Other` gender and fill up the textbox, the data is saved in the db, but whenever I open up the speaker details again, I'm unable to set the dropdown value to `Other` because the value saved in `data.speaker.gender` is the value of textbox in such case.
_While entering the details_
Screenshot_2019-05-14 Edit Speaker Call for Speakers Test Open Event

_While editing again_
Screenshot_2019-05-14 Edit Speaker Call for Speakers Test Open Event(1)

**Comment by uds5501** [comment]
@shreyanshdwivedi Can't we leave the `Other` section as just Other? Why do the user need to specify it?

**Comment by shreyanshdwivedi** [comment]
@uds5501 I also thought the same but it was mentioned in the issue itself that their must be an option to specify `Other` gender
However people of `Other` gender may find it awkward to specify it. @CosmicCoder96 @mrsaicharan1 your thoughts?

**Comment by mrsaicharan1** [comment]
We can have the option of selecting the `Prefer not to specify` similar to other sites which contain the `gender as mandatory`

**Comment by shreyanshdwivedi** [comment]
So you are suggesting to have 4 options in drop down, including `Prefer not to specify`. Right?
When user selects `Other` he/she is given a textbox to specify it. How can we tackle it?

I'm suggesting that we should have only 4 drop down options - `Male`, `Female`, `Other`, `Prefer not to specify`. Waiting for you thoughts on this @mariobehling @CosmicCoder96

**Comment by mrsaicharan1** [comment]
Is the textbox really necessary? Does the person have to specify it?

**Comment by uds5501** [comment]
@shreyanshdwivedi @mrsaicharan1 IMO, the three categories Male, Female, Others should suffice

**Comment by mrsaicharan1** [comment]
@uds5501 That's fine as well.

**Comment by kushthedude** [comment]
@shreyanshdwivedi , I totally agree with @uds5501, 3 options are suffice and stating the gender when the user has selected other would make an awkward choice.

**Comment by shreyanshdwivedi** [comment]
PFA the screenshot 
Screenshot_2019-05-15 Edit Speaker Call for Speakers Test Open Event

@mrsaicharan1 @kushthedude please review

**Comment by uds5501** [comment]
@CosmicCoder96 Since the stored data type is :
`gender = db.Column(db.String)` and it is not being changed here, I don't think it should not break the db

**Comment by CosmicCoder96** [comment]
@uds5501 you missed the point of what I am trying to say here. Yes I know it's a string. A custom form field is created for each event. That 'string' field happens to contain the values of either `text`, `select` or `paragraph`. Ergo, any of the previous events have an entry in the database with a row having values for say `72, 598, gender, text` for id, event_id, name, type columns respectively. Making this type as 'select' will make these values to something like `73, 600, gender, select` for  id, event_id, name, type columns respectively. How is that not a problem if the `type` is the very thing which determines what sort of UI to render on FE.

**Comment by shreyanshdwivedi** [comment]
@uds5501 @CosmicCoder96 please review :)

**Pull request merged**
