### PR TITLE
WIP: Improve Responsiveness of Search Bar in Mobile View

### LINKED ISSUE #2399: Fix responsiveness of filter options on home page.
**Describe the bug**

The filter options on home page isn't responsive. The search bar gets cut for smaller screens.

**To Reproduce**
1. Go to '/'
2. Switch to responsive mode.
3. See error

**Expected behavior**

I suggest moving search bar and buttons in different lines for mobile screens.
**Screenshots**

Screenshot from 2019-03-27 09-51-31

Screenshot from 2019-03-27 09-51-16

**Additional context**

I am working on it.

### PR DESCRIPTION
**Pull request by prateekj117**
#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Search Bar UI gets congested in Mobile View, so move buttons and Search Bar to different lines. 

Fixes #2399

### CODE REVIEW

**Comment by prateekj117** [comment]
@mohitm15 
Screenshot from 2019-04-18 14-57-21

@CosmicCoder96 I am not able to make the input field to extend horizontally, can you help me in that?

**Comment by prateekj117** [comment]
@kushthedude Yup, that's why I asked @CosmicCoder96 for help. I think I should put a WIP tag on it.

**Comment by uds5501** [comment]
@prateekj117 Kindly refer to the discussion in the gitter channel.
Here is a piece of code which you may use when i queried about it

```hbs
<div class=""> // the bounding class which we need to figure out
  <div class="fluid ui buttons">
    <button class="ui blue button" type="button" {{action 'search'}}>{{t 'Search'}}</button>
  <div> // first button
  <div class="ui hidden divider">
  </div> // for space
  <div class="fluid ui buttons">
    <button class="ui red button medium {{if disableClear 'disabled'}}" type="button" {{action 'clearFilters'}}>{{t 'Clear Filters'}}</button> //second button
  </div>
</div>
```

CC: @pradeepgangwar

**Comment by CosmicCoder96** [comment]
https://github.com/fossasia/open-event-frontend/pull/2772
Aren't these two solving the same thing? What's happening?

**Comment by kushthedude** [comment]
@CosmicCoder96 I think @prateekj117 made the PR  earlier, @Anupam-dagar should have checked the issue before opening a new PR.

**Comment by Anupam-dagar** [comment]
My bad, didn't see it. I remembered opening an issue for this and uddeshya asking to work on it with no PR's opened and hence I worked on the issue without checking for any other PR being opened.

**Comment by CosmicCoder96** [comment]
Take care from next time.

**Pull request closed without merging**
