### PR TITLE
Change route filter according to User's status

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Changes inactivity period from year to month

Fixes fossasia/open-event-server#5739

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 The Issue arises because in User's model, the inactivity period is defined by Month while in the route, it's defined by year.
Will this change be good enough or should I change User's inactivity period?

```js

status: computed('lastAccessedAt', function() {
    return (new Date().getMonth() - new Date(this.get('lastAccessedAt')).getMonth() < 1);
  }),
```

**Comment by CosmicCoder96** [comment]
@uds5501 keep it in months just make it `< 12` then it will basically be a year right?

**Comment by uds5501** [comment]
@CosmicCoder96 please review :)

**Comment by uds5501** [comment]
@CosmicCoder96 Doing so

**Pull request merged**
