### PR TITLE
speaker image visible on session page

### LINKED ISSUE #2027: Speaker image not appearing in session
**Describe the bug**
Speaker image not appearing in session

**Expected behavior**
Speaker image should in session

**Screenshots**
speakerpic
speakerpic1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I am working on this issue.

### PR DESCRIPTION
**Pull request by shubham3211**
#### Short description of what this resolves:
Speaker image is visible on session page

Fixes #2027

### CODE REVIEW

**Comment by shubham3211** [comment]
@CosmicCoder96 the thumbnail image_url is null.

**Comment by CosmicCoder96** [comment]
@shubham3211 Noted. It should not be null, will merge when the URLs are fixed on the server as it's a server issue.

**Comment by mrsaicharan1** [comment]
@shubham3211 @CosmicCoder96 Would like to fix this up on the server side. Will open a PR over there. We just need to generate a thumbnail and send it over to this route right?

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 Fixed it on the server already, @shubham3211 icon and thumbnail images now exist on server, just replace `speaker.image` as it's an invalid field.

**Comment by shubham3211** [comment]
@CosmicCoder96 It has been done in https://github.com/fossasia/open-event-frontend/pull/2088/files .

**Pull request closed without merging**
