### PR TITLE
fix: user not able to delete other followers

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7691

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@daretobedifferent18 @pc-beast please test it.

**Comment by mariobehling** [comment]
Could you post a screenshot and test link, please? I do not remember exactly where the user could previously remove other users.

I do not see that this is possible now.

**Comment by maze-runnar** [comment]
follow/unfollow from group view page was giving many unexpected error. And admin was able to remove all followers by clicking on follow button continuously. this PR solve both issues.
Screenshot from 2021-09-24 20-57-31

**Comment by pc-beast** [comment]
Before changes, it was showing 'access forbidden error'
image

Now it works as expected.

**Review by pc-beast — APPROVED** [review]

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
