### PR TITLE
fix: Apply Discount Code Ui.

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Fixes
Ui part of promo code to buy tickets.

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
Screenshot from 2021-05-12 10-08-51
the changes

**Comment by iamdevvalecha** [comment]
@sachinchauhan2889 @MeghalBisht  please review.

**Comment by iamdevvalecha** [comment]
The Changes:-
Screenshot from 2021-05-12 10-08-51
please review:-
@MeghalBisht 
@sachinchauhan2889

**Review by MeghalBisht — CHANGES_REQUESTED** [review]
No tick icon in front of apply code.
Remove text "Remove code".
Height of the boxes should be equal to the input box.

**Comment by iamdevvalecha** [comment]
Screenshot from 2021-05-12 18-22-08
it that we want ? can i send these changes?

**Comment by MeghalBisht** [comment]
> Screenshot from 2021-05-12 18-22-08
> it that we want ? can i send these changes?

Height still not equal to input box

**Comment by iamdevvalecha** [comment]
closing this. due to some conficts in branch

**Pull request closed without merging**
