### PR TITLE
feature-9008: Select Session Type button hits the browser border

### LINKED ISSUE #9008: Select Session Type button hits the browser border
In some screen resolutions on the schedule page the button "Select Session Type" hits the browser border. The button is also wider than the buttons on the right side bar above. Expected: Button should have the same width as the buttons above and it should not hit the browser border.

Compare https://eventyay.com/e/8f889410/schedule

**Buttons on the top right.**

Screenshot from 2023-07-27 18-08-24

**The select session type button should have same width and behavior.**
Screenshot from 2023-07-27 18-08-06

### PR DESCRIPTION
**Pull request by lthanhhieu**
Fixes #9008 

#### Short description of what this resolves:
- Select Session Type button hits the browser border

#### Changes proposed in this pull request:
- Select Session Type button hits the browser border

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-frontend/issues/9008
Please help me check and verify.
Thanks,
Screenshot from 2023-08-03 18-46-40

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please match the width of this button with the "Join Event" and "Add to Calendar" button. The width of the button is too small.

Screenshot from 2023-08-03 14-39-23

**Comment by khangon** [comment]
> Please match the width of this button with the "Join Event" and "Add to Calendar" button. The width of the button is too small.
> 
> Screenshot from 2023-08-03 14-39-23

Hi @mariobehling,
We have updated it. Please help me check.
Thanks,
Screenshot from 2023-08-07 16-14-56

**Review by mariobehling — APPROVED** [review]
Thanks.

**Pull request merged**
