### PR TITLE
fix: reverting the infinityModal on my session

### LINKED ISSUE #3752: My-session: session is showing multiple times
**Describe the bug**
My-session: session is showing multiple times 

**Expected behaviour**
session should show only once

**Screenshots**
[multiple session](http://www.youtube.com/watch?v=EMXLyCehYCM "multiple session")

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
i want to work on this

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3752

### CODE REVIEW

**Comment by kushthedude** [comment]
@iamareebjamal Session submitted by the organiser for the user not registered on platform are getting shown under `my session` of the organiser. Is this behaviour ok or should this be fixed too?

**Comment by iamareebjamal** [comment]
Not good. We need to use more infinity loaded. Not less

**Comment by iamareebjamal** [comment]
Updating the dependency will never work because the logic is wrong. InfinityLoader.model('sessions') != authUser.sessions

**Comment by kushthedude** [comment]
> Updating the dependency will never work when the logic is wrong. InfinityLoader.model('sessions') != authUser.sessions

For that is why we have defined Store in the infinity query !

**Comment by iamareebjamal** [comment]
> else this is we got.

Sorry, I will not be merging a PR which contributes to the murder of server. It has got to work with pagination. If it can't work with infinity loader, implement custom loader. 'This is we got'

Furthermore, I will be going ahead some time after and make page_size 0 return at max 50 or 100 results so clients can't abuse the server by loading everything in one go, so everything has to move to pagination

**Comment by kushthedude** [comment]
> > else this is we got.
> 
> Sorry, I will not be merging a PR which contributes to the murder of server. It has got to work with pagination. If it can't work with infinity loader, implement custom loader. 'This is we got'
> 

Will look into it.

**Comment by kushthedude** [comment]
infinityLoader renders twice .

**Comment by CosmicCoder96** [comment]
@kushthedude Can you dig a bit deeper into it -- and maybe raise an issue with them, it is maintained actively, and is the standard choice for ember apps. Loading all sessions will be taking a step back.

**Comment by kushthedude** [comment]
Sure, I will raise an issue there.

**Comment by iamareebjamal** [comment]
Instead of that, just see in the network panel what requests are being sent and why data is duplicated. Most likely it is our bug, and not theirs

**Comment by kushthedude** [comment]
> Instead of that, just see in the network panel what requests are being sent and why data is duplicated. Most likely it is our bug, and not theirs

@iamareebjamal Checked it looks like API is returning duplicated data :
First URL : 
` 
http://127.0.0.1:5000/v1/users/1/sessions?page%5Bsize%5D=10&page%5Bnumber%5D=1&include=event&filter=%5B%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222020-01-18T09%3A21%3A21.512Z%22%7D%2C%7B%22and%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%5D%7D%5D%7D%5D&sort=starts-at`
Second URL:
` http://127.0.0.1:5000/v1/users/1/sessions?page%5Bsize%5D=10&page%5Bnumber%5D=2&include=event&filter=%5B%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222020-01-18T09%3A21%3A21.512Z%22%7D%2C%7B%22and%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%5D%7D%5D%7D%5D&sort=starts-at
`
Both are returning same sessions. Seems like there is issue in pagination in API

**Comment by iamareebjamal** [comment]
Remove the filter and see if it is working correctly then

**Comment by kushthedude** [comment]
> Remove the filter and see if it is working correctly then

Nope

**Comment by iamareebjamal** [comment]
Can you give a link to api.eventyay or dev server so I can easily debug the issue instead of recreating it locally? Will help in fixing the problem faster. Also, raise an issue on server and close the one in infinity model

**Comment by kushthedude** [comment]
@iamareebjamal 
 https://api.eventyay.com/v1/users/7667/sessions?page%5Bsize%5D=10&page%5Bnumber%5D=2&include=event&filter=%5B%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222020-01-18T09%3A44%3A11.827Z%22%7D%2C%7B%22and%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%5D%7D%5D%7D%5D&sort=starts-at


 https://api.eventyay.com/v1/users/7667/sessions?page%5Bsize%5D=10&page%5Bnumber%5D=3&include=event&filter=%5B%7B%22or%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22ge%22%2C%22val%22%3A%222020-01-18T09%3A44%3A11.827Z%22%7D%2C%7B%22and%22%3A%5B%7B%22name%22%3A%22starts-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%2C%7B%22name%22%3A%22ends-at%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Anull%7D%5D%7D%5D%7D%5D&sort=starts-at

**Comment by iamareebjamal** [comment]
@kushthedude have you raised the issue on server?

**Pull request closed without merging**
