### PR TITLE
Makes whole event card clickable

### LINKED ISSUE #277: Complete event card is not clickable
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
On home page, event item card used is not clickable in whole portion. Making it less user friendly.

**Expected behavior:**
It should be clickable in whole portion. 

**Steps to reproduce:**
Click below event title not working

### PR DESCRIPTION
**Pull request by CosmicCoder96**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Earlier only the image and header were clickable to navigate to an event in event card component.

#### Changes proposed in this pull request:
Makes whole event card clickable

Fixes #277

### CODE REVIEW

**Comment by CosmicCoder96** [comment]
Deployment link : http://cc96-opev-frontend.herokuapp.com/
@geekyd @niranjan94 Please review

**Comment by CosmicCoder96** [comment]
Fixing the acceptance tests

**Comment by niranjan94** [comment]
@CosmicCoder96 please make a PR only if the tests pass locally.

**Comment by CosmicCoder96** [comment]
@niranjan94 Yes, apologies. Sometimes the loader test fails arbitrarily on my system and co incidentally it failed to So I assumed that is what it was, and since lint tests passed, I made the PR, will be more careful.

**Comment by CosmicCoder96** [comment]
@niranjan94 Please review again

**Pull request merged**
