### PR TITLE
Only display events who the User is an Organizer of.

### LINKED ISSUE #2390: every user is organizer for every event
**Describe the bug**

Please refer to the screen shot given below

**Expected behavior**

Only the events whom the user is actually an organiser should be displayed

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #2390 

#### Short description of what this resolves:
Admin panel of Users displays user as an organizer of every event.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by prateekj117** [comment]
@CosmicCoder96 @iamareebjamal This seems like a temporary fix, though I think that this issue is of the server as @uds5501 commented above. Can you please transfer this to the server so that I can do the permanent fix there.

**Comment by uds5501** [comment]
@prateekj117 this might actually be the correct fix. Just wanted to know is there any events element in user schema in server. If so, what does it represent

**Comment by prateekj117** [comment]
@uds5501 Yaa. There is. Here is the code.
`    events = Relationship(
        self_view='v1.user_events',
        self_view_kwargs={'id': '<id>'},
        related_view='v1.event_list',
        related_view_kwargs={'user_id': '<id>'},
        schema='EventSchema',
        many=True,
        type_='event')
`
Not sure what it represents. Can you help me understanding this code?

**Comment by mrsaicharan1** [comment]
> @uds5501 Yaa.
> [Here](https://github.com/fossasia/open-event-server/blob/0844ad291523ed94811b41ac56da4c6d373b5c8d/app/api/schema/users.py#L194) it is.
> Not sure what it represents. Can you help me understanding this code?

Try checking out the `marshamllow-jsonapi` docs

**Comment by uds5501** [comment]
@CosmicCoder96 I have no idea why is this working but it is working. 
@mrsaicharan1 your thoughts?

**Comment by mrsaicharan1** [comment]
Screenshot 2019-05-25 at 1 23 50 PM
Do we still have this issue?

**Comment by uds5501** [comment]
@mrsaicharan1 No, only those events are showing up of which the user is actually an organiser. Although, i haven't tested for other roles yet

**Comment by mrsaicharan1** [comment]
So you mean to say that all the events are not visible for the admin now right? @uds5501

**Comment by uds5501** [comment]
@mrsaicharan1 There was never a listing of events for an admin :sweat_smile: The issue was that every organiser was being listed as an organiser of every event. After this, only those events are being listed which the user is actually an organiser of

**Comment by kushthedude** [comment]
@uds5501 Its not the permanent fix , Relational Data is no changing rather we are just tweaking with FE rather than fixing the Database

**Comment by uds5501** [comment]
@kushthedude You can use postman to test the relationship at the backend, IMO it's working :sweat_smile:

**Comment by iamareebjamal** [comment]
AFAIK there is no issue in the data stored in the DB, only the fetching logic is wrong. The reason can be frontend or API. This may fix the issue and get merged, I'm fine by it but it should be known that why it fixes the issue. The things you guys are looking at is the FE code and what not. See the query made and the API code and check if they make sense, if they do, FE change is correct. If they don't, make the change in API

**Comment by uds5501** [comment]
@iamareebjamal understood, will have a look at the query itself.

**Comment by prateekj117** [comment]
@iamareebjamal Ok. Will have a look into it.

**Comment by mariobehling** [comment]
Please follow a new approach as mentioned above and provide a new PR. Closing it therefore. Thanks.

**Pull request closed without merging**
