### PR TITLE
fix: standard group card height

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7985
Fixes https://github.com/fossasia/open-event-frontend/issues/8005
Fixes https://github.com/fossasia/open-event-frontend/issues/8004

#### Short description of what this resolves:
Screenshot from 2021-10-29 08-21-55

Screenshot from 2021-10-30 09-21-39

Screenshot from 2021-10-30 09-04-43

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
Screenshot from 2021-10-30 07-19-35

**Comment by maze-runnar** [comment]
Screenshot from 2021-10-30 09-04-43

**Review by codedsun — APPROVED** [review]

**Comment by mariobehling** [comment]
Thumbnails are using original images, e.g. https://open-event-frontend-git-fork-maze-runnar-group-card-eventyay.vercel.app/explore/groups?name=fossasia . Check the thumbnail. It is 6MB big. Not really a small thumbnail.

**Comment by maze-runnar** [comment]
I think celery is not working correctly on server side. Let me look.

**Comment by maze-runnar** [comment]
@mariobehling I checked it locally, it's resizing correctly, maybe there is a problem with celery on production.

**Comment by mariobehling** [comment]
Ok, will test it after deploying again on live server. Thanks.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
