### PR TITLE
fix: Navbar consistent throughout group pages

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes https://github.com/fossasia/open-event-frontend/issues/7665 
Fixes https://github.com/fossasia/open-event-frontend/issues/7664

#### Short description of what this resolves:
Screenshot from 2021-08-09 22-43-00

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks.

Please also delete heading "Edit Group".

**Comment by mariobehling** [comment]
Please also standardize width of Settings, Followers and Team heading location and content area.

e,g. make the area full width same as teams page.
Screenshot from 2021-08-09 19-51-47

**Comment by mariobehling** [comment]
The Followers table has a larger width than the above areas.

Screenshot from 2021-08-09 19-52-12

**Comment by mariobehling** [comment]
Upcoming events are no longer in the right area below the heading.

Compare https://open-event-frontend-git-fork-meghalbisht-navbarr-eventyay.vercel.app/groups/edit/40/events
Screenshot from 2021-08-09 19-56-54

**Comment by mariobehling** [comment]
Screenshot from 2021-08-09 20-02-59

**Comment by mariobehling** [comment]
Upcoming Events heading is missing.

Screenshot from 2021-08-10 22-45-59

**Comment by mariobehling** [comment]
On the page "Settings", the heading "Settings" is positioned slightly different to the heading on e.g. the Followers tab. Please make it consistent.

**Comment by MeghalBisht** [comment]
> Upcoming Events heading is missing.
> 
> Screenshot from 2021-08-10 22-45-59

upcoming events are not loading for some reason. Will discuss in meeting

**Comment by MeghalBisht** [comment]
@maze-runnar You worked on the group separation part in https://github.com/fossasia/open-event-frontend/pull/7534
Please check what has broken? Even on eventyay.com it seems broken

**Comment by maze-runnar** [comment]
> @maze-runnar You worked on the group separation part in #7534
> Please check what has broken? Even on eventyay.com it seems broken

let's discuss this in the meeting.

**Comment by maze-runnar** [comment]
> @ranjitkshah @maze-runnar I think we can merge it?

Yes

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
