### PR TITLE
fix: past option added in Date Filter

### LINKED ISSUE #5802: Search: Allow search of "Past" events and add the option "Past" into the filters
The search only seems to allow searching future events. Please add the option "Past" as a filter.

Screenshot from 2020-11-28 01-18-13

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #5802

#### Short description of what this resolves:
Past option is added in Date Filter.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Not working https://open-event-frontend-git-past-5802.eventyay.now.sh/explore?end_date=2020-12-01T19%3A17%3A58.208Z&location=Online

**Comment by MeghalBisht** [comment]
> Not working https://open-event-frontend-git-past-5802.eventyay.now.sh/explore?end_date=2020-12-01T19%3A17%3A58.208Z&location=Online

No date filter is working for me. Is it some other issue?

**Comment by MeghalBisht** [comment]
@iamareebjamal  #5104 needs to be solved in order to make the date filters work (which will then resolve this PR), am I right?

**Comment by iamareebjamal** [comment]
No

**Comment by MeghalBisht** [comment]
> Well yes, but actually no. That issue can be solved in this PR itself

Okay, I will look into it. I hope no server code is involved to solve this issue as I am not familiar with it at the moment?

**Comment by iamareebjamal** [comment]
No

**Pull request closed without merging**
