### PR TITLE
fix: omise image optimisation

### LINKED ISSUE #3395: Order Form: Optimise Omise Icon for Proper UI
Omise image is clearly a lot bigger than it should be supposed to. Refactor it accordingly.
image

### PR DESCRIPTION
**Pull request by vishakhanihore**
Fixes #3395 

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@CosmicCoder96 @shreyanshdwivedi @kushthedude  please check

**Comment by vishakhanihore** [comment]
> This looks fine but make sure that you provide a screenshot always

@mrsaicharan1 Actually I am still understanding the workflow, This issue seemed so trivial to make a PR. I will manage ss from next PR

**Comment by mrsaicharan1** [comment]
That’s fine but update the description here with a screenshot for later
reference.

**Comment by shreyanshdwivedi** [comment]
@vishakhanihore please add a screenshot in this PR itself and update the PR description

**Comment by vishakhanihore** [comment]
> Thanks. Please help to provide good descriptions in future PRs. Merging this.

Sure sir, I will take care from next time.

**Pull request merged**
