### PR TITLE
fix: making track optional

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/4584

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Is it working? I don't think so because it requires changes on the server as I said in the issue. Secondly, this needs to be editable in the session custom forms as written in the issue but I see no changes for that in this PR. So what issue is it solving?

**Comment by maze-runnar** [comment]
> Is it working? I don't think so because it requires changes on the server as I said in the issue. Secondly, this needs to be editable in the session custom forms as written in the issue but I see no changes for that in this PR. So what issue is it solving?

it's working. I tried it. But not for the existing events, for existing events it is fixed and that part is needed to fix on the server. But for new events it's working fine as expexted. Please try with creating new Event .

**Comment by maze-runnar** [comment]
Frontend requires this change to make `track field` optional.

**Comment by iamareebjamal** [comment]
Yes but it is not even half of the issue on even the frontend. It does not make the track switchable in custom forms as well

**Comment by maze-runnar** [comment]
for already created events
```
this.store.createRecord('custom-form', {
        fieldIdentifier : 'track',
        form            : 'session',
        type            : 'select',
        isRequired      : true,
        isIncluded      : true,
        isFixed         : true,
        event           : parent
      }),
```
So the events that are already created for them `is_fixed` is true in server-side,  so while editing them `is_fixed` is `true`.
But for new events it's switchable.

**Comment by maze-runnar** [comment]
captured (2)

**Comment by iamareebjamal** [comment]
Can you create a session without a track in a new event? Please show an example

**Comment by maze-runnar** [comment]
> Can you create a session without a track in a new event? Please show an example

no

`{"errors": [{"status": 422, "source": {"pointer": "/data/relationships/track"}, "title": "Unprocessable Entity", "detail": "A valid relationship with track resource is required"}], "jsonapi": {"version": "1.0"}}`

**Comment by maze-runnar** [comment]
What to do for it in server side?

**Comment by iamareebjamal** [comment]
Check the custom form and require track conditionally. It is a bit complicated, so focus on other issues

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
Now session can be create  without track.

**Pull request merged**
