### PR TITLE
Fix UI defect in mobile mode

### LINKED ISSUE #2394: UI issue in buttons on creating event
**Expected behavior**
I think buttons should stack according to size of display screen.

**Screenshots**
Screenshot from 2019-03-26 19-26-36

**Additional context**
Working on it.

### PR DESCRIPTION
**Pull request by prateekj117**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

Fixes #2394

### CODE REVIEW

**Comment by prateekj117** [comment]
Screenshot from 2019-03-28 11-52-47
Screenshot from 2019-03-28 11-53-52

**Comment by ritikamotwani** [comment]
@prateekj117 , this hasn't been fixed properly yet. 
image

This is what I am getting in the mobile view now.
The button previous isn't properly visible.

**Comment by prateekj117** [comment]
@ritikamotwani Ok, on it.

**Comment by prateekj117** [comment]
@ritikamotwani @CosmicCoder96 Please review now.

**Comment by ritikamotwani** [comment]
@prateekj117 good work.
Can you please do it for the sessions and speakers step.
image

**Comment by prateekj117** [comment]
@ritikamotwani @CosmicCoder96 Done. Please review now.

**Pull request merged**
