### PR TITLE
feat: Add menu tab Sponsors

### LINKED ISSUE #4888: Public Event Page: Add menu tab "Sponsors"
If an organizer has activated "Sponsors" in the event creation wizard and added sponsors, please show a tab "Sponsors" on the left hand-side of the public page.

1. Implement the sponsors menu tab above the menu item "Organizers".
2. Change the heading of the "Sponsors" section to match the heading level and style of "Organizers".

Screenshot from 2020-08-27 19-04-10

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4888

Screenshot from 2020-08-28 10-30-36

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@maze-runnar Great that you took up this issue but please stick to the specified milestones or we'll remain behind schedule

**Comment by iamareebjamal** [comment]
Pick only high priority issues and pick others only if high priority ones are closed. There are a lot of High Priority issues in Forms and Custom Forms milestone

**Comment by maze-runnar** [comment]
ok I am starting Forms and Custom Forms milestone from today.

**Comment by mariobehling** [comment]
Please just change the existing heading "Sponsors" to "Sponsors and Partners" and make it into the larger heading (2?). Do not add "Sponsored by..."

**Comment by mariobehling** [comment]
Sorry. Even better would be actually if you make the heading as "Supported By". So:

Change "Sponsored By" to "Supported By" and take out the small heading directly below named "Sponsors".

**Comment by mariobehling** [comment]
And in the menu bar use "Sponsors" not just "Sponsor".

**Review by iamareebjamal — APPROVED** [review]

**Comment by mariobehling** [comment]
We now have "Supported By" and "Sponsors". Only need "Supported By"

Screenshot from 2020-08-29 10-28-04

**Pull request merged**
