### PR TITLE
Fixing the ambiguity in Tickets Sales

### LINKED ISSUE #2796: Ambiguity in 'Events/Overview' Sales Section
**Describe the bug**

Sales total shown in `Event/Overview` is different in Overview and Each Ticket section.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to `Events/Overview` 
2. See error
3. Refer to Screenshot

**Expected behaviour**

Ambiguity should not be there

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari
 - Version: 23.0.3

**Additional context**

Looking into the cause

### PR DESCRIPTION
**Pull request by kushthedude**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

Fixes #2796 

#### Screenshot

Screenshot 2019-04-25 at 4 28 58 AM

Fixes #2796

### CODE REVIEW

**Comment by kushthedude** [comment]
Will resolve it

**Comment by CosmicCoder96** [comment]
@kushthedude Update this.

**Comment by kushthedude** [comment]
Will update tonight

**Comment by CosmicCoder96** [comment]
Inactive, please reopen when finished.

**Pull request closed without merging**
