### PR TITLE
fix: all date filter 

### LINKED ISSUE #5921: Search: Fix and Enhance filter options
The filters are not consistent, e.g. it is currently not possible to choose all location types at the same time even though this is the default search behavior. Therefore please make the filter display and search functionality consistent and allow searching of past events as well. 

Please change the filters as follows and make the below options the standard search setting:
- Rename "Event Location Type" to "Setting"
  - Tick all boxes Online, Location, Mixed - by default
- If user only ticks online show all online events already even if no event name has been specified
- Date 
   - Change "All dates" filter to actually display "All dates" including past dates and move it to the end of the search filter area
   - Implement filter "Past" and "All Upcoming"
   - By default tick "All Upcoming" and when ticking "All Upcoming" tick "Today" and all other future filters (except custom dates)
   - Show "Past" at the end of the widget before "All dates"
- Categories - leave it as is to "All Categories"
- Event Types - leave it as is to "All Types"
- Ticket Type - tick Free and Paid by default
- Event Call For Speakers rename it to "Call for Speakers"
- By default tick "Open" only
- Finally change "Clear Filters" to "Default Filters" and reset filters to the standard search filter config when the user clicks it

Furthermoe
* Ensure that the search as above works in the same way from the start page as well the explore page
- The search from the start page should always use the standard search parameters for now

Screenshot from 2020-12-05 13-30-59

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #5921 

#### Short description of what this resolves:
self-explanatory and referring [comment](https://github.com/fossasia/open-event-frontend/pull/6155#pullrequestreview-559264013)

#### screenshot:
image

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ranjitkshah** [comment]
@iamareebjamal @sachinchauhan2889  pls review

**Review by MeghalBisht — COMMENTED** [review]
Filters work for me, what I found missing is -

1. By default tick "All Upcoming" and when ticking "All Upcoming" tick "Today" and all other future filters (except custom dates)
2. "All dates" -> move it to the end of the search filter area
3. Show "Past" at the end of the widget before "All dates"

**Comment by ranjitkshah** [comment]
Thank you mam for reviewing my PR,
> 2. "All dates" -> move it to the end of the search filter area
> 3. Show "Past" at the end of the widget before "All dates"

done

> 1. By default tick "All Upcoming" and when ticking "All Upcoming" tick "Today" and all other future filters (except custom dates)

facing an issue. currently, when we type in the search box it shows all upcoming but when the route is only "/explore" it shows from a specific date (oct). any suggestion or guidance

**Comment by ranjitkshah** [comment]
updated screenshot -
image

**Comment by ranjitkshah** [comment]
@mariobehling  please review the filters thanks

**Comment by mariobehling** [comment]
I think it would be best if you participate in the next meeting. The default search already does the correct behavior, but the UI does not portray the default behavior. For example does the search cover all events for tomorrow? Yes, but in your changes you only show "Upcoming". Tomorrow is a part of upcoming, but you do not show it. Difficult to explain every single point here. You should try to understand the intention of the logic.

**Comment by mariobehling** [comment]
If you did understand the logic, then it is not implemented yet as it appears for me as below.

Screenshot from 2021-01-30 20-09-29

**Comment by ranjitkshah** [comment]
now only `All date` filter is fixed in this PR. @iamareebjamal, please review

**Pull request merged**
