### PR TITLE
fix: Change selected video room text to previous state on cancel

### LINKED ISSUE #6999: Organizer Video Tab Edit Form Changes Video Choice Even Though User Chooses "Cancel"
In the organizer video room edit form when the user clicks on other video options a pop up message appears. If the user clicks cancel to this message the system will just work in the same way as if the user clicks ok. Expected is that the previous setup remains.

Screenshot from 2021-03-13 23-40-38

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6999

#### Short description of what this resolves:
The dropdown selected text was the only thing that changed on cancel. However the video channel selected was not changed.

https://user-images.githubusercontent.com/61330148/114930331-7dcc9b00-9e52-11eb-9617-bffd8647e1b2.mp4

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x]  I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This is not the correct solution. No use of jquery should be needed

**Comment by iamareebjamal** [comment]
Secondly, the issue is about the video channel change. I don't understand the focus of this PR. Please read the issue again carefully and see the screenshot

**Comment by MeghalBisht** [comment]
Yes I know however on testing the channel was working as expected.

> The dropdown selected text was the only thing that changed on cancel. However the video channel selected was not changed.

**Comment by MeghalBisht** [comment]
@sachinchauhan2889 Please test if the issue linked is actually an issue as it works fine in mine. This PR changes the dropdown text back to the original state on pressing cancel.
Feel free to close otherwise

**Review by sachinchauhan2889 — COMMENTED** [review]
it is just changing the text not value.




youtube is still highlighted.

**Comment by MeghalBisht** [comment]
> it is just changing the text not value.

Ok, the video channel works fine for me. Did you test that? If yes then I think we don't need this PR as per https://github.com/fossasia/open-event-frontend/pull/7139#issuecomment-820704170 this comment

**Review by ranjitkshah — APPROVED** [review]

**Review by maze-runnar — APPROVED** [review]

**Pull request merged**
