### PR TITLE
Adds speakers page on public section

### LINKED ISSUE #1471: Add speakers page to public section
**Is your feature request related to a problem? Please describe.**
Speakers page is not present in the public section and should be made similar to the web app.

**Describe the solution you'd like**
Add the separate page in the public section.

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Adds speakers page on the public section of the project with the layout a bit similar to the web app.

#### Changes proposed in this pull request:

- Added a separate page for speakers.

- Screenshot:
screenshot from 2018-07-24 17-44-10

Fixes #1471

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@pradeepgangwar @ritikamotwani @srv-twry please review. I will be fixing the speakers section on `index` page in another PR with only the `featured speakers` present there.

**Comment by ritikamotwani** [comment]
@agbilotia1998 fix the travis!
And instead of changing the css can you please try using pop ups directly through semantic UI https://semantic-ui.com/modules/popup.html

**Comment by agbilotia1998** [comment]
@ritikamotwani I tried using the popup directly from Semantic-UI and its ember wrappers https://semantic-org.github.io/Semantic-UI-Ember/#/modules/popup as well. The problem I am facing is that data to be loaded is dynamic but these popups support static content only like this `https://semantic-org.github.io/Semantic-UI-Ember/#/modules/popup`, to add dynamic content here the complex HTML needs to be added inside the controller/component like this https://stackoverflow.com/questions/32765839/bootstrap-tooltip-with-complex-html-in-ember but that was also not conventional. Therefore I used the popup similar to the web app and used the same CSS with some manipulations from there.

**Comment by ritikamotwani** [comment]
@agbilotia1998 can't you create a component and then use it in the content part. This is like to much CSS for a semantic UI project :smile:

**Comment by agbilotia1998** [comment]
Okay, I will be opening an alternate PR for this and we can move with that if the similar design to web app is achieved there as well. Thanks for the review :)

**Pull request merged**
