### PR TITLE
Added meta and ogp tags for better SEO

### LINKED ISSUE #1697: Add meta tags and ogp tags for better SEO
**Describe the bug**

We should add meta tags and ogp tags in the index.html for better SEO

**Expected behavior**

Meta tags and OGP tags help for better SEO and can help us improve the rank of our page

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Currently, we don't have meta and ogp tags for better SEO optimisations

#### Changes proposed in this pull request:

- I've added meta and SEO tags for optimisations

Fixes #1697

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar @CosmicCoder96 please review

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi I am not sure if this is the right way to do it for OEF. I will check and come back.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar @CosmicCoder96 
As we need the meta description to be updated when we use view events, I came to following way to solve this -
1. _When we go to `/e/:event_id`_ 
I'll add this piece of code in `routes/public/index.js` 
```
afterModel(model) {
    set(this, 'headData.description', model.event.description);
  }
```

2. _When we go to `/events/:event_id`_
I'll add this piece of code in `routes/events/view.js`
```
afterModel(model) {
    set(this, 'headData.description', model.description);
  }
```

And in `templates/head.hbs`
```
{{#if model.description}}
  <meta name="description" content={{model.description}}>
{{else}}
  <meta name="description" content="The front end for the Open Event Server where event organisers can create and manage their event.">
{{/if}}
```
And title meta tag is same as title on page. All the other meta tags are constant.
Is this what we need?

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar @CosmicCoder96 please review :)

**Pull request merged**
