### PR TITLE
fix: search bar enhancement and working

### LINKED ISSUE #6399: Search box in mobile View not working
The top search bar is not working in mobile view. Please also change the following
* The magnifying glass icon should always stay where it is before the use clicks on it
* Tipping on the magnifying glass icon should result in the search being performed
* When the user clicks on the search area the keyboard should open automatically
* There should be no x icon. If the user clicks outside of the search field the search should be automatically deactivated

Please compare the search functionality of the Google search box. Implement the same functionality and behavior for the search box on eventyay.

Screenshot_20210117_013114_com android chrome

### PR DESCRIPTION
**Pull request by Creatoon**
Fixes #6399 

#### Short description of what this resolves:

- [x] The magnifying glass icon should always stay where it is before the use clicks on it
- [x] Tipping on the magnifying glass icon should result in the search being performed
- [x]  When the user clicks on the search area the keyboard should open automatically
- [x]  There should be no x icon. If the user clicks outside of the search field the search should be automatically deactivated

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Creatoon** [comment]
@iamareebjamal sir please review

**Comment by Creatoon** [comment]
@iamareebjamal sir now search icon it starts from right and stays in the right as well.


https://user-images.githubusercontent.com/65965202/105247420-c6015780-5b9a-11eb-9e2a-436913dd19f4.mp4

**Comment by Creatoon** [comment]
@mariobehling please also look at this feature , thanks

**Comment by mariobehling** [comment]
Thank you. Please also ensure it works with a blue enter button on the mobile keyboard. Currently there is no way to finalize the input and start the search using the mobile keyboard.

Screenshot_20210121_222653_com android chrome

**Comment by Creatoon** [comment]
@mariobehling Sir now mobile enter button is working just fine , please have a look , thanks

**Comment by Creatoon** [comment]
@mariobehling Sir now mobile enter button is working just fine , please have a look , thanks

**Review by mariobehling — APPROVED** [review]
Thanks! Works for me.

**Pull request merged**
