### PR TITLE
fix: Wizard step 3 and 5 enhanced accordingly

### LINKED ISSUE #5013: Wizard Form: Simplify design
Please simplify the design of the wizard as follows:

Wizard Step 1
* Simplify page by taking out 4 horizontal lines as shown below

screencapture-open-event-frontend-git-fork-iamareebjamal-online-events-eventyay-vercel-app-create-2020-09-08-10_07_32

Wizard Step 3
* Add Custom Form Field - demote from heading to standard text. This should not be a heading.

Screenshot from 2020-09-08 10-37-59

Wizard Step 5
* "Customize registration form" rename to -> "Customize submission forms"
* Add Custom Form Field - demote from heading to standard text. This should not be a heading.

Screenshot from 2020-09-08 10-39-11

### PR DESCRIPTION
**Pull request by terminator0309**
Fixes #5013 

#### Short description of what this resolves:
Simplifies wizard Step 3 and 5 as stated in the issue.

#### Changes proposed in this pull request:

-Wizard step 3 : demoted "Add Custom form field" from heading to standard text.
-Wizard step 5 : "Customize registration form" renamed to -> "Customize submission forms"
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

Annotation 2020-10-25 185951
Annotation 2020-10-25 190104

### CODE REVIEW

**Comment by mariobehling** [comment]
Is this the same pull request? https://github.com/fossasia/open-event-frontend/pull/5334

It is confusing to have several PRs for the same thing.

**Comment by mariobehling** [comment]
It complicates things if you do not update an existing PR and instead make a new one. Also please post screenshots of the changes in your PR description to make it easier to see the changes you have done.

**Comment by terminator0309** [comment]
Added screenshots...

**Review by mariobehling — CHANGES_REQUESTED** [review]
Yes, it does the changes, but there are a lot of unrelated changes just moving code in the lines. Please revert the unnecessary indent changes.

**Comment by terminator0309** [comment]
OMG ! I think i did it. That was a nightmare to fix that indentation problem.  Hopefully everthing will be good this time.

**Pull request merged**
