### PR TITLE
feature-8758: Redesign Menu Area on Schedule Page

### LINKED ISSUE #8758: Redesign Menu Area on Schedule Page
The schedule page has a lot of filter options, but we also need to ensure the user can easily find the schedule itself. Therefore please redesign and reduce the number of rows used by filters on the schedule page as follows:

* Row 1: Schedule (Calendar View) [Clear Filters Icon] [Sort by]
* Row 2: [Public Schedule] [My Schedule] [My Speaker Sessions] (for logged in users)
* Row 3: [Time Zone] [Search] 
* Row 4: [All] [Date 1] [Date 2] etc.
* Row 5:  [Track] [Room] [Sessions]

Screenshot from 2023-05-26 18-05-56

Compare https://eventyay.com/e/7cfe0771/schedule

### PR DESCRIPTION
**Pull request by ntthitrinh**
Fixes #8758

#### Short description of what this resolves:
Redesign Menu Area on Schedule Page

#### Changes proposed in this pull request:

-Redesign Menu Area on Schedule Page.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket #8758 
Please help me check and verify.
Thanks,
Screenshot from 2023-08-07 11-45-20

**Comment by mariobehling** [comment]
Thanks. 

Please test and fix the filters.
* [ ] Choosing more than one filter results in no result. Instead it should show all the results of the filters.
* [ ] Please increase height of dropdown
* [ ] Do not close dropdown immediately when the user clicks a filter. The user might want to choose several options, e.g. several tracks. Compare https://open-event-frontend-git-fork-lthanhhieu-ntthitr-d9fbc1-eventyay.vercel.app/e/8f889410/schedule?sort=starts-at&track=Open%20Data%2CCommunity%20Initiatives
Screenshot from 2023-08-08 03-44-41

Spacing
* [ ] reduce space above date (Wednesday here)
Screenshot from 2023-08-08 03-49-58

**Comment by ntthitrinh** [comment]
Hi @mariobehling,
> Choosing more than one filter results in no result. Instead it should show all the results of the filters.

I could not add the session type  and session level to speaker and session. Could you please share me the way to do?

>Show background colors of tracks same as on desktop version

Did you mean to show the color in the dropdown of the tracks? This will take a long time to do.
>Ensure the dropdown box design is not broken, e.g. top line is missing (see screenshot)

as the image in attachment, I feel it not friendly
image

**Comment by mariobehling** [comment]
Please compare for example to https://2019.fossasia.org/event/schedule.html

A dropdown box should be closed as a box and it should not be connected to another menu item.

Screenshot from 2023-08-08 14-01-45

**Comment by mariobehling** [comment]
> > Choosing more than one filter results in no result. Instead it should show all the results of the filters.
> 
> I could not add the session type and session level to speaker and session. Could you please share me the way to do?

Please check out on the desktop site how it works. It should work in exactly the same way on the mobile site.

**Comment by mariobehling** [comment]
Using the filters on the mobile site gives the following link:
https://open-event-frontend-git-fork-lthanhhieu-ntthitr-d9fbc1-eventyay.vercel.app/e/8f889410/schedule?sort=starts-at&track=Open%20Data%2CCommunity%20Initiatives

Choosing the same filter options on the frontend gives the following link:
https://open-event-frontend-git-fork-lthanhhieu-ntthitr-d9fbc1-eventyay.vercel.app/e/8f889410/schedule?sort=starts-at&track=Open%20Data%3A%2CCommunity%20Initiatives%3A

Hence the filter functionality of the mobile site needs to be fixed.

**Comment by mariobehling** [comment]
Thank you! Filters are working now. Please also take care of the other points and tick them here once finished.

> * [ ]  Please increase height of dropdown
> * [ ]  **Do not** close dropdown immediately when the user clicks a filter. The user might want to choose several options, e.g. several tracks. Compare https://open-event-frontend-git-fork-lthanhhieu-ntthitr-d9fbc1-eventyay.vercel.app/e/8f889410/schedule?sort=starts-at&track=Open%20Data%2CCommunity%20Initiatives
>   Screenshot from 2023-08-08 03-44-41

> Spacing
> 
> * [ ]  reduce space above date (Wednesday here)
>   Screenshot from 2023-08-08 03-49-58

**Comment by mariobehling** [comment]
Please reduce white spaces

Screenshot from 2023-08-10 01-41-28

**Comment by ntthitrinh** [comment]
> [ ] Please increase height of dropdown
Hi @mariobehling,
image

Currently, the dropdown's height has been adjusted, as shown in the image. You're welcome to take a look on Vercel. Would you like to make any further adjustments?

**Comment by mariobehling** [comment]
* [ ] Do not close dropdown immediately when the user clicks a filter. The user might want to choose several options, e.g. several tracks

**Comment by mariobehling** [comment]
Spacing
* [ ] reduce space above date (Wednesday here)
Screenshot from 2023-08-08 03-49-58

**Comment by ntthitrinh** [comment]
> * [X]  1. Choosing more than one filter results in no result. Instead it should show all the results of the filters.
> * [x]  2. Please increase height of dropdown
> * [ ]  3. Do not close dropdown immediately when the user clicks a filter. The user might want to choose several options, e.g. several tracks. Compare https://open-event-frontend-git-fork-lthanhhieu-ntthitr-d9fbc1-eventyay.vercel.app/e/8f889410/schedule?sort=starts-at&track=Open%20Data%2CCommunity%20Initiatives
> * [x]  4. Ensure the dropdown icon does not overlap with the "Rooms" text
> * [x]  5. Ensure the dropdown box design is not broken, e.g. top line is missing (see screenshot)
> * [x]  6. Increase the width of the dropdown box to make things more easily readable, e.g. show "Community Initiatives" in one row
> * [ ]  7.Show background colors of tracks same as on desktop version
> * [ ]  8. reduce space above date (Wednesday here)

Hi @mariobehling.
Here is the list of tasks I have completed:
I am currently working on items point 3 and 8. 
For point 7: As the @lthanhhieu mentioned that we just need to show the filter, the color can be added it latter.
For point 3: The dropdown list is overlapped by other element and I am investigating the resolution.
For point 8: I am not sure the distance you want to remove, so I just try to make it looks better from my end. As the commented for your, I will make it closes to the dropdown list with the space as the same the other element.
While I doing it, please help me review the other and if it good for you, please merge it. The other will raise the new PR later. How do you think about it?

**Review by mariobehling — APPROVED** [review]
Thanks! Make sense. Good job!

**Pull request merged**
