### PR TITLE
Fix issue with brackets and commas across platform

### LINKED ISSUE #5452: Fix issue with brackets and commas across platform
We have a number of places where there is no space in front of a bracket, e.g. as in "User(Email)", "Sales($) etc., or other places where there is a space in front of a comma, e.g. "Hello ," or no space after a comma, e.g. "organizer,co-organizer" etc.

- Please find all places where there is no space in front of a bracket and add a space. Expected is "User (Email)"
- Find all places where there is a space in front of a comma and where there is no space after a comma and fix them. Expected is, e.g. "organizer, co-organizer"
- Ensure that changes do not impact functionality of the system

Screenshot from 2020-11-02 13-53-26

### PR DESCRIPTION
**Pull request by Chadha93**
Fixes #5452

#### Short description of what this resolves:
fixed issue with brackets and commas across the platform without changing the functionality of the system.

#### Changes proposed in this pull request:

-fixed spacing before commas
-fixes no spacing in front of brackets
-fixes spacing issues with inverted commas
-added space where needed according to commas and brackets

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests, and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I can't see a single bracket fix

**Comment by Chadha93** [comment]
@iamareebjamal maybe

**Comment by iamareebjamal** [comment]
Definitely

**Review by mariobehling — CHANGES_REQUESTED** [review]
No brackets fixed, e.g. issue with User(Email) sill there.

Also I am confused about the conversation. What does it mean as an answer "maybe"?

**Comment by Chadha93** [comment]
I will be looking for the bracketing issue as soon as possible.  "maybe"- meant bracket error was missed by me

**Comment by iamareebjamal** [comment]
Fixed in #5508

**Pull request closed without merging**
