### PR TITLE
Add view functionality to events/{event_identifier}/sessions

### LINKED ISSUE #1022: Add view functionality to events/{event_identifier}/sessions
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

The view button in the route events/{event_idenrifier}/sessions is not functional.
**Expected behavior:**

The button should help to view the content of that session.

### PR DESCRIPTION
**Pull request by ritikamotwani**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
When the view button is clicked sessions content is visible.
image

#### Changes proposed in this pull request:

- Functionality added to the view button on this route.

Fixes #1022

### CODE REVIEW

**Comment by niranjan94** [comment]
Deployment link: https://pr-1023-open-event-frontend-fossasia.surge.sh

**Comment by ritikamotwani** [comment]
@mariobehling @CosmicCoder96 @geekyd please review.

**Comment by ritikamotwani** [comment]
@geekyd I found no form which showed the details of the session like short abstracts, comments etc., so I redirected it to the same form where there is information of the session and you can also edit the form.

**Comment by ritikamotwani** [comment]
@geekyd can you please tell the new route where the view button redirects shows what exactly? I'll create a dynamic route but I am a bit confused about what all information has to be there?

**Comment by CosmicCoder96** [comment]
@ritikamotwani This is the route required 
image
The frontend for it doesn't exist yet, feel free to split this issue into two issues, and make the required frontend as well.

**Comment by ritikamotwani** [comment]
Oh okay! Thank you.
I'll start working on this.

**Comment by CosmicCoder96** [comment]
The Url will be exactly like `https://eventyay.com/events/mysessions/4559/`

**Comment by ritikamotwani** [comment]
@CosmicCoder96 If I click view on this route on eventyay
image
I get redirected to the edit session URL
image

**Comment by geekyd** [comment]
@ritikamotwani We need to follow the same approach as on eventyay. What we should do is add a new route `sessions/<id>` and redirect it there. On the route make a request for the session using the id & populate the form.

**Comment by niranjan94** [comment]
Deployment link: https://pr-1023-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-1023-open-event-frontend-fossasia.surge.sh

**Comment by ritikamotwani** [comment]
@mariobehling @CosmicCoder96 @geekyd please review.

**Comment by ritikamotwani** [comment]
@mariobehling @CosmicCoder96 @geekyd please review :smile:

**Comment by niranjan94** [comment]
Deployment link: https://pr-1023-open-event-frontend-fossasia.surge.sh

**Pull request merged**
