### PR TITLE
fix: License of Event Data & Content clear field

### LINKED ISSUE #2302: Event Type,Event Topic,Event subtopic, License cannot be made null once set
**Describe the bug**

Event Type,Event Topic,Event subtopic, License cannot be made null once set
**To Reproduce**
1. Go to 'Basic Details'
3. Scroll down to 'Event topic'

**Expected behavior**

There should be an option "none" which sets these fields to null.
**Screenshots**

Screenshot 2019-03-15 at 6 43 09 PM

**Additional context**

I'm working on it.

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #2302 (completing remaining part of wizard step 2 of licence )

captured (1)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
there is no option like power select `allowClear` in case of `UIDropDown`

**Comment by snitin315** [comment]
I think there was a `clearable` named property for dropdown in Semantic-UI.

**Comment by iamareebjamal** [comment]
That won't work here AFAIK as this is not a property of event but `event.copyright.license`

**Comment by iamareebjamal** [comment]
@maze-runnar Try using Power Select for this as well

**Comment by maze-runnar** [comment]
@iamareebjamal i have added powerselect - 
```
<PowerSelect
      @selected={{this.data.event.copyright.licence}}
      @allowClear={{true}}
      @options={{this.licenses}}
      @placeholder={{t 'Select Licence'}}
      @onChange={{fn (mut this.data.event.copyright.licence)}} as |licence|>
        {{licence.name}}
    </PowerSelect>
```
But it is showing [Object object ] on event page.
Screenshot from 2020-09-04 15-51-35

**Comment by iamareebjamal** [comment]
The JS object was assigned instead of name

**Comment by maze-runnar** [comment]
> The JS object was assigned instead of name

```
<PowerSelect
      @selected={{this.data.event.copyright.licence.name}}
      @allowClear={{true}}
      @options={{this.licenses}}
      @placeholder={{t 'Select Licence'}}
      @onChange={{fn (mut this.data.event.copyright.licence.name)}} as |licence|>
        {{licence}}
    </PowerSelect>
```

tried this too, not worked

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
