### PR TITLE
feat: Search Page Further enhance design

### LINKED ISSUE #6017: Search Page: Further enhance design
Please enhance the design of the search page as shown in the screenshot below. Change the following:
* Move search bar to middle top menu bar
* Take out heading "Events" above search results
* Take out search box from left hand side menu bar
* rename Location Type to Setting

compare https://eventyay.com/explore
Screenshot from 2020-12-13 12-25-56

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #6017 

#### Changes proposed in this pull request:

  - [x]   Move search bar to middle top menu bar
  - [x]   Take out heading "Events" above search results
  - [x]   Take out search box from left hand side menu bar
  - [x]  rename Location Type to Setting
  - [ ]  change DOM manipulation to ember (Follow up PR #6007)

#### ScreenShot

Desktop | Mobile 
---- | ----------
Screenshot from 2020-12-15 06-28-53 | Screenshot from 2020-12-15 06-29-34

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@mariobehling should I place the search bar in middle?
Are the current changes made ok?

**Comment by iamareebjamal** [comment]
Search term not visible in search bar

**Comment by daretobedifferent18** [comment]
> Search term not visible in search bar

oh really
These are the results
Screenshot from 2020-12-15 01-36-27
Screenshot from 2020-12-15 01-36-52
Screenshot from 2020-12-15 01-39-39

**Comment by iamareebjamal** [comment]
Search term means the event name which was searched

**Comment by mariobehling** [comment]
On the search page we need a large search bar on the top. Please see the screenshot in the issue as well. 

Screenshot from 2020-12-14 23-28-23

**Comment by iamareebjamal** [comment]
image

**Comment by daretobedifferent18** [comment]
@mariobehling Pls see the styling part

**Review by MeghalBisht — COMMENTED** [review]
The input should have the width till the search icon because if I enter a bigger search term then it hides the text as I enter, and the search icon is still far away which looks a little weird.

**Comment by iamareebjamal** [comment]
Please fix the warnings from lint as well

**Comment by daretobedifferent18** [comment]
> Search term still not visible in search bar

yup I am left with this part only.

**Comment by daretobedifferent18** [comment]
@iamareebjamal styling and UI part is ok?

**Comment by iamareebjamal** [comment]
Yes

**Comment by daretobedifferent18** [comment]
@iamareebjamal Its done. Pls have a look

**Comment by iamareebjamal** [comment]
Code is much more complicated now, why can't we just bind the query param to the search bar in search page?

Also, because of this, now changing the search param doesn't search automatically

**Comment by daretobedifferent18** [comment]
> Code is much more complicated now, why can't we just bind the query param to the search bar in search page?
> 
> Also, because of this, now changing the search param doesn't search automatically

changing searchParams for eg event_name=dfg to event_name=dsdg is working for me

**Comment by iamareebjamal** [comment]
Please move to other issues. Let me think of a solution

**Comment by iamareebjamal** [comment]
@sachinchauhan2889 @maze-runnar Please complete this

**Comment by MeghalBisht** [comment]
Inactive from a long time, lot of conflicts, also design is a less of a priority. Can be reopened later

**Pull request closed without merging**
