### PR TITLE
[WIP] Make Speaking Experience into Paragraph and Gender as dropdown

### LINKED ISSUE #1860: Speaker Form: Make "Speaking Experience" into Paragraph and "Gender" as dropdown
* The speaking experience form element should be offering a paragraph.
* The Gender should be a dropdown with the option to enter "Other" and specify that.

screenshot from 2019-01-17 00-46-58

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-  The speaking experience form element should be offering a paragraph.
- The Gender should be a dropdown with the option to enter "Other" and specify that.

Fixes #1860

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I'm changing the `type` of `gender` to `select` in `app/mixins/custom-form.js` so that the gender type is changed to select type, but Idk why it is not reflecting on the frontend. I tried with other fields too, but it isn't reflecting. Please help

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi For a given event, once the custom form fields are created, their type is stored on the database itself.

**Comment by ritikamotwani** [comment]
@shreyanshdwivedi any updates?

**Comment by CosmicCoder96** [comment]
please reopen it later when complete.

**Pull request closed without merging**
