### PR TITLE
WIP: addition of exhibitors

### PR DESCRIPTION
**Pull request by himanshujaidka**
working on #6199 

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by himanshujaidka** [comment]
what to add in the field of exhibitors

**Comment by MeghalBisht** [comment]
I believe this cannot be merged until server is modified

**Comment by himanshujaidka** [comment]
> I believe this cannot be merged until server is modified

I don't want to merge it, I want to set up things for this feature

**Comment by mariobehling** [comment]
Please make a PR into the "Draft" stage and add the label "WIP" for work in progress if it is not ready for review.

**Comment by himanshujaidka** [comment]
> Please make a PR into the "Draft" stage and add the label "WIP" for work in progress if it is not ready for review.

Ok sir

**Comment by himanshujaidka** [comment]
@mariobehling sir, is this slider is ok? so that I will proceed further
Screenshot (143)

**Pull request closed without merging**
