### PR TITLE
[WIP] Fix failing tests

### LINKED ISSUE #1100: Tests are failing for the application
Some tests are failing on the application currently. This is affecting all incoming pull requests as contributors/reviewers are not sure if the PR is causing a test fail or it was an already failing test.

The test suite needs to be fixed on priority.

### PR DESCRIPTION
**Pull request by pradeepgangwar**
#### Short description of what this resolves:
Fixes failing tests on travis.

Fixes #1100

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@niranjan94 @CosmicCoder96 Can u look into travis tests?  All tests pass on my local system but travis shows timeout error on some routes tests.
screenshot from 2018-05-07 23-49-12

**Comment by ritikamotwani** [comment]
@niranjan94 @CosmicCoder96 @geekyd could you please look into the travis tests. There are certain route tests that are showing timeout error in the build of every PR.

**Comment by CosmicCoder96** [comment]
@pradeepgangwar when testing locally, are you using the local deployment of the server or the one hosted on heroku?

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 I use local deployment.

**Comment by niranjan94** [comment]
@pradeepgangwar can you change travis config to setup a local server and use that while running the tests on travis ?

**Comment by pradeepgangwar** [comment]
@niranjan94 Yeah! Although I have never tried that but I can try that.

**Comment by pradeepgangwar** [comment]
@niranjan94 I got confused previously by the term local deployment. While I run my tests I use default server setup. I don't use local instance of open-event-server. So I think by default tests on my machine should be using heroku deployment. And tests pass for that too.

**Comment by CosmicCoder96** [comment]
@niranjan94 What is being done in scripts/local-server.sh , is that what you meant by local deployment ?

**Comment by CosmicCoder96** [comment]
handled in #1127

**Pull request closed without merging**
