### PR TITLE
Fix: Remove Extra network requests on initial ember table load

### PR DESCRIPTION
**Pull request by CosmicCoder96**
Makes sure that ember model table doesn't execute it's own query hook, if route model already takes care of it.

### CODE REVIEW

**Comment by kushthedude** [comment]
I think this fixes #2670 , As tables were reloading after they have been loaded @CosmicCoder96

**Comment by CosmicCoder96** [comment]
@kushthedude Not completely, that issue's scope is all lazy loading calls, ember tables don't have lazy loading.

**Comment by kushthedude** [comment]
On my local repo , there were only issues with ember tables , but on `next.eventyay.com` this issue exist at most of the places and i think the github branch and the deployment is not synced right now .

**Comment by CosmicCoder96** [comment]
On next.eventyay there are 6000 users, 4000 events, 8000 sessions. Load time is negligible on localhost. You can't observe it.

**Comment by kushthedude** [comment]
Oops , i was not knowing next.eventyay is in production, thought we were still using eventyay V.1 😅

**Comment by kushthedude** [comment]
@CosmicCoder96 Ember Tables are still getting a reload after getting loaded completely .

**Comment by CosmicCoder96** [comment]
@kushthedude While changing tabs, yes. That needs to be handled separately. For instance, if you go to Manage events, it won't load twice. However if you switch tabs within My events route, it loads twice while switching them. This PR fixed only a part of it.

**Comment by kushthedude** [comment]
Yup switching tabs causes it to reload twice , Do we need to do similar type of fix for that @CosmicCoder96

**Comment by CosmicCoder96** [comment]
@kushthedude yes.

**Pull request merged**
