### PR TITLE
Ticket Icon Changed

### LINKED ISSUE #5624: Order Page and Complete Order Page: Choose better icon for "Ticket Buyer Information"
The ticket buyer information uses the same icon as the ticket holder's information. Please find and implement a better suited different icon, maybe something related to money or payment?

Screenshot from 2020-11-13 22-29-04

### PR DESCRIPTION
**Pull request by Saumyachitransh01**
Fixes #5624 
Order page
Screenshot from 2020-11-15 15-27-52
Complete Order page
Screenshot from 2020-11-15 15-31-12

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
We already have a PR for this https://github.com/fossasia/open-event-frontend/pull/5625

**Comment by sachinchauhan2889** [comment]
Already having PR for #5624.

**Comment by Saumyachitransh01** [comment]
> We already have a PR for this #5625

yes but I thought it's better icon for ticket buyer

**Comment by snitin315** [comment]
Instead creating a new PR you should suggest changes to the existing PR. 😀

**Comment by Saumyachitransh01** [comment]
> Instead creating a new PR you should suggest changes to the existing PR.

Okay

**Pull request closed without merging**
