### PR TITLE
Enforce DRY in event wizard & Add Fastboot support

### PR DESCRIPTION
**Pull request by niranjan94**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Extract event wizard code snippets that are used in multiple files into a single mixin 
- Had started on fastboot once upon a time and came across the branch. Took it to completion. 
- Updated ember-simple-auth-token dependency

### CODE REVIEW

**Comment by CosmicCoder96** [comment]
@niranjan94 The login custom helper is the issue.

**Comment by niranjan94** [comment]
Hey @CosmicCoder96 .. Haven't got a chance to check the build yet. Will check later tonight. 

> The login custom helper is the issue.

Which one ?

**Comment by niranjan94** [comment]
@CosmicCoder96 looks like its an issue with [`ember-simple-auth-token`](https://github.com/jpadilla/ember-simple-auth-token). I have dropped the problem commit for now. And have also opened an issue at https://github.com/jpadilla/ember-simple-auth-token/issues/239

**Comment by CosmicCoder96** [comment]
@niranjan94 can you rebase and merge please, thanks !

**Pull request merged**
