### PR TITLE
feat: Multiple documents for Session Speakers

### LINKED ISSUE #5820: Speakers Form/Public Schedule: Implement option to add several files for slides
The speakers form currently has the option to upload or link one slide. Organizer feedback is that speakers in some events have several files to share. Therefore please implement the option to add or link several files and provide a field to indicate some details about the file or link.

Implement this as follows:
* Show a field to add a "Name" and field to add a link or upload a file in the speakers form (similar to now)
* In the public schedule show a download button with a dropdown function that displays the slide files or links

Screenshot from 2020-11-29 10-08-17

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #5820 #7616

#### Short description of what this resolves:
self-explantory

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ranjitkshah** [comment]
Screenshot from 2021-07-27 03-52-26
Screenshot from 2021-07-27 03-48-09

**Comment by ranjitkshah** [comment]
@maze-runnar google-iframe is not showing url. do you have any indea ?

**Comment by maze-runnar** [comment]
> @maze-runnar google-iframe is not showing preview. do you have any indea ?

On reloading the page it is showing preview or not? And opening in new tab it is showing document correctly or not?

**Comment by ranjitkshah** [comment]
> > @maze-runnar google-iframe is not showing preview. do you have any indea ?
> 
> On reloading the page it is showing preview or not? And opening in new tab it is showing document correctly or not?

no can you please check , what is wrong here

**Comment by ranjitkshah** [comment]
@SundaramDubey please check here why google iframe preview is not working

**Comment by maze-runnar** [comment]
Actually the problem is that the pdf we are uploading is going to api.eventyay.com and changes are merge with test-api. And also Google viewer doesn't show previews for local host pdf URLs. I have replaced the URL with some other URL which is available and not on local host, and its working. 
Screenshot from 2021-08-16 08-52-57

**Comment by ranjitkshah** [comment]
> @ranjitkshah
> Actually the problem is that the pdf we are uploading is going to api.eventyay.com and changes are merge with test-api. And also Google viewer doesn't show previews for local host pdf URLs. I have replaced the URL with some other URL which is available and not on local host, and its working.
> Screenshot from 2021-08-16 08-52-57

ahh cool , I think we can merge it and test it more on testing server

**Review by maze-runnar — APPROVED** [review]

**Comment by ranjitkshah** [comment]
slide_url into slide_name and slide_url
slide_name is session name
name = "what's solution fsklkl klgsklklsklgs"

**Comment by mariobehling** [comment]
Unfortunately this implementation does not work as expected everywhere. Compare https://github.com/fossasia/open-event-frontend/issues/7735

**Pull request merged**
