### PR TITLE
fix: Reorder and rename event dashboard boxes

### LINKED ISSUE #5468: Reorder event dashboard boxes and rename them
Reorder event dashboard boxes and rename them as below.

Please make the box order as follows:

Event Checklist - Overview
Sponsors - Tickets
Apps - Team Members

Screenshot from 2020-11-03 11-58-40

### PR DESCRIPTION
**Pull request by Soumi150**
Fixes #5468 

#### Short description of what this resolves:

Reorder and rename event dashboard boxes.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

Before
Screenshot from 2020-11-03 11-58-40

After making changes
Screenshot (19)

Screenshot (22)_LI

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Before and after screenshots

**Comment by iamareebjamal** [comment]
And please resolve the conflicts

**Comment by Raunaksingh100** [comment]
@Soumi150 if someone do comment i am working on this so first ask that he is not working on it so can i work on it

cheat

**Comment by iamareebjamal** [comment]
If @carrycooldude has a PR, we'll close this one. But we value actual contribution. Not just commenting "I want to work on this" and then disappearing on a trip to Bahamas. We will not stop other contributors from contributing just because someone commented "I want to work on this" or "I am working on this"

If they have commented and started the work, they can send a PR, even an incomplete one as a proof and ask this PR to be closed. We'll do it without any problem. But it's in fashion these days to just say I want to work on this issue and then forget about it. Actual contributions are hurt because of this and this is bad for both the contributors who could fix the issue and get codeheat rewards and also for us because the issue doesn't get solved.

For example, you can't just reserve a Phone from amazon and say "I'll pay for it" and prevent others from buying it. If you don't finalize payment within 2-3 hours, it'll be sold to someone else. We usually allow up to 7 days. But if someone else can immediately start working on something within hours and you haven't started working on it, the issue should go to that person.

That's why please only comment on an issue you actually will be fixing and soon, otherwise anyone else who can send a PR soon will get that. And it is only fair

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
