### PR TITLE
Admin: Add Groups Tab in Menu

### LINKED ISSUE #6717: Admin: Add Groups Tab in Menu
We now have the groups feature but an admin does not have any way to control the feature. Please add a page with a table for admins and add a menu item behind "Users". The tables should have the following columns:

- Groups with buttons View, Edit, Delete
- Owner
- Number of events
- Created
- Public URL

Add two sub tabs:
- Live
- Deleted

Screenshot from 2021-02-15 17-40-07

### PR DESCRIPTION
**Pull request by g4rry420**
Fixes #6717 

#### Short description of what this resolves:
Added the Groups tab in the Admin Page.

#### Changes proposed in this pull request:

- Added Groups tab with buttons - Edit and Delete
- Also, added Owner, Number of events, Created, Public Url
- Added sub tabs - Live and Deleted

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by g4rry420** [comment]
Currently, there are only two unresolved solution for this pr:

- createdAt is not showing the returned value, I think createdAt is not received from the server.
- public url on initial loads works fine but if you suppose access another tab like 'users' or any other after that you access 'groups' then the public urls becomes undefined. I couldn't seem to find the reason for this.

Other than that, everything works fine.

**Comment by iamareebjamal** [comment]
Screenshots

**Comment by g4rry420** [comment]
https://user-images.githubusercontent.com/61521805/113226740-e0247980-925e-11eb-8dc3-cfce130f6ade.mp4


Also, I find that when a admin deleted a event and then enter the Deleted route then that deleted event is not fetched from the server.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Public URLs do not show up on the overview page.

Screenshot from 2021-04-28 01-17-42

**Comment by maze-runnar** [comment]
> Public URLs do not show up on the overview page.
> 
> Screenshot from 2021-04-28 01-17-42

@mariobehling I have refactored this PR, please review here https://github.com/fossasia/open-event-frontend/pull/7187

**Pull request closed without merging**
