### PR TITLE
fix : Add all sessions tab in my-sessions

### LINKED ISSUE #2262: bug : only scheduled sessions being shown in my-sessions
**Describe the bug**

At the moment, only published events are being shown in my-sessions making it impossible for an user to access his/her other sessions.

**To Reproduce**
1. Go to My-sessions
2. See error
image

**Expected behavior**

I am planning to add a new tab which can show user's all session proposals and rename the existing ones so that they signify the scheduled status.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubutnu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Adds a new tab which shows all the sessions of the concerned user by setting the filter to `[ ]` for that `token` 

#### Changes proposed in this pull request:

- Add a new tab in my-sessions
- Add corresponding route
image

Fixes #2262

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 Review Please!

**Comment by CosmicCoder96** [comment]
After some discussion, we concluded that we don't need an all sessions route for now. Please stick to the features of v1 right now.

**Comment by uds5501** [comment]
@CosmicCoder96 Understood

**Comment by uds5501** [comment]
@CosmicCoder96 corresponding PR #2266

**Pull request closed without merging**
