### PR TITLE
fix: making filter for upcoming events on index page

### LINKED ISSUE #2659: Filter upcoming events on the basis of their end date and time.
**Describe the bug**

Currently the events are being filtered on the basis of end date only. If an event is single day event of 2hrs, then the vent will get removed from upcoming events on the next day. The event should not be shown in upcoming events if it is over.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event.
2. Set event start time and end time for a small period.
3. After the event is over, it is still shown in upcoming events.

**Expected behaviour**

Once the event is over, it should not be shown in the upcoming events or browse events.

**Screenshots**

Screenshot from 2019-04-15 18-05-18

Screenshot from 2019-04-15 18-05-11

**Additional context**

I am working on this issue.

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #2659 
upcoming event are showing that events too till next date that are finished . Making a function to filter them .
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
Wrong approach!

**Comment by kushthedude** [comment]
Stale ?

**Comment by maze-runnar** [comment]
> Wrong approach!

why?

**Comment by kushthedude** [comment]
Make a filter for this.

**Comment by CosmicCoder96** [comment]
Read the issue carefully, it's about increasing the precision of filtering by making use of time in addition to the date, not sure what you are trying to here. Please reopen a PR with the correct implementation.

**Pull request closed without merging**
