### PR TITLE
feat: Showing Tickets Stat on Public Event Page

### LINKED ISSUE #3090: Show Remaining Tickets On Tickets Page if Opted-Out
**Is your feature request related to a problem? Please describe.**

As EventBrite, Show the number of remaining ticket which are available for sale in the tickets public page

**Describe the solution you'd like**

Provide a toggle option if you want to show `Remaining Tickets` of the following on public page or not .
Parent : #2993 
**Additional context**

Screenshot 2019-06-08 at 1 13 14 PM

### PR DESCRIPTION
**Pull request by kushthedude**
- Fixes #3090 

- Corresponding Server PR : https://github.com/fossasia/open-event-server/pull/6032

#### Screenshot :- 

image

#### Short description of what this resolves:

- Addition of `Remaining Stats` on `Public Event Page`

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
@uds5501 Have a look

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Review !

**Comment by uds5501** [comment]
@shreyanshdwivedi seems fair. what's your opinion on this? @kushthedude

**Comment by kushthedude** [comment]
> @kushthedude @uds5501 I wanted to ask your opinion if we should implement this toggle feature on tickets or events?
> I think it'll be better if we implement it on event rather than ticket because an organizer will not prefer to toggle each ticket.

Agreed, @uds5501 I think the following field should be included in `Event Schema` , I will make appropriate changes

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Review Please

**Comment by kushthedude** [comment]
@CosmicCoder96 @niranjan94 @pradeepgangwar Review Please

**Pull request closed without merging**
