### PR TITLE
API integration on explore route

### LINKED ISSUE #553: Implement API on explore route
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Integrate event-type, event-topic, event-subtopic API to side bar
- Implement event search using filters

@anu-007 You can take it up until #551 is resolved

### PR DESCRIPTION
**Pull request by anu-007**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
API integration on explore route

#### Changes proposed in this pull request:

Fixes #553

### CODE REVIEW

**Comment by anu-007** [comment]
@niranjan94 I am trying to pass selected options from `sidebar` component to `explore` controller where the filtering is performed but getting an unexpected error on console 
image

**Comment by anu-007** [comment]
@niranjan94 here I am trying to pass filtered data to inner markup as a variable `eventlist` for this I have passed a function called `filterEventtype` function to side-bar component so that it is available as `filter` property to the component and for each selected items in component I have called filter function with the selected value which will become available to `filterEventType` function where filtering of event is done.
I followed this- https://guides.emberjs.com/v2.12.0/tutorial/autocomplete-component/

**Comment by geekyd** [comment]
@anu-007 Any updates on this?

**Comment by niranjan94** [comment]
Will re-open when needed.

**Pull request closed without merging**
