### PR TITLE
feat: Add afterOrderMessage field in event

### LINKED ISSUE #5560: Tab "Email" Implement Organizer Message and Email/Ticket PDF as Feature "Customize your order confirmation"
We need a way to allow organizers to share a message with ticket buyers right at the end of the order process, in the ticket email send to ticket buyers and in the ticket PDF. Custom Emails should be configurable through a tab on the Dashboard menu of events. Therefore please implement:

1. A tab "Custom Emails" on the organizer top menu of events behind the item "Tickets"
Screenshot from 2020-11-22 03-11-22

* [ ] a) On the page add a section heading: Customize Order Page
  * [ ] with message "After registering for your event, attendees will see a message on their order page. Here you can add special instructions or other useful information.
* [ ] b) Section: Customize Email and Ticket PDF
  * [ ] with message "Your attendees will also receive an email after registration, confirming their order. Add important instructions or other useful information for attendees here that you want to include in the ticket email and ticket PDF.

2. Add a **"customize a message on the order page"** (the page where the user can download the tickets and invoice)
  * [ ] a) Please add a box "Organizer Message" above the box "Attendee Information"
  * [ ] b) Only add the box if the organizer has actually included this information
  * [ ] c) Ensure it works on mobile view as well
Screenshot from 2020-11-10 13-53-11

3. Show the **customized message on the ticket email and order PDF**
  * [ ] a) Include the message in the ticket email below the final greetings as follows
  * [ ] b) But: Only show the message in the email if the organizer has actually configured a message (do not show a message if the organizer has not configured it)
  * [ ] c) Include the info on the ticket PDF.

`Below you find a message from the organizer.`

`---------------------------------------------------------------------------------------`
`[Message from organizer here]`

`----------------------------------------------------------------------------------------`

**LINKS**
Compare: https://www.eventbrite.com/support/articles/en_US/How_To/how-to-create-custom-order-confirmations

Screenshot from 2020-11-10 16-25-58

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5560

required #https://github.com/fossasia/open-event-server/pull/7611

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Screenshots please

**Comment by sachinchauhan2889** [comment]
order page 

order page


 basic step pages

basic step

**Comment by sachinchauhan2889** [comment]
order page

order page


create page

basic step

**Comment by mariobehling** [comment]
It does not work yet for me on this event here: https://open-event-fro-git-fork-sachinchauhan2889-after-order-a2281c.eventyay.vercel.app/orders/0e5fa96c-5ae8-4432-8b7d-b5913eda428f/view

I just added some text into the field and tested it.

Screenshot from 2021-01-15 23-33-03

Screenshot from 2021-01-15 23-33-56

**Comment by mariobehling** [comment]
I am not seeing the info in the order email neither yet.

Screenshot from 2021-01-15 23-34-52

**Comment by iamareebjamal** [comment]
Because the server PR is not merged and deployed https://github.com/fossasia/open-event-server/pull/7611

**Comment by iamareebjamal** [comment]
Oops, it was already mentioned here - https://github.com/fossasia/open-event-frontend/pull/6388#issue-555903040

> required #fossasia/open-event-server#7611

**Comment by mariobehling** [comment]
Ahh sorry, missed that. So, from what I can see up to here it looks good. Rich-text editor would be nice, but can also done in follow-up issues.

**Pull request merged**
