### PR TITLE
Sorting of the latest added languages in languages drop-down table

### LINKED ISSUE #2847: Languages added in the drop down are not sorted
**Describe the bug**

The languages added latest in the drop down of languages are not sorted as some of them were added latest.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Home page'
2. Click on 'English button'
3. See error

**Expected behaviour**

Should be in sorted order

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Chrome
 - Version : 71.0398

**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Sorted the latest added languages in languages drop-down table.

#### Changes proposed in this pull request:

- Update `languages.js`

Fixes #2847

### CODE REVIEW

**Comment by mohitm15** [comment]
@CosmicCoder96 @pradeepgangwar Please review it

**Comment by kushthedude** [comment]
I think, it is not required there are still numerous bugs out there and still, we will sort the languages using `Sort By Name`, What you say @uds5501

**Comment by uds5501** [comment]
@kushthedude not sure about the requirement but yes, @mohitm15 please use `sort by name`

**Comment by mohitm15** [comment]
> @kushthedude not sure about the requirement but yes, @mohitm15 please use `sort by name`

@uds5501 Earlier it was hardcoded so I preferred it rather than using `sort by name`. Let's mentors decide @CosmicCoder96

**Comment by mohitm15** [comment]
@CosmicCoder96 sure l will do it

**Comment by CosmicCoder96** [comment]
@mohitm15 Update or close this please.

**Comment by mohitm15** [comment]
> @mohitm15 Update or close this please.

Sure !

**Comment by ritikamotwani** [comment]
@mohitm15 , have you tested the code?

**Comment by mariobehling** [comment]
This PR does not seem to meet quality requirements. Please open a PR that works once ready. Thanks!

**Pull request closed without merging**
