### PR TITLE
fix: Speakers Call Page fix

### LINKED ISSUE #3016: Call for Speakers page Error
**Describe the bug**
The cfs event has an error when its trying to be accessed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any event with Call for Speakers.
2. Click on **Call for Speakers.**
3. See error

**Expected behaviour**
The CFS page must open as usual

**Error log**

`Error while processing route: public.cfs.index – "undefined is not an object (evaluating 'transition.params['public.cfs']')" (1)
`
`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'transition.params['public.cfs']')`

**Desktop (please complete the following information):**
 - MacOS
 - Browser [Safari]

**Additional context**
Working on this.

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #3016 

#### Changes proposed in this pull request:

- Changed the access method to `transition.params`

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
Shouldn't this be how we access `transition.params.{route-name}.{parameter-name}`?

**Comment by uds5501** [comment]
@mrsaicharan1 Funny, I can't see any property `params` in this Transition object :thinking:

**Comment by kushthedude** [comment]
@uds5501 @mrsaicharan1 I cant understand why do we need to define `Hash for CFS Route` , I have seen `Comparators` and those work well even without defining `Hash` , Or am I missing some thing here ?

**Comment by uds5501** [comment]
@kushthedude tbh, i don't really know what's that hash for, could you suggest an alternative

**Comment by mrsaicharan1** [comment]
Yeah, that’s what. @shreyanshdwivedi can you check this

**Comment by mrsaicharan1** [comment]
@niranjan94 Can you please clarify why we are using hash for cfs?

**Comment by mrsaicharan1** [comment]
Yeah, that’s what. @shreyanshdwivedi can you check this
@CosmicCoder96 @niranjan94 Can you please clarify why we are using hash for cfs?

**Comment by kushthedude** [comment]
> Yeah, that’s what. @shreyanshdwivedi can you check this
> @CosmicCoder96 @niranjan94 Can you please clarify why we are using hash for cfs?

@mrsaicharan1 I tried to understand the code a bit deeper , And If i am right the `Hash` is used to protect unauthorised access to `CFS` when CFS is set private by the organiser , If the valid hash is not provided while trying to access a `Private CFS` , you will be routed to `Not Found` .
@CosmicCoder96 @niranjan94 Please correct me if I am wrong

**Comment by mrsaicharan1** [comment]
@kushthedude Hmm okay. Could you check why `transition` has no property params? Wasn't able to find why it was missing.

**Comment by CosmicCoder96** [comment]
@kushthedude is correct.

**Pull request merged**
