### PR TITLE
Sort the events at /explore in ascending order

### LINKED ISSUE #617: Sort the events at '/explore' by date( nearer event first ).
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently, the events are shown in descending order i.e the event which is at last datewise is shown first.
acc4

Expected:
The event which is nearer by date should be shown first as is shown on index page.
acc5

### PR DESCRIPTION
**Pull request by sumedh123**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #617

### CODE REVIEW

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 @harshitagupta30 Please review.
The acceptance tests are failing here for schedule and event-copyright since ember data request is returning 404 for an event. Is there a way around to fix this?

**Comment by niranjan94** [comment]
Comment out all acceptance tests that fail. We'll still have unit and
integration
We'll be facing these issues until we have our own mock server.

**Comment by niranjan94** [comment]
Deployment link: https://pr-618-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@niranjan94 Done :+1:

**Comment by niranjan94** [comment]
Deployment link: https://pr-618-open-event-frontend-fossasia.surge.sh

**Pull request merged**
