### PR TITLE
Implement ember fastboot server

### LINKED ISSUE #1947: Modify Docker image to run fastboot server in production environment
Current deployment does not make use of ember fast boot, the site should load through a fastboot sever.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
#### Changes proposed in this pull request:

-  Create files for fastboot server
- Modify Dockerfile to support fastboot server

Fixes #1947

### CODE REVIEW

**Comment by iamareebjamal** [comment]
docker build is failing, do not merge

**Comment by CosmicCoder96** [comment]
@iamareebjamal putting this on hold for now, there is a known bug with ember-fastboot-server not being able to load all it's dependencies independently. Will have to figure something out.

**Comment by CosmicCoder96** [comment]
@niranjan94 can you take a look.

**Comment by niranjan94** [comment]
@CosmicCoder96 will take a look

**Comment by niranjan94** [comment]
@CosmicCoder96 https://github.com/fossasia/open-event-frontend/compare/feature/fastboot-production-ready this one works. Check it out

**Comment by CosmicCoder96** [comment]
thanks @niranjan94 closing this in favor of #1962

**Pull request closed without merging**
