### PR TITLE
Redirect to Create Event Page after the user is authenticated

### LINKED ISSUE #2370: Login page does not redirects back to create event for guest user
**Describe the bug**

When the guest user (not logged in) tries to create event, he/she is taken to the login page, but after that, the user is not redirected back to the create event page upon successful login.

**To Reproduce**
1. Go to 'Create event' page when not logged in.
2. Fill the login form with correct credentials.
3. See error

**Expected behavior**

User should be redirected back to the create event page upon successful login.

**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #2370 

#### Short description of what this resolves:
Unauthenticated User was redirected back to home page instead of the last route he accessed.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
@prateekj117 Similar to this https://github.com/fossasia/open-event-frontend/pull/2377/files#r277937540 Please change approach

**Comment by prateekj117** [comment]
@niranjan94 @CosmicCoder96 @kushthedude I tried using [fulfillCallback](https://guides.emberjs.com/release/routing/asynchronous-routing/) and [rejectCallback](https://guides.emberjs.com/release/routing/asynchronous-routing/), but that didn't work no idea why. What other approaches can I go with?

**Comment by niranjan94** [comment]
@prateekj117 this is provided by `ember-simple-auth` already. (See -> https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/application-route-mixin.js#L102) 

Could you investigate what is wrong with our implementation and of ember-simple-auth and do the necessary changes ?

**Comment by prateekj117** [comment]
@niranjan94 One thing I noticed is that redirects work in case we manually put the Url in Address Bar, and not when we click the Create Event Button as already pointed out by @Haider8 in the issue. So does this seem to point anything specific out to you?

**Comment by mariobehling** [comment]
Thanks, please follow the suggestions. Let's keep conversations concise and focus on code. Cheers.

**Comment by mariobehling** [comment]
@prateekj117 Looks like this PR is inactive.Please reopen if you would like to follow up. Thanks.

**Pull request closed without merging**
