### PR TITLE
fix: Style of events-app on Overview Page 

### PR DESCRIPTION
**Pull request by daretobedifferent18**
#### Description
Style not good for event-app on the overview page

BEFORE
Screenshot from 2020-12-12 00-26-45

AFTER
Screenshot from 2020-12-12 00-25-42

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@iamareebjamal Pls have a look

**Comment by daretobedifferent18** [comment]
@iamareebjamal Pls have a look

**Comment by iamareebjamal** [comment]
Can't see the issue 
image

**Comment by daretobedifferent18** [comment]
> Can't see the issue
> image

oh really

**Comment by iamareebjamal** [comment]
Applicable on lower resolutions

**Comment by daretobedifferent18** [comment]
@iamareebjamal yes it was applicable on lower revolution

**Pull request merged**
