### PR TITLE
fix: Session and Exhibitor Form Simplify Slide Form Element

### LINKED ISSUE #7000: Session and Exhibitor Form: Simplify Slide Form Element
In the past we had decided to offer an option to either upload slides or link them from somewhere else. It turns out that this makes things more complicated. We cannot validate slides and link locations of slides might change.

Therefore change the slide form areas in the session form and the exhibitor form to only provide the option to upload slides.
Also change the following:
* Do not show the API link of slides anymore, instead show a more standard display with the slide name similar to other services with this feature

For existing slides that are on external pages, please use a script to download these slides and import them into the system and show them as uploaded slides.

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #7000 

Screenshot from 2021-05-24 17-09-05
Screenshot from 2021-05-24 17-08-46
Screenshot from 2021-05-24 17-07-17

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
also the remove file button, should be similar to as in delete image bottom attached I think.

**Comment by ranjitkshah** [comment]
> previously uploaded files are not showing, due to google iframe issue.
> Screenshot from 2021-05-25 08-20-04

should i need to implement refresh button here also  or any other way to show slides?

**Comment by maze-runnar** [comment]
don't add refresh button , just refresh is on initialize.

**Comment by ranjitkshah** [comment]
> also the remove file button, should be similar to as in delete image bottom attached I think.

Screenshot from 2021-05-27 09-17-26

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please do not add a preview into the form itself. The issue only states to get rid of the link element. Slides always need to be uploaded. No more links to external slides.

**Review by MeghalBisht — APPROVED** [review]

**Review by maze-runnar — APPROVED** [review]

**Pull request merged**
