### PR TITLE
feat: introduce event owner role to the system

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Reference - #3225
Server PR - https://github.com/fossasia/open-event-server/pull/6131

#### Short description of what this resolves:
Recently, event `owner` role is added to server. This is a follow-up PR to ensure the changes are applied to FE too

#### Changes proposed in this pull request:
- Adds `owner` to admin-statistics-user
- Changes `hasOrganizerInfo`, `organizerName`, `organizerDescription` to -> `hasOwnerInfo`. `ownerName`, `ownerDescription` respectively in event model.
- Adds owner relationship to event model
- Adds `isUserOwner` and `ownerEvents` to user model.
- Adds owner to event-role permissions
- Make relevant changes to template to accomodate above mentioned changes 

_Manage Events_
Screenshot_2019-07-03 Live Events Open Event

_Event Owner Permissions_
Screenshot_2019-07-03 Event Roles Permissions Administration Open Event

_Admin Events_
Screenshot_2019-07-03 Events Administration Open Event

_Admin Dashboard_
Screenshot_2019-07-03 Administration Open Event

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
@shreyanshdwivedi Make the changes in `Admin/Dashboard` too

**Comment by shreyanshdwivedi** [comment]
@kushthedude which changes? I'll suggest you to pull the changes and check because I think I already implemented what you're suggesting. Please check if I left any place which needs refactor too.
Thank You

**Comment by kushthedude** [comment]
`Permissions Panel` needs updation too : 

image

**Comment by shreyanshdwivedi** [comment]
@kushthedude please refer to my screenshots for first issue. Multiple roles are getting rendered.
For other issues, I've already opened a server PR. Forgot to link it - https://github.com/fossasia/open-event-server/pull/6131

**Comment by kushthedude** [comment]
@shreyanshdwivedi Great, so we can cover each and every refactor in various PRs to test it properly

**Comment by shreyanshdwivedi** [comment]
@kushthedude @uds5501 @mrsaicharan1 please review

**Comment by shreyanshdwivedi** [comment]
@uds5501 @kushthedude @CosmicCoder96 the server PR is merged. This PR is ready to be reviewed and can be merged

**Pull request merged**
