### PR TITLE
feat: Order Summary making similar to EventBrite

### LINKED ISSUE #2993: Order Summary Improvements and Making it similar to EventBrite
There is scope for several improvements in Tax Modal generated at `Order Checkout` -:
 
* [x] Include `Ticket Price` in row of every ticket
* [x] For a `Free Ticket` adding tax does not make any sense , Remove the `Column for Free Ticket`.
* [x] Fix the alignment issue in `Order Checkout`
* [x] Remove the `Discount Column` if no `Discount Code` is applied
* [ ] Show `Subtotal` inclusive of `Individual Ticket with Tax Rate`
* [x] Columns of `Payment Dialogue` are wrongly placed , Use standard order as in `Eventbrite` or any E-Commerce Site.

#### Screenshot -:

Screenshot 2019-05-23 at 4 19 45 PM

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #2993 

#### Changes Made in This PR -:

- Modifies the Summary Table for Free tickets or Discounted Tickets with Net Order Value Resulting in Zero.
- Hide Discount Column if the discount is not applied.
- Subtotal includes the Tax for each ticket now 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@kushthedude I was able to see parts of everything over there. Could you please add a final screenshot? Thanks!

**Comment by kushthedude** [comment]
#### Screenshot :
image

image

image

image

**Comment by kushthedude** [comment]
@mrsaicharan1 @shreyanshdwivedi @uds5501 Please Review

**Comment by kushthedude** [comment]
@CosmicCoder96 Please Review

**Comment by kushthedude** [comment]
@CosmicCoder96 I think we are good to go for this now?

**Comment by kushthedude** [comment]
@CosmicCoder96 I think we are good to go for this now?

**Comment by kushthedude** [comment]
@uds5501 @mrsaicharan1 Please Review

**Pull request merged**
