### PR TITLE
fix: show location in different line and remove reset map

### PR DESCRIPTION
**Pull request by maze-runnar**
scrnli_10_8_2020_1-13-39 PM
scrnli_10_8_2020_1-15-49 PM
scrnli_10_8_2020_1-15-08 PM

scrnli_10_8_2020_1-16-46 PM

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Your example does not seem to get the location. It just shows a world map. Are you using a real world location? Please test with a real address.

Also change:
* Please do not make a new paragraph for each line. A simple line break should do. In any case the spacing should not be so big
* Show Zip code behind the state on the same line

**Comment by maze-runnar** [comment]
> Are you using a real world location?

no, will test it.

> Please do not make a new paragraph for each line. A simple line break should do. In any case the spacing should not be so big

ok

> Show Zip code behind the state on the same line

What it means, I am not getting it

**Comment by mariobehling** [comment]
Do not make the ZIP code on a new line. Display the Zip Code as it would be usually written.

**Comment by maze-runnar** [comment]
map location is showing correctly -
scrnli_10_9_2020_7-53-36 AM

**Comment by maze-runnar** [comment]
ember leflet has been added to project and I will solve adding address to new line issue in another PR.

**Pull request closed without merging**
