### PR TITLE
feat: followers table export as csv

### LINKED ISSUE #7601: Groups: Add "Followers" page for Owners/Organizers
The group information is implemented and following is possible. Group organizers do not have the possibility to view the members yet though. Therefore please

Implement the following:
- [x] Add a tab "Followers" behind the "Events" tab on the groups edit page for organizers
- [x]  * On this "Followers" page (for organizers) show a table of followers with user image (if made public), public profile name, group join date, email address
- [ ] Also implement a CSV export for this table

- [x] Change the implementation when users click a "Follow" button of a group as follows:
 Implement a pop up with the message: "By following this group you accept that: 1. You will receive announcement emails for events of this group. 2. You share your email with the group owners and organizers. 3. All group members will be able to see your public profile image and name. Do you want to proceed? Yes, follow this group. / Cancel"

Screenshot from 2021-07-23 17-13-30

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #7601 
reqd #https://github.com/fossasia/open-event-server/pull/8163

#### Short description of what this resolves:
Screenshot from 2021-08-10 13-46-01

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
This is a bit confusing. I think we would actually want to see this
1. Public Profile Name
2. Email
3. Group Join Date
4. Role (Owner, Organizer or Follower)

**Comment by mariobehling** [comment]
Screenshot from 2021-08-10 15-28-25

Please move the CSV download button in front of the Search box on the same row.

**Comment by ranjitkshah** [comment]
Screenshot from 2021-08-12 18-08-59

**Comment by MeghalBisht** [comment]
> Please move the CSV download button in front of the Search box on the same row.

The download button and search box are in different components. Hence this is not possible without doing major changes. Also. in other table related pages the same UI is followed. 
We can take this up if needed.

**Review by MeghalBisht — APPROVED** [review]

**Review by maze-runnar — APPROVED** [review]

**Comment by maze-runnar** [comment]
> This is a bit confusing. I think we would actually want to see this
> 
> 1. Public Profile Name
> 2. Email
> 3. Group Join Date
> 4. Role (Owner, Organizer or Follower)

Done

**Pull request merged**
