### PR TITLE
Time format mixed up fixed

### PR DESCRIPTION
**Pull request by SARTHAK1SINGH**
Fixes # https://github.com/fossasia/open-event-frontend/issues/8637

## Before:
Screenshot from 2023-01-26 13-22-42

## After:
Screenshot from 2023-01-26 13-05-21

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by maze-runnar — APPROVED** [review]

**Comment by maze-runnar** [comment]
LGTM!

**Comment by SARTHAK1SINGH** [comment]
@mariobehling Tests are failing due to some other reason.
Tests failed before this PR also.
PR cannot be merged due to this.
Please create a new issue for this.
I will take a lot of time and effort for this.

**Comment by maze-runnar** [comment]
tests are failed for master as well currently. 
Screenshot 2023-01-26 at 7 23 29 PM

**Review by mariobehling — APPROVED** [review]

**Review by mariobehling — APPROVED** [review]

**Comment by rolandturner** [comment]
I have presumably missed a motivating discussion somewhere, but would suggest that there remains a problem:

- It's good that we no longer show sessions as finishing in the early hours of the morning more than 12 hours after they start!
- It's unfortunate that we're using two different time formats in the same display. At any one time we should either use either 12-hour or 24-hour, not mix the two.

We already have a means to select timezone. I'd suggest the same again immediately beside it to select 12/24 hour time. If there is information available in the browser to default to the user's current preference then of course it should default accordingly.

**Comment by marcoag** [comment]
This PR lacks explanation on the problem and why this change fixes the issue. The template of the issue is ignored. Let's try to document PR/Issues properly.

I agree with @rolandturner in that we should not mix time formats in the same display but I would say not even across eventyay. We should further discuss this over issues and other discussion means 

Since this change is minimal and it seems to solve an issue I'll give the LGTM, however I don't think we should close the issue until the standarization of time formats is completed.

**Review by marcoag — APPROVED** [review]

**Review by cweitat — APPROVED** [review]

**Pull request merged**
