### PR TITLE
Aligning the options horizontally in the mobile view wherever required

### LINKED ISSUE #2541: Aligning the options to preview, edit event boxes horizontally in mobile view
**Is your feature request related to a problem? Please describe.**

The icons of the boxes shown in the previewing the event are shown vertically taking a lot space in the mobile view.

**Describe the solution you'd like**

To align them horizontally

**Describe alternatives you've considered**

We can also use drop down menu for this thing

**Screenshot**
https://photos.app.goo.gl/4a4H58WeBhqxJPv98

**Additional context**

Share your views, I would like to work on it.

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
It displays the option box like `edit`,`view`,`delete`,`activate`,`deactivate` on the event overview horizontally in the mobile view.

#### Changes proposed in this pull request:

- Update files by adding conditions for mobile view. Changed files are listed in the pull request.

#### Screenshot

Screenshot 2019-04-13 22:41:48

Fixes #2541

### CODE REVIEW

**Comment by kushthedude** [comment]
@mohitm15 Dont you even check the git status before pushing a pr , Remove the Conflicts and squash your commits.

**Comment by kushthedude** [comment]
Squash your commits @mohitm15

**Comment by kushthedude** [comment]
Your PR has parsing error do local tests before pushing @mohitm15 , How much more you need for this issue , dont just blindly push commits ?

**Comment by kushthedude** [comment]
@mohitm15 Are you still there or just busy with random stuff ?

**Comment by mohitm15** [comment]
@kushthedude I will make the changes as soon as l reach home pal. Don't
worry.

**Comment by kushthedude** [comment]
? Status

**Comment by mohitm15** [comment]
> ? Status

Just reached home, making changes accordingly!

**Comment by kushthedude** [comment]
Squash the commits

**Pull request merged**
