### PR TITLE
Align options horizontal at required places in mobile view

### LINKED ISSUE #2541: Aligning the options to preview, edit event boxes horizontally in mobile view
**Is your feature request related to a problem? Please describe.**

The icons of the boxes shown in the previewing the event are shown vertically taking a lot space in the mobile view.

**Describe the solution you'd like**

To align them horizontally

**Describe alternatives you've considered**

We can also use drop down menu for this thing

**Screenshot**
https://photos.app.goo.gl/4a4H58WeBhqxJPv98

**Additional context**

Share your views, I would like to work on it.

### PR DESCRIPTION
**Pull request by mohitm15**
Align options horizontal at required places in mobile view
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
 It makes the option buttons horizontally as they were taking much spaces when are vertical in mobile view.

#### Changes proposed in this pull request:

- update required files listed in the commits

Fixes #2541 

#### Screenshot

Screenshot 2019-04-13 22:41:48

### CODE REVIEW

**Comment by kushthedude** [comment]
Your branch has merge conflicts remove them and squash your commits @mohitm15

**Comment by mohitm15** [comment]
@CosmicCoder96 Reviews required.

**Comment by kushthedude** [comment]
@mohitm15 before asking for reviews you should squash commits and last time i told you too please squash them

**Comment by mohitm15** [comment]
@kushthedude these commits are not appearing on  the terminal after rebasing, so unable to squash them.
So that's why I am asking reviews for that to @CosmicCoder96

**Comment by CosmicCoder96** [comment]
@mohitm15  This PR has some random commits which are not even authored by you,  I believe I closed 3 PRs last time because you couldn't generate proper commits and repeatedly asked you to not Open PRs until you figure out how git, and GitHub works. There is no hurry or a deadline to make these PRs. This is not the right place to learn how to pull requests and commits work, please do this testing on your personal repositories.
You are cluttering up the repository with closed, redundant PRs. This has 8 commits, one of them authored by @uds5501 and merged by you.  On top of it, a failed build. No, I cannot review this.

**Comment by uds5501** [comment]
@mohitm15 make a branch off updated development and then work on it. That should fix your problems

**Pull request closed without merging**
