### PR TITLE
fix: Do not allow "Withdraw" session after session was held

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/5051

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Does this also need a change in the backend?

**Comment by maze-runnar** [comment]
> Does this also need a change in the backend?

i think, no.

**Comment by iamareebjamal** [comment]
It does. This will only not show the button, but the API will allow it

**Comment by maze-runnar** [comment]
> It does. This will only not show the button, but the API will allow it

ok, making changes on server side too.

**Pull request merged**
