### PR TITLE
fix: Change speakers list from 3 column to 4 column layout in Public Speaker's Page

### LINKED ISSUE #6594: Public Speaker's Page: Change speakers list from 3 column to 4 column layout
The public speakers page has a 3 column layout. Speakers are also prominent enough if we have a 4 column layout similar to the reorder page of speakers. Please change the layout on the public speakers page to 4 column, e.g. here https://eventyay.com/e/fa96ae2c/speakers (but leave it at 3 columns on the event start page for now). Adjust the size of images and area as needed.

Screenshot from 2021-02-03 11-13-14

### PR DESCRIPTION
**Pull request by afzal442**
Fixes #6594 

Screenshot after changes proposed
c2

#### Changes proposed in this pull request:

- Changed the column of speakers list

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by afzal442** [comment]
@mariobehling sir, plz review it.

**Comment by mariobehling** [comment]
The spacing is not following the main page and spacing below the text is too large. I need to come back with more details later or you can try to find out by comparing things. This is not pixel correct compared to other pages. Thanks.

**Comment by afzal442** [comment]
Thanks Sir. I am not able to access speaker's reorder page. Could you share the link please?

**Comment by afzal442** [comment]
Sir, plz elaborate a bit more. If I try to adjust the size of images and area, it can alter the same on speaker's list of event's start page.

**Pull request closed without merging**
