### PR TITLE
feat: Reorder Speakers

### LINKED ISSUE #5443: Public Speaker Page/Organizer Speaker Page: Make Speakers Sortable
Currently there is no option to control the order of speakers on the public page. Sometimes important speakers are listed at the end of the speakers list. This is not good. We need a way to sort speakers. Therefore please implement the following:
* On the organizer speakers page provide the option to change the order of speakers. Use the same up and down arrow feature that is available on the ticket list.
* On the feature speaker list and public speaker page of an event show the speakers in the same orders as on the organizer speakers page.

Speakers on the organizer speakers page
Screenshot from 2020-11-01 23-33-48

Public speakers view
Screenshot from 2020-11-01 23-25-59

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #5443

### CODE REVIEW

**Comment by mariobehling** [comment]
Excellent!

Just one small thing. Can the width of the buttons be expanded a bit so they only cover one line like most other buttons. Thanks!

Screenshot from 2021-02-03 10-34-02

**Comment by mariobehling** [comment]
Does not seem to be 100% reliably yet. If I change a lot of speakers it does not seem to save all changes. Maybe the API does not catch everything so fast? Also some speaker appear twice.

Screenshot from 2021-02-03 10-46-11

**Comment by mariobehling** [comment]
When I save and then refresh changes are gone.

**Comment by iamareebjamal** [comment]
Because of the cache, it'll take 10 minutes. I'm thinking of a solution

**Comment by mariobehling** [comment]
> Because of the cache, it'll take 10 minutes. I'm thinking of a solution

Ok, I understand. If the public page is cached that is ok, but the order is also not correct if I save the re-order page and then reload it here https://open-event-frontend-git-fork-iamareebjamal-speaker-order.eventyay.vercel.app/events/fa96ae2c/speakers/reorder

Maybe it works a bit later. Need to test in more detail.

**Comment by iamareebjamal** [comment]
That page is cached as well

**Comment by iamareebjamal** [comment]
Now the reorder page is not cached, so changes should be visible after reload. Public page is cached so changes will take 10 minutes to show and because of this, some speakers may be visible twice

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
