### PR TITLE
fix: increase table width to avoid overflow and collapse

### LINKED ISSUE #4113: horizontal buttons are overflowing in mobile-view
**Describe the bug**
Screenshot from 2020-02-18 00-08-11

**Additional context**
working on it.

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4113 
Screenshot from 2020-02-18 00-34-30

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
before : 
Screenshot from 2020-02-18 00-51-49
After :
Screenshot from 2020-02-18 00-54-39

**Comment by kushthedude** [comment]
Increase the column width rather than this and also increase widths for URL sections too as I can see overlaps

**Comment by maze-runnar** [comment]
> Increase the column width rather than this and also increase widths for URL sections too as I can see overlaps

How to increase width in ember-tables?

**Comment by kushthedude** [comment]
There will be multiple old PRs for similar sort of issue. Just make a
search and you will get your answer.

**Comment by maze-runnar** [comment]
> There will be multiple old PRs for similar sort of issue. Just make a search and you will get your answer.


https://github.com/fossasia/open-event-frontend/pull/3579#pullrequestreview-310805668

**Comment by kushthedude** [comment]
Increase the width for now , actions column is ultimately going to be
removed if number of properties increaaes.

**Comment by mohitm15** [comment]
@maze-runner Refer #2871

**Comment by maze-runnar** [comment]
Screenshot from 2020-02-18 12-18-05
Screenshot from 2020-02-18 12-21-51
Screenshot from 2020-02-18 12-21-54

**Comment by maze-runnar** [comment]
> @Maze-runner Refer #2871

that's not the solution, that is root of this issue.

**Comment by snitin315** [comment]
Screenshot_2020-02-18-15-30-04-489_com android chrome


### Overlapping for name email and phone field as well.

**Comment by kushthedude** [comment]
> > @Maze-runner Refer #2871
> 
> that's not the solution, that is root of this issue.

@maze-runnar For the speaker section, Please the sessions table and implement it similarly with actions buttons beneath the name. Regarding the access code tables, just increase the column width so that values do not overlap.

**Comment by maze-runnar** [comment]
> Screenshot_2020-02-18-15-30-04-489_com android chrome
> 
> ### Overlapping for name email and phone field as well.

@snitin315 can you please specify its path.

**Comment by snitin315** [comment]
Speakers table.

**Comment by maze-runnar** [comment]
> > > @Maze-runner Refer #2871
> > 
> > 
> > that's not the solution, that is root of this issue.
> 
> @maze-runnar For the speaker section, Please the sessions table and implement it similarly with actions buttons beneath the name. 

I'm not getting this line, can you please tell what to do exactly?

**Comment by kushthedude** [comment]
> > > > @Maze-runner Refer #2871
> > > 
> > > 
> > > that's not the solution, that is root of this issue.
> > 
> > 
> > @maze-runnar For the speaker section, Please the sessions table and implement it similarly with actions buttons beneath the name.
> 
> I'm not getting this line, can you please tell what to do exactly?

Just increase the widths for now then.

**Comment by maze-runnar** [comment]
> Just increase the widths for now then.

Done !

**Comment by maze-runnar** [comment]
@kushthedude  please review

**Comment by snitin315** [comment]
>When you make very minor changes to a PR of yours (like for example fixing a failing Travis build or some small style corrections or minor changes requested by reviewers) make sure you squash your commits afterward so that you don't have an absurd number of commits for a very small fix.

**Pull request merged**
