### PR TITLE
Add test for routes

### LINKED ISSUE #958: Increase code coverage by adding acceptance test
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently the code coverage is very low. This is because of lack of tests.

**Expected behavior:**
Add tests for routes to increase code coverage

### PR DESCRIPTION
**Pull request by pradeepgangwar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works

#### Short description of what this resolves:
Add test for routes to increase code coverage.

Partially Fixes issue #958

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@geekyd Please review.

**Comment by niranjan94** [comment]
Deployment link: https://pr-961-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
These won't increase coverage. These are just test boilerplates. No point in adding this just for the sake of increasing coverage.

**Comment by niranjan94** [comment]
Deployment link: https://pr-961-open-event-frontend-fossasia.surge.sh

**Comment by pradeepgangwar** [comment]
@geekyd Thanks! I think i can try adding more tests. I will commit soon if i am able to add more tests.

**Comment by niranjan94** [comment]
Deployment link: https://pr-961-open-event-frontend-fossasia.surge.sh

**Comment by pradeepgangwar** [comment]
@geekyd please review.

**Pull request merged**
