### PR TITLE
fix: set default mail-log size to 10

### LINKED ISSUE #2905: Admin Mail Logs page at shows error
Mail Logs page at https://eventyay.com/admin/reports/system-logs/mail-logs displays error messages when sorting. It also shows more than 10 messages even though 10 is set as default.

Screenshot from 2019-05-13 10-20-26

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This makes sure that the initial number of mail-logs being shown in reports/mail-logs are `10`
As far as sorting is concerned, it is working fine for me :sweat_smile: 

Fixes #2905

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 @ritikamotwani Please review

**Comment by mariobehling** [comment]
Please avoid to ping the same people for review and start to work together with your co-developers. Review each others PRs, please!

**Comment by uds5501** [comment]
@mariobehling Sure, will keep this in mind!

**Comment by uds5501** [comment]
@shreyanshdwivedi @mrsaicharan1 Have a look

**Comment by uds5501** [comment]
@shreyanshdwivedi @mrsaicharan1 Please review :)

**Comment by uds5501** [comment]
@CosmicCoder96 The issue specified the initials to be set to 100 for `activity-logs` , maybe the `mail-logs` were updated with that too?

**Comment by CosmicCoder96** [comment]
@uds5501 I believe it referred to logs in general, as they all share the same table.

Either way, this issue should fix the inconsistency in dropdown value of page limit, and the one actually loaded in the model on the first render.

**Comment by CosmicCoder96** [comment]
@uds5501 Any updates on this?

**Comment by uds5501** [comment]
@CosmicCoder96 To be honest, i can't find any decent connection between the page size and initial route render. You can close it for now

**Pull request closed without merging**
