### PR TITLE
fix: Order Form Stripe Payment: Increase button size

### LINKED ISSUE #6406: Order Form Stripe Payment: Increase button size
The order button of the stripe button is not prominent enough. Please increase the size of the "Pay Now" button to the entire width of the sidebar.

Compare https://eventyay.com/e/19128bdf

Screenshot from 2021-01-17 23-57-17

### PR DESCRIPTION
**Pull request by afzal442**
Fixes #6406 

#### Changes proposed in this pull request:

- Extended the button width
 Screenshot
c1

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please also increase the button height and font size to the same as the gray area of the below "attendee information".

**Comment by afzal442** [comment]
Latest Commit SS
c1

**Comment by afzal442** [comment]
@mariobehling plz have a look.

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
