### PR TITLE
Fix: The overlapping of the logo to navbar

### PR DESCRIPTION
**Pull request by Raunaksingh100**
### Description---
The logo is  overlapping to the navbar and covering the half of the content  Due to the large size of the width,,,
 i reduced the width of the logo by doing this the bug fixed  and it doesnot affect the DESKTOP SITE and fixed the MOBILE SITE
plz see in the screenshot given below for the better understanding..........................

### 1.
fixed moto
### 2.
fixe3d gs5

###  Screenshot for the Desktop Site ------
issue desk

@iamareebjamal plz review-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Raunaksingh100** [comment]
@iamareebjamal  this doesnot affect the desktop site you can also see in the mobile view given above

**Comment by iamareebjamal** [comment]
Please add screenshots of several examples

**Comment by Raunaksingh100** [comment]
> Please add screenshots of several examples in desktop and mobile mode

Sure I will add the screenshot for before and after

**Comment by Raunaksingh100** [comment]
> Please add screenshots of several examples in desktop and mobile mode

### After my Code this bug doesnot show in any screens i tested carefully, and doesnot effect the desktop site
screenshots are given below------

### for all the mobile site---
### 1.
fixed moto
### 2.
fixe3d gs5
### 3.
fgixed pixel 2
### 4.
fixed 678

### for the desktop site ------
issue desk

**Comment by Raunaksingh100** [comment]
@iamareebjamal  plz merge this pr

**Review by sachinsingh162 — APPROVED** [review]
LGTM

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/components/public/session-item.js  2
- app/models/social-link.js  1
- app/helpers/general-date.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6069670&bid=19876128)

**Pull request closed without merging**
