### PR TITLE
fix: added translations to licenses

### LINKED ISSUE #6340: Wizard Step 2: Make license names in dropdown and info links translatable
The licenses in the wizard step 2 dropdown and info box are not translatable.

Screenshot from 2021-01-12 19-19-01

### PR DESCRIPTION
**Pull request by himanshujaidka**
Fixes #6340 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Revert all changes in pot file, they are generated automatically

**Comment by himanshujaidka** [comment]
> Revert all changes in pot file, they are generated automatically

okay

**Comment by himanshujaidka** [comment]
> Revert all changes in pot file, they are generated automatically

@iamareebjamal sir pls have a look now

**Comment by iamareebjamal** [comment]
The messages will not be extracted, because they are not wrapped in t

**Comment by himanshujaidka** [comment]
> The messages will not be extracted, because they are not wrapped in t

the messages are in a typescript and there is no use of functions, so how to wrap them?

**Comment by iamareebjamal** [comment]
Exactly, if the issue was that easy, it would have been solved already

**Comment by himanshujaidka** [comment]
> Exactly, if the issue was that easy, it would have been solved already

No problem sir, I want to do that, I am here for learning new things and gained some experience, but pls guide me in this issue and it is seems to be interesting one

**Comment by iamareebjamal** [comment]
https://github.com/Cropster/ember-l10n We want a way for strings to be extracted but l10n.t returns translated strings, you'll need to modify the library to add a no-op function that returns untranslated string but extracts it using CLI.

First create an issue in the library asking the author if it is possible to do so already, if not, ask if they'd merge a PR containing the feature, if they say yes, send the PR

**Comment by himanshujaidka** [comment]
> https://github.com/Cropster/ember-l10n We want a way for strings to be extracted but l10n.t returns translated strings, you'll need to modify the library to add a no-op function that returns untranslated string but extracts it using CLI.
> 
> First create an issue in the library asking the author if it is possible to do so already, if not, ask if they'd merge a PR containing the feature, if they say yes, send the PR

ok, thank you, look into it

**Pull request closed without merging**
