### PR TITLE
Improve text in basic details step and videoroom form

### LINKED ISSUE #8517: Improve text and options for online video in the wizard step 1
Please improve this as follows:
* Change Public Stream VideoId to "Public Stream Video-ID"
* Move Autoplay/Loop into one line/row
* Please also implement this for Vimeo

Screenshot from 2022-04-14 11-02-40

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #8517 
Screenshot 2022-04-14 at 23-49-58 Create an Event eventyay
Screenshot 2022-04-14 at 23-56-55 Create Video Room Microlocation new 7735 Events eventyay

### CODE REVIEW

**Comment by mariobehling** [comment]
Please make it aligned in one line and add some spacing between the text and the buttons.

**Comment by progmatic-99** [comment]
Screenshot 2022-04-15 at 11-48-09 Create an Event eventyay
Screenshot 2022-04-15 at 11-55-30 Create Video Room Microlocation Stripe-test Events eventyay

**Comment by mariobehling** [comment]
This issue is only related to the wizard step 1.

Please do not make any change on the video page area.

* [x] Change Public Stream VideoId to "Public Stream Video-ID"
* [x]  Move Autoplay/Loop into one line/row
* [ ]  Please do not make the space between text and buttons too big. Maybe a third of the current spacing.

* [ ] Please also implement this for Vimeo on the wizard
Implementing this for Vimeo means that the form element should show the vimeo video if a link like https://vimeo.com/16817564 is working as well additionally to Youtube.

**Comment by progmatic-99** [comment]
Screenshot 2022-04-15 at 23-40-23 Create an Event eventyay

**Comment by mariobehling** [comment]
Does not work with vimeo e.g. https://vimeo.com/16817564

**Comment by progmatic-99** [comment]
@mariobehling Do you want the video link to be previewed like, under a `Preview URL` ??

**Comment by progmatic-99** [comment]
Screenshot 2022-04-22 at 15-05-46 new-event eventyay

@mariobehling I have also changed how youtube video's are embedded. Please also test this.
Though I have tested both with youtube and vimeo.


**For autoplay to work, you have to allow in your browser to let videos autoplay and also enable audio autoplay.**

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
