### PR TITLE
feat: Add public page of exhibitors and view page of exhibitor

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please change the following:
1. In order to not confuse the user do not show the event social links and twitter box on the specific exhibitors sidebar (of single exhibitors)
Screenshot from 2021-02-09 02-04-36
2. Change sidebar menu item and link from "Exhibitors" to "Exhibition"
3. If there is no exhibitor in state "accepted" do not show the exhibitor on the public page and do not show a tab "Exhibition"
4. Increase the size of the slides and YouTube video to full width same as the image.
5. Add a "heading 2" above the slides "Exhibitor Slides", add a heading above the video "Exhibitor Video"
6. In the event side panel show a button "Exhibition", if the exhibition is active with at least one accepted exhibitor.
Screenshot from 2021-02-09 02-10-19
7. Make icons consistent and ensure all icons work. e.g. Google Groups does not have an icon
8. The website icon is not working. Please add it.
Screenshot from 2021-02-09 02-17-58

**Comment by mariobehling** [comment]
Thanks so far.

> In order to not confuse the user do not show the **event social links** and **twitter box** on the specific exhibitors sidebar (of single exhibitors)

But: Keep everything else (Join Event button, date, calendar button).

**Comment by mariobehling** [comment]
The icons of Twitter, Facebook, Flickr, Github, Youtube have the typical colors of the service, but all other icons are blue. These icons should also be in the default style and color of the service.

Screenshot from 2021-02-09 23-32-29

**Comment by mariobehling** [comment]
Also
* Please make "Exhibitor Slides" and "Exhibitor Video" into H2
* Ensure the top heading and all other headings have sufficient spacing above and below
   * Add spacing above heading 1
   * Add spacing below "Exhibitor Slides" and "Exhibitor Video"

**Comment by mariobehling** [comment]
Thanks! A final change please:
https://open-event-fro-git-fork-sachinchauhan2889-public-exhibit-d72c66.eventyay.vercel.app/e/fa96ae2c/exhibitors
should be -> https://open-event-fro-git-fork-sachinchauhan2889-public-exhibit-d72c66.eventyay.vercel.app/e/fa96ae2c/exhibition
After this is done it looks good to merge for me.

**Comment by iamareebjamal** [comment]
And exhibitor detail page? That should be exhibition/id as well

**Comment by mariobehling** [comment]
I discovered another issue unfortunately:

Pending exhibitors are listed on the overview page. Only accepted exhibitors should be listed on the overview page.

Thanks!

Screenshot from 2021-02-12 16-45-51

**Comment by mariobehling** [comment]
As you can see in the above screenshot: If an exhibitor does not upload an image the overview page shows a broken image. Please use a default image for "exhibitors" who do not upload an image.

**Comment by sachinchauhan2889** [comment]
Done

**Comment by mariobehling** [comment]
Thanks! Please compare https://open-event-fro-git-fork-sachinchauhan2889-public-exhibit-d72c66.eventyay.now.sh/e/fa96ae2c/exhibition/17

The exhibitor test image has a different size on the front page. 

Screenshot from 2021-02-12 20-14-10

And the issue with the broken image still exists on the specific exhibitor page.

Screenshot from 2021-02-12 20-16-23

**Comment by mariobehling** [comment]
@iamareebjamal Should we merge this here and change other things in follow up PRs?

Specifically the logo is too small on boath the overview page and on the detail page. 

Not sure how to position it that it looks nicely when it is bitter though. This needs to be tried out a bit.

**Comment by iamareebjamal** [comment]
Yes, let's follow up in other PR

**Pull request merged**
