### PR TITLE
fix: Ticket Deletion only when they don't have orders

### LINKED ISSUE #7806: Prevent Ticket Types and Registrations with Orders from Deletion
Ticket types and registrations can currently be deleted even if they have orders. Please prevent them from deletion and implement the following:
If an organizer tries to delete a ticket or registration from deletion show an error pop up: "This ticket or registration type already has orders. Therefore it cannot be deleted. Please hide this type instead by using the hide option under the settings symbol." and show an "Ok" button to close the pop up.

Screenshot from 2021-09-19 20-02-47

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #7806 

#### Short description of what this resolves:
Ticket types and registrations can currently be deleted even if they have orders. Please prevent them from deletion and implement the following:
If an organizer tries to delete a ticket or registration from deletion show an error pop up: "This ticket or registration type already has orders. Therefore it cannot be deleted. Please hide this type instead by using the hide option under the settings symbol." and show an "Ok" button to close the pop up.

#### Screenshots (If ticket has order)
Before | After
---------- | --------
Screenshot from 2021-09-20 18-04-01 | Screenshot from 2021-09-21 05-01-11

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by daretobedifferent18 — COMMENTED** [review]
If tickets are not allowed to delete, it show popup as show below.

has Orders | has No Orders
----------| ----------
Screenshot from 2021-09-20 18-04-01 | Screenshot from 2021-09-20 18-02-20

### Todo: 

- [ ] Change buttons from no and yes to only "OK" button.

Otherwise everything is working.

@mariobehling Pls have a look.

**Comment by maze-runnar** [comment]
it's good so far, just complete the remaining part of this PR.

**Comment by maze-runnar** [comment]
this is not working for a placed order, if the order is in the placed state, the organizer should not be able to delete ticket.

**Comment by daretobedifferent18** [comment]
> this is not working for a placed order, if the order is in the placed state, the organizer should not be able to delete ticket.

@maze-runnar This work for orders that are completed, should I validate for placed as well. let me know.

**Comment by maze-runnar** [comment]
Yes validate for placed too.

**Comment by maze-runnar** [comment]
Also I am not able to update your branch please allow edit from maintainers. i won't delete your code 😅

**Review by maze-runnar — APPROVED** [review]

**Pull request merged**
