### PR TITLE
fix : Event Dashboard: Fix and Enhance Sponsorbox 

### PR DESCRIPTION
**Pull request by ayushontop**
Fixes #

#### Short description of what this resolves:
#5462 As per the issue I deleted options column and edited Add Sponsors button to Edit and added margin to previous and next button

#### Changes proposed in this pull request:

- Deleted Column Options
- Edited Add Sponsors
- Given Margin between previous and next button 

#### Checklist

- [x]  I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).

- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thank you. Please change as follows:
* Align left of table with the same distance as the box heading to the left
* Expand column "name" to make space usage more efficient
* Reduce space between table and previous/next buttons

Screenshot from 2020-11-03 11-41-47

**Comment by mariobehling** [comment]
Please also use the same distance to the box edges for the "Edit" button as the other "Edit" button in the other box.

Screenshot from 2020-11-03 11-46-56

**Comment by ayushontop** [comment]
I wanna remove inline css but Can't find any css files . Can you please guide.

**Comment by ayushontop** [comment]
I think edit button is aligned, If not can you please elaborate what changes are required

**Comment by ayushontop** [comment]
@mariobehling  sir is it ok?

**Comment by iamareebjamal** [comment]
Issue has been fixed

**Pull request closed without merging**
