### PR TITLE
fix: add translations in order form

### LINKED ISSUE #7333: Order Process: Attendee form not translated
The attendee form elements are not translated on the order forms. Please make them translatable. They are already translated on the wizard. Also make "ticket holder" translatable.

Order Process Step 2

Screenshot from 2021-05-25 20-13-51

Order Process Step 3

Screenshot from 2021-05-25 22-53-53

Screenshot from 2021-05-25 22-54-05

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #7333
Screenshot from 2021-05-26 03-31-18
Screenshot from 2021-05-26 03-30-58

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by ranjitkshah — APPROVED** [review]

**Comment by mariobehling** [comment]
I cannot see "Ticketholder for Ticket 1" translated. Did you make it translatable?

**Comment by MeghalBisht** [comment]
> I cannot see "Ticketholder for Ticket 1" translated. Did you make it translatable?

It is already translatable in code. Maybe weblate didn't pick it.

**Comment by MeghalBisht** [comment]
Updated
Screenshot from 2021-05-27 00-04-07

**Comment by ranjitkshah** [comment]
works
Screenshot from 2021-05-27 09-24-49

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
