### PR TITLE
feat: Session Item: Make track, session room and date to direct to respected filter

### LINKED ISSUE #6932: Schedule: Make track, session room and date clickable and direct respected filter
On the public schedule on the session area please make the track, session room and date clickable and direct the user to the respective filter for the item.
Screenshot from 2021-03-07 08-32-54

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6932

#### Short description of what this resolves:
On the public schedule on the session area please make the track, session room and date clickable and direct the user to the respective filter for the item.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Yes, would be good to get this without a full page reload every time.

**Comment by maze-runnar** [comment]
to prevent reloading, use it same as it is in side filters.
            <LinkTo
                  class="p-1 mb-1 rounded-default link-item {{if (eq this.params.track track.name) 'active'}}"
                  @route="public.sessions"
                  @models={{array this.model.id}}
                  @query={{hash track=track.name}}>

**Comment by MeghalBisht** [comment]
> to prevent reloading, use it same as it is in side filters.

@maze-runnar  the reloading is triggered after I add prevent-bubbling helper. No reloading is triggered if I remove it.
`<div role="button" onclick={{prevent-bubbling}} class="left floated twelve wide column">
`

**Comment by maze-runnar** [comment]
> > to prevent reloading, use it same as it is in side filters.
> 
> @maze-runnar the reloading is triggered after I add prevent-bubbling helper. No reloading is triggered if I remove it.
> `<div role="button" onclick={{prevent-bubbling}} class="left floated twelve wide column"> `

in prevent-bubbling helper try adding `event.preventDefault()`. see if it works.

**Comment by MeghalBisht** [comment]
> in prevent-bubbling helper try adding `event.preventDefault()`. see if it works.

No, this stops the normal behaviour of `a/linkto` that is opening a link

**Review by mariobehling — APPROVED** [review]
Thank you.

**Pull request merged**
