### PR TITLE
Merge development to master

### LINKED ISSUE #1199: Merge development to master
As mentioned:
image

We need to merge master from the development branch.

### PR DESCRIPTION
**Pull request by Kreijstal**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 

I think right now the development branch is fairly stable, so we can get away with updating it a little, right now, I don't see there are possible conflicts, what does everyone think?

#### Short description of what this resolves:
This merges development to master

Fixes #1199

### CODE REVIEW

**Comment by niranjan94** [comment]
@SaptakS don't merge via the GitHub interface. Would create new commits on master make it ahead of development. Instead, once all status checks pass here & approvals are done, fast-forward master via `git` and push.

**Comment by niranjan94** [comment]
I have fixed master now.

**Comment by SaptakS** [comment]
@niranjan94 cool. I was also doing the same. So was surprised to see the logs as same. Thanks. We don't need to create these PRs then, right? We can follow the same flow as in server, right?

**Comment by niranjan94** [comment]
Yep

**Comment by Kreijstal** [comment]
Good to know

**Pull request merged**
