### PR TITLE
fix: Changed the semantic class for the image in attendee and organizer app

### LINKED ISSUE #3529: Attendee Landing Page: Change the Semantic Class for the Image used
Current Image used in the `Attendee App Landing` is much larger than it should be. Change the class used for image and fix up. 

Screenshot 2019-09-18 at 3 44 21 PM

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #3529 

#### Short description of what this resolves:
Replaced `fluid` class with `medium` in `attendee-app.hbs` file.
 
#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
When contributing in software, cheating is the key. See what's done in Organizer App section. Ctrl+C Ctrl+V and save your and reviewer's time :)

**Comment by Dishebh** [comment]
> When contributing in software, cheating is the key. See what's done in Organizer App section. Ctrl+C Ctrl+V and save your and reviewer's time :)

Totally agree with you. But, in the `organizer-app` page, `large` is used instead of the `medium` which results in more unused space on the page. Pls refer the screenshots below for better picture:

* for `large`:
Screenshot from 2020-03-15 17-16-39

* for `medium`:
Screenshot from 2020-03-15 17-16-23

**Comment by Dishebh** [comment]
So, which one should I go for?

**Comment by iamareebjamal** [comment]
Then change both

**Comment by Dishebh** [comment]
> Then change both

Done.

**Comment by iamareebjamal** [comment]
Follow PR title guidelines

**Comment by Dishebh** [comment]
> Follow PR title guidelines

Can you pls share the link to refer?

**Comment by iamareebjamal** [comment]
See any merged PR's title

**Comment by Dishebh** [comment]
> See any merged PR's title

How about now?

**Comment by iamareebjamal** [comment]
@kushthedude If we keep changing the title ourselves, they'll never learn how to copy guidelines of a particular project

**Comment by Dishebh** [comment]
> @kushthedude If we keep changing the title ourselves, they'll never learn how to copy guidelines of a particular project

True! But, aren't both the titles same 😅

**Comment by snitin315** [comment]
>True! But, aren't both the titles same

~~Fix~~ fix

**Comment by iamareebjamal** [comment]
You're a programmer. Case matters

**Pull request merged**
