### PR TITLE
fix: realign event list action buttons 

### LINKED ISSUE #2947: Events Dashboard: Move buttons to first column and improve design
In the events dashboard at https://eventyay.com/events/live please move the buttons in the column "Actions" to the front below the name in horizontal order. Increase the size of the buttons and improve logic. Show 4 buttons:
* Event Dashboard button
* View Event button -> to public event page
* Edit Event

Don't show the "delete event button" in the dashboard.

Screenshot from 2019-05-18 13-46-51

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #2947

#### Short description of what this resolves:
Places the action buttons in the front row in horizontal alignment and improved logic as requested.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by uds5501** [comment]
@mariobehling The Manage event table after the restructure
Screenshot from 2019-05-22 12-01-40

**Comment by uds5501** [comment]
@ritikamotwani @shreyanshdwivedi @kushthedude Please review!

**Comment by uds5501** [comment]
@ritikamotwani These changes messes up the admin/event table. Shall I create a different cell-event component for this particular table?

**Comment by ritikamotwani** [comment]
@uds5501 , I guess you'll have to if we don't want the changes in admin/events.
Do we have to place the action buttons of admin/events too in the first column?

**Comment by uds5501** [comment]
@ritikamotwani I don't think so, the admin should have an option to delete and the revamp requires removal of that option. I will create a new component and push the changes accordingly

**Comment by ritikamotwani** [comment]
@uds5501 , Yes the admin should have the option to delete and everything. I was just asking if the action buttons in admin/events have to be moved to the first column or not.

**Comment by uds5501** [comment]
@ritikamotwani as far as this issue is concerned, no. The issue pointed out the manage events section specifically. 
Also, a review would be lovely! @shreyanshdwivedi @mrsaicharan1

**Pull request merged**
