### PR TITLE
chore: Integrated ember-cli-babel-polyfills

### LINKED ISSUE #4181: Integrate ember-cli-babel-polyfills
ember-cli-babel is not including polyfills for latest features like Promise.allSettled. This is breaking the app on browsers like Safari 12.

Integrate https://github.com/pzuraq/ember-cli-babel-polyfills to solve the issue

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #4181 

#### Short description of what this resolves:
Integrated ember-cli-babel-polyfills for app stability in cross browser platforms.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This PR changes nothing and still fails the build. Read difference between integrate and install.

**Comment by Dishebh** [comment]
> This PR changes nothing and still fails the build. Read difference between integrate and install.

Looking out for the build failure. 

`Installing the addon will automatically include the polyfills without any additional configuration.` Wouldn't installing it just do fine, since we have already made `includePolyfill: true` in `ember-cli-build.js` file?

**Comment by Dishebh** [comment]
Why does the app builds successfully and passes all the tests locally, while it fails here?

**Comment by iamareebjamal** [comment]
You have to debug that

**Comment by Dishebh** [comment]
Build now passes!

**Comment by iamareebjamal** [comment]
Promise.allSettled polyfill is still missing. Will have to check something else

**Comment by Dishebh** [comment]
Does the app fails even now on safari 12?

**Comment by Dishebh** [comment]
@iamareebjamal what more shall be done to solve the issue?

**Comment by Dishebh** [comment]
> Where have you added the ember-cli-polyfills ?
> Integrating a module doesn't mean doing ` yarn add module_name`

https://github.com/pzuraq/ember-cli-babel-polyfills
https://www.npmjs.com/package/ember-cli-babel-polyfills

The docs and the links mentioned above say that `Installing the addon will automatically include the polyfills without any additional configuration.`

**Comment by Dishebh** [comment]
Can anyone please give me some lead here? I am a bit confused.

**Comment by Dishebh** [comment]
@kushthedude any thoughts?

**Comment by iamareebjamal** [comment]
Hi, I think we have a fundamental difference in understanding what software development means in general. Software Development constitutes picking a problem and solving it, and then codifying the solution. Not asking for a solution and codifying it. If that was it, nobody would need external contributors. Where you are not getting answers from anyone, it means nobody knows what's the solution. Think, if anyone knew what was the solution, or spent the time to find it themselves, then wouldn't they send the PR anyway themselves? Please take up issues you know you can solve. Getting stuck on things and asking for answers is acceptable and appreciated, but if those problems require anyone else to solve the issue itself, and then just tell you the steps you need to do in order to get the PR merged, that's called spoon-feeding. In fact, I am so against spoon-feeding that even if I know the solution to a problem, I don't tell that to the person trying to solve the issue. Because if the only goal was for the issue to be solved, I could send a PR myself. But the goal is also for the person fixing the bug to develop problem-solving skills and do things on their own. If I tell you the solution, what will you have learned? Nevertheless, in this case, I have no idea on what to do to solve the bug anyway

**Comment by Dishebh** [comment]
> Hi, I think we have a fundamental difference in understanding what software development means in general. Software Development constitutes picking a problem and solving it, and then codifying the solution. Not asking for a solution and codifying it. If that was it, nobody would need external contributors. Where you are not getting answers from anyone, it means nobody knows what's the solution. Think, if anyone knew what was the solution, or spent the time to find it themselves, then wouldn't they send the PR anyway themselves? Please take up issues you know you can solve. Getting stuck on things and asking for answers is acceptable and appreciated, but if those problems require anyone else to solve the issue itself, and then just tell you the steps you need to do in order to get the PR merged, that's called spoon-feeding. In fact, I am so against spoon-feeding that even if I know the solution to a problem, I don't tell that to the person trying to solve the issue. Because if the only goal was for the issue to be solved, I could send a PR myself. But the goal is also for the person fixing the bug to develop problem-solving skills and do things on their own. If I tell you the solution, what will you have learned? Nevertheless, in this case, I have no idea on what to do to solve the bug anyway

Couldn't agree more with you. Thanks for sharing! You can't say you can (cannot) solve any issue until you try, right? I'll try looking it up again and see if I can do something.
Thanks a lot, again.

**Comment by Dishebh** [comment]
One thing, can you let me know is, how can you say the issue is not resolved yet? Does the app still break on safari 12, even after implementing the above changes?

**Comment by iamareebjamal** [comment]
Yes

**Pull request closed without merging**
