### PR TITLE
feat: Add stream side panel to public event page

### LINKED ISSUE #6135: Virtual Event: Streamline Participation and In-App Experience in Online Event
What is the easiest way to create a full online event experience with schedule, speaker and event information pages? We already have these pages, but they are not included in the "video app experience" yet. We probably do not want to start replicating the pages. So, what is the easiest way to include these pages without getting into loops and confusing users?

Here is an approach. For the online event experience with the iframe and videos, we can include the event pages such as the speaker page and make it accessible from the UI, but we need to limit the access to the eventyay area to make the experience consistent. 

So, basically when the user is within the iframe, the user is participating in the event. When the user is outside of the iframe he/she is just viewing the event (but not participating!). 

Therefore we need to make the following changes:
1. When the user clicks on a session "Join Video" change the implementation to open the link in the same tab and show a loading icon and the message _"Joining Event"_
2. After the user joined the event the user has access to the event information through the sidebar and can access different pages. The user is now participating in the event itself and accesses all info through the "app UI". This should work as follows:
  * Open all external links in a new tab (let's just implement this across eventyay by default)
  * Change the top bar as follows: When the user clicks the "eventyay" logo they leave the app and go to the frontpage
3. From the event name on the left side iframe sidebar direct to the info page of the event with the sidebar instead of opening a new tab.
4. When no schedule is available also do not show the button on the sidebar.

Screenshot from 2020-12-24 11-04-26

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #6135

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. The schedule button disappears when the user is on the schedule page itself.

Do you think we could also have "Speakers" button here? But only show buttons when there is a schedule and speakers defined. Could that be solved in this PR or a follow-up PR rather?

Screenshot from 2020-12-29 07-36-54

**Comment by iamareebjamal** [comment]
I deliberately hid schedule button from here. Will remove the logic to hide it

Will add speaker button here as well soon

**Comment by iamareebjamal** [comment]
However, I think there is no way an event can have a stream without schedule or sessions? Is it?

**Comment by mariobehling** [comment]
> However, I think there is no way an event can have a stream without schedule or sessions? Is it?

Yes, there is - the event stream, that you are also implementing in wizard step 1.

**Comment by mariobehling** [comment]
Screenshot from 2020-12-29 08-03-28

Sidepanel event link should now open in same tab.

**Comment by mariobehling** [comment]
After last changes, Jitsi does not show up anymore.

Screenshot from 2020-12-29 08-14-16

The order of video rooms is different on the sidepanel of the schedule compared to the sidepanel when the user is on a video room page. Any chance to standardize this?

**Comment by iamareebjamal** [comment]
Jitsi is showing up for me correctly. https://open-event-frontend-git-fork-iamareebjamal-side-pane.eventyay.now.sh/e/a315169f/video/codeheat-ask-me-anything-january-edition/65?side_panel=true

About order, the room you are in is always on top and then the event room. Then we can order the rooms by name so they will be in order

**Comment by mariobehling** [comment]
As you adjusted the way it works I think the "Join Video" button can now open in the same window for our integrated Jitsi and BBB, but it should still open in an external window for other services, right?

**Comment by iamareebjamal** [comment]
But it can't detect jitsi or BBB without loading an additional resource - video channel (which it loads on the dedicated video page). So, it is not that straightforward to implement. So, I think we follow up on it in another PR and explore what can be done otherwise it will result in code duplication or waited loading
_

**Pull request merged**
