### PR TITLE
fix: remove HTML tags from calendar description text

### LINKED ISSUE #8179: Calendar entries with HTML tags in text in Thunderbird, Kopano, MacOS, Outlook
Adding an event to a calendar only looks ok in Google calendar. Other calendars display HTML tags in the text. I assume there is a HTML header or body tag getting filtered possibly? Please identify and solve the problem. You can use Thunderbird to test this.

Test on https://eventyay.com/e/c5fc6d42 or https://eventyay.com/e/94edc3cb

Screenshot from 2021-12-07 14-02-37

Bildschirmfoto 2021-10-20 um 10 47 55
Bildschirmfoto 2021-10-20 um 07 22 31

References 

- Google Calendar does not support HTML https://www.thunderbird-mail.de/forum/thread/79812-termin-beschreibung-wird-mit-html-tags-angezeigt/?postID=445801#post445801
- MS Teams invites does not support HTML https://bugzilla.mozilla.org/show_bug.cgi?id=1666296
- EM Calendar does not support all fields and HTML https://forum.emclient.com/t/event-notifications-in-indecipherable-html-code/68516/9
- Google calendar event descriptions contain HTML tags but Thunderbird renders descriptions as plain text https://bugzilla.mozilla.org/show_bug.cgi?id=1659363
- Bug 1659363 - Render HTML in calendar item descriptions. https://phabricator.services.mozilla.com/D88366

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #8179 

**Yahoo**
Screenshot 2021-12-09 at 15-37-46 https calendar yahoo com

**Outlook**
Screenshot 2021-12-09 at 15-38-38 Calendar - Shubham Upreti - Outlook

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you.

As discussed, please only Stripe the HTML from the ical and update the implementation for Outlook and Yahoo to ensure rich text works for those services.

**Comment by progmatic-99** [comment]
@mariobehling Yahoo doesn't render html text with the solution that I proposed in the meeting but Outlook & Gmail works
So, ical and Yahoo would be plain text

**Outlook**
Screenshot 2021-12-10 at 11-50-29 Calendar - Shubham Upreti - Outlook

**Yahoo**
Screenshot 2021-12-10 at 12-03-51 https calendar yahoo com

**Comment by progmatic-99** [comment]
@pc-beast Please test for ical with this [server PR](https://github.com/fossasia/open-event-server/pull/8450)

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Ok, looks good. Thank you.

**Pull request merged**
