### PR TITLE
feature-8683: Add Options for Badges in Wizard

### LINKED ISSUE #8683: Add Options for Badges in Wizard
Add options for badges in the event wizard after "Attendee Form".

Provide a button "Switch on/off".

Screenshot from 2023-04-30 21-42-26

Allow organiser to choose fields from a dropdown to show and no duplicates

- Name
- Organisation
- Position
- QR code (to show if option to be used for checkin and sharing of contact info is true)

When the user chooses "QR Code" also provide the option to include more info through a dropdown menu with tickboxes, e.g. if the user wants to include Email, Website, and Linkedin in the Barcode. On scan, .vcf contact file will be downloaded

Screenshot from 2023-04-30 22-44-33

Compare: https://help.eventnook.com/en/articles/6005872-how-to-customize-event-badge

In the badge template, there are essential options to customize:
* the Badge Size, Badge Orientation, and Badge Color. 
* the fields inside the badge, such as the delegate's name, company, job title, category, QR Code
* the styling of the font such as Font Size, Alignment, Text Style (such as Upper Case, Lower Case, etc.) 
* Custom paper sizes
* As the user designs the badge, they can preview the final result of the badge.

Finally provide a button below which lets the user download a sample PDF.

> Download Example Badge

### PR DESCRIPTION
**Pull request by lthanhhieu**
Fixes #8683 

#### Short description of what this resolves:
- Add Options for Badges in Wizard

#### Changes proposed in this pull request:
- Add Options for Badges in Wizard

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ntthitrinh** [comment]
Hi @mariobehling, @norbusan, @cweitat,
This is UI Badge that we have created.
Please help us review it.
Thanks
image

**Comment by cweitat** [comment]
@ntthitrinh hi previously mentioned that the preview to be inside the preview dropdown instead outside of the card

**Comment by mariobehling** [comment]
1. The badge should be inside the box "show sample data".
2. The sample data should be shown if the button is set to "on". In the screenshot the button is set to "off".

@cweitat Should we merge this as Work in Progress?

**Comment by ntthitrinh** [comment]
> 1. The badge should be inside the box "show sample data".
> 2. The sample data should be shown if the button is set to "on". In the screenshot the button is set to "off".
> 
> @cweitat Should we merge this as Work in Progress?
Hi @mariobehling, @cweitat,
I have fixed the above issues. Please help me review.
Thanks

image
image

**Review by mariobehling — APPROVED** [review]

**Review by cweitat — APPROVED** [review]

**Comment by mariobehling** [comment]
Ok, thank you! Merging this for further tests on test server.

**Pull request merged**
