### PR TITLE
feat: Add the Submit proposal modal for Call for Speakers(UI only)

### LINKED ISSUE #761: Add the submit proposal modal for Call for speakers(UI only)
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Todo:
Implement the UI for the Submit proposal for call for speakers on public/index.

### PR DESCRIPTION
**Pull request by sumedh123**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #761

### CODE REVIEW

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 @harshitagupta30 Please review.

**Comment by niranjan94** [comment]
Deployment link: https://pr-762-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@sumedh123 We can also integrate the API to check if the user has speakers details or not, similar to the orga-server where the add sessions button is disabled if the user speaker detail is missing.

**Comment by niranjan94** [comment]
Deployment link: https://pr-762-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@geekyd Please review.

**Comment by niranjan94** [comment]
Deployment link: https://pr-762-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 @harshitagupta30 Please review. The API part for the modal will be taken care in other PR.

**Pull request merged**
