### PR TITLE
fix: font size standardization across event public page

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes from meeting notes (Can we increase our standard font size a bit?)
Screenshot from 2021-02-25 16-11-59
Screenshot from 2021-02-25 16-11-52
Screenshot from 2021-02-25 16-10-45
Screenshot from 2021-02-25 16-10-13
Screenshot from 2021-02-25 16-09-47

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you!

1. In the ticket box on public events please only change the default font, but not the font size of the sub text.
2. On the Call for Speakers page on the bottom there is a line with the unchanged size. Please also change it here.
Screenshot from 2021-02-25 19-23-06
3. Please also the change the default font size on the organizer area and in each tab. (but only the default font, not the sub texts etc.).
Screenshot from 2021-02-25 19-26-41

**Comment by maze-runnar** [comment]
Screenshot from 2021-02-26 20-22-14
Screenshot from 2021-02-26 20-22-09
Screenshot from 2021-02-26 20-31-39

**Comment by mariobehling** [comment]
Thanks for the update, but please change the standard font everywhere including all organizer pages:
- Dashboard: 1) Team members box, 2) Sponsors box
- Organizer Tickets subpages
- Organizer Speakers page
- Organizer Sessions page
- Organizer Video Page
- Organizer Exhibitors Page
- Organizer Team Page

**Comment by mariobehling** [comment]
I do not understand why you need to define a new class everywhere. The advantage of CSS was always that one change would reflect everywhere. Defining more and more styles can cause us to loose track event more. 

Less styles and and a standardized few styles should be our goal.

So, could we change the default style and the existing styles or does it break the design?

**Comment by mariobehling** [comment]
To keep the discussion on chat and in the issue aligned I am adding the below screenshot.

Screenshot from 2021-02-27 20-01-56

**Pull request closed without merging**
