### PR TITLE
[WIP] GitHub oauth tokens field addition

### LINKED ISSUE #2153: Adding Github Token section in Admin/Settings | System
**Is your feature request related to a problem? Please describe.**

No, it's regarding the implementation of additional login implementations. To implement Github OAuth, we need to let the client to provide Github client id and secret.

**Describe the solution you'd like**

I would simply like addition of Github Tokens field to the System in Admin/Settings
Something like this 
image

**Describe alternatives you've considered**

None, to implement a github OAuth, we will need these exclusive tokens

**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Added a new field for acquiring Github OAuth tokens from the client

#### Changes proposed in this pull request:

- Addition of the Github Token field in `social-media-tokens`
- Modifying the `settings` model accordingly
-

Fixes #2153

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 Do I need to add any other field for acquiring github tokens in frontend from the client? If no, I'd like to remove this [Discussion Required] tab

**Comment by CosmicCoder96** [comment]
@uds5501 The fields required would be exact and as per the implementation on the server using Github's API, not really a discussion.

**Comment by CosmicCoder96** [comment]
is there a corrsepodning server issue?

**Comment by mariobehling** [comment]
Priority low: Delay

**Pull request closed without merging**
