### PR TITLE
[WIP]: make nearby events in footer workable

### LINKED ISSUE #2232: Footer section recommendations
**Is your feature request related to a problem? Please describe.**

No. There are mostly enhancements.

**Describe the solution you'd like**

Some of the content on footer is hardcoded on the templates and doesn't provide any context in a on-premise deployment. My proposals are:

1. Use `settings.appName` variable to replace "eventyay" text.
https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/footer-main.hbs#L5

screenshot_2019-02-24 gnome events

2. Hide or drop the content of **"Nearby Events"** section as the URLs don't point to any page/section [1]. A more sophisticated solution here, would be to create a dynamic list based on the event locations [2].

[1] https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/footer-main.hbs#L25
[2] https://open-event-api-dev.herokuapp.com/#event-locations

screenshot_2019-02-24 gnome events 1

3. Hide **"Connect with us"** section by default and show it only when the user adds a link.

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #2232

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@kushthedude , i need help in  app/components/footer-main.js to get city_name from lattitude and longitude, can you please help me here.

**Comment by maze-runnar** [comment]
I think i should use mapbox, or google reverse geocoding api, is it ok to get city or what needed?

**Comment by maze-runnar** [comment]
https://api.mapbox.com/geocoding/v5/mapbox.places/-93,40.733.json?access_token=pk.eyJ1IjoibWF6ZS1ydW5uYXIiLCJhIjoiY2s2MG82OThkMDloZTNkbG9jZTRiam1sdSJ9.-4Ygipk0hyX3uDRZu_bkaA

this api may give all we want, but how to use is within our file?

**Comment by kushthedude** [comment]
Wrong Approach, API Support needed first!

**Pull request closed without merging**
