### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aaryan078**
I update the README.md

There was some grammatical mistake which I try to correct

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Which grammatical mistakes did you fix?

**Comment by aaryan078** [comment]
Screenshot (673)_LI
line no.112-i removed the word 'really'
line no.  120- I added 'the' before the development word.

**Comment by iamareebjamal** [comment]
According to which book are those grammatically wrong?

**Comment by aaryan078** [comment]
Sorry I thought 
'the' is an article and the article come under Grammar that's why I said the grammatical mistake .

**Pull request closed without merging**
