### PR TITLE
Standardized Date and Time

### LINKED ISSUE #5490: Date and Time: Standardize it across system
The date and time are using different formats in the system. Please identify different places for the date and time usage and standardize the date and time in all ways.

### PR DESCRIPTION
**Pull request by Saumyachitransh01**
Fixes #5490

#### Short description of what this resolves:

All dates and time converted to single format

#### Changes proposed in this pull request:
1. Weekly days are set to "ddd"   
 i.e Mon, Tue ...
2. Dates are set to DD MMMM, YYYY  
 eg. 30 November 2020
3. Time has been set to hh:mm A   
eg. 09:00 PM

Also use of commas are set to same all over

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
How many distinct time formats used in the project? Can they be listed in a single place to avoid duplication?

**Comment by Saumyachitransh01** [comment]
> How many distinct time formats used in the project? Can they be listed in a single place to avoid duplication?

Yes but there are some places where days of the week(ddd) are used and someplace where they aren't. So how to list it in a single place?

**Comment by iamareebjamal** [comment]
Single place means in a single file, not a single format being used everywhere

**Comment by Saumyachitransh01** [comment]
It's very confusing, it'll require altering too many files .js as well as .hbs files. 
Screenshot from 2020-11-08 14-51-38
Screenshot from 2020-11-08 14-51-22

Please suggest a way of what needs to be done.

**Comment by iamareebjamal** [comment]
First check if it possible or not. Because if it is, then it'll make #5491 extremely easy to solve

**Comment by Saumyachitransh01** [comment]
Okay working on it

**Comment by Saumyachitransh01** [comment]
> How many distinct time formats used in the project? Can they be listed in a single place to avoid duplication?
I determined >20 date and time formats used across the platform.

**Comment by iamareebjamal** [comment]
After this PR

**Comment by Saumyachitransh01** [comment]
Yes after this PR, I thought the issue is about making the format same everywhere

**Comment by Saumyachitransh01** [comment]
Okay so I'll make upto 4 5 formats across and the platform and list it in a file be used everywhere. Is that correct?

**Comment by iamareebjamal** [comment]
Yes

**Comment by Saumyachitransh01** [comment]
I converted all time formats to only 5 formats till now but unable to combine those in a single place. M new to this framework. Would that be accepted?
Or does it have to be in that combined way only?

**Comment by iamareebjamal** [comment]
Accepted

**Pull request closed without merging**
