### PR TITLE
chore: Add Video Stream models

### PR DESCRIPTION
**Pull request by iamareebjamal**
For #5101

~~For some reason, ember data is not working correctly with relationships. Need to do more research~~

Fixed

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit/models/video-stream-test.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6353907&bid=20630066)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit/models/video-stream-test.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6353907&bid=20630066)

**Comment by mariobehling** [comment]
Oh no, too much troubel with Ember.

**Comment by iamareebjamal** [comment]
Fixed in [`d560a49` (#5330)](https://github.com/fossasia/open-event-frontend/pull/5330/commits/d560a4925c7760abe94ab324bc1f2d282219a944) :) 

Using https://emberigniter.com/saving-models-relationships-json-api/ but yes, the docs are very sparse and this information is not available anywhere in the docs

**Pull request merged**
