### PR TITLE
added additional info option

### LINKED ISSUE #4671: Wizard: Simplify UX by separating step 1 into two steps
The wizard step one has increase complexity over time. A number of fields are not necessary to publish an event. We can simplify the user experience by adding a step 2 and moving some of the form elements to step 2. Please implement it as follows:

* Add a step two with the heading "Additional Info and Settings"
* Move the following fields to step 2:
  * Links and Social Media
  * Listing Privacy
  * Add Code of Conduct
  * License of Event Data and Content

Screenshot from 2020-07-30 16-03-00

### PR DESCRIPTION
**Pull request by himanshujaidka**
I have removed Links and Social Media
Listing Privacy
Add Code of Conduct
License of Event Data and Content and add it to new file inside wizard (additional-info-step.hbs)
and one file inside edit (aditional.hbs)

Fixes #4671

#### Short description of what this resolves:
I removed Links and Social Media
Listing Privacy
Add Code of Conduct
License of Event Data and Content all this from basic details

#### Changes proposed in this pull request:

-added new file inside wizard (additional-info-step.hbs)
-added new file inside edit (additional.hbs)

-but unable to put inside main contant

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

review my PR and tell me what to do next with it

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please always add pictures/GIF for UI changes. And build is failing

**Comment by himanshujaidka** [comment]
@iamareebjamal could you please tell me how I solve this build failure issue because I am new o open-source

**Comment by iamareebjamal** [comment]
Check errors here https://travis-ci.com/github/fossasia/open-event-frontend/builds/177912236

**Review by vsasvipul0605 — APPROVED** [review]

**Comment by mariobehling** [comment]
Already fixed. Therefore closing it. Thank you!

**Pull request closed without merging**
