### PR TITLE
fix: table with ticket details is not responsive in phone

### LINKED ISSUE #3511: The table with ticket details is not responsive in phone.
**Is your feature request related to a problem? Please describe.**
The table with ticket details on the events page is not responsive in mobile phone view and there is an overflow on the x-axis of the entire page on the phone due to same reason.

**Describe the solution you'd like**

I would like to use bootstrap or Bulma to make the tables more responsive and better looking.

**Describe alternatives you've considered**

**Additional context**

issue1

Please assign me the task to implement this. Thank you.

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #3511 

#### Short description of what this resolves:
Ticket table was breaking in mobile responsive view when one of the ticket type is donation ticket.
*Compare* - https://open-event-frontend.now.sh/e/a315169f (in mobile view)

#### Changes proposed in this pull request:

- Removed an empty column after type and added after price.
- Removed class for input for donation tickets which was producing bug.

### Before 

(with Donation tickets)
Screen Shot 2020-11-16 at 23 21 58

(without Donation tickets)
Screen Shot 2020-11-16 at 23 28 26

### After

(with Donation tickets)
Screen Shot 2020-11-16 at 23 29 31

(without Donation tickets)
Screen Shot 2020-11-16 at 23 32 55

(other screenshots for different screen size)
Screen Shot 2020-11-16 at 23 35 58

Screen Shot 2020-11-16 at 23 34 50

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see the changes I have made and let me know to make any changes further.
This looks good to me. as now in every possibly situation ticket Table is responsive and nicely aligned.

**Comment by daretobedifferent18** [comment]
@iamareebjamal PLease see the changes

**Comment by maze-runnar** [comment]
Not working - 
scrnli_11_19_2020_2-41-49 PM
scrnli_11_19_2020_2-41-15 PM

**Comment by daretobedifferent18** [comment]
> Not working -
@iamareebjamal @maze-runnar I want to know till which point or min-width for which it should not break.

**Comment by daretobedifferent18** [comment]
can we just not display subtotal field in mobile view bcz otherwise the table looks so untidy and I think subtotal field could be removed and will not disturb the logic or user exp for user and also not displaying subtotal field leads to easy repressiveness of table.

**Comment by iamareebjamal** [comment]
Subtotal is important, reaarange price field for donation ticket

**Comment by daretobedifferent18** [comment]
> > Not working -
> 
> @iamareebjamal @maze-runnar I want to know till which point or min-width for which it should not break.

??

**Comment by iamareebjamal** [comment]
Smallest width device preset in your browser

**Comment by daretobedifferent18** [comment]
@iamareebjamal I found this to be a nice way in mobile device making tables stackable. What do you want to say about this?
Screen Shot 2020-11-20 at 12 07 06

**Comment by iamareebjamal** [comment]
Looks good

**Comment by daretobedifferent18** [comment]
> Looks good

further more changes?

**Review by iamareebjamal — APPROVED** [review]

**Review by daretobedifferent18 — COMMENTED** [review]
.

**Pull request merged**
