### PR TITLE
enh: Rounded corners

### LINKED ISSUE #4306: Restore rounded corners
https://github.com/fossasia/open-event-theme/commit/0206df77b4d535b35a8fd4ddbabdb0f36adb0d12

There's a lot of research on why rounded corners are better in UI. Flat design with square corners makes Open Event look unfinished and drab. Not to say that a lack of theme color is not helping. Hence, I think rounded corners should be restored. Except Microsoft's UI, which is still not a golden standard, I have seen no site which uses sharp corners. 

https://designmodo.com/rounded-corners/
https://uxmovement.com/thinking/why-rounded-corners-are-easier-on-the-eyes/
https://uxplanet.org/rounded-or-sharp-corner-buttons-def3977ed7c4
https://medium.com/@gotoxplore/rounded-or-square-corners-for-better-user-experience-28af389bf979

First button does not even look like a button, and looks unfinished

If someone has strong opinions on this, let's discuss

PS: Even Microsoft: https://github.com/microsoft/microsoft-ui-xaml/issues/524#issuecomment-497356510
https://github.com/mrlacey/microsoft-ui-xaml-specs/blob/RoundedCornerVisualizations/active/RoundedCorner/ImageFiles/index.md

### PR DESCRIPTION
**Pull request by naman360**
Fixes #4306 

#### Short description of what this resolves:
Adds rounded corners.

#### Changes proposed in this pull request:

- Change version of `@open-event/theme` from `0.2.1` to `0.2.1-rounded`

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Unneeded commits. Never create a PR from development/master branch

**Comment by naman360** [comment]
ok so what should I do now?

**Comment by snitin315** [comment]
Rebase correctly.

**Comment by iamareebjamal** [comment]
Close the PR and make it from a new branch

**Comment by naman360** [comment]
Okay sure.

**Pull request closed without merging**
