### PR TITLE
Speaker submission/Session submission - same form areas differ: Implement abstraction layer

### LINKED ISSUE #3775: Speaker submission/Session submission - same form areas differ: Implement abstraction layer
Screenshot from 2020-01-08 18-42-11

The form "add a session" has the option to expand it below and add speaker details as well. The form "add a speaker" has the option to add session details below. These exact same features are implemented differently. Code is duplicate and the forms don't behave in the same way.

Expected: Forms should be identical as it is the exact same feature. Please implement an abstraction layer and ensure form elements are always the same.

### PR DESCRIPTION
**Pull request by nikolaytoplev**
Fixes #3775

#### Short description of what this resolves:
Added abstraction layer for session-speaker forms

#### Changes proposed in this pull request:

-Add speaker-session and session-section component
-Modify session-speaker-form component
-Keep data relationship in all transcations

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Codewise looks fine. Not tested every part of the functionality yet

**Comment by nikolaytoplev** [comment]
> Codewise looks fine. Not tested every part of the functionality yet

What should I do?

**Comment by iamareebjamal** [comment]
Please continue working on other issues

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
checkbox for "do not require email for this speaker"  is not showing.
all other functionality is working totally fine.

Please review conflicts and update it as soon as possible.
## actual
review new

 ## in this deployment
new review problem

**Comment by iamareebjamal** [comment]
@sachinchauhan2889 Please update this PR. @nikolaytoplev will no longer be able to work on it

**Comment by iamareebjamal** [comment]
Continued in #6195

**Pull request closed without merging**
