### PR TITLE
feat: Add My Speaker Session filter

### PR DESCRIPTION
**Pull request by sachinchauhan2889**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
What if user is not logged in?

And try using checkbox

**Comment by mariobehling** [comment]
Which issue is this related to?

**Comment by sachinchauhan2889** [comment]
@mariobehling  sir, this is a filter for filtering sessions in which the current user is speaker

**Comment by iamareebjamal** [comment]
Change filter to `my_speaker_sessions`

**Comment by mariobehling** [comment]
Thanks. Please move "my speaker session" to the right of "My Schedule".

Screenshot from 2021-02-16 13-20-16

**Comment by iamareebjamal** [comment]
It should be `My Speaker Sessions`. Plural

**Pull request merged**
