### PR TITLE
Set Event Type,Event Topic,Event subtopic, License to be null when once set

### LINKED ISSUE #2302: Event Type,Event Topic,Event subtopic, License cannot be made null once set
**Describe the bug**

Event Type,Event Topic,Event subtopic, License cannot be made null once set
**To Reproduce**
1. Go to 'Basic Details'
3. Scroll down to 'Event topic'

**Expected behavior**

There should be an option "none" which sets these fields to null.
**Screenshots**

Screenshot 2019-03-15 at 6 43 09 PM

**Additional context**

I'm working on it.

### PR DESCRIPTION
**Pull request by harsh-jindal**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Set Event Type,Event Topic,Event subtopic, License to be null when once set

#### Changes proposed in this pull request:
Screenshot 2019-03-17 at 5 28 39 PM

Fixes #2302

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@CosmicCoder96 clearable=true doesn't seem to work. All other attributes are working other than clearable,I couldn't find anything for that on internet. Another work around logic would be to allow multiple select and make maxSelections=1.

**Comment by CosmicCoder96** [comment]
@harsh-jindal Seems like this feature was released in the latest version of semantic UI, not available in semantic-ui-ember as of now, so we'll wait for it as it's clearly a better choice.

**Comment by harsh-jindal** [comment]
@CosmicCoder96  Okay

**Comment by CosmicCoder96** [comment]
https://github.com/Semantic-Org/Semantic-UI-Ember/issues/248

Wait for this to get resolved.

**Comment by kushthedude** [comment]
@harsh-jindal Status?

**Comment by CosmicCoder96** [comment]
> [Semantic-Org/Semantic-UI-Ember#248](https://github.com/Semantic-Org/Semantic-UI-Ember/issues/248)
> 
> Wait for this to get resolved.

@kushthedude What does this comment mean? How will @harsh-jindal give a status of this?

**Comment by kushthedude** [comment]
> > [Semantic-Org/Semantic-UI-Ember#248](https://github.com/Semantic-Org/Semantic-UI-Ember/issues/248)
> > Wait for this to get resolved.
> 
> @kushthedude What does this comment mean? How will @harsh-jindal give a status of this?

@CosmicCoder96 i mean i read the comment and there he said to switch to power selector so what we need to do next regarding it?

**Comment by CosmicCoder96** [comment]
@kushthedude No we don't bloat our already large app with an additional module for clearing a dropdown.

**Comment by CosmicCoder96** [comment]
@niranjan94 Can you please update the semantic UI-ember package for 2.4+ support :) ?

**Pull request closed without merging**
