### PR TITLE
fix: mark location and Link field as required in basic-details step

### LINKED ISSUE #4045: basic-details-step: Location and Links are required & FE checks are missing.
**Expected behaviour**

Correspondig fields should be marked as `*`.
FE checks should be present as well.

**Screenshots**

Screenshot from 2020-02-10 20-26-20

Screenshot from 2020-02-10 20-26-30

Screenshot from 2020-02-10 19-31-10

Screenshot from 2020-02-10 20-23-01

**Additional context**

I will work on this.

### PR DESCRIPTION
**Pull request by snitin315**
## Marked the fields as required & added missing front-end checks for the same as well.

Fixes #4045 

Screenshot from 2020-02-10 20-30-54

Screenshot from 2020-02-10 20-41-08

Screenshot from 2020-02-10 20-31-01

Screenshot from 2020-02-10 20-50-40

### CODE REVIEW

**Comment by kushthedude** [comment]
Link is not mandatory. Coming to the location field this behaviour it is not required as what if you want to save the event and fill the location afterwards.

**Comment by snitin315** [comment]
@kushthedude We can't save event without filling both the fields. Server throws an error.

**Comment by kushthedude** [comment]
Link is never a required a field. Location is also not required to save a
draft event.

**Comment by snitin315** [comment]
@kushthedude CHeckout the gif below , Even draft event can not be saved without providing link and location ------

location

**Comment by snitin315** [comment]
Can you check this behavior?

**Comment by kushthedude** [comment]
Remove the location from this check https://github.com/fossasia/open-event-frontend/blob/957934c9e0b3229c05320ffea85592f79e74c894/app/mixins/event-wizard.js#L120 .

**Comment by snitin315** [comment]
Should I create new PR for changes ? or I can commit directly to this one.

**Pull request closed without merging**
