### PR TITLE
[WIP]feat: Add support for donations

### LINKED ISSUE #3057: Ability to provide donation ticket
Describe the feature
Related server issue https://github.com/fossasia/open-event-server/issues/5991

Our system requires the option of adding a donation ticket which users can purchase for a specific event.

Additional context
Working on it.

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #3057 

#### Short description of what this resolves:
Adds support for:
• Correct Implementation of Donations (Introduction of Donation ticket)
• Add relevant model fields & UI changes

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a screenshot.

**Comment by mariobehling** [comment]
Your issue description is unclear. The only thing we need in the first step is to enable organizers to use donations. To do this there should be a third option apart from "free tickets" and "paid tickets" -> donation tickets.

Screenshot from 2019-06-05 00-46-12

Please provide an option "minumum" and "maximum" here for an amount a ticket buyer should enter. Provide the option "Leave empty for no minimum or maximum amount."

**Comment by mariobehling** [comment]
> • Allow free tickets only for NGO/Open Source events

This is not needed. Just forget about this point.

**Comment by mrsaicharan1** [comment]
@mariobehling Will open a new PR with the requested changes.

**Pull request closed without merging**
