### PR TITLE
 Adds fields and change order of fields in Billing Information

### LINKED ISSUE #1939: Billing Information: Add fields and change order of fields
Change it to the following order and add fields as shown below:

* Name or Company -> make this one required
* Tax Number -> make this one optional
* Street Address
* City
* State/Province -> this one optional
* Zip Code
* Select country -> move country to bottom

screenshot from 2019-01-22 09-07-04

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
It adds few fields to `order-form` e.g. `company`, `taxNumber` and also changes order of few other fields.

#### Changes proposed in this pull request:

- Added fields to order-form
- Changed order of few fields

screenshot_2019-01-23 new order -2a09d329-e026-492e-ad66-f524e9a3b4e8 orders open event
screenshot_2019-01-23 completed order -46ec9e46-9507-4a5f-bbd6-b0bbd325d6c9 orders open event

Fixes #1939

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar @srv-twry I'm having trouble in one case.
This PR adds whatever is required and on submitting form and making payment, the data is successfully stored in the database.
But, when we reach the step just after filling `order-form`, if I reload page at that point i.e. when I'm on `placed` route, the `Company` and `Tax Number` info is lost. Otherwise everything works fine
I tried but could not locate the exact problem. Can you help me out?
screenshot_2019-01-24 placed order -76fe7832-af9e-48bf-bbf0-158ef7e870be orders open event

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi did u check if server has these fields in database? Also check the model file for the orders and make sure that they have those fields.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar I think server doesn't have these fields. Reference - http://open-event-api.herokuapp.com/#orders-orders-collection-post
Should I open a PR in `open-event-server` to fix this?

**Comment by pradeepgangwar** [comment]
Sure @shreyanshdwivedi . Go ahead!

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 please review this. PR related to this, on server, is merged

**Pull request merged**
