### PR TITLE
fix: remove edit video page error

### LINKED ISSUE #7153: Edit Video Page: When there is only one recording, recording is not shown.
**Describe the bug**

When there is only one BBB recording, then it is not shown in table and there is an error in console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'video edit page of any BBB video'
2. See error

**Expected behaviour**

it should show recording.

**Screenshots**

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #7153

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I don't understand. Why does that happen?

**Comment by sachinchauhan2889** [comment]
### when there is only one recording in bbb video stream:---

recordings.result.response.recordings.recording ===> **_Dict/Object_**
 `{ "recordID": "12345678", startTime": "123456789", endTime": "123456789" .......}`

### When there are more than one recordings in BBB video stream:----

recordings.result.response.recordings.recording ====> **_Array/list_**
`[
{ "recordID": "123456", startTime": "123456789", endTime": "123456789" .......},
{ "recordID": "1234567", startTime": "123456789", endTime": "123456789" .......},
{ "recordID": "12345678", startTime": "123456789", endTime": "123456789" .......}
]`

**Comment by iamareebjamal** [comment]
What a terrible API. However, it'd be better to now return our recording table rows instead of bbb API 

So in your recording server pr, return JSON using our table and use that API here

**Comment by sachinchauhan2889** [comment]
require https://github.com/fossasia/open-event-server/pull/7907

**Review by MeghalBisht — APPROVED** [review]
Works!
Screenshot from 2021-05-07 02-04-16

**Comment by mariobehling** [comment]
Please reopen this PR.

**Pull request merged**
