### PR TITLE
Chore: hide the top right social link icons when at 'Schedule'

### LINKED ISSUE #8678: Do not show social links on right side bar on schedule page
The schedule page show social links. Please take out the social links on this page.

Screenshot from 2023-05-29 15-28-00

### PR DESCRIPTION
**Pull request by Leslie-Wong-H**
Fixes #8678 

#### Short description of what this resolves:

Do not show social links on right side bar on schedule page

#### Changes proposed in this pull request:

- Comment the related hbs code out without side effect
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
@Leslie-Wong-H I think there is a misunderstanding of this issue. On the schedule page we need the social media icons to go away (but keep them on the other pages). The goal is to clean up the appearance for the user.

To clarify please see the screenshot below.

Screenshot from 2023-05-29 15-28-00

**Comment by Leslie-Wong-H** [comment]
Make social icons disappeared in the schedule page both mobile and desktop?
Since the schedule page is visited by an URL enddiing with "/schedule", we
can use this signal to
achieve this requirement conditionally.

**Comment by Leslie-Wong-H** [comment]
OK. This PR isn't ready yet. It needs extra commits.

**Comment by Leslie-Wong-H** [comment]
I face a strange phenomenon. And this commit under this PR is to solve it. 
[[Fix: info to schedule tab shows two active effect](https://github.com/fossasia/open-event-frontend/pull/8764/commits/802ca78ca0bea21f0c6f28bd6460395c13da38ae)](https://github.com/fossasia/open-event-frontend/pull/8764/commits/802ca78ca0bea21f0c6f28bd6460395c13da38ae)

The phenomenon is that when I launched open-event-frontend locally, used api.eventyay.com as the backend, and visited the FOSSASIA 2023 event page, like this one https://eventyay.com/e/7cfe0771 but with localhost, it is at the info page, if I clicked the schedule tab, double active effect will occur and retain. 
image

So I tried to solve this and got it done locally. Yet when I referred to the production site. such a phenomenon does not exist. You can freely switch between tabs, and the info tab has a scrollintoview effect. Strange enough. Probably I need to revert and squash. 

As for this issue #8678 to hide social icon links on the schedule page, I surveyed for a while and tried to use the `this.session.currentRouteName` variable at `public.hbs` to detect the correct route path and hide social icons links conditionally. 
https://github1s.com/fossasia/open-event-frontend/blob/development/app/templates/public.hbs#L62-L63
Yet the variable does not correctly reflect the route path when you switch from "info" to "schedule", and the others are ok. Obviously, I need more understanding of the life cycle of this template and catch the right hook moment to resolve this issue. 

Or `this.session.currentRouteName` is buggy from the very beginning. ;(

**Comment by cweitat** [comment]
@Leslie-Wong-H heyy how is it going for this?

**Comment by Leslie-Wong-H** [comment]
The proper signal was inspected and found.
The non-issue-related code was abandoned. 
Extra space at order-form.js was auto-formatted by pre-commit.
Just keeping the commit context is fine and scrum.
You are ready to merge.

smaill-ssocial-links

**Pull request merged**
