### PR TITLE
chore: Convert components to angle bracket syntax

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
If you're spending 4x time on solving framework compatibility issues and bugs as compared to fixing bugs and adding features in your own project, there is something seriously wrong in that framework :(((

**Comment by iamareebjamal** [comment]
Spent 2 hours chasing useless errors and indecipherable stacktraces

**Comment by kushthedude** [comment]
> Spent 2 hours chasing useless errors and indecipherable stacktraces

But alas, Build is still failing 🏗

**Comment by iamareebjamal** [comment]
It never was successful. This is the thing with ember. I'll try something, it'll fail. I'll curse and vent and come back a week later to be detective again in a crime where I myself am the murderer and the murdered and solve it and break something again and repeat

**Comment by iamareebjamal** [comment]
So bye for another week and I'll fix it and break something again probably

**Comment by snitin315** [comment]
Maybe its time to create a new branch and start migrating the project to react bit by bit.
not an easy task :disappointed:

**Comment by iamareebjamal** [comment]
Let's check by upgrading to octane first and see if it works out. None of it is easy. Neither migrating to react/vue

**Comment by iamareebjamal** [comment]
I feel like it is some kind of joke where in one place, it is said to upgrade to latest ember and someone else says stay classic
https://twitter.com/mwpastore/status/1246980602412351489

**Comment by kushthedude** [comment]
Octane is new, but ember has still not dropped support for classic format.
Anyway sooner or later, it will drop support and move away from classic
forever. So we would need to upgrade anyway, only advantage we can get
later is some new and efficient codemods which may not require a lot of
labour work perhaps.

**Comment by iamareebjamal** [comment]
The weird thing about anyone who is defending ember here is that no one among them is creating PRs to move the project further. I am. And it is exhausting debugging this stuff. So, maybe if @kushthedude can move the project ahead by fixing the PR and handling other required changes to get the project to latest standard. Or should we wait for it to be deprecated?

**Comment by kushthedude** [comment]
> The weird thing about anyone who is defending ember here is that no one among them is creating PRs to move the project further. I am. And it is exhausting debugging this stuff. So, maybe if @kushthedude can move the project ahead by fixing the PR and handling other required changes to get the project to latest standard. Or should we wait for it to be deprecated?

I was just explaining that guy's point of view 😬

**Comment by kushthedude** [comment]
> The weird thing about anyone who is defending ember here is that no one among them is creating PRs to move the project further. I am. And it is exhausting debugging this stuff. So, maybe if @kushthedude can move the project ahead by fixing the PR and handling other required changes to get the project to latest standard. Or should we wait for it to be deprecated?

I was just explaining that guy's point of view. Also, I was not the one to choose Ember for the project.

**Comment by iamareebjamal** [comment]
The migration we are doing here is not octane, it is ES6 classes and angle bracket syntax. And it is not even problem with it, at least ember has codemods. But the debugging is too difficult that it took me an hour to get which component was throwing an error and the error was completely unrelated as well. It originated from ember composable helpers `sort by` which would not even be needed if ember did not use hbs.

1. Debugging is terribly hard
2. HBS is atrocious to work with and needs 3rd party packages to get basic stuff
3. Packages are not maintained (issue open for 6 months in repo)

**Comment by snitin315** [comment]
Ember is a nightmare

**Comment by jaydgruber** [comment]
Hi folks. Please take a look at #4301, which hopefully should provide a template for a more incremental path forward

Also, from personal experience, when I see a team really struggling with and fighting with Ember, and venting some frustration like this, it is because they are cut off from the community.

The majority of Ember developers are not putting their problems and answers up on StackOverflow as you might be used to from other ecosystems. It can be frustrating to google a problem and not find any answers. The best way to find help is to drop into the [discord](https://discordapp.com/invite/emberjs) and, I suggest the `#topic-octane-migration` channel. I think you will find a very welcoming and helpful community there

**Comment by iamareebjamal** [comment]
Finally! Fingers crossed!!!

**Pull request merged**
