### PR TITLE
added login message

### LINKED ISSUE #5456: Login Box: Show info message when page directs to login page
If a user wants to perform different actions, they need to login. However, there is no message usually like "You need to login to perform this action." 

Please identify different cases when the login page shows up and add a message for the user, e.g.
* User verified by clicking verification link show "Thank you for verifying your email address. Please login to continue."
* User clicks "Create Event", but is not logged in show "Please login to create an event. If you have not registered yet, please create an account first. Thank you!"
* What other actions require a user to login? Please add cases and messages.

Screenshot from 2020-11-02 14-36-43

### PR DESCRIPTION
**Pull request by namanjain007**
Screenshot from 2020-11-07 21-29-08

I want to resolve #5456 issue .

Fixes #5456

#### Short description of what this resolves:
Shows login first message if tried to create an event before authentication.

#### Changes proposed in this pull request:

- Removed AuthenticatedRouteMixin from /routes/create.js as user if not logged in , and tries to create an event ,  this will automatically redirect to login page without showing the message . Also there is no process to save previous url to create as the method deleted directly transitions to login for authentication . 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by namanjain007** [comment]
The message to show after user successfully confirms the email is already there .

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Completely irrelevant changes

**Comment by namanjain007** [comment]
> Completely irrelevant changes

Can you suggest how to approach this issue ?

**Comment by iamareebjamal** [comment]
I would have if the changes were somewhat related to the issue. What're you trying to do? What's your approach

**Comment by namanjain007** [comment]
> I would have if the changes were somewhat related to the issue. What're you trying to do? What's your approach

 An action "Create Event" requires user to be authenticated . If i click on the "Create Event Button" , I get redirected to Login Page . Now To display "Please login to create an event. If you have not registered yet, please create an account first. Thank you!", I have to store some state that i reached login page from create event trigger . Now to resolve that , I removed AuthenticatedRouteMixin  from /routes/create.js and forces user to redirect to create route and conditionally showing the error message if user not logged in . Please tell the desired approach .

**Comment by namanjain007** [comment]
There is a variable named "session.previousURL" . I tried accessing that too somehow. But this variable stores "/" as create event button is rendered on home.

**Comment by iamareebjamal** [comment]
You cannot remove Auth mixin. It is there for a reason. Will you remove that from hundreds of routes? Think of a solution which requires the least amount of changes. Check if there's a callback fired before redirection in a route protected by AuthMixin

**Comment by namanjain007** [comment]
I have found this "attemptedTransition"  which is part of 'ember-simple-auth/services/session' as a property. Now can I inject this service in login form and make cases of previous transition url and based on that show the message ?

**Comment by iamareebjamal** [comment]
Another PR is in works

**Pull request closed without merging**
