### PR TITLE
fix: update beforeModel transitions

### LINKED ISSUE #3026: Existing users are required to confirm account again and receive error page
Existing users and admins are required to confirm their account again.

Screenshot from 2019-05-28 09-49-58

When user receives a confirmation link and clicks on it s/he receives an error page.

Screenshot from 2019-05-28 09-38-15

### PR DESCRIPTION
**Pull request by uds5501**
Partially Fixes #3026 and fixes fossasia/open-event-server#5969

#### Short description of what this resolves:
This fixes the token access of the verify route.

### CODE REVIEW

**Comment by uds5501** [comment]
I have given partial fix status because this just makes sure that the verify route works fine. I am not sure if this reappears after the verification, I could not recreate it.

**Comment by uds5501** [comment]
@kushthedude @mrsaicharan1 @shreyanshdwivedi I think this resolves the issue of verification page not opening. Can you guys take a look?

**Comment by kushthedude** [comment]
@uds5501 will check locally , still i dint think its the actual cause of random appearance of error message

**Comment by uds5501** [comment]
@kushthedude I have a feeling that the user is not being verified at all. IMO what happening is that you resend the link. User opens it, but the verification fails because of this error.

**Comment by prateekj117** [comment]
@uds5501 Checked it locally. It worked. Also, locally, the verification message does not reappear after verification. Are you facing it locally?

**Comment by uds5501** [comment]
> @uds5501 Checked it locally. It worked. Also, locally, the verification message does not reappear after verification. Are you facing it locally?

Nope, not facing it locally. This user verification error must've been evident after the recent refactor. I don't remember which PR, but @mrsaicharan1 's PR had to be modified in a similar way to get transitions working properly.

**Comment by mrsaicharan1** [comment]
WhatsApp Image 2019-05-31 at 8 58 32 AM

I'm getting this locally and on netlify. Just check if something went wrong.

**Comment by uds5501** [comment]
@CosmicCoder96 please take a look at it. Thanks

**Pull request merged**
