### PR TITLE
fix: order paid ticket with unverified account

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/6893

https://user-images.githubusercontent.com/56407566/119666421-fad83080-be52-11eb-9b9a-f3066f31199c.mp4

@sachinchauhan2889 where the server changes are needed in this? Please test this at your end too. it seems fine to me.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ranjitkshah** [comment]
signup with new user and directlly go to paid event it not works there
Screenshot from 2021-05-27 12-57-39

**Comment by maze-runnar** [comment]
@sachinchauhan2889 @ranjitkshah @MeghalBisht I am not understanding why it's not working on directly going on public ticket page. `ticket.orderQuantity` is showing undefind. But we go back to other url like on exhibition page and come back to ticket page it's working. The ticket dropdown is not updating values for this I guess. I am trying to solve this, please check if there is a solution for this.

**Comment by MeghalBisht** [comment]
> `ticket.orderQuantity` is showing undefind. 

Can we use ticket type instead? I am not sure why its not loading on the first go.

**Comment by maze-runnar** [comment]
> Can we use ticket type instead?

yeah we can, but we will also need ticket.orderQuantity.

**Comment by MeghalBisht** [comment]
> yeah we can, but we will also need ticket.orderQuantity.

But if quantity is zero. it would already show sold out?
Screenshot from 2021-06-09 00-22-34

**Comment by maze-runnar** [comment]
it's orderQuantity, let's say if there are 2 types of ticket, paid and free. And user is ordering free ticket, bt in ticket.type we will also see paid ticket, and button would be enabled.

**Comment by ranjitkshah** [comment]
works but subtotal is not updating
Screenshot from 2021-06-23 22-32-08

**Comment by maze-runnar** [comment]
This is also not part of this issue, you go on another url , and come back
to this again, it will start updating.

**Comment by ranjitkshah** [comment]
works 🚀

**Comment by maze-runnar** [comment]
We cant remove that false, it will break for other cases, it was there for a reason.

**Comment by maze-runnar** [comment]
updating amount now

**Comment by maze-runnar** [comment]
@ranjitkshah , please check if all things are working correctly?

**Review by MeghalBisht — APPROVED** [review]
Works

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
