### PR TITLE
Add Paragraph field, text area

### PR DESCRIPTION
**Pull request by minhho89**
Fixes #8831 

#### Short description of what this resolves:

- Changed `TextArea` input instead of `Widgets::Forms::RichTextEditor` in `app/templates/components/forms/orders/order-form.hbs`
- Added `<span>` tag for showing the `paragraph` in `app/templates/components/forms/orders/attendee-list.hbs`

#### Checklist

- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ x] My branch is up-to-date with the Upstream `development` branch.
- [ x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by marcoag — APPROVED** [review]

**Comment by marcoag** [comment]
Thanks for the fix! It should be deployed in around 10mins, @minhho89 please double check it works as expected.

**Comment by minhho89** [comment]
Thanks @marcoag it works as expected in development

**Comment by mariobehling** [comment]
@minhho89 Is it possible to keep the line breaks? No need for rich text but line breaks.

**Comment by minhho89** [comment]
Sure! Let me check on that

**Comment by minhho89** [comment]
@mariobehling  Please refer to [this PR](https://github.com/fossasia/open-event-frontend/pull/8910) for the line breaks

**Pull request merged**
