### PR TITLE
feature-8845: Languages missing from language dropdown

### LINKED ISSUE #8845: Languages missing from language dropdown
Some languages are already translated mostly, but do not appear in the dropdown menu for languages. Please add the following:
* Arabic - عربي
* Norwegian - Bokmål
* Swedish - Svenska

Screenshot from 2023-06-27 07-26-29

### PR DESCRIPTION
**Pull request by lthanhhieu**
Fixes #8845 

#### Short description of what this resolves:
- Languages missing from language dropdown

#### Changes proposed in this pull request:
- Languages missing from language dropdown

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by mariobehling — COMMENTED** [review]
Please sort it according to the alphabet, e.g. Arabic should be on top.

**Comment by khangon** [comment]
Hi @mariobehling , @cweitat , @norbusan
We have completed ticket 8845.
Please help me check and verify.
Thanks,

image
image

**Comment by mariobehling** [comment]
Please sort by Alphabet, e.g. Arabic on top and Svenska in the middle.

**Comment by mariobehling** [comment]
Please make state "ready for review" if PR is ready.

**Comment by khangon** [comment]
> Please make state "ready for review" if PR is ready.
Hi @mariobehling 
Here's the list I've sorted.
Please help me check.
image

**Comment by mariobehling** [comment]
yes, the list is ok.

**Comment by mariobehling** [comment]
Ok, thanks for feedback. Then setting it to review and merging it.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
