### PR TITLE
Making unread notification dropdown look better.

### LINKED ISSUE #914: Make the dropdown menu for unread notifications look better
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

image

**Expected behavior:**

It should look better.

### PR DESCRIPTION
**Pull request by jainkeval**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
It makes the dropdown for unread notifications look better.

Fixes #914

### CODE REVIEW

**Comment by niranjan94** [comment]
Deployment link: https://pr-915-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@geekyd When there are no notifications, the class applied would be 'ui fluid list', would that be correct way? What do you think?

**Comment by jainkeval** [comment]
@geekyd I have changed the commit message. Thanks for the review.

**Comment by niranjan94** [comment]
Deployment link: https://pr-915-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@sumedh123 That would be incorrect but if we remove the list class the indentation and alignment will not remain the same as we no notification is a list item like any other notification that will be populated in the list. @sumedh123 @jainkeval Please suggest a better solution that can be used here.

**Comment by sumedh123** [comment]
@geekyd Seems this is the only solution. We can merge this for now. There is one item in the list, so making it a list wont be totally incorrect.

**Comment by geekyd** [comment]
Sounds right

**Comment by niranjan94** [comment]
Deployment link: https://pr-915-open-event-frontend-fossasia.surge.sh

**Pull request merged**
