### PR TITLE
Added Sitemap

### LINKED ISSUE #1820: Footer: Sitemap Link not working
There is no sitemap link and sitemap.

screenshot from 2019-01-14 23-06-57

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Sitemap has been added for open-event

Fixes #1820

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Added Sitemap

screenshot from 2019-01-18 11-57-57

### CODE REVIEW

**Comment by sk9331657** [comment]
We need to determine routes using total available routes in the current app. If available routes are changed ,sitemap should change automatically.

**Comment by rajvaibhavdubey** [comment]
@CosmicCoder96 temporarily we can have this till the service is in use. Till then I'll work on dynamic sitemap.

**Comment by sk9331657** [comment]
@rajvaibhavdubey  I have already created pr on using static sitemap but @niranjan94  told to use dynamic sitemap. It is better if you directly integrate  dynamic Url.

**Comment by CosmicCoder96** [comment]
Make a new PR with dynamic routes, when ready. This can't be merged.

**Pull request closed without merging**
