### PR TITLE
[wip]enh: rename settings to accounts

### LINKED ISSUE #3119: Rename "Settings" to "Account"
Please rename "Settings" to "Account" in the settings tab and the drop-down menu.

Reason: We are storing more info than just "settings" in that area. Therefore "Account" is a more appropriate name.

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #3119 

#### Short description of what this resolves:
Renames settings to account in dropdown

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by uds5501** [comment]
@mariobehling @CosmicCoder96 the issue specified renaming in "settings tab" , I wanted to know which tab are you referring to? Is it the admin/settings or the chrome tab itself?

**Comment by kushthedude** [comment]
> @mariobehling @CosmicCoder96 the issue specified renaming in "settings tab" , I wanted to know which tab are you referring to? Is it the admin/settings or the chrome tab itself?


I think both @uds5501

**Comment by uds5501** [comment]
@kushthedude I have fixed the chrome tab, although will wait for confirmation of admin/settings

**Comment by kushthedude** [comment]
@uds5501  ?

**Comment by uds5501** [comment]
@kushthedude  I have no idea what happened, I force pushed and it automatically closed. Wait, will make a new one.

**Comment by mrsaicharan1** [comment]
> @uds5501 ?

What is that supposed to mean?

**Comment by kushthedude** [comment]
@uds5501 There was no need to make new PR , You could have pushed other local branch to the following branch , If you messed up enh-3119 , You could have done `git push -f origin NewBranch:enh:3119`

**Comment by kushthedude** [comment]
@uds5501 There was no need to make new PR , You could have pushed other local branch to the following branch , If you messed up enh-3119 , You could have done `git push -f origin NewBranch:enh:3119`

**Comment by kushthedude** [comment]
> > @uds5501 ?
> 
> What is that supposed to mean?

@mrsaicharan1 That was supposed to mean , `Why did he close the PR ?`

**Comment by shreyanshdwivedi** [comment]
@kushthedude maybe you should stop monitoring over each PR and issue. People will tag you if they'll need your help.
He closed the PR or whatever happened, atleast give him time to open a new one or fix what he messed up. Please give commenting everywhere a pause for now.

**Comment by mrsaicharan1** [comment]
> @uds5501 There was no need to make new PR , You could have pushed other local branch to the following branch , If you messed up enh-3119 , You could have done `git push -f origin NewBranch:enh:3119`

This was all you had to mention, rather than prolonging the conversation.

**Pull request closed without merging**
