### PR TITLE
fix:add sort options to Speakers Table

### LINKED ISSUE #3483: Speakers Table: Show `sort action` buttons in Speakers Table
**Is your feature request related to a problem? Please describe.**

No, Add sort buttons in `Name` and `Email` column of `Speakers Table`.

### Expected
Screenshot 2019-08-27 at 4 07 18 AM

### Actual
Screenshot 2019-08-27 at 4 07 57 AM

**Additional context**

Only for **BEGINNERS**

### PR DESCRIPTION
**Pull request by amreshk005**
Fixes #3483

#### Short description of what this resolves:
Added sort button to speakers Table
Screen Shot 2019-09-27 at 8 55 27 PM

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by amreshk005** [comment]
@kushthedude I have fixed the issue. 

Please check it out.

**Comment by amreshk005** [comment]
> Fix the indentation

I have fixed the indentation

**Comment by kushthedude** [comment]
@amreshk005 please use a meaningful commit name from next time when your force push

**Comment by amreshk005** [comment]
> @amreshk005 please use a meaningful commit name from next time when your force push

Ok, I will take care of that.

**Pull request merged**
