### PR TITLE
Placed view icon on top in events table

### LINKED ISSUE #1811: On tables edit icon is on top. View icon should be on top.
The edit icon is on top as the most prominent icon in tables and dashboards. Please change the icon listing and show the "View" icon on the top of every view.

screenshot from 2019-01-14 22-02-01

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Placed `view icon` on the top in events table

screenshot_2019-01-15 live events open event

Fixes #1811

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 please review

**Comment by mariobehling** [comment]
@shreyanshdwivedi Could you please provide screenshots in your PRs? Thank you.

**Comment by shreyanshdwivedi** [comment]
@mariobehling I've added screenshots. Please review :)

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 PFA
screenshot_2019-01-15 live events open event 2

**Pull request merged**
