### PR TITLE
fix: Removing FE Validation of Time

### LINKED ISSUE #2077: Not able to set event start time
**Describe the bug**

When creating a new event and filling up start time, the time doesn't set properly. For example a time of 09:35 is not being set instead 00:35 is getting set.
**To Reproduce**
1. Go to event creation page
2. set start time to hours and minutes
3. you will see hours get reset

**Expected behavior**

The time should be set properly
**Screenshots**

ezgif com-video-to-gif

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I would like to work on this issue

### LINKED ISSUE #2366: Event end time error
**Describe the bug**

Not able to set end time prior to start time

**To Reproduce**

1. Go to 'http://127.0.0.1:4200/create'
2. Set a start time and date
3. Change the end date.
4. Try to set end time before start time.
5. See error

**Expected behavior**

User should be able to set end time as per his flexibility.

**Screenshots**

Screenshot 2019-03-23 at 12 52 35 AM

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 72.0.36

**Additional Context:**

Would like to work on it.

### PR DESCRIPTION
**Pull request by kushthedude**
- Fixes #2077 

- Fixes #2366 

#### Screenshot : 

image

### CODE REVIEW

**Comment by niranjan94** [comment]
@kushthedude removing validations when something doesn't work is not a viable fix. Please fix the validations instead.

**Comment by kushthedude** [comment]
> @kushthedude removing validations when something doesn't work is not a viable fix. Please fix the validations instead.

@niranjan94 Its the issue with the Date-Time module present, They are not interlinked so if I did make changes to time validator it won't be any good.
 That's @CosmicCoder96 removed the other validations from the `Event Wizard` related to `Date & Time`, I think he missed this part.

**Comment by CosmicCoder96** [comment]
Actually @kushthedude, that was done haphazardly because a customer was
using the live system and was unable to edit things, now would be a good
time to fix this issue properly.

**Comment by niranjan94** [comment]
@kushthedude I agree with @CosmicCoder96 on this. Time to re-add the validations and fix them.

**Comment by kushthedude** [comment]
Closing it, May need to find a new fix with validation

**Pull request closed without merging**
