### PR TITLE
fix: tax update work correctly

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7810 https://github.com/fossasia/open-event-frontend/issues/7824

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@pc-beast please test this.

**Comment by pc-beast** [comment]
I see no change in behaviour on my localhost. This is probably because of #7824. 🤔

**Comment by maze-runnar** [comment]
I don't know, it seemed working on my system.

**Comment by pc-beast** [comment]
let me test once again

**Comment by maze-runnar** [comment]
@pc-beast complete https://github.com/fossasia/open-event-frontend/pull/7881 and then we will test both (this and yours) in one go.

**Comment by progmatic-99** [comment]
Not working for me.
Tax doesn't event show in price as described in this [issue](https://github.com/fossasia/open-event-frontend/issues/7824)
Tax is not appearing either with "included" or "on top"


ss_1633758743

**Comment by maze-runnar** [comment]
> Not working for me. Tax doesn't even show in price as described in this [issue](https://github.com/fossasia/open-event-frontend/issues/7824) Tax is not appearing either with "included" or "on top"
> 
> ss_1633758743

@progmatic-99 please re-test.

**Comment by progmatic-99** [comment]
Now it's working. 🔥 🔥 

ss_1633765929

**Comment by maze-runnar** [comment]
@mariobehling please review and merge.

**Comment by maze-runnar** [comment]
@mariobehling please review & merge

**Pull request merged**
