### PR TITLE
Adding end date

### LINKED ISSUE #1883: Fix dashboard view to be more appropriate
* Fix date to show starting and end data. Maked date in one row and the time directly below the date. Reduce width of the column.
* Expand the width of the column "Tickets" and reduce the column width of other column respectively. The goal is that each ticket name and the ticket numbers fit in one row also when ticket names are long.
* Ensure the view works on mobile views

Compare: https://eventyay.com/events/live

screenshot from 2019-01-18 00-32-53

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves
After this PR, the end time and start time shall be visible in a clear understandable format.

UI Change : 
image

#### Changes proposed in this pull request:

- using ``records.startsAt`` as a conditional
- formatting the template to include end date and start date

Fixes #1883

### CODE REVIEW

**Comment by uds5501** [comment]
@sk9331657 @mariobehling Please review

**Comment by uds5501** [comment]
@sk9331657 Doing So

**Comment by uds5501** [comment]
One sample view from Galaxy S5
image

Another view from Iphone 5/SE configuration
image

I think these should do as mobile screen checks @sk9331657 @pranav1698

**Comment by sk9331657** [comment]
@uds5501  Just add tab view i.e. mid-screen view .

**Comment by uds5501** [comment]
@sk9331657 I didn't get it, could you please elaborate what is a tab view?

**Comment by sk9331657** [comment]
@sk9331657  I mean tablet view.

**Comment by sk9331657** [comment]
@uds5501  Try Ipad.

**Comment by uds5501** [comment]
This is the iPad view
image
@sk9331657

**Comment by CosmicCoder96** [comment]
I am sorry, you are modifying a global component, it will disrupt a fair portion of the app, create a new component to do this, and use it on this particular route. The title of the PR is misleading and very vague, so is the commit message. Please follow best practices, and make a new PR with all those changes. The discussion in this thread is redundant. I don't understand the point of requesting screenshots for review as the addition of some text is not likely to affect the resolution which is already there.
@pranav1698 There is  an autodeployment created for each PR, by netlify. 
image
You can click it to view changes, no need for asking for screenshots.

**Comment by uds5501** [comment]
@CosmicCoder96 I will keep the commit messages and PR titles in mind, also, I shall try making a local component and try solving this issue in the method you proposed.

**Pull request closed without merging**
