### PR TITLE
chore: removing template-inline-precompile

### PR DESCRIPTION
**Pull request by kushthedude**
ember-cli-htmlbars-inline-precompile is not needed anymore with dependencies upgrades.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@kushthedude No need to merge dev into branches. You're just wasting CI minutes that way, a new build with no changes will be created. The only need for merges in when there are conflicts, DB migrations or interdependent dependencies

**Comment by kushthedude** [comment]
> @kushthedude No need to merge dev into branches. You're just wasting CI minutes that way, a new build with no changes will be created. The only need for merges in when there are conflicts, DB migrations or interdependent dependencies

Then why there is need for update branch button, Also isn't target branch needs to be in sync with HEAD branch before development in this option ?

**Comment by iamareebjamal** [comment]
> Then why there is need for update branch button

Because of this - The only need for merges in when there are conflicts, DB migrations or interdependent dependencies

There's an option to merge without CI passing, should that be done as well? I wish there was an option to restrict branch updates to only admin

> Also isn't target branch needs to be in sync with HEAD branch before development in this option ?

No

**Comment by kushthedude** [comment]
> No

So you can merge a PR whose head is not in sync with development 😕 ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by kushthedude** [comment]
Might be an admin only feature then😅

**Pull request merged**
