### PR TITLE
Trim email input before login.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Trim the email input on login form submit.

#### Changes proposed in this pull request:

- Trim email input.

Fixes: #2503

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I have edited the input in on submit function. I wasn't able to find how the value `identification` is getting set. Let me know if changes are required.

**Comment by uds5501** [comment]
@Anupam-dagar @CosmicCoder96 Can't this be handled on server? This would be helpful on not only tackling the Frontend but also the API issue.

**Comment by Anupam-dagar** [comment]
@uds5501 Agreed. I'll push the fix for the same there.

**Comment by uds5501** [comment]
@Anupam-dagar Shall I open a corresponding server issue?

**Comment by Anupam-dagar** [comment]
@uds5501 With the issue transfer feature in place, I guess it's best for the repo owners to transfer the issue rather than us closing it here and opening it there.

**Comment by Anupam-dagar** [comment]
Opened https://github.com/fossasia/open-event-server/pull/5759 as a server fix for the same.

**Comment by CosmicCoder96** [comment]
Handle it on server.

**Pull request closed without merging**
