### PR TITLE
fix: change sidepanel style

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/6826
Screenshot from 2021-03-02 00-57-32

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Inconsistent padding

**Comment by mariobehling** [comment]
I am updating the branch as some changes are not reflected here yet.

**Comment by mariobehling** [comment]
Thanks. 

1. It looks like a table now, but I think it would be better if each item would look like a button. But, the button should be invisible unless I scroll over it.
2. The color of the existing video boxes changes. Can we also make the video rooms in the same size, indent and style as Schedule, Speakers, Exhibition and when a user selects it, highlight it, please.

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-02 22-48-29

**Comment by iamareebjamal** [comment]
That's how it looks for me

And there is no hover on video room item list

image

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-04 18-38-16

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-04 19-57-08

**Comment by iamareebjamal** [comment]
Still not circle 

image

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-04 22-18-49

**Comment by iamareebjamal** [comment]
Current selected video should be highlighted

**Comment by mariobehling** [comment]
I am not able to access the sidepanel even though the account is a speaker and it works on eventyay.com

Screenshot from 2021-03-04 18-44-16

**Comment by mariobehling** [comment]
Still same issue. Cannot test it.

**Comment by iamareebjamal** [comment]
@mariobehling Reload the page and try. It's another bug which I am trying to fix

**Comment by mariobehling** [comment]
Thanks. Please change as follows:

1. In the previous version of the side panel, when the user scrolls over a video room the color changes. Please use the same color for the scroll over in the new version of the sidepanel. I am hardly able to see the color change otherwise.
2. In the previous version of the side panel, when the user selects a video room the color of that room appears differently. Please use the same color to be displayed for the active page or video room.

Screenshot from 2021-03-06 20-01-10

**Comment by mariobehling** [comment]
About 2: Or is it already the same color? Currently it is not well visible. Please try a brighter color than the current one.

**Comment by mariobehling** [comment]
I think in this version changing the order does not make sense as it did before. Therefore please keep the order static. Thanks.

**Comment by maze-runnar** [comment]
> I think in this version changing the order does not make sense as it did before. Therefore please keep the order static. Thanks.

Schedule -> speaker -> exhibition this is order right?

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-07 14-06-17

**Comment by mariobehling** [comment]
> > I think in this version changing the order does not make sense as it did before. Therefore please keep the order static. Thanks.
> 
> Schedule -> speaker -> exhibition this is order right?

The order is right, but the video rooms still change the order, e.g. the active one goes on top. Please do not change the order of video rooms anymore.

**Comment by mariobehling** [comment]
Please ensure the video rooms as well as the other pages are highlighted when selected, if possible, e.g. if the user selects "Exhibition" highlight exhibition in the sidepanel same as when you highlight the video rooms.

**Comment by maze-runnar** [comment]
> The order is right, but the video rooms still change the order, e.g. the active one goes on top. Please do not change the order of video rooms anymore.

this is not related to this PR. It is implemented like this previosly.
Screenshot from 2021-03-08 11-19-55

fixed rest of requirements - 
Screenshot from 2021-03-08 10-53-37
Screenshot from 2021-03-08 10-53-32

**Comment by iamareebjamal** [comment]
image

**Comment by iamareebjamal** [comment]
@maze-runnar Please see the latest changes. There were far too many unused styles and the stream preview latter styling was still wrong

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
