### PR TITLE
feat: Reorder exhibitors

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/6681
Order at exhibition page before and after : 
Screenshot from 2021-02-15 21-02-04
Screenshot from 2021-02-15 21-01-53

reordering - 
Screenshot from 2021-02-15 21-01-49
Screenshot from 2021-02-15 21-01-39
Reset:
Screenshot from 2021-02-15 20-59-26
Screenshot from 2021-02-16 11-42-26

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Test event gives error page.

https://open-event-frontend-git-fork-maze-runnar-reorder.eventyay.vercel.app/events/fa96ae2c/exhibitors/list

Screenshot from 2021-02-16 08-20-02

**Comment by maze-runnar** [comment]
> Test event gives error page.
> 
> https://open-event-frontend-git-fork-maze-runnar-reorder.eventyay.vercel.app/events/fa96ae2c/exhibitors/list
> 
> Screenshot from 2021-02-16 08-20-02

server PR is also opened - https://github.com/fossasia/open-event-server/pull/7748/

**Comment by maze-runnar** [comment]
@iamareebjamal when event is not published, reordering is showing 404?

**Comment by maze-runnar** [comment]
speaker reorder also shows 404 when event is not published.
Screenshot from 2021-02-16 14-00-02

**Comment by iamareebjamal** [comment]
It should not show 404 for organizers and admins.

**Comment by maze-runnar** [comment]
Everything else is working fine.

**Pull request merged**
