### PR TITLE
chore: Remove ember jquery references

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4887667&bid=16190380)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4887667&bid=16190380)

**Comment by kushthedude** [comment]
@iamareebjamal Rather than using native jquery, Why can't we import `$` from `@ember/jquery` ? We are already using this optional dependency.

**Comment by iamareebjamal** [comment]
https://github.com/emberjs/ember-jquery#usage

**Comment by kushthedude** [comment]
> https://github.com/emberjs/ember-jquery#usage

What about enabling the `jquery-integration` explicitly ?

**Comment by iamareebjamal** [comment]
It is still enabled

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4887667&bid=16190380)

**Comment by kushthedude** [comment]
Seriously 😆

**Comment by kushthedude** [comment]
You didn't need to give up finally 🎉

**Comment by iamareebjamal** [comment]
Makes no sense why it was failing. It is literally the same function call, but anyway never going to touch it again

**Comment by kushthedude** [comment]
> Makes no sense why it was failing. It is literally the same function call, but anyway never going to touch it again

There is a reason why all modern web-apps are moving away from jquery.

**Comment by iamareebjamal** [comment]
I gave up, had to revert the form.js to deprecated jquery call. It's just failing without any good reason, first saying prop('tagName') is undefined and then `setting property on destroyed object`

I don't know why this.$ will have different effect on destroyed objects than $*(

**Comment by iamareebjamal** [comment]
I hate it with a passion of thousand burning suns

**Pull request merged**
