### PR TITLE
chore: Release v1.9

### PR DESCRIPTION
**Pull request by kushthedude**
- Speaker/Session Fixes.
- Session were restricted to 20 and some enhancements

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Fix the speaker image CSS issue before this

**Comment by kushthedude** [comment]
> Fix the speaker image CSS issue before this

@iamareebjamal Should we release this, as Speaker CSS PR is still due, We may make a patch after 2-3 days for that? As this contains bug fixes for Session/Speaker form and various new features.

**Comment by kushthedude** [comment]
@iamareebjamal How should this be merged, using rebase or merge commit ?

**Comment by iamareebjamal** [comment]
Merge Commit

**Pull request merged**
