### PR TITLE
Userlinks

### PR DESCRIPTION
**Pull request by harsh-98**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Refers #695

### CODE REVIEW

**Comment by niranjan94** [comment]
Deployment link: https://pr-1063-open-event-frontend-fossasia.surge.sh

**Comment by harsh-98** [comment]
@niranjan94 i am not able to register at https://pr-1063-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-1063-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-1063-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@harsh-98 There is not API for updating the social links, also we should avoid using loader for making network calls, we must use ember-data to handle the network requests. Please update the status of the PR. Thanks

**Pull request closed without merging**
