### PR TITLE
fix: position of logout icon in other languages

### LINKED ISSUE #5721: Top Menu: Log out menu icon disappears in other languages
The logout icon disappears in other languages if the word is longer in some languages and depending on the resolution. Please ensure the icon shows up as normal even if the word is longer.

Question: How and where does the design needs to be changed to ensure this does not happen at other places?

Screenshot from 2020-11-23 10-56-46
Screenshot from 2020-11-23 10-56-17

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5721 

#### Short description of what this resolves:
fix position of logout icon in other languages

__Screenshots__
__before__
sachin2

__after__

sachin1

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
space between isnt good. Use d-flex and ml-auto on icon

**Comment by sachinchauhan2889** [comment]
> space between isnt good. Use d-flex on container and ml-auto on icon

@iamareebjamal sir, not working. ml-auto is overrided.

sachin3

**Comment by iamareebjamal** [comment]
Use inline style. And please check your gitter

**Comment by sachinchauhan2889** [comment]
@iamareebjamal sir, ready for review.

**Pull request merged**
