### PR TITLE
feat: Add URL and Email validations in speaker-session form

### LINKED ISSUE #1326: Validations on new speaker form fail silently
**Describe the bug**

**To Reproduce**
1. Go to call for speakers and start submitting a proposal as a new speaker.
2. Enter an invalid url (no `https` or `http` deems a URL as invalid)
3. Try to submit
image
This behavior is because server declares it as an unprocessable  entity on account of the Invalid URL. And the request silently fails. 

**Expected behavior**

There should be validation on the frontend which lets the user know what they are entering wrong.

### LINKED ISSUE #1430: Add URL and Email validations in the speaker session form
**Describe the solution you'd like**

Add URL and Email validations in the speaker session form

**Additional context**

Parent: #1225

### PR DESCRIPTION
**Pull request by srv-twry**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
URL and Email fields aren't validated in the session/speaker form.

#### Changes proposed in this pull request:
Add validation to those fields.

Fixes #1430 
Fixes #1326

### CODE REVIEW

**Comment by srv-twry** [comment]
@mayank8318 @ritikamotwani @pradeepgangwar Please review :) 
You can test it using the deploy preview.

**Comment by ritikamotwani** [comment]
@srv-twry 
image
Shouldn't this be a valid URL?

**Comment by bhaveshAn** [comment]
https or http is request i guess ...

**Comment by srv-twry** [comment]
@ritikamotwani The server fails if there is no protocol for the URL. Check the second of the related issue.

**Comment by ritikamotwani** [comment]
@srv-twry okay it git accepted after writing http or https.
But the social accounts should have a check for the username 
Like facebook.com/user-name etc
You can do that in a separate issue too.

**Pull request merged**
