### PR TITLE
fix: one click signup enhancement

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7727
Screenshot from 2021-08-26 09-04-38
Screenshot from 2021-08-26 09-04-16

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
Screenshot from 2021-08-28 09-06-21
Screenshot from 2021-08-28 09-06-13
Screenshot from 2021-08-28 08-47-42

**Comment by mariobehling** [comment]
Thanks. In mobile view could you also keep the radio buttons on the left (in front of the right-side text), please?

Screenshot from 2021-08-30 05-45-55

**Comment by maze-runnar** [comment]
Screenshot from 2021-08-30 13-19-19
Screenshot from 2021-08-30 13-18-17

**Comment by maze-runnar** [comment]
> Thanks. In mobile view could you also keep the radio buttons on the left (in front of the right-side text), please?
> 
> Screenshot from 2021-08-30 05-45-55

Done :+1:

**Pull request merged**
