### PR TITLE
feat: Show attendee information of attendee form on the order overview page. 

### LINKED ISSUE #7905: Show attendee information of attendee form on the order overview page
The order overview page of attendees does not show all the information that attendees fill into custom forms. Please add a box "Attendee Form" on the attendee overview order page and show all the information attendees fill in.

Screenshot from 2021-10-09 23-06-51

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Fixes #7905 

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
@maze-runnar in the custom form their are too many information that attendee fill in. but currently we only show name and email id of attendee. so, do we need to show all the info that user fill in? what's the best way to do?

**Comment by mariobehling** [comment]
Please show all information that is activated by the organizer, yet.

**Comment by maze-runnar** [comment]
@iamdevvalecha enable more fields and see if any info is missing. @mariobehling please clarify which field is missing in the attendeeInfo

**Comment by maze-runnar** [comment]
@mariobehling please look into it

**Pull request closed without merging**
