### PR TITLE
fix: Email and Contact button not in one line and heading not standardized

### LINKED ISSUE #6962: Exhibitors Page: Email and Contact button not in one line and heading not standardized
If an exhibitor has both email and contact button they are not longer in a line. The space above "Get in touch" is different to other headings. Please standardize the space here.

Compare https://eventyay.com/e/fa96ae2c/exhibition/56
Screenshot from 2021-03-09 16-10-08

### PR DESCRIPTION
**Pull request by afzal442**
Fixes #6962 

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Screenshot?

**Comment by afzal442** [comment]
> Screenshot?

sorry, Sir, I didn't see ur comment. WIP!

**Comment by afzal442** [comment]
after this commit
Plz have a look
c2

**Comment by afzal442** [comment]
@mariobehling sir, plz review it. Thanks

**Review by mariobehling — APPROVED** [review]
Works for me. Thanks

**Pull request merged**
