### PR TITLE
feat: Removing session names from modal

### LINKED ISSUE #3514: Call for Speakers: Show existing sessions and info on page instead of on popup
If user has not submitted a session or speaker details it currently shows "Submit Proposal". This is correct.

If a user has already submitted speaker and session info, please show the info on the page itself instead of on the popup.

Integrate the popup content in the page.
Screenshot from 2019-09-08 01-35-04

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3514 

#### Screenshots :

Screenshot 2019-09-08 at 3 00 06 PM

Screenshot 2019-09-08 at 3 00 14 PM

### CODE REVIEW

**Comment by kushthedude** [comment]
I tried simple links, they were looking poor thats why I used labels.

**Comment by kushthedude** [comment]
@mariobehling @CosmicCoder96 Please Review

**Comment by kushthedude** [comment]
@iamareebjamal @uds5501 Please review

**Comment by iamareebjamal** [comment]
@prateekj117 Please review PRs to get them merged

**Comment by kushthedude** [comment]
> @prateekj117 Please review PRs to get them merged

@prateekj117

**Comment by prateekj117** [comment]
@iamareebjamal Not sure about the UI, everything else LGTM.

**Comment by prateekj117** [comment]
@kushthedude https://github.com/fossasia/open-event-frontend/pull/3515#pullrequestreview-290734008

**Comment by kushthedude** [comment]
> @iamareebjamal Not sure about the UI, everything else LGTM.

Plain links were looking way to poor, also it were degrading the way we have designed the public page hence I use ui banner

**Comment by iamareebjamal** [comment]
Why are they each on their own line? Why not make them inline-block so they don't occupy so much vertical space

**Comment by kushthedude** [comment]
> Why are they each on their own line? Why not make them inline-block so they don't occupy so much vertical space

Various session names have different length, making them inline wont make them utilise a same amount of space due to which some row will have 2-3 sessio and other would have 4-5. You can check at netlify deployment it looks quite good in using😅

**Comment by iamareebjamal** [comment]
URL for testing?

**Comment by kushthedude** [comment]
Netlify deployment is there.

**Comment by iamareebjamal** [comment]
Yes, but for which event, which page?

**Comment by kushthedude** [comment]
You will have to login to check the same, as the speaker will be able to
see his sessions. I would be able to give a gif for the following.

**Comment by iamareebjamal** [comment]
Screenshot_2019-11-25_15-15-58

Screenshot_2019-11-25_15-18-07

Tell me which one looks better?

**Comment by kushthedude** [comment]
Cool will be making inline asap

**Comment by kushthedude** [comment]
@iamareebjamal There is a bug in this approach. 
@prateekj117 Can you check once on your local if this PR is working is fine ?

**Comment by iamareebjamal** [comment]
What;s the bug?

**Comment by kushthedude** [comment]
When new speaker registers he is not redirected to correct route

**Comment by kushthedude** [comment]
image

**Comment by kushthedude** [comment]
@iamareebjamal Please review

**Pull request merged**
