### PR TITLE
Correcting typo in 'Bug_Report' template

### LINKED ISSUE #2520: Typo in 'Bug_Report' Template of new issue
**Expected behavior**

Correct the typo for behaviour which is written as 'behavior' .

**Screenshots**

image

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #2520

### CODE REVIEW

**Comment by mohitm15** [comment]
@kushthedude @CosmicCoder96 l think no need to merge this PR because it was already correct. If you type `behaviour` it will show error on Grammarly

**Comment by CosmicCoder96** [comment]
@mohitm15 Behavior and Behaviour are both correct spellings. Behavior is US English. Behaviour is UK. And the fact that a PR was made for it was a time waste enough -- honestly, what do you hope to gain by elongating this pointless discussion further since this PR is already merged.  I am not going to revert it.

**Comment by kushthedude** [comment]
Well it my mac was highlighting the word behavior and not behaviour . As you can see here 
image 
@mohitm15

**Comment by mohitm15** [comment]
@kushthedude @CosmicCoder96 Please refer this 
Screenshot 2019-04-08 12:39:37

**Comment by shreyanshdwivedi** [comment]
@mohitm15 please refer to this and end the discussion now :)
IMG_20190408_124449

**Pull request merged**
