### PR TITLE
fix: add option "Add Related Session" 

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/6864

 - @iamareebjamal I amfacing some issue here 
 
  ```
<UiDropdown
        @class="fluid multiple selection"
        @selected={{this.sessionsDetails}}
        @onChange={{action (mut this.sessionssDetails)}} as |execute mapper|>

``` 
as In octane syntax it should be
```
<UiDropdown
        @class="fluid multiple selection"
        @selected={{@sessionsDetails}}
        @onChange={{action (mut @sessionssDetails)}} as |execute mapper|>

 but {{action (mut @sessionssDetails)}} is giving error.

```
Screenshot from 2021-03-06 23-23-27
Screenshot from 2021-03-06 23-22-12

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
What's the error?

**Comment by maze-runnar** [comment]
> What's the error?
```

Uncaught (in promise) Error: Assertion Failed: You can only pass a path to mut
    at assert (vendor.js:58582)
    at mut (vendor.js:28764)
    at Object.evaluate (vendor.js:72616)
    at AppendOpcodes.evaluate (vendor.js:72509)
    at LowLevelVM.evaluateSyscall (vendor.js:75405)
    at LowLevelVM.evaluateInner (vendor.js:75361)
    at LowLevelVM.evaluateOuter (vendor.js:75353)
    at JitVM.next (vendor.js:76429)
    at JitVM.execute (vendor.js:76406)
    at TryOpcode.handleException (vendor.js:75548)
```

**Comment by iamareebjamal** [comment]
Check the spelling of the action

**Comment by maze-runnar** [comment]
> Check the spelling of the action

in the speakers multiselection section this is working fine(without octane syntax)
<UiDropdown
      @class="fluid multiple selection"
      @selected={{this.speakersDetails}}
      @onChange={{action (mut this.speakersDetails)}} as |execute mapper|>

And this is also not working in my case.

**Comment by iamareebjamal** [comment]
You had written `@sessionssDetails` instead of `@sessionsDetails`

**Comment by maze-runnar** [comment]
adding it in the same section where rest of info of exhibitor is. The right (twitter above) section is the whole different component.

https://user-images.githubusercontent.com/56407566/110232022-1c570980-7f41-11eb-80d1-39e9e305f4b7.mp4

**Comment by mariobehling** [comment]
Good. On the public exhibitor's page please display the session similar to the schedule and link the arrow to the detailed session page from the schedule.

Screenshot from 2021-03-07 08-32-54

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-07 13-33-55

**Comment by mariobehling** [comment]
> On the exhibitors page show a section "Related Sessions" above the "Tweets" section.

**Comment by maze-runnar** [comment]
> > On the exhibitors page show a section "Related Sessions" above the "Tweets" section.

> adding it in the same section where rest of info of exhibitor is. The right (twitter above) section is the whole different component.

**Comment by mariobehling** [comment]
Please add it right above the tweet section. Below social links etc.

**Comment by mariobehling** [comment]
Screenshot from 2021-03-07 09-37-43

**Comment by mariobehling** [comment]
Please also change the following:
* Rename "Exhibitor Sessions" to "Related Sessions" and center the heading.
* In the form section:
   * make the session field into a dropdown field where the user can type in to find a sessions similar to the "add speakers form"
   * add existing related sessions below instead of inside the form field

Screenshot from 2021-03-07 09-30-14

**Comment by maze-runnar** [comment]
> add existing related sessions below instead of inside the form field

not understanding this one.

**Comment by mariobehling** [comment]
> > add existing related sessions below instead of inside the form field
> 
> not understanding this one.

No problem. It also works in the way it is implemented now it seems.

**Comment by mariobehling** [comment]
Screenshot from 2021-03-07 10-39-42

Could you please sort sessions by default by date and time on the exhibition page. Right now it seems like a random order.

**Comment by mariobehling** [comment]
It is not yet possible to select the circle and to favorite the session.

Screenshot from 2021-03-07 10-42-27

**Comment by mariobehling** [comment]
In the add related sessions form you show all sessions including pending sessions. Expected: Only show accepted and confirmed sessions.

**Comment by iamareebjamal** [comment]
Also, please hide the favourite button, it doesn't work correctly in pages other than schedule

**Comment by maze-runnar** [comment]
Screenshot from 2021-03-08 12-21-44

**Review by mariobehling — APPROVED** [review]
Nice! Thank you.

**Pull request merged**
