### PR TITLE
[WIP]Making TimeZone on GMT basis

### LINKED ISSUE #2248: Add TimeZone in 'Create an Event' on GMT basis
**Is your feature request related to a problem? Please describe.**
-When you create an event , TimeZones of different country are on alphabatical basis.
-It would be better if they are based on GMT,As every individual could search for particular timezone.
-Rather than searching for which city or his country has been included in the dropdown.

**Describe the solution you'd like**
-TimeZones should be classified on basis of GMT.

**PS: I would like to work on this enhancement.**

**Additional context**

screenshot 2019-03-02 at 10 32 48 pm

### PR DESCRIPTION
**Pull request by kushthedude**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
It makes TimeZones appear on the basis of its GMT value.

#### Changes proposed in this pull request:

- Solved GMT problem.
- Added A loop to parse the GMT value of timezone and concatenate in a additional variable.

Supposed To Fix #2248

### CODE REVIEW

**Comment by kushthedude** [comment]
@CosmicCoder96 This was the problem I was referring to in gitter chat . Should i modify the moment.js library ?

**Comment by Anupam-dagar** [comment]
@kushthedude Your PR is failing tests.

**Comment by kushthedude** [comment]
@Anupam-dagar not only test , this thing is not building and @CosmicCoder96 told me to move discussion on PR , thats why askin for help 😕

**Comment by CosmicCoder96** [comment]
Next gen is going in production soon, not a priority right now. Will figure it out later when there is better testing across the app/ Timezones can potentially break a lot of the app functionality -- after looking at the scheduler.

**Pull request closed without merging**
