### PR TITLE
fix position of logout icon in other languages

### LINKED ISSUE #5721: Top Menu: Log out menu icon disappears in other languages
The logout icon disappears in other languages if the word is longer in some languages and depending on the resolution. Please ensure the icon shows up as normal even if the word is longer.

Question: How and where does the design needs to be changed to ensure this does not happen at other places?

Screenshot from 2020-11-23 10-56-46
Screenshot from 2020-11-23 10-56-17

### PR DESCRIPTION
**Pull request by aryamanprince**
Fixes #5721 

#### Short description of what this resolves:

fix log out menu icon disappearing in other languages.
before 
wrongpad

after 
right

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sachinchauhan2889** [comment]
Already have PR for this issue #5722.

**Comment by aryamanprince** [comment]
> Already have PR for this issue #5722.

But that didn't solve the issue effectively. An issue can have multiple pr which can collectively solve issue.

**Review by daretobedifferent18 — COMMENTED** [review]
Screenshot_2020-11-24 UNESCO TechCul Ideathon eventyay  Screenshot_2020-11-24 UNESCO TechCul Ideathon eventyay(1) Screenshot_2020-11-24 UNESCO TechCul Ideathon eventyay(2)
@aryamanprince 
Sorry but this does not solves the issue. Pls have a solution which is consistent

**Comment by aryamanprince** [comment]
yeah you are right it doesn't resolve for one language.

**Comment by daretobedifferent18** [comment]
pls close this PR, issue is being resolved.

**Pull request closed without merging**
