### PR TITLE
Issue2

### PR DESCRIPTION
**Pull request by nikolaytoplev**
Fixes #

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Raunaksingh100** [comment]
Plz add the issue number in your or description

**Review by daretobedifferent18 — COMMENTED** [review]
Please add the information about the issue you are solving and all in PR description.

**Comment by iamareebjamal** [comment]
This PR still contains fix of 2 issues and the build is failing

**Comment by Raunaksingh100** [comment]
@nikolaytoplev plz fixed one issue in one pr and if you want to fixed other issues then you can also use branches.

**Pull request closed without merging**
