### PR TITLE
Add a down arrow in tabbed navigation to indicate button as a dropdown in mobile devices.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This PR adds a down arrow in the `tabbed navigation` component button in mobile devices.

#### Changes proposed in this pull request:

- Add semantic icon `angle down` after the text in tabbed navigation for mobile devices.

## Screenshots
Screenshot from 2019-04-07 01-14-14

Screenshot from 2019-04-07 01-14-32

Fixes: #2488

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@Anupam-dagar You should add an up arrow too when the toggle menu is open.

**Comment by kushthedude** [comment]
@Anupam-dagar Just a suggestion rather arrow down or up you just add the mobile-toggle-icon to indicate there is a drop down

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 @ritikamotwani please review

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I have implemented the required changes.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 Please review.

**Pull request merged**
