### PR TITLE
fix: Show Roles in capitalise form at team page

### LINKED ISSUE #5793: Team box and page: Show "organizer" with first letter in capital
The "organizer" role is not starting with a capital in contrast to the Owner role. Please standardize this and show "Organizer" with a capital too on the event dashboard team box and teams page.

Screenshot from 2020-11-27 21-02-03
Screenshot from 2020-11-27 21-01-37

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5793 

new screenshot today

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sachinchauhan2889** [comment]
@iamareebjamal sir, do i still need to remove role_name field from role_invite model from server and frontend.

**Comment by iamareebjamal** [comment]
Yes, in this PR, just include role in the invites request in the route

**Comment by iamareebjamal** [comment]
In event overview page as well

**Comment by iamareebjamal** [comment]
In event overview page as well

**Comment by sachinchauhan2889** [comment]
> In event overview page as well

sir, it is already in capital at overview page.

**Comment by iamareebjamal** [comment]
>  include role in the invites request in the route

**Comment by sachinchauhan2889** [comment]
@iamareebjamal sir, please review

**Pull request merged**
