### PR TITLE
feature 9125: Fix top menu for mobile screens

### LINKED ISSUE #9125: Fix top menu for mobile screens
* Standardize left width of burger menu to match the size of the event burger menu
* Slightly reduce size of Schedule, Speakers, Exhibition menu item
* within column center "eventyay" logo same as on standard menu bar

Screenshot from 2023-08-17 00-52-56
Screenshot from 2023-08-17 00-52-21

### PR DESCRIPTION
**Pull request by khangon**
Fixes #9125

#### Short description of what this resolves:
Fix top menu for mobile screens

#### Changes proposed in this pull request:

- Fix top menu for mobile screens

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket #9125 
Please help me check and verify.
Thanks,
Screenshot from 2023-08-18 14-49-26

Screenshot from 2023-08-18 14-49-48

**Comment by mariobehling** [comment]
Please centre "Exhibition" in the column as well.

**Comment by khangon** [comment]
> Please centre "Exhibition" in the column as well.

Hi @mariobehling ,
We have fixed. Please help me review. Thanks!
Screenshot from 2023-08-21 09-46-51

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please center the "open event" logo on the top right.

**Comment by khangon** [comment]
> Please center the "open event" logo on the top right.

Hi @mariobehling,
I have fixed this issue. Please help me check it.
Thanks 

image

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
