### PR TITLE
Added Show  100, 250, All

### LINKED ISSUE #1878: Speakers and Sessions List: Show 100, 250, All
Currently the speakers and sessions lists don't have a working search. Also it only shows 50 sessions maximum at the moment. It is very difficult to find a certain speaker and takes a long time as the pages load slowly.

Please change the dropdown max number as follows and enable:
* Show 100, 250, All

screenshot from 2019-01-17 16-21-37

### LINKED ISSUE #1906: Child Issue : Added Option 100, 250 and All in Search Events
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Working on it.

### PR DESCRIPTION
**Pull request by sk9331657**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Added Show  100, 250, All

#### Changes proposed in this pull request:

-
-
screenshot from 2019-01-17 23-33-56

-

Fixes #1906

### CODE REVIEW

**Comment by sk9331657** [comment]
@CosmicCoder96  PLease review.

**Comment by iamareebjamal** [comment]
@sk9331657 The issue is about search as well. If you can, solve that, or create a new child issue for that

**Comment by sk9331657** [comment]
@iamareebjamal I have resolved the issue the same way @mariobehlibg told.

**Comment by iamareebjamal** [comment]
> **Currently the speakers and sessions lists don't have a working search.** Also it only shows 50 sessions maximum at the moment

You missed the *first* sentence of the issue

**Comment by sk9331657** [comment]
I will resolve that in other pr.

**Comment by sk9331657** [comment]
@CosmicCoder96  @mariobehling  Please review.

**Comment by sk9331657** [comment]
@mariobehling  Please review.

**Comment by iamareebjamal** [comment]
Please create another child issue for that since the parent will close after this PR is merged

**Comment by sk9331657** [comment]
@CosmicCoder96  Option All needs to be implemented in backend too. I am creating pr for that.

**Comment by sk9331657** [comment]
> Please create another child issue for that since the parent will close after this PR is merged

Surely.

**Comment by CosmicCoder96** [comment]
@sk9331657 There is no separate PR needed for this issue, finish it here itself.

**Comment by sk9331657** [comment]
> @sk9331657 There is no separate PR needed for this issue, finish it here itself.

Ok But server issues needs to be rectified on server repo.

**Comment by iamareebjamal** [comment]
You need to pass page size 0 to get all, no change needs to be done on server side

**Comment by sk9331657** [comment]
> You need to pass page size 0 to get all, no change needs to be done on server side

Ok Thanks

**Comment by sk9331657** [comment]
@iamareebjamal  Please review now.

**Comment by iamareebjamal** [comment]
Please be patient with reviews. We voluntarily do this and may be busy with other things

**Pull request merged**
