### PR TITLE
fix: added check for required-fields and rendering gender

### LINKED ISSUE #3406: Attendee List: Only render required fields and some of the fields are not rendering.
Since we are rendering all fields in `attendee list` due to this many incomplete fields are getting shown.
Also, some of the select fields are not getting rendered fix them.
image

### PR DESCRIPTION
**Pull request by akshat0047**
Fixes #3406 

#### Short description of what this resolves:
When displaying the attendee list on the frontend, few blank fields with labels were getting rendered I have fixed it by implementing a check if there is a value returned through get request

[Before](https://pasteboard.co/ID0lgBN.png)  [After](https://pasteboard.co/ID0klcW.png)  

#### Changes proposed in this pull request:

- Shifted is-input-field helper check at the top of each loop
- Implemented a check for value is present in get data

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by akshat0047** [comment]
Please review the PR, Travis CI is probably failing because of indentation errors, fixing it soon. Is my approach correct? @CosmicCoder96 @mrsaicharan1

**Comment by akshat0047** [comment]
>     * Semantic Naming for PR.
>       Will edit name once I implement changes below
>     * Fix Indents.
>       On it
>     * Check the PR previously made to it and follow the same.
>       Ok sure
>     * Include a GIF showing what changes you have made and details you filled. (Before/After).
>      I have added hyper link with name Before and After, there was some issue with markup showing up my images
>     * Show me the rendering of `gender field`
        Fixing this

**Comment by kushthedude** [comment]
Update?

**Comment by akshat0047** [comment]
I was away for a while due to festive season, back on it and will give you the updates asap.

**Comment by akshat0047** [comment]
I have updated the changes suggested 
- semantic naming for PR
- fixing indents
- rendering gender (there was a bug in input-type helper)
- fixing Travis CI failure
- Adding gif of change(below)

Please review @CosmicCoder96  @kushthedude  @mrsaicharan1 
Frontend Fix

**Comment by akshat0047** [comment]
@iamareebjamal I have fixed the changes required please review, already requested active reviewers on the project

**Comment by iamareebjamal** [comment]
Thanks. Can you please confirm that if you remove the `required` check from frontend, are you able to successfully submit the form or not

**Comment by akshat0047** [comment]
@iamareebjamal the change is not related to form submission, I have changed the way things are rendering in the attendee section i.e. in the attendee list template

**Comment by akshat0047** [comment]
@iamareebjamal Please let me know if I am wrong with my facts, the form was getting submitted before I added the required field, my workflow was:

- Added an event
- Created tickets for free
- Buyed two tickets for two different attendees one with only required fields and another with req. + extra fields
- After applying the check in attendee-list only fields marked as required while creating the attendee form was rendered
- Rendered in the terms of Attendee dashboard in my events

Please merge my Pull Request if this is the correct approach.

**Comment by akshat0047** [comment]
> Thanks. Can you please confirm that if you remove the `required` check from frontend, are you able to successfully submit the form or not

I have checked this and yes we are able to submit the form successfully. Created two tickets with both required and non-required fields, working is as shown in initial screenshots.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/helpers/is-input-field.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/fossasia/open-event-frontend/pullRequest?prid=4354127&bid=14792936)

**Comment by akshat0047** [comment]
Please merge @CosmicCoder96 @mrsaicharan1 @iamareebjamal

**Comment by iamareebjamal** [comment]
Then it needs to be fixed on server. Please open an issue on server

**Comment by akshat0047** [comment]
ok opening an issue on server for required fields but I think I should modify this for correcting the rendering of gender field?

**Comment by iamareebjamal** [comment]
@kushthedude Will be able to tell better

**Comment by akshat0047** [comment]
@kushthedude  Please suggest me if I should modify the PR in the context mentioned above

**Comment by iamareebjamal** [comment]
@kushthedude Please confirm

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/helpers/is-input-field.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-frontend/open-event-frontend/pullRequest?prid=4354127&bid=14792936)

**Comment by kushthedude** [comment]
@akshat0047 Please make a follow up PR to remove a extra field rendering with every `gender` drop-down.

**Pull request merged**
