### PR TITLE
Refactor code to remove redundancy while setting loader to false

### LINKED ISSUE #787: Refactor code to remove redundancy while using 'this.set('isLoading', false)'.
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Todo:**
Refactor the code in view.js to remove redundancy while setting the loader false.

### PR DESCRIPTION
**Pull request by sumedh123**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #787

### CODE REVIEW

**Comment by sumedh123** [comment]
@fossasia/open-event-frontend Please review.

**Comment by sumedh123** [comment]
@niranjan94 How can we run the travis build again? There is some "EINTEGRITY" error which resolves when we push again?

**Comment by niranjan94** [comment]
Deployment link: https://pr-788-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-788-open-event-frontend-fossasia.surge.sh

**Comment by sumedh123** [comment]
@CosmicCoder96 Done :+1: Please review.

**Pull request merged**
