### PR TITLE
fixes #1697 (added meta tags and ogp tags for better SEO)

### LINKED ISSUE #1697: Add meta tags and ogp tags for better SEO
**Describe the bug**

We should add meta tags and ogp tags in the index.html for better SEO

**Expected behavior**

Meta tags and OGP tags help for better SEO and can help us improve the rank of our page

### PR DESCRIPTION
**Pull request by sarnava1**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This PR adds meta tags and OGP tags for better SEO 

#### Changes proposed in this pull request:

-Added meta tags to index.html
-Added OGP tags to index.html
-Thus after this PR gets merged the rank of our page will increase and will have better SEO

Fixes #1697

### CODE REVIEW

**Comment by sarnava1** [comment]
@ritikamotwani please review my PR.

**Comment by CosmicCoder96** [comment]
@sarnava1 Any updates on this?

**Comment by sarnava1** [comment]
@CosmicCoder96 I will do the required changes.

**Comment by sarnava1** [comment]
I will resolve conflicts and do the changes in a separate PR.

**Comment by sarnava1** [comment]
I will resolve conflicts and do the changes in a separate PR.

**Comment by sarnava1** [comment]
I will resolve conflicts and do the changes in a separate PR.

**Pull request closed without merging**
