### PR TITLE
feat: Attendee Form: Add user content for various options

### LINKED ISSUE #6377: Attendee Form: Implement "Photo & video & text consent" in attendee form with tickbox
As there are many online events nowadays, which are recorded, we need an option to announce that events are recorded when people order a ticket.

This means that people **must** accept that an event is recorded, photos are taken or text is copied in order to complete the order. Therefore please implement this as a field for the attendee form as follows:
* Add option "Photo & video & text consent" into the attendee form
* Only permit option to be "Required" in the form (so when an organizer chooses the option, it must be "required")
* On the order form of attendees show the following text with a tickbox, that the ticket buyer must accept.
   * "I agree that the event organizer is allowed to take photo, video and/or audio recordings of me or my profile and also texts created by me in the chats which might be published on the event organizer's websites and/or social media channels."
* If the ticket buyer does not tick the box, show an error message: "In order to complete the order process you need to agree to the Photo & video & text consent."

Screenshot from 2021-01-15 00-25-08

### LINKED ISSUE #6379: Attendee Form: Add user content to receive email
Many organizers would like to be officially permitted to stay in touch with attendees. Therefore please add the following options to the attendee form:

For the agreement of a participant to receive emails after the event implement 
* the text "We would like to share information with you after the event by email for example through personal emails by our team, newsletters or other electronic communications. You can drop out of this agreement at any time. Do you agree to receive electronic mail?"
* a switch button to accept this. This switch button should have set "Yes" by default (on the right) and "No" to the left.
* If the organizer makes the agreement of the participant required and the participant switches the button to "No", then show an error message "You need to agree to the condition of the organizer to receive emails in order to continue the order process."
* If the user does not agree, the user should not be able to continue the order process

Screenshot from 2021-01-15 00-25-08

### LINKED ISSUE #6380: Attendee Form: Add user consent option for sponsor sharing agreement
Many organizers would like to be officially permitted to share contact information with event partners, such as sponsors. Therefore please add the following options to the attendee form:

For the agreement of a participant to share contact information with event partners 
* the text "We would like to share information among event partners to provide you with the best possible experience and enable partners to contact you with additional information after the event through electronic communications. You can drop out of this agreement at any time. Do you agree to share your information with event partners and receive electronic mail?"
* a switch button to accept this. This switch button should have set "Yes" by default (on the right) and "No" to the left.
* If the organizer makes the agreement of the participant required and the participant switches the button to "No", then show an error message "You need to agree to the condition of the organizer to share information among event partners in order to continue the order process. Such a requirement could be necessary in order to provide the event services."
* If the user does not agree, the user should not be able to continue the order process

Screenshot from 2021-01-15 00-25-08

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #6379
Fixes #6377
Fixes #6380

#### Short description of what this resolves:
1. the text "We would like to share information with you after the event by email for example through personal emails by our team, newsletters or other electronic communications. You can drop out of this agreement at any time. Do you agree to receive electronic mail?"
2. a switch button to accept this. This switch button should have set "Yes" by default (on the right) and "No" to the left.
3. If the organizer makes the agreement of the participant required and the participant switches the button to "No", then show an error message "You need to agree to the condition of the organizer to receive emails in order to continue the order process."
4. If the user does not agree, the user should not be able to continue the order process

**Video :** 
https://user-images.githubusercontent.com/61330148/105086873-a77a5e00-5abf-11eb-85d2-2664e4ed54cd.mp4

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. In the order form please change to "Accepted to receive emails."
Please also ensure that all text is translatable.

**Comment by MeghalBisht** [comment]
@iamareebjamal Can we change the text inside these labels?

Capture

I tried changing the name property but it doesn't seem to work
Capture

**Comment by iamareebjamal** [comment]
I don't understand, which text are you talking about?

**Comment by MeghalBisht** [comment]
"Accept receive emails" -> "Accepted to receive emails."

**Comment by iamareebjamal** [comment]
OK, if you're talking about "Accept Receive Emails", then no. Those are stored in DB, you need a DB migration to change them. Once they are created, they can't be changed without migration

**Comment by MeghalBisht** [comment]
Okay so I think no changes are needed for this PR as of now, it is ready for review

**Comment by iamareebjamal** [comment]
Also also confirm the final text for other fields like video recording, etc so that it can all be handled in one migration

**Comment by MeghalBisht** [comment]
@iamareebjamal In the server, I am just changing **"Accept Receive Emails" to "Accepted to receive emails"** and not the field name so migration will not be generated, right?
Capture

**Comment by iamareebjamal** [comment]
You have to manually write the migration

**Comment by MeghalBisht** [comment]
Okay, and what will be the migration about? Column is not changing?

**Comment by iamareebjamal** [comment]
Please handle all consent fields in the same PR, thanks

**Comment by mariobehling** [comment]
Thank you. Please change:
* In order to complete the order process you need to agree to the Photo & video & text consent -> In order to complete the order process you need to agree to the photo & video & text consent.
* Ensure all error messages end with a full stop. Sentences should always end with a full stop.

Screenshot from 2021-01-21 11-55-52

After these small changes it is good for me to merge. Good job!

**Comment by mariobehling** [comment]
Please also change
* Accepted to receive emails -> Email consent
* Accepted to share details with sponsors -> Partner contact consent

**Comment by mariobehling** [comment]
Sorry, I have one more point. Please move the consent forms to the bottom of the list in the wizard and ensure it is on the bottom in the forms page as well.

Screenshot from 2021-01-21 12-01-19

**Comment by mariobehling** [comment]
Typ of two consent box is "switch". The other box is a checkbox.

**Comment by MeghalBisht** [comment]
> * Accepted to receive emails -> Email consent
> * Accepted to share details with sponsors -> Partner contact consent

Um, this will need a server migration again.
@iamareebjamal Should I make migration again?

**Comment by MeghalBisht** [comment]
> Sorry, I have one more point. Please move the consent forms to the bottom of the list in the wizard and ensure it is on the bottom in the forms page as well.

The attendee fields are arranged alphabetically, I am not sure if this can be done

**Comment by MeghalBisht** [comment]
> Typ of two consent boxes is "switch". The other box is a checkbox.

Also, this "switch" cannot be added as switch is not a valid type 😅

**Comment by mariobehling** [comment]
> > Sorry, I have one more point. Please move the consent forms to the bottom of the list in the wizard
> 
> The attendee fields are arranged alphabetically, I am not sure if this can be done

Ok, thanks for the info. Let me open a new issue for this.

**Comment by iamareebjamal** [comment]
> > * Accepted to receive emails -> Email consent
> > * Accepted to share details with sponsors -> Partner contact consent
> 
> Um, this will need a server migration again.
> @iamareebjamal Should I make migration again?

Yup, that's why I tagged to confirm before merging

**Comment by MeghalBisht** [comment]
@iamareebjamal Okay and what about https://github.com/fossasia/open-event-frontend/pull/6435#issuecomment-764577064

**Comment by mariobehling** [comment]
> > Typ of two consent boxes is "switch". The other box is a checkbox.
> 
> Also, this "switch" cannot be added as switch is not a valid type

If it is not too much work maybe add it now. If not it can also be solved in this issue https://github.com/fossasia/open-event-frontend/issues/6454

**Comment by iamareebjamal** [comment]
> @iamareebjamal Okay and what about [#6435 (comment)](https://github.com/fossasia/open-event-frontend/pull/6435#issuecomment-764577064)

Check if adding it will break any past forms

**Comment by MeghalBisht** [comment]
> Check if adding it will break any past forms

**Comment by iamareebjamal** [comment]
Easiest thing is to show switch instead of checkbox in frontend and let it remain checkbox everywhere. Not only is switch not a valid type, but it does not have logic in server to handle it. text, select and checkbox are handled.

We follow HTML input types as form handles, switch will break it

https://www.w3schools.com/tags/att_input_type_checkbox.asp

We chose checkbox because it is a valid HTML input type and we use it to generate the form without any custom logic. Making it to switch will break a lot of things and logic

**Comment by MeghalBisht** [comment]
> Easiest thing is to show switch instead of checkbox in frontend and let it remain checkbox everywhere. 

Not sure what you meant by this 😅

**Comment by MeghalBisht** [comment]
> If it is not too much work maybe add it now. If not it can also be solved in this issue #6454

As discussed in the meeting, "switch" type is not handled in server. So, we can change the 2 switch boxed to checkbox as well. 
@mariobehling Please provide inputs on this.

**Comment by ranjitkshah** [comment]
@iamareebjamal pr closed?

**Comment by mariobehling** [comment]
> > If it is not too much work maybe add it now. If not it can also be solved in this issue #6454
> 
> As discussed in the meeting, "switch" type is not handled in server. So, we can change the 2 switch boxes to checkbox as well.
> @mariobehling Please provide inputs on this.

The UI is fine as it is now, but the info in the column is not correct. This can also be solved in a later PR if you cannot do this now. It does not make sense to change the UI in order to get the text right. The text needs to be changed.

**Comment by iamareebjamal** [comment]
@mariobehling, the text `checkbox` or `switch` is not just text, it's the instruction to server to validate the field as checkbox and for frontend to render the proper field in the form, we cannot change it to anything.

The switches displayed here are added as special case here by Meghal even when the field is checkbox. This won't work in general custom form and also confuse contributors and users

These are the options:

1. We show all checkbox type as type switch in the UI
2. We show all as checkbox in the UI itself

To add a new type switch which behaves same as checkbox while is not a valid HTML element will be adding needless complexity to already complicated custom forms

Even Google Form, which is much more feature rich, and is focused on forms itself and has many more maintainers does not have different UI elements for a switch, they just use a normal checkbox. And I'm not sure if any other platform provides a distinction of switch/checkbox as well. If it was just some text we could change without changing the logic and complexity, we would have done it already

image

**Comment by mariobehling** [comment]
Ok, thanks. Then let's change the switches to checkbox and we can think about if we really need this when we move to another framework.

**Comment by mariobehling** [comment]
I guess the following needs to be changed on the server

- Accepted to receive emails -> Email consent
- Accepted to share details with sponsors -> Partner contact consent

**Comment by MeghalBisht** [comment]
@mariobehling Already done in #7651 I think it's not deployed yet to api.eventyay.com

**Review by mariobehling — APPROVED** [review]
Ok, great. Then thank you! Good job!

**Pull request merged**
