### PR TITLE
added .nvmrc with required version of node

### PR DESCRIPTION
**Pull request by adrijshikhar**
#### Short description of what this resolves:
In this PR, I added .nvmrc which specifies the required version of the node to be used with nvm. 
Type `nvm use` to automatically switch to the required node version.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Add it in gitignore

**Comment by adrijshikhar** [comment]
I did not understand why you asked me to add it in gitignore?

**Comment by snitin315** [comment]
won't it lock down node version to 12.14.1 ?

**Comment by iamareebjamal** [comment]
This is your local setting

**Pull request closed without merging**
