### PR TITLE
feat: improve event dashboard top nav

### LINKED ISSUE #4592: Event Dashboard: Show "View" instead of "Preview" for Live Events, Delete "Copy" Feature
The event dashboard shows "Preview" for live events. Expected:
* Show "View"
* Open event link in new tab
* Only show "Preview" for unpublished events

Furthermore, we have a lot of features in the system. To keep the system more simple, for now:
* comment out the feature "Copy an Event" from the top right dashboard.
(We could come back later to this feature, but for now we dont have resources to test and maintain it.)

Screenshot from 2020-07-20 21-24-38

### PR DESCRIPTION
**Pull request by snitin315**
#### Short description of what this resolves:
Fixes #4592

#### Changes proposed in this pull request:

- Show "View"
- Open event link in new tab
- Only show "Preview" for unpublished events

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please always add screenshots for UI changes

**Comment by snitin315** [comment]
Here is the GIF -

event-nav

**Comment by iamareebjamal** [comment]
@mariobehling I'm a bit confused if this is the expected result. Please check

**Comment by mariobehling** [comment]
Yes, this is the expected result. View/Preview opens in new tab, right? Then please accept this PR.

**Comment by snitin315** [comment]
> Yes, this is the expected result. View/Preview opens in new tab, right? Then please accept this PR.

Yes, it opens in a new tab now.

**Comment by mariobehling** [comment]
Good. There is a follow up issue here: https://github.com/fossasia/open-event-frontend/issues/4621

**Pull request merged**
