### PR TITLE
Fixes layout of order now button in ticket-list component

### LINKED ISSUE #509: Fix layout of order button in ticket-list component
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
screenshot from 2017-07-19 15-15-45

**Expected behavior:**
screenshot from 2017-07-19 15-14-46

### PR DESCRIPTION
**Pull request by geekyd**
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes layout of order now button in ticket-list component

Deployment link: https://open-event-frontend-app.herokuapp.com
Fixes #509

### CODE REVIEW

**Comment by geekyd** [comment]
Travis is having, some issues which leads to the failing of the build. Looking into it.

**Comment by CosmicCoder96** [comment]
@geekyd Please resolve the conflicts

**Comment by geekyd** [comment]
@niranjan94 @CosmicCoder96 Resolved the conflicts please review again. Thanks

**Comment by geekyd** [comment]
@CosmicCoder96 I cant see the problem you described above. Please check the attached screenshots
screen shot 2017-07-19 at 7 16 32 pm
screen shot 2017-07-19 at 7 18 43 pm

**Comment by CosmicCoder96** [comment]
@geekyd  
My bad, when I reviewed the deployment link was not updated. This PR is actually fixing the tiny extra space and since it was negligible dismissed the review anyway on realising that this space is there irrespective of this PR :)

**Pull request merged**
