### PR TITLE
fix: size of state button in sessions table in overview of events

### LINKED ISSUE #5318: Organizer Session Page Table: Size of state button is less
**Describe the bug**

In the Organizer Session Page Table, size of state button is less. Present space for button is sufficient for pending state but not for other state

.
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'overview of event'
2. Click on 'sessions'

#### Links
/events/:event_id/sessions/all

**Expected behaviour**

increase the size of state button.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version:86.0.4240.75 (Official Build) (64-bit)

**Screenshots**

new issue

Final fix

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5318

#### Short description of what this resolves:
Increase size of state button.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

#### Screnshots

__before__

new issue

__after__

fix new issue

### CODE REVIEW

**Comment by snitin315** [comment]
I can see some non-related past commits. Please rebase your branch correctly with `fossasia:development`.

**Comment by sachinchauhan2889** [comment]
sorry for rebase problem. i am resolving this.

**Comment by iamareebjamal** [comment]
That is true but as long as only required changes are in Files Changed, we can squash commits from our end. But for future reference, as @snitin315 said, please create branches from dev.

**Review by iamareebjamal — APPROVED** [review]

**Comment by iamareebjamal** [comment]
And thanks for following up yourself on the issue

**Pull request merged**
