### PR TITLE
feat: Virtual room creation

### LINKED ISSUE #5101: Video Tab: Implement Feature "Add Jitsi Room" to Microlocations
Organizers should have two options to add a video room 
a) add a room manually anywhere on the Internet
b) add a Jitsi room with a button.

According to the Jitsi documentation here https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe the following should be possible.

Open question is: In order to restrict access to rooms we could also add rooms into an 100% iframe on eventyay.com and restrict access to account/ticket holders.

Please implement the option to automatically create a Jitsi room as follows on the video tab:
- Microlocation: add a button "Add Jitsi Room" and autofill other columns
- Video Room: After user has pushed "Add Jitsi Room" automatically create a virtual room at https://meet.jit.si/eventyay/[eventID-room-name]
- Pin: Automatically create a room password and add info here
- Additional Information: Automatically add Jitsi dial-in numbers etc. into this column
- Stream: Apart from the existing public stream URL, also show a field for the Streamkey here, that organizers can enter and pass on the stream key to Jitsi to enable the feature "Stream to Youtube" 
- In field "Additional Information" add: In order to stream a Jitsi Session the moderator in the session needs to start the stream.

Other features:
* Mute all participants in room when they join
* remove the "Embed Jitsi Meet Conference"
* Hide "Invite More People" using HIDE_INVITE_MORE_HEADER (Reference https://github.com/jitsi/jitsi-meet/pull/7021)
* Hide "not secure icon"

Screenshot from 2020-09-19 14-16-04

### LINKED ISSUE #5299: Video: Autogenerate underlying Jitsi Room and Phone numbers
There is a way to autogenerate a Jitsi room with "additional information" such as phone numbers. An example of an implementation is available in the calendar chrome plugin at https://github.com/jitsi/jidesha.

Please implement this in a way that such "Additional Information" is added automatically into the field "Additional Information".

Screenshot from 2020-10-13 10-49-11

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #5101 
Fixes #5299 

image
image

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@iamareebjamal what should be next in this PR?

**Comment by mariobehling** [comment]
Good start. Please take care of the following:
* [ ] Use International English, e.g. always make a space before "(", always make a space after ",". Correct Url -> URL
* [ ] Only make fields required which are really required, e.g. Stream is not required.
* [ ] Use the rooms which are defined as microlocations in the wizard step 5 (but also allow to add more microlocations in the video tab as you have done). So in the first iteration of this feature it is: Microlocation = Video Room (we will further develop this feature later, but the first step is Microlocation = Video Room)
* [ ] Define the access level for ticket holders according to the tickets in wizard step 1, e.g. If there are different ticket types provide the option according to the real ticket types that exist in the system.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/events/view/videoroom/list.js  8
- app/controllers/events/view/videoroom/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6307320&bid=20509680)

**Comment by iamareebjamal** [comment]
@maze-runnar Please make the changes discussed in the meeting today

**Comment by iamareebjamal** [comment]
- [ ] The table should be of rooms and not sessions
- [ ] Certain fields should not be required

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/events/view/videoroom/list.js  8
- app/controllers/events/view/videoroom/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6307320&bid=20509680)

**Comment by mariobehling** [comment]
Please do have a look at the issue.

The table headings and content for the video overview pages is already listed there. Also the linked Google doc provides more details.

Screenshot from 2020-10-13 11-48-04

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/events/view/videoroom/list.js  8
- app/controllers/events/view/videoroom/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6307320&bid=20509680)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/events/view/videoroom/list.js  8
- app/controllers/events/view/videoroom/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6307320&bid=20509680)

**Comment by iamareebjamal** [comment]
image

**Comment by mariobehling** [comment]
Very nice!

Where do attendees see the link or a button to the video room?
I created a video room for the Codeheat January meetup for this session: https://open-event-frontend-git-sideways.eventyay.vercel.app/e/a315169f/schedule

Cannot find a button to the video room yet.

**Comment by mariobehling** [comment]
What is the difference between "Room Name" and "Choose from existing room(s)"? Why there two areas for rooms? I think it would be the same name.

This difference probably makes sense in future for "Session Rooms" where different sessions even though there are in the same microlocation could have different session rooms, right?

**Comment by mariobehling** [comment]
Here is an issue with the implementation so far:
When I create a new Video Room and save it with one of the microlocations and then again create a Video Room using the same Microlocation it will show "Saved", but it will actually update the previously saved room and not create a new video room.

I see the use care for the implementation, where for example an event organizer could implement a video stream combining sessions from different microlocations, e.g. Main Hall and Workshop in one stream because these sessions never overlap. However I am unclear how to make things clear for users.

**Comment by iamareebjamal** [comment]
We'll show a warning to the user saying that a room can have a single video stream, so choosing a microlocation that already has a video stream will overwrite it

**Comment by mariobehling** [comment]
* When I try to delete several rooms at once (and they have different URLs), it is not possible. There is an "Unexpected Error" message. But, it is possible after I refresh.

* When I give all rooms the same URL and want to delete the video room link from one of the room, als an "Unexpected Error" shows up and I am not able to unlink the video room.

Screenshot from 2020-11-14 06-56-12

**Comment by mariobehling** [comment]
When I added the same video room to all microlocations and then I change the video room URL for one of the microlocations, all microlocations have the changed URL.

**Comment by iamareebjamal** [comment]
> When I added the same video room to all microlocations and then I change the video room URL

Yes, because they're the same video room

**Comment by mariobehling** [comment]
> > When I added the same video room to all microlocations and then I change the video room URL
> 
> Yes, because they're the same video room

How to unlink them?

**Comment by iamareebjamal** [comment]
Create a new video room and choose the room which should be linked to it, but yeah, delete icon should unlink the video room, not delete it. Fixing it shortly

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-frontend/pull/5270#issuecomment-727150895 This error is because of the above behaviour as well

**Comment by mariobehling** [comment]
Could we add a message on top that the feature is still in Alpha stage, please?
Something like "This feature is still in Alpha stage. Please use with care. Thank you."

**Comment by iamareebjamal** [comment]
Done

**Comment by iamareebjamal** [comment]
@mariobehling Can we merge this and move ahead in another PR?

**Comment by mariobehling** [comment]
Yes, sounds good.

**Pull request merged**
