### PR TITLE
fix: event URL generated by frontend

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes https://github.com/fossasia/open-event-server/issues/6833

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
How is this the solution?

**Comment by kushthedude** [comment]
This action was adding the extra server url in the event download url.

**Comment by mrsaicharan1** [comment]
If there's an extra param, why would you change the whole logic? There's a precise workflow in place. Please check it out on the server and FE. 
I don't think this is the correct fix.

**Comment by kushthedude** [comment]
The URL fetch logic was added in this #3294, Indeed the cause for invalid `localhost` URL specified in the issue might be empty fields for API URL & Frontend URL in Settings.

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-frontend/pull/4042#issuecomment-584160690

**Pull request closed without merging**
