### PR TITLE
fix: Organizer Speaker/Session Page: Colors of status badge differ

### LINKED ISSUE #6521: Organizer Speaker/Session Page: Colors of status badge differ
The colors of the status badges e.g. "Accepted" differ between the speaker overview page and the session overview page of organizers.

Please use the same colors everyhwere.

Screenshot from 2021-01-29 06-58-43
Screenshot from 2021-01-29 06-58-26
Screenshot from 2021-01-29 06-58-00

### PR DESCRIPTION
**Pull request by afzal442**
Fixes #6521 

#### Short description of what this resolves:
Screenshot After
c1

#### Changes proposed in this pull request:

- Changed the status color
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by afzal442** [comment]
@mariobehling sir plz have a look.

**Comment by iamareebjamal** [comment]
This is a workaround. Why were the colors different in the first place? Make both places use the same source of color

**Comment by afzal442** [comment]
Sorry Sir, if this is not the case, you can close it.

**Comment by iamareebjamal** [comment]
Make both functions use the same source of color

**Comment by afzal442** [comment]
> Make both functions use the same source of color

Should I add these into that function of session-color?
withdrawn : 'black',
  canceled  : 'orange'

**Comment by iamareebjamal** [comment]
No, use single source of color

**Comment by afzal442** [comment]
> No, use single source of color.

Don't mind sir. That means I should make those options into same color like in Statecolor.

**Comment by iamareebjamal** [comment]
I don't know what you're asking. The colors must be loaded from a single source

**Comment by afzal442** [comment]
Thanks sir. I will share first screenshot once I am done.

**Comment by afzal442** [comment]
c3

**Pull request closed without merging**
