### PR TITLE
Adds session creation from CFS in public route

### LINKED ISSUE #883: Add session API on public/cfs/index route
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add session API on public/cfs/index route to enable session proposal for a speaker.

### PR DESCRIPTION
**Pull request by geekyd**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds session creation/updation fro CFS

Fixes #883

### CODE REVIEW

**Comment by niranjan94** [comment]
Deployment link: https://pr-943-open-event-frontend-fossasia.surge.sh

**Comment by geekyd** [comment]
@CosmicCoder96 @niranjan94 @sumedh123 @harshitagupta30 Please review this.

**Comment by niranjan94** [comment]
Deployment link: https://pr-943-open-event-frontend-fossasia.surge.sh

**Comment by niranjan94** [comment]
Deployment link: https://pr-943-open-event-frontend-fossasia.surge.sh

**Pull request merged**
