### PR TITLE
fix: Broken Links

### PR DESCRIPTION
**Pull request by RahulBansal123**
#### Short description of what this resolves:
Fixed the Broken Link.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@RahulBansal123 Please add which issue are you solving in your description

**Comment by RahulBansal123** [comment]
> @RahulBansal123 Please add which issue are you solving in your description



> @RahulBansal123 Please add which issue are you solving in your description

I haven't created a issue regarding it yet.

**Comment by daretobedifferent18** [comment]
Let the maintainers approve the issue first.

**Review by akashgp09 — COMMENTED** [review]
LGTM :+1:

**Pull request closed without merging**
