### PR TITLE
fix: basic details image display enhancement

### LINKED ISSUE #4983: Wizard Step 1 Basic Details: Enhance Image Display and Info
Once images are uploaded it is difficult to understand where images are displayed. Please make the following changes therefore.
* [ ] Switch images - on the left the background image, on the right the logo
* [ ] Use width area as follows 75% for the background image, 25% for the logo
* [ ] Below the images show a small info: "Background Image", "Logo"

Screenshot from 2020-09-04 14-49-51

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4983

Screenshot from 2020-09-21 15-13-15
Screenshot from 2020-09-21 15-12-17

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-21 15-45-51
Screenshot from 2020-09-21 15-50-38

**Comment by mariobehling** [comment]
Nice.

Now the actual goal of this issue is to show the uploaded background image in more or less the way it would look like on the live page. How can we get closer to achieving this?

In this image could you show the background image in the entire available width. There is a white space in the middle now.
Screenshot from 2020-09-21 15-45-51

**Comment by maze-runnar** [comment]
> Now the actual goal of this issue is to show the uploaded background image in more or less the way it would look like on the live page. How can we get closer to achieving this?

is this kind of structure is needed?
Screenshot from 2020-09-21 16-45-52

**Comment by maze-runnar** [comment]
@mariobehling please confirm what of the above is requirement?

**Comment by mariobehling** [comment]
Option 2 uses the space as desired, but you scaled the picture out of proportion. On the live pages of events the picture is sclaed and shown in proportion. Maybe check there how it is done.

**Comment by maze-runnar** [comment]
> Option 2 uses the space as desired, but you scaled the picture out of proportion. On the live pages of events the picture is sclaed and shown in proportion. Maybe check there how it is done.

the images on event page has a greater height than here is. here it is only 150px

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-22 16-31-14

**Comment by mariobehling** [comment]
> > Option 2 uses the space as desired, but you scaled the picture out of proportion. On the live pages of events the picture is sclaed and shown in proportion. Maybe check there how it is done.
> 
> the images on event page has a greater height than here is. here it is only 150px

Good. You understand what I mean then.

- What is the ratio on the event page? 
- What is the ratio on the wizard?

Please make the ratio on the wizard the same ratio as on the event page.

**Comment by mariobehling** [comment]
When you upload an image, there is a preview feature. This preview feature shows the area that will be displayed on the live site. 

Here on the wizard the preview area should be displayed in the same way, please.

**Comment by maze-runnar** [comment]
public page:
Screenshot from 2020-09-22 16-56-11

Upload :
Screenshot from 2020-09-22 16-56-26

**Comment by maze-runnar** [comment]
> Here on the wizard the preview area should be displayed in the same way, please.

For this, I have to increase the height from 150px. This is looking good in this way.

**Comment by maze-runnar** [comment]
on increasing height to 250 px -
Screenshot from 2020-09-22 17-10-43

**Comment by maze-runnar** [comment]
@mariobehling please confirm, should I change it to 250px?

**Comment by mariobehling** [comment]
Yes, seems a good idea to change the height accordingly.

Have a look at this though:

Screenshot from 2020-09-23 08-19-38

Screenshot from 2020-09-23 08-20-30

* [ ] Please keep the original way for the logo.
* [ ] Rename Background Image to "Header Image"
* [ ] Rename "Select Event Image" to "Select Event Header Image"
* [ ] Reduce the spacing above the image description
Screenshot from 2020-09-23 08-23-28
* [ ] Do not make image description bold
* [ ] Ensure it looks fine on mobile view - there is no space below "Background Image" in mobile view
Screenshot from 2020-09-23 08-24-45

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-23 15-14-30

**Comment by maze-runnar** [comment]
- [x] Please keep the original way for the logo.
- [x] Rename Background Image to "Header Image"
 - [x] Rename "Select Event Image" to "Select Event Header Image"
 - [x] Reduce the spacing above the image description
- [x]Do not make image description bold
- [x] Ensure it looks fine on mobile view - there is no space below "Background Image" in mobile view

**Review by mariobehling — APPROVED** [review]
Nice. Looks good to me now. Thank you.

**Pull request merged**
