### PR TITLE
feat: Groups: Add social & custom links, switch to 2 tabs for edit group page

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes parts of https://github.com/fossasia/open-event-frontend/issues/4662
Requires https://github.com/fossasia/open-event-server/pull/8084

#### Short description of what this resolves:
Screenshot from 2021-07-07 13-50-39
Screenshot from 2021-07-07 13-50-16

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Looks good.

Could we have two tabs, please:
1. Events
2. Settings (Group Name, Social Media, Extra Links)

**Comment by mariobehling** [comment]
The share icon does not work here. Not sure, if it is related to this PR though.

**Comment by MeghalBisht** [comment]
Screenshot from 2021-07-08 11-22-54
Screenshot from 2021-07-08 11-22-29

**Comment by mariobehling** [comment]
Very good. Please also add "Team" as a tab here.

**Comment by MeghalBisht** [comment]
> Very good. Please also add "Team" as a tab here.

Adding Team section is currently not working. Will look into it after this PR.

**Review by mariobehling — APPROVED** [review]
Ok, good we can follow up on open points in the following PRs. Thanks.

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
