### PR TITLE
Added Currency symbol in the total amount of ticket

### LINKED ISSUE #2224: Add Currency symbol in items total of Add Order section
**Describe the bug**

NO Currency symbol in items total of Add Order section 
**To Reproduce**
1. Go to 'Tickets'
2. Click on 'Add order'

**Expected behavior**

Currency symbol in items total of Add Order section 
**Screenshots**

screenshot 2019-02-23 at 2 25 38 am

**Additional context**

I'm working on it.

### PR DESCRIPTION
**Pull request by mohitm15**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Now it displays the currency symbol for  the total amount of the tickets

#### Changes proposed in this pull request:

-I had changed a file to resolve this issue.
-The issue was fixed as now it displays the currency symbol.
-A screenshot is also attached to give brief understanding.

Fixes #2224 

## After the change
Screenshot from 2019-03-25 19-10-44

### CODE REVIEW

**Comment by mohitm15** [comment]
@mariobehling  please review it

**Comment by kushthedude** [comment]
I think i had already opened a PR regarding this and you had a discussion too about it on the issue.

**Comment by kushthedude** [comment]
@mohitm15 Please take a look at #2376 and #2255 , Before opening a PR please make a thorough check if someone is already on it or not!

**Comment by mohitm15** [comment]
@kushthedude Closed this PR

**Pull request closed without merging**
