### PR TITLE
fix alignment in attendees, order and access-code routes on mobile view

### LINKED ISSUE #472: improper alignment in attendees,order and overview routes on mobile view
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

the content is left aligned on mobile view
image
image

**Expected behavior:**

they should be centered aligned like access code route
image

### PR DESCRIPTION
**Pull request by anu-007**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
fix alignment in attendees, order and access-code routes on mobile view

#### Changes proposed in this pull request:

-aligned header to left
-buttons take full width on mobile view

demo- https://open-event-frontend-branch3.herokuapp.com/

Fixes #472

### CODE REVIEW

**Comment by anu-007** [comment]
@geekyd the size of drop down increases due to the text inside it ,I think we simply reduce the text inside the drop down i.e instead of 'showing all the records' we can use 'showing all'.here is the screen shot 
image

**Comment by geekyd** [comment]
@anu-007 That won't fix the design issue here. Please check the attached screenshot.

screen shot 2017-07-18 at 1 49 16 pm
If we select an option from the dropdown the design will distort.

**Comment by anu-007** [comment]
@geekyd removed some padding please review.
image

**Comment by anu-007** [comment]
@geekyd please review.thanks!!

**Pull request merged**
