### PR TITLE
8763 video translation frontend

### PR DESCRIPTION
**Pull request by minhho89**
issue #8763 
Making the Front-end for the input form of Video channel.
This includes:
- UI Form
- API Integration

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by minhho89** [comment]
Implementation so far
image

**Comment by mariobehling** [comment]
I am changing this to "ready for review" in order to enable the automatic tests.

**Comment by minhho89** [comment]
The `PATCH` API keeps returning the `404 NOT FOUND` error even though everything is probably configurated. Need to check on the backend side

**Comment by minhho89** [comment]
Please ignore this PR, shift to this PR https://github.com/fossasia/open-event-frontend/pull/9011

**Pull request closed without merging**
